from django.dispatch import Signal


ACCOUNT_USER_TYPE_CHANGED = Signal()
VPROFILE_CONFIRMATIVE_FIELD_CHANGED = Signal()
VERIFICATION_REQUEST_STATUS_CHANGED = Signal()
BANK_ITEM_CONFIRMED = Signal()
BANK_ITEM_REJECTED = Signal()
MERGE_REQUEST_STATUS_CHANGED = Signal()
