# Generated by Django 2.2.14 on 2020-10-25 18:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='روز')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')], verbose_name='رمزارز')),
                ('tp', models.IntegerField(choices=[(0, 'نامعین'), (11, 'داخلی - واریز'), (12, 'داخلی - برداشت'), (13, 'داخلی - معامله'), (21, 'برداشت هات')])),
                ('expected_value', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='مقدار مورد انتظار')),
                ('real_value', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='مقدار واقعی')),
                ('diff', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='دیف')),
            ],
            options={
                'verbose_name': 'دیف',
                'verbose_name_plural': 'دیف',
                'unique_together': {('date', 'currency', 'tp')},
            },
        ),
    ]
