# Generated by Django 2.2.24 on 2022-01-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('wallet', '0001_nobitex2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مبلغ تراکنش')),
                ('balance', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('transactions', models.ManyToManyField(to='wallet.Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_wallets', to='wallet.Wallet', verbose_name='کیف پول')),
            ],
        ),
    ]
