apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: exchange-internal
  type: {{ .Values.core.service.type }}
  ports:
    - name: exchange
      port: 8000
      targetPort: 8000
      protocol: {{ .Values.core.service.protocol | default "TCP" }}
