# Generated by Django 2.2.28 on 2022-12-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantransaction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='plantransaction',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plantransaction',
            name='wallet_transaction',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='extended_from',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='pooltransaction',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='pooltransaction',
            name='wallet_transaction',
        ),
        migrations.AlterUniqueTogether(
            name='staking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staking',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='staking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stakingtransaction',
            name='staking',
        ),
        migrations.RemoveField(
            model_name='stakingtransaction',
            name='wallet_transaction',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanTransaction',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='PoolTransaction',
        ),
        migrations.DeleteModel(
            name='Staking',
        ),
        migrations.DeleteModel(
            name='StakingTransaction',
        ),
    ]
