# Generated by Django 2.2.28 on 2023-02-05 14:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staking', '0003_auto_20230128_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staking',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staking.plan',),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='externalearningplatform',
            name='tp',
            field=models.SmallIntegerField(choices=[(101, 'Staking'), (201, 'Margin Trading'), (301, 'Yield Aggregator')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='estimated_annual_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extended_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='extended_to', to='staking.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='stakingtransaction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staking_transactions', related_query_name='staking_transaction', to='staking.Plan'),
        ),
        migrations.AlterField(
            model_name='stakingtransaction',
            name='tp',
            field=models.SmallIntegerField(choices=[(10, 'Staking Request'), (11, 'Cancel Create Request'), (20, 'End Request'), (21, 'Cancel End Request'), (112, 'System Accepted user create request'), (113, 'System Rejected user create request'), (122, 'System Accepted user end staking request'), (123, 'System Rejected user end staking request'), (213, 'System Rejected user create request'), (223, 'System Rejected user end staking request'), (301, 'announce_reward'), (302, 'give_reward'), (303, 'stake'), (304, 'release'), (305, 'unstake'), (311, 'extend_out'), (312, 'extend_in')]),
        ),
        migrations.CreateModel(
            name='UserWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.AlterField(
            model_name='externalearningplatform',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, '1MBitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'MultiversX'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFIMoney'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis'), (122, 'Aptos'), (123, 'Flare'), (124, 'Loopring'), (125, 'EthereumNameService'), (126, 'Livepeer'), (127, 'Golem'), (128, 'API3'), (129, 'aelf'), (130, 'DAOMaker'), (131, 'Civic'), (132, 'Numeraire'), (133, 'Storj'), (134, 'ConvexFinance'), (135, 'Status'), (136, 'SmoothLovePotion'), (137, '1MApeNFT'), (138, 'Serum'), (139, 'Aragon'), (140, 'Illuvium'), (141, 'Threshold'), (142, 'InternetComputer'), (143, 'Helium'), (144, '1B_BabyDoge'), (145, 'Toncoin'), (146, '100K_Floki'), (147, '0x'), (148, 'ImmutableX'), (149, 'MeasurableDataToken'), (150, 'Blur'), (151, 'Magic')]),
        ),
        migrations.AlterField(
            model_name='plantransaction',
            name='tp',
            field=models.SmallIntegerField(choices=[(103, 'check_stake_amount'), (203, 'stake_amount_approval'), (204, 'release_amount_approval'), (213, 'stake_amount_refusal'), (403, 'system_stake_amount_approval'), (301, 'announce_reward'), (302, 'give_reward'), (322, 'system_reward'), (303, 'stake'), (304, 'release'), (305, 'unstake'), (311, 'extend_out'), (312, 'extend_in'), (313, 'fee'), (314, 'fetched_reward'), (999, 'deactivator')]),
        ),
    ]
