# Generated by Django 2.2.28 on 2023-01-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0003_externalearningplatform_plan_plantransaction_staking_stakingtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='extended_from',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='external_platform',
        ),
        migrations.RemoveField(
            model_name='plantransaction',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plantransaction',
            name='wallet_transaction',
        ),
        migrations.AlterUniqueTogether(
            name='staking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staking',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='staking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stakingtransaction',
            name='staking',
        ),
        migrations.RemoveField(
            model_name='stakingtransaction',
            name='wallet_transaction',
        ),
        migrations.DeleteModel(
            name='ExternalEarningPlatform',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanTransaction',
        ),
        migrations.DeleteModel(
            name='Staking',
        ),
        migrations.DeleteModel(
            name='StakingTransaction',
        ),
    ]
