# Generated by Django 2.2.28 on 2023-06-19 07:43

from django.db import migrations, models


def remove_non_final_end_requests(apps, _):
    model = apps.get_model('staking', 'StakingTransaction')
    non_final_end_requests_ids = list(model.objects.filter(tp=20, child__tp=20).values_list('id', flat=True))
    model.objects.filter(tp=20).update(parent=None)
    model.objects.filter(id__in=non_final_end_requests_ids).delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('staking', '0004_auto_20230205_1827'),
    ]

    operations = [
        migrations.RunPython(remove_non_final_end_requests),
        migrations.AddConstraint(
            model_name='stakingtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(tp=20), fields=('user_id', 'plan_id'), name='stkng_trx_unique_end_request'),
        ),
    ]
