# Generated by Django 2.2.28 on 2023-01-09 16:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.base.calendar


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staking', '0004_auto_20230109_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEarningPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.SmallIntegerField(choices=[(101, 'Proof of Stake'), (201, 'Margin Trading'), (301, 'Lending')])),
                ('currency', models.SmallIntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis'), (122, 'Aptos')])),
                ('network', models.CharField(default='', max_length=32)),
                ('address', models.CharField(default='', max_length=128)),
                ('tag', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30)),
                ('filled_by_extension', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30)),
                ('filled_capacity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30)),
                ('released_capacity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30)),
                ('extended_capacity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30)),
                ('announced_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField()),
                ('request_period', models.DurationField()),
                ('staked_at', models.DateTimeField()),
                ('staking_period', models.DurationField()),
                ('unstaking_period', models.DurationField()),
                ('initial_pool_capacity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('is_extendable', models.BooleanField()),
                ('reward_announcement_period', models.DurationField()),
                ('min_staking_amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('staking_precision', models.DecimalField(decimal_places=10, default=Decimal('1E-10'), max_digits=12)),
                ('extended_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staking.Plan')),
                ('external_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='staking.ExternalEarningPlatform')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.SmallIntegerField(choices=[(101, 'check_announce_reward_amount'), (102, 'check_give_reward_amount'), (103, 'check_stake_amount'), (104, 'check_release_amount'), (105, 'check_unstake_amount'), (201, 'announce_reward_amount_approval'), (202, 'give_reward_amounts_approval'), (203, 'stake_amount_approval'), (204, 'release_amount_approval'), (205, 'unstake_amount_approval'), (211, 'announce_reward_amount_refusal'), (212, 'give_reward_amounts_refusal'), (213, 'stake_amount_refusal'), (214, 'release_amount_refusal'), (215, 'unstake_amount_refusal'), (301, 'announce_reward'), (302, 'give_reward'), (303, 'stake'), (304, 'release'), (305, 'unstake'), (311, 'extend_out'), (312, 'extend_in')])),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='staking.PlanTransaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to='staking.Plan')),
                ('wallet_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='StakingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.SmallIntegerField(choices=[(10, 'Staking Request'), (11, 'Cancel Create Request'), (20, 'End Request'), (21, 'Cancel End Request'), (112, 'System Accepted user create request'), (113, 'System Rejected user create request'), (122, 'System Accepted user end staking request'), (123, 'System Rejected user end staking request'), (301, 'announce_reward'), (302, 'give_reward'), (303, 'stake'), (304, 'release'), (305, 'unstake'), (311, 'extend_out'), (312, 'extend_in')])),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='staking.StakingTransaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staking.Plan')),
                ('plan_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staking.PlanTransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
            ],
        ),
    ]
