# Generated by Django 2.2.28 on 2023-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0005_auto_20230619_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_instantly_unstakable',
            field=models.BooleanField(default=True),
        ),
    ]
