# Generated by Django 3.2.25 on 2024-04-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0006_auto_20231018_1008'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stakingtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('tp', 302), ('plan_id__gt', 297))), fields=('user_id', 'plan_id'), name='stkng_trx_unique_give_reward'),
        ),
    ]
