# Generated by Django 4.2.16 on 2024-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0007_auto_20240424_1451'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plantransaction',
            index=models.Index(fields=['tp'], name='staking_plantransaction_tp_idx'),
        ),
    ]
