# Generated by Django 4.2.16 on 2025-04-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.base.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0139_withdrawrequestrestriction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staking', '0008_plantransaction_tp_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            (10, 'Requested'),
                            (20, 'Admin Rejected'),
                            (30, 'Locked'),
                            (40, 'Pending Renewal'),
                            (50, 'Extend To Next Cycle'),
                            (60, 'Extend From Previous Cycle'),
                            (70, 'Pending Release'),
                            (80, 'Released'),
                            (90, 'User Canceled'),
                        ]
                    ),
                ),
                (
                    'locked_amount',
                    models.DecimalField(decimal_places=10, help_text='total locked amount', max_digits=30),
                ),
                (
                    'requested_amount',
                    models.DecimalField(
                        decimal_places=10, default=0, help_text='total user requested amount', max_digits=30
                    ),
                ),
                (
                    'admin_rejected_amount',
                    models.DecimalField(
                        decimal_places=10, default=0, help_text='total locked amount rejected by admin', max_digits=30
                    ),
                ),
                ('admin_reject_reason', models.TextField(blank=True, null=True)),
                (
                    'released_amount',
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        help_text='total amount released at the end of cycle',
                        max_digits=30,
                    ),
                ),
                (
                    'extended_to_next_cycle_amount',
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        help_text='total amount that is extended to next plan - old extend_out amount',
                        max_digits=30,
                    ),
                ),
                (
                    'extended_from_previous_cycle_amount',
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        help_text='total amount that is from previous plan - old extended_in amount',
                        max_digits=30,
                    ),
                ),
                (
                    'early_ended_amount',
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        help_text='total amount ended in the lock period - old instant_end amount',
                        max_digits=30,
                    ),
                ),
                (
                    'reward_amount',
                    models.DecimalField(
                        decimal_places=10, default=0, help_text='total gained reward amount', max_digits=30
                    ),
                ),
                ('auto_renewal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'next_cycle_plan',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staking.userplan'
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staking.plan'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserPlanChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'from_status',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, 'Requested'),
                            (20, 'Admin Rejected'),
                            (30, 'Locked'),
                            (40, 'Pending Renewal'),
                            (50, 'Extend To Next Cycle'),
                            (60, 'Extend From Previous Cycle'),
                            (70, 'Pending Release'),
                            (80, 'Released'),
                            (90, 'User Canceled'),
                        ],
                        null=True,
                    ),
                ),
                (
                    'to_status',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, 'Requested'),
                            (20, 'Admin Rejected'),
                            (30, 'Locked'),
                            (40, 'Pending Renewal'),
                            (50, 'Extend To Next Cycle'),
                            (60, 'Extend From Previous Cycle'),
                            (70, 'Pending Release'),
                            (80, 'Released'),
                            (90, 'User Canceled'),
                        ],
                        null=True,
                    ),
                ),
                ('extra_reason', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.userplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlanRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('tp', models.IntegerField(choices=[(10, 'Subscription'), (20, 'Early End')])),
                (
                    'status',
                    models.IntegerField(
                        choices=[(10, 'Created'), (20, 'Admin Rejected'), (30, 'Failed'), (40, 'Accepted')]
                    ),
                ),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.userplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlanWalletTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    'tp',
                    models.IntegerField(
                        choices=[(10, 'Reward'), (20, 'Subscription'), (30, 'Release'), (40, 'Early End')]
                    ),
                ),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.userplan')),
                (
                    'user_plan_request',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staking.userplanrequest'
                    ),
                ),
                (
                    'wallet_transaction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wallet.transaction',
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='userplanwallettransaction',
            index=models.Index(fields=['user_plan'], name='staking_use_user_pl_e07f91_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanwallettransaction',
            index=models.Index(fields=['user_plan', 'tp'], name='staking_use_user_pl_d24dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanwallettransaction',
            index=models.Index(fields=['user_plan_request'], name='staking_use_user_pl_ad9072_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanrequest',
            index=models.Index(fields=['user_plan'], name='staking_use_user_pl_8b4964_idx'),
        ),
        migrations.AddIndex(
            model_name='userplanrequest',
            index=models.Index(fields=['user_plan', 'tp'], name='staking_use_user_pl_4359a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['plan', 'status'], name='staking_use_plan_id_57250e_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['plan'], name='staking_use_plan_id_5db024_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user'], name='staking_use_user_id_318359_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['next_cycle_plan'], name='staking_use_next_cy_750fde_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplan',
            constraint=models.UniqueConstraint(
                fields=('user', 'plan'), name='staking_userplan_user_and_plan_unique_constraint'
            ),
        ),
    ]
