# Generated by Django 4.2.16 on 2025-05-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0139_withdrawrequestrestriction_and_more'),
        ('staking', '0009_userplan_userplanchangelog_userplanrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='the time user plan locked(staked)', null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='unlocked_at',
            field=models.DateTimeField(
                blank=True,
                help_text='the time user plan unlocked and pending release - old unstaked and is released after unstaking period',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staking.plan'),
        ),
        migrations.AlterField(
            model_name='userplanrequest',
            name='user_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staking.userplan'),
        ),
        migrations.AlterField(
            model_name='userplanwallettransaction',
            name='user_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staking.userplan'),
        ),
        migrations.AlterField(
            model_name='userplanwallettransaction',
            name='user_plan_request',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staking.userplanrequest'
            ),
        ),
        migrations.AlterField(
            model_name='userplanwallettransaction',
            name='wallet_transaction',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction'
            ),
        ),
        migrations.RemoveIndex(
            model_name='userplan',
            name='staking_use_next_cy_750fde_idx',
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='next_cycle_plan',
            new_name='next_cycle',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['next_cycle'], name='staking_use_next_cy_3ad517_idx'),
        ),
    ]
