# Generated by Django 4.2.16 on 2025-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staking', '0010_alter_user_plan_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalearningplatform',
            name='is_available',
            field=models.BooleanField(default=True),
        )
    ]
