from .common import MAIN_WALLET_SERVER

WALLET_SERVER = MAIN_WALLET_SERVER
# BTC
ELECTRUM_JSONRPC_URL = WALLET_SERVER + '/btc'
ELECTRUM_WALLET_PATH = '~/.electrum/wallets/wallet_1'
# ETH
GETH_JSONRPC_URL = WALLET_SERVER + '/eth'
GETH_ACCOUNT = '0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c'
# LTC
LTC_WALLET_SERVER = WALLET_SERVER
ELECTRUM_LTC_JSONRPC_URL = LTC_WALLET_SERVER + '/ltc'
# XRP
RIPPLE_WALLET_SERVER = WALLET_SERVER
RIPPLE_JSONRPC_URL = RIPPLE_WALLET_SERVER + '/xrp'
# BNB
BNB_WALLET = 'bnb1990lfutz0f9wza6rsh36ysfwt9xpctxrll884r'
BNB_RPC_URL = WALLET_SERVER + '/bnb-rpc/'
BNB_API_SERVER_URL = WALLET_SERVER + '/bnb-api/'
BNB_JSONRPC_URL = WALLET_SERVER + '/bnb/'
# BCH
ELECTRON_CASH_JSONRPC_URL = WALLET_SERVER + '/bch'
# ETC
PARITY_JSONRPC_URL = WALLET_SERVER + '/eth-classic'
PARITY_ACCOUNT = '0x6637d9b2f3569f8e4998bdcb62769b1cfb3d9c3b'
ETC_SERVER_NAME = 'nobitex1/nodes-etc'
# TRX
TRX_JSONRPC_URL = WALLET_SERVER + '/trx/'
# XLM
XLM_JSONRPC_URL = WALLET_SERVER + '/xlm/'
# PMN
PMN_JSONRPC_URL = WALLET_SERVER + '/pmn/'
# GATEWAY
GATEWAY_SERVER = 'https://wallet-gateway.nobitex1.ir'
GATEWAY_BTC_JSONRPC_URL = GATEWAY_SERVER + '/gateway-btc'
GATEWAY_LTC_JSONRPC_URL = GATEWAY_SERVER + '/gateway-ltc'
GATEWAY_XRP_JSONRPC_URL = GATEWAY_SERVER + '/gateway-xrp'
