# Generated by Django 3.2.25 on 2024-06-15 07:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('from_email', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('context', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(max_length=10)),
                ('backend', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'مدل تستی ایمیل',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'tp',
                    models.IntegerField(
                        choices=[
                            (0, 'Manual SMS'),
                            (1, 'Verify Phone'),
                            (2, 'Verify Withdraw'),
                            (3, 'Process'),
                            (4, 'android'),
                            (7, 'Enable TFA'),
                            (5, 'Disable TFA'),
                            (6, 'Price Alert'),
                            (7, 'Gift OTP'),
                            (8, 'Gift Password'),
                            (8, 'Gift Batch'),
                            (10, 'Coin Withdrawal Restriction Due To New Device Notification'),
                            (11, 'Verify Password Recovery'),
                            (12, 'Verify Password Recovery'),
                            (13, 'Deactivate Whitelist Mode'),
                            (14, 'New Address In AddressBook'),
                            (15, 'Verify New Address'),
                            (16, 'Affirm Withdraw'),
                            (17, 'Send OTP to Deactivate Whitelist Mode'),
                            (18, 'Social User Set Password'),
                            (19, 'Social Trade Leadership Request Acceptance'),
                            (20, 'Social Trade Leadership Request Rejection'),
                            (21, 'User Merge'),
                            (22, 'Social Trade Notification to Leader for Deletion'),
                            (23, 'Social Trade Notification to Subscribers for Leader Deletion'),
                            (24, 'Social Trade Notification to Trials for Leader Deletion'),
                            (25, 'KYC'),
                            (26, 'KYC Parameter'),
                            (27, 'Grant Financial Service'),
                            (28, 'Staff User Password Recovery'),
                            (29, 'ABC Margin Call'),
                            (30, 'ABC Margin Call Liquidate'),
                            (31, 'ABC Liquidate By Provider'),
                            (32, 'Direct Debit Create Contract Successfully'),
                            (33, 'Direct Debit Remove Contract Successfully'),
                            (34, 'Direct Debit Cancel Contract For Some Reason'),
                            (35, 'ABC Margin Call Adjustment'),
                        ]
                    ),
                ),
                ('to', models.CharField(max_length=12)),
                ('text', models.TextField()),
                (
                    'template',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, 'پیش\u200cفرض'),
                            (6816, 'به نوبیتکس خوش آمدید . کد تایید عضویت شما : [VerificationCode] '),
                            (3065, 'کد تایید شما در سایت نوبیتکس [VerificationCode] است '),
                            (54043, 'درخواست فعال سازی شناسه دوعاملی نوبیتکس\nکد: [VerificationCode]'),
                            (51443, 'درخواست غیرفعالسازی شناسه دوعاملی نوبیتکس\nکد: [VerificationCode]'),
                            (55503, 'نوبیتکسی عزیز\nلطفا ایمیل ارسال شده از واحد [VerificationCode] را بررسی نمایید.'),
                            (63653, 'کد تایید دریافت کارت هدیه شما در نوبیتکس\n[VerificationCode]'),
                            (68559, 'هشدار نوبیتکس\n[Duration] محدودیت برداشت بعلت ورود از دستگاه/مرورگر جدید'),
                            (70745, 'نوبیتکس\nکاربر گرامی [ChangeType] شما در نوبیتکس تغییر کرد.'),
                            (72801, 'هشدار!\nاین کد تایید «برداشت» از حساب نوبیتکس شماست: [VerificationCode]'),
                            (
                                51444,
                                'نوبیتکس\nدرخواست برداشت [Fund]\nکد تایید: [VerificationCode]\nلغو اضطراری: https://nobitex.ir/sos/[CancelCode]',
                            ),
                            (72802, 'کد تایید بازیابی رمزعبور در نوبیتکس: [VerificationCode]'),
                            (77406, 'کد یکبار مصرف برای تعیین رمزعبور در حساب کاربری نوبیتکس:  [VerificationCode]'),
                            (75172, 'کد تایید افزودن آدرس جدید به دفترآدرس برداشت در نوبیتکس: [VerificationCode]'),
                            (77370, 'کد تایید غیرفعال\u200cسازی حالت برداشت امن نوبیتکس: [VerificationCode]'),
                            (77411, 'هشدار نوبیتکس! [Duration] محدودیت برداشت به دلیل غیرفعال\u200cسازی برداشت امن'),
                            (
                                77836,
                                'کاربر گرامی نوبیتکس، درخواست شما برای انتخاب به عنوان تریدر مرجع تایید شده و از تاریخ [Date] امکان دریافت دنبال کننده را خواهید داشت.',
                            ),
                            (77778, 'کاربر گرامی، درخواست شما برای انتخاب به عنوان تریدر مرجع رد شد. دلیل رد [Reason]'),
                            (
                                77788,
                                'هشدار نوبیتکس!\nکد امنیتی برای تایید ادغام شماره تماس شما با حساب زیر:\n[Mobile]\nکد تایید ادغام:\n[VerificationCode]',
                            ),
                            (
                                77789,
                                'نوبیتکس!\nکاربر گرامی ادغام [Data2] در حساب [Data1] با موفقیت انجام شد.\nبه منظور افزایش امنیت، برداشت رمزارز در حساب شما [Duration] محدود می\u200cشود.\nدر صورت هرگونه مغایرت با پشتیبانی موضوع را مطرح\u200c نمایید.',
                            ),
                            (
                                77779,
                                'کاربر گرامی،\u200c از این تاریخ شما امکان دریافت اشتراک جدید را نداشته و پس از پایان دوره اشتراک کاربران، امکان فعالیت به عنوان تریدر سوشال ترید را نخواهید داشت. دلیل: [Reason]',
                            ),
                            (
                                77780,
                                'کاربر گرامی، تریدر انتخابی شما تا پایان دوره فعلی اشتراک فعالیت خواهد داشت و پس از آن امکان تمدید اشتراک وجود نخواهد داشت.\nتریدر: [Trader]',
                            ),
                            (
                                77781,
                                'کاربر گرامی، به دلیل عدم فعالیت تریدر انتخابی شما، امکان فعال\u200cسازی اشتراک سوشال ترید برای تریدر انتخابی وجود نداشته و دوره آزمایشی اشتراک شما به پایان رسیده است.\nتریدر: [Trader]',
                            ),
                            (78073, 'هشدار نوبیتکس! ورود با [Device] به حساب نوبیتکس شما'),
                            (78074, 'هشدار نوبیتکس! محدودیت [Duration] برداشت به دلیل تغییر گذرواژه'),
                            (78075, 'هشدار نوبیتکس! [Reason] حساب کاربری شما ثبت شد.'),
                            (
                                81287,
                                'کد تأیید جهت فعالسازی سرویس [FinancialService] در نوبیتکس\nکد: [VerificationCode]',
                            ),
                            (80109, 'کد تایید بازیابی رمزعبور حساب کاربری پشتیبانی نوبیتکس شما : [VerificationCode]'),
                            (80531, 'وثیقه شما در [Platform] نوبیتکس در آستانه تبدیل قرار گرفته است.'),
                            (80532, 'وثیقه شما در سرویس [Platform] نوبیتکس تبدیل شد.'),
                            (
                                80533,
                                'به درخواست [ProviderName] وثیقه [ServiceName] به میزان [Amount] تومان تبدیل و تسویه شد.',
                            ),
                            (81281, 'قرارداد واریز مستقیم بانک [BankName] شما در نوبیتکس ایجاد شد.'),
                            (81282, 'قرارداد واریز مستقیم بانک [BankName] شما در نوبیتکس حذف شد.'),
                            (81283, 'قرارداد واریز مستقیم شما در نوبیتکس به\u200cدلیل [Reason] لغو شد.'),
                            (81848, 'به\u200cدلیل کاهش نسبت ارزش در نوبیتکس، اعتبار شما در [ServiceName] غیرفعال شد.'),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ('details', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_id', models.IntegerField(blank=True, null=True)),
                (
                    'carrier',
                    models.IntegerField(
                        blank=True, choices=[(0, 'رست فول اس ام اس'), (1, 'فینوتکست')], default=0, null=True
                    ),
                ),
                ('tracking_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                (
                    'admin',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='new_sms_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='new_sent_sms_set',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'پیامک کاربر',
                'verbose_name_plural': 'پیامک کاربر',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('otp_type', models.IntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')])),
                (
                    'otp_usage',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 'TFA Removal'),
                            (2, 'Email Verification'),
                            (3, 'Generic'),
                            (4, 'Change Phone Number'),
                            (5, 'Welcome SMS'),
                            (6, 'Anti Phishing Code'),
                            (7, 'Address Book'),
                            (8, 'Deactivate Whitelist Mode'),
                            (9, 'Social User Set Password'),
                            (10, 'User Merge'),
                            (11, 'Grant Permission To Financial Service'),
                            (12, 'Staff Password Recovery'),
                        ],
                        null=True,
                    ),
                ),
                ('otp_status', models.IntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')], default=1)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='new_otps',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف کاربر',
                'verbose_name_plural': 'کدهای یکبار مصرف کاربر',
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_to_telegram', models.BooleanField(default=False)),
                ('sent_to_fcm', models.BooleanField(default=False, null=True)),
                (
                    'admin',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='new_sent_notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='new_notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'اعلان\u200cها',
                'verbose_name_plural': 'اعلان\u200cها',
            },
        ),
    ]
