# Generated by Django 4.2.13 on 2024-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_emailinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailinfo',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='emailinfo',
            name='headers',
        ),
    ]
