# Generated by Django 3.2.23 on 2023-12-30 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):

    replaces = [('oauth', '0001_initial'), ('oauth', '0002_refreshtoken_access_token'), ('oauth', '0003_accesstoken_source_refresh_token'), ('oauth', '0004_auto_20231031_1631')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    run_before = [
        ('oauth2_provider', '0008_alter_accesstoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.TextField(null=True)),
                ('acceptable_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('algorithm', models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], default=None, max_length=32)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('client_secret', oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255)),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default=None, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('post_logout_redirect_uris', models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated')),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated')),
                ('skip_authorization', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اپلیکیشن',
                'verbose_name_plural': 'اپلیکیشن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=None)),
                ('scope', models.TextField(blank=True)),
                ('token', models.CharField(default=None, max_length=255, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accesstoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن دسترسی',
                'verbose_name_plural': 'توکن\u200cهای دسترسی',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('access_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_token', to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('revoked', models.DateTimeField(null=True)),
                ('token', models.CharField(default=None, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refreshtoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن بازیابی',
                'verbose_name_plural': 'توکن\u200cهای بازیابی',
                'unique_together': {('token', 'revoked')},
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('claims', models.TextField(blank=True)),
                ('code', models.CharField(default=None, max_length=255, unique=True)),
                ('code_challenge', models.CharField(blank=True, default='', max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, choices=[('plain', 'plain'), ('S256', 'S256')], default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=None)),
                ('nonce', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_uri', models.TextField(default=None)),
                ('scope', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
            },
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='source_refresh_token',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='refreshed_access_token',
                to='oauth.RefreshToken',
            ),
        ),
    ]
