# Generated by Django 4.2.16 on 2025-04-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0001_migrations_1_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allowed_origins',
            field=models.TextField(
                blank=True, default='', help_text='Allowed origins list to enable CORS, space separated'
            ),
        ),
        migrations.AddField(
            model_name='application',
            name='hash_client_secret',
            field=models.BooleanField(default=True),
        ),
    ]
