# Generated by Django 2.2.17 on 2020-12-27 14:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='روز')),
                ('registered_users', models.IntegerField(default=0, help_text='تعداد کاربران ثبت\u200cنام شده')),
                ('verified_users', models.IntegerField(default=0, help_text='تعداد کاربران تایید شده')),
                ('monthly_active_trade_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال ماهانه\u200c(معامله)')),
                ('daily_active_trade_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال روزانه\u200c(معامله)')),
                ('monthly_active_login_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال ماهانه\u200c(لاگین)')),
                ('daily_active_login_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال روزانه\u200c(لاگین)')),
                ('verified_users_identity', models.IntegerField(default=0, help_text='تعداد کاربران تایید شده(هویت)')),
            ],
            options={
                'verbose_name': 'آمار روزانه فعالیت\u200cهای کاربران',
                'verbose_name_plural': 'آمار روزانه فعالیت\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserBalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز')),
                ('balance', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='موجودی کیف پول داخلی')),
                ('date', models.DateField(db_index=True, verbose_name='روز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آمار روزانه موجودی کاربران',
                'verbose_name_plural': 'آمار روزانه موجودی کاربران',
            },
        ),
        migrations.CreateModel(
            name='WalletsStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')])),
                ('balance_user', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_bot', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_system', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_cold', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_hot', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_binance', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_kraken', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_cold_system', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
            ],
            options={
                'verbose_name': 'آمار موجودی والت\u200cها',
                'verbose_name_plural': 'آمار موجودی والت\u200cها',
                'ordering': ['-date', '-hour', 'currency'],
                'unique_together': {('date', 'hour', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='DailyCustomersStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='روز')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز')),
                ('sells', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع فروش این ارز توسط کاربران - شامل کارمزد', max_digits=30)),
                ('buys', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع خرید این ارز توسط کاربران - شامل کارمزد', max_digits=30)),
                ('user_trades', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع معاملات بین کاربران - شامل کارمزد، هر معامله یک بار محسوب شده', max_digits=30)),
                ('fees', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع کارمزد دریافت شده از معاملات', max_digits=30)),
                ('deposits', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع مبالغ اضافه شده به حساب کاربران برای واریزها - بدون کارمزدها', max_digits=30)),
                ('withdraws', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع مبالغ کسر شده از حساب کاربران جهت برداشت - شامل کارمزدها', max_digits=30)),
                ('manuals', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع تراکنش\u200cهای دستی بدون دلیل', max_digits=30)),
                ('diff', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='اختلاف حساب', max_digits=30)),
                ('invalids', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع تراکنش\u200cهای نامعتبر', max_digits=30)),
                ('diff_deposit', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='اختلاف حساب واریز', max_digits=30)),
                ('diff_self_trade', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='اختلاف ناشی از معامله سیستمی', max_digits=30)),
                ('diff_trade', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='اختلاف حساب معاملات', max_digits=30)),
                ('diff_withdraw', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='اختلاف حساب برداشت', max_digits=30)),
                ('giveaways', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع مبالغ اهدایی به کاربران', max_digits=30)),
                ('gateways', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='مجموع تراکنش\u200cهای درگاهی', max_digits=30)),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'verbose_name': 'آمار روزانه',
                'verbose_name_plural': 'آمار روزانه',
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
