# Generated by Django 2.2.25 on 2022-02-25 21:25

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    replaces = [('report', '0001_initial'), ('report', '0002_auto_20210506_0242'), ('report', '0003_auto_20210609_2044'), ('report', '0004_auto_20210612_1624'), ('report', '0005_auto_20210613_1753'), ('report', '0006_reportlogs_type'), ('report', '0007_auto_20210615_1425'), ('report', '0008_auto_20210618_1739'), ('report', '0009_auto_20210623_1852'), ('report', '0010_auto_20210717_1308'), ('report', '0011_auto_20210718_0930'), ('report', '0012_auto_20210928_1302'), ('report', '0013_auto_20211018_1603'), ('report', '0013_dailywithdraw_gateway_fee'), ('report', '0014_auto_20211221_1247'), ('report', '0015_auto_20220207_1850'), ('report', '0016_auto_20220208_1613'), ('report', '0017_auto_20220226_0040')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shetab', '0017_auto_20210928_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='روز')),
                ('registered_users', models.IntegerField(default=0, help_text='تعداد کاربران ثبت\u200cنام شده')),
                ('verified_users', models.IntegerField(default=0, help_text='تعداد کاربران تایید شده')),
                ('monthly_active_trade_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال ماهانه\u200c(معامله)')),
                ('daily_active_trade_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال روزانه\u200c(معامله)')),
                ('monthly_active_login_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال ماهانه\u200c(لاگین)')),
                ('daily_active_login_users', models.IntegerField(default=0, help_text='تعداد کاربران فعال روزانه\u200c(لاگین)')),
                ('verified_users_identity', models.IntegerField(default=0, help_text='تعداد کاربران تایید شده(هویت)')),
            ],
            options={
                'verbose_name': 'آمار روزانه فعالیت\u200cهای کاربران',
                'verbose_name_plural': 'آمار روزانه فعالیت\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='BanksGatewayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('gateway', models.IntegerField(choices=[(1, 'جیبیت'), (2, 'وندار'), (3, 'پی'), (3, 'پی پینگ')])),
                ('Balance', models.BigIntegerField(verbose_name='موجودی')),
                ('balance_user', models.BigIntegerField(verbose_name='موجودی کاربران')),
                ('deposit', models.BigIntegerField(verbose_name='واریز')),
                ('withdraw', models.BigIntegerField(verbose_name='برداشت')),
            ],
            options={
                'verbose_name': 'آمار درگاه\u200cهای بانکی',
                'verbose_name_plural': 'آمار درگاه\u200cهای بانکی',
                'ordering': ['-date', '-hour', 'gateway'],
                'unique_together': {('date', 'hour', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='WalletsStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')])),
                ('balance_user', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_bot', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_system', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_cold', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_hot', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_binance', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_kraken', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
                ('balance_cold_system', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=25)),
            ],
            options={
                'verbose_name': 'آمار موجودی والت\u200cها',
                'verbose_name_plural': 'آمار موجودی والت\u200cها',
                'ordering': ['-date', '-hour', 'currency'],
                'unique_together': {('date', 'hour', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(db_index=True)),
                ('to_date', models.DateField(db_index=True)),
                ('report', models.IntegerField(choices=[(0, 'سایر'), (1, 'گزارش درآمد کاربران از معرفی دوستان'), (2, 'گزارش کارمزد کل'), (3, 'گزارش کارمزد روزانه'), (4, 'گزارش کارمزد کاربران'), (5, 'گزارش عملکرد درگاهها')], db_index=True, default=0)),
                ('report_type', models.IntegerField(choices=[(0, 'Default'), (1, 'Splitted'), (2, 'Overall'), (3, 'Export')], default=0)),
                ('result', JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تاریخچه گزارشات',
                'verbose_name_plural': 'تاریخچه گزارشات',
            },
        ),
        migrations.AddConstraint(
            model_name='reportresult',
            constraint=models.UniqueConstraint(fields=('from_date', 'to_date', 'report'), name='unique_report'),
        ),
        migrations.RemoveConstraint(
            model_name='reportresult',
            name='unique_report',
        ),
        migrations.AddConstraint(
            model_name='reportresult',
            constraint=models.UniqueConstraint(fields=('from_date', 'to_date', 'report', 'report_type'), name='unique_report'),
        ),
        migrations.CreateModel(
            name='DailyAccountingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta')])),
                ('trade_fees', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='کارمزدهای معاملات')),
                ('deposits', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='برداشت\u200cها')),
                ('withdraws', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='واریزها')),
                ('wallet_balances_sum', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مجموع موجودی کیف\u200cهای پول')),
            ],
            options={
                'verbose_name': 'گزارش سند روزانه',
                'verbose_name_plural': 'گزارش سند روزانه',
            },
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report',
            field=models.IntegerField(choices=[(0, 'سایر'), (1, 'گزارش درآمد کاربران از معرفی دوستان'), (2, 'گزارش کارمزد کل'), (3, 'گزارش کارمزد روزانه'), (4, 'گزارش کارمزد کاربران'), (5, 'گزارش عملکرد درگاهها'), (6, 'گزارش کاربران ماه'), (7, '\u200cاعلانات معاملات بات\u200cها')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Splitted'), (2, 'Overall'), (3, 'Export'), (4, 'Pending')], default=0),
        ),
        migrations.AlterField(
            model_name='walletsstats',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta')]),
        ),
        migrations.CreateModel(
            name='DailyShetabDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('gateway_pk', models.CharField(max_length=70, verbose_name='شناسه درگاه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='شناسه مرجع')),
                ('user_identifier', models.CharField(max_length=50, verbose_name='هویت کاربر')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('additional_data', models.CharField(max_length=300, verbose_name='اطلاعات اضافه شده')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'In progress'), (2, 'Ready to verify'), (3, 'Failed'), (4, 'Success'), (5, 'Expired'), (6, 'Reversed')], default=0, verbose_name='وضیعت پرداخت')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(verbose_name='تاریخ تغییر')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انفضا')),
                ('payer_card', models.CharField(max_length=16, verbose_name='شماره کارت پرداخت کننده')),
                ('national_code', models.CharField(max_length=12, verbose_name='کد ملی')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shetab.ShetabDeposit')),
            ],
            options={
                'verbose_name': 'واریزی\u200cهای روزانه',
                'verbose_name_plural': 'واریزی\u200cهای روزانه',
                'unique_together': {('broker', 'gateway_pk')},
            },
        ),
        migrations.CreateModel(
            name='DailyWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('transfer_pk', models.CharField(max_length=70, unique=True, verbose_name='شناسه درگاه')),
                ('transfer_mode', models.CharField(max_length=10, verbose_name='روش انتقال')),
                ('destination', models.CharField(max_length=30, verbose_name='شبا مقصد')),
                ('destination_first_name', models.CharField(max_length=50, verbose_name='نام برداشت کننده')),
                ('destination_last_name', models.CharField(max_length=50, verbose_name='نام\u200cخانوادگی برداشت کننده')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('bank_transfer', models.CharField(max_length=20, unique=True, verbose_name='شناسه انتقال')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.WithdrawRequest')),
                ('gateway_fee', models.IntegerField(default=0, verbose_name='کارمزد درگاه')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Cancelling'), (2, 'Cancelled'), (3, 'In progress'), (4, 'Transferred'), (5, 'Failed')], default=0, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'برداشت\u200cهای روزانه',
                'verbose_name_plural': 'برداشت\u200cهای روزانه',
            },
        ),
    ]
