# Generated by Django 2.2.26 on 2022-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='additional_data',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='اطلاعات اضافه شده'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(1, 'Jibit'), (2, 'JibitV2')], verbose_name='درگاه'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='national_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='payer_card',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='broker',
            field=models.IntegerField(choices=[(1, 'Jibit'), (2, 'JibitV2')], verbose_name='درگاه'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='destination_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام صاحب شبا'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='destination_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام\u200cخانوادگی صاحب شبا'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='gateway_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='کارمزد درگاه'),
        ),
    ]
