# Generated by Django 2.2.17 on 2021-05-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanksGatewayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('gateway', models.IntegerField(choices=[(1, 'جیبیت'), (2, 'وندار'), (3, 'پی'), (3, 'پی پینگ')])),
                ('Balance', models.BigIntegerField(verbose_name='موجودی')),
                ('balance_user', models.BigIntegerField(verbose_name='موجودی کاربران')),
                ('deposit', models.BigIntegerField(verbose_name='واریز')),
                ('withdraw', models.BigIntegerField(verbose_name='برداشت')),
            ],
            options={
                'verbose_name': 'آمار درگاه\u200cهای بانکی',
                'verbose_name_plural': 'آمار درگاه\u200cهای بانکی',
                'ordering': ['-date', '-hour', 'gateway'],
                'unique_together': {('date', 'hour', 'gateway')},
            },
        ),
    ]
