# Generated by Django 2.2.21 on 2021-06-09 16:14

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210506_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(db_index=True)),
                ('to_date', models.DateField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('report_data', JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تاریخچه گزارشات',
                'verbose_name_plural': 'تاریخچه گزارشات',
            },
        ),
        migrations.AlterField(
            model_name='dailycustomersstats',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='walletsstats',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')]),
        ),
        migrations.DeleteModel(
            name='UserBalanceHistory',
        ),
    ]
