# Generated by Django 2.2.26 on 2022-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220711_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywithdraw',
            name='bank_transfer',
            field=models.CharField(max_length=20, verbose_name='شناسه انتقال'),
        ),
    ]
