# Generated by Django 2.2.21 on 2021-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210609_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogs',
            name='name',
            field=models.CharField(choices=[('user_referral', 'گزارش درآمد کاربران از معرفی دوستان'), ('other', 'سایر')], db_index=True, max_length=500),
        ),
    ]
