# Generated by Django 2.2.26 on 2022-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220803_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywithdraw',
            name='bank_transfer',
            field=models.CharField(max_length=50, verbose_name='شناسه انتقال'),
        ),
    ]
