# Generated by Django 2.2.21 on 2021-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210612_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogs',
            name='name',
            field=models.CharField(choices=[('other', 'سایر'), ('user_referral', 'گزارش درآمد کاربران از معرفی دوستان'), ('total_commission', 'گزارش کارمزد کل')], db_index=True, max_length=500),
        ),
    ]
