# Generated by Django 2.2.28 on 2022-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20220827_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
