# Generated by Django 2.2.21 on 2021-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210613_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlogs',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
