# Generated by Django 2.2.28 on 2022-10-26 14:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0104_auto_20221016_1353'),
        ('report', '0005_auto_20221025_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawDepositDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph')], verbose_name='ارز')),
                ('network', models.CharField(blank=True, max_length=200, null=True, verbose_name='شبکه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('hash', models.CharField(max_length=200, verbose_name='هش تراکنش')),
                ('system_amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='مقدار سیستم')),
                ('network_amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='مقدار شبکه')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('resolved', models.BooleanField(default=False, verbose_name='رفع شده')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.ConfirmedWalletDeposit', verbose_name='برداشت')),
                ('withdraw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.WithdrawRequest', verbose_name='واریز')),
            ],
            options={
                'verbose_name': 'گزارش تفاوت تراکنش',
                'verbose_name_plural': 'گزارش تفاوت تراکنش',
            },
        ),
    ]
