# Generated by Django 2.2.21 on 2021-06-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportlogs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogs',
            name='name',
            field=models.CharField(choices=[('other', 'سایر'), ('user_referral', 'گزارش درآمد کاربران از معرفی دوستان'), ('total_commission', 'گزارش کارمزد کل'), ('daily_commission', 'گزارش کارمزد روزانه')], db_index=True, max_length=500),
        ),
    ]
