# Generated by Django 2.2.28 on 2022-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20221026_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawdepositdiff',
            name='withdraw',
        ),
        migrations.AlterField(
            model_name='withdrawdepositdiff',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='آدرس'),
        ),
    ]
