# Generated by Django 3.2.15 on 2022-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20221029_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='نام تسک')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'INFO'), (1, 'WARNING'), (2, 'ERROR'), (3, 'CRITICAL')], default=0, verbose_name='نوع لاگ')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام لاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لاگ تسک های سلری',
                'verbose_name_plural': 'لاگ تسک های سلری',
                'ordering': ['-created_at'],
            },
        ),
    ]
