# Generated by Django 2.2.28 on 2022-12-03 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20221030_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawdepositdiff',
            name='network_amount',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0'), max_digits=20, null=True, verbose_name='مقدار شبکه'),
        ),
        migrations.AlterField(
            model_name='withdrawdepositdiff',
            name='system_amount',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0'), max_digits=20, null=True, verbose_name='مقدار سیستم'),
        ),
    ]
