# Generated by Django 2.2.21 on 2021-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210618_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogs',
            name='name',
            field=models.CharField(choices=[('other', 'سایر'), ('user_referral', 'گزارش درآمد کاربران از معرفی دوستان'), ('total_commission', 'گزارش کارمزد کل'), ('daily_commission', 'گزارش کارمزد روزانه'), ('users_commission', 'گزارش کارمزد کاربران'), ('gateway_performance', 'گزارش عملکرد درگاهها')], db_index=True, max_length=500),
        ),
    ]
