# Generated by Django 2.2.28 on 2023-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20221203_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksgatewaystats',
            name='balance_user',
            field=models.BigIntegerField(default=0, verbose_name='موجودی کاربران'),
        ),
        migrations.AlterField(
            model_name='banksgatewaystats',
            name='deposit',
            field=models.BigIntegerField(default=0, verbose_name='واریز'),
        ),
        migrations.AlterField(
            model_name='banksgatewaystats',
            name='gateway',
            field=models.IntegerField(choices=[(1, 'جیبیت'), (2, 'وندار'), (3, 'پی')]),
        ),
        migrations.AlterField(
            model_name='banksgatewaystats',
            name='withdraw',
            field=models.BigIntegerField(default=0, verbose_name='برداشت'),
        ),
    ]
