# Generated by Django 2.2.24 on 2021-07-17 08:38

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20210623_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(db_index=True)),
                ('to_date', models.DateField(db_index=True)),
                ('report', models.IntegerField(choices=[(0, 'سایر'), (1, 'گزارش درآمد کاربران از معرفی دوستان'), (2, 'گزارش کارمزد کل'), (3, 'گزارش کارمزد روزانه'), (4, 'گزارش کارمزد کاربران'), (5, 'گزارش عملکرد درگاهها')], db_index=True, default=0)),
                ('report_type', models.IntegerField(choices=[(0, 'Default'), (1, 'Splitted'), (2, 'Overall'), (3, 'Export')], default=0)),
                ('result', JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تاریخچه گزارشات',
                'verbose_name_plural': 'تاریخچه گزارشات',
            },
        ),
        migrations.DeleteModel(
            name='ReportLogs',
        ),
        migrations.AddConstraint(
            model_name='reportresult',
            constraint=models.UniqueConstraint(fields=('from_date', 'to_date', 'report'), name='unique_report'),
        ),
    ]
