# Generated by Django 2.2.24 on 2021-07-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20210717_1308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportresult',
            name='unique_report',
        ),
        migrations.AddConstraint(
            model_name='reportresult',
            constraint=models.UniqueConstraint(fields=('from_date', 'to_date', 'report', 'report_type'), name='unique_report'),
        ),
    ]
