# Generated by Django 2.2.28 on 2023-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20230221_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksgatewaystats',
            name='Balance',
        ),
        migrations.AddField(
            model_name='banksgatewaystats',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
