# Generated by Django 2.2.24 on 2021-09-28 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0017_auto_20210928_1302'),
        ('report', '0011_auto_20210718_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('transfer_pk', models.CharField(max_length=70, verbose_name='شناسه درگاه')),
                ('transfer_mode', models.CharField(max_length=10, verbose_name='روش انتقال')),
                ('destination', models.CharField(max_length=30, verbose_name='شبا مقصد')),
                ('destination_first_name', models.CharField(max_length=50, verbose_name='نام برداشت کننده')),
                ('destination_last_name', models.CharField(max_length=50, verbose_name='نام\u200cخانوادگی برداشت کننده')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(max_length=8, verbose_name='واحد پول')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('bank_transfer', models.CharField(max_length=15, verbose_name='شناسه انتقال')),
                ('state', models.CharField(max_length=15, verbose_name='وضعیت')),
                ('transferred_amount', models.BigIntegerField(verbose_name='مبلغ انتقال داده شدع')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.WithdrawRequest')),
            ],
            options={
                'verbose_name': 'برداشت\u200cهای روزانه',
                'verbose_name_plural': 'برداشت\u200cهای روزانه',
            },
        ),
        migrations.CreateModel(
            name='DailyShetabDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('gateway_pk', models.CharField(max_length=70, verbose_name='شناسه درگاه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(max_length=5, verbose_name='نوع ارز')),
                ('reference_number', models.CharField(max_length=50, verbose_name='شناسه مرجع')),
                ('user_identifier', models.CharField(max_length=50, verbose_name='هویت کاربر')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('additional_data', models.CharField(max_length=300, verbose_name='اطلاعات اضافه شده')),
                ('status', models.CharField(max_length=13, verbose_name='وضیعت پرداخت')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(verbose_name='تاریخ تغییر')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انفضا')),
                ('payer_card', models.CharField(max_length=16, verbose_name='شماره کارت پرداخت کننده')),
                ('national_code', models.CharField(max_length=12, verbose_name='کد ملی')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shetab.ShetabDeposit')),
            ],
            options={
                'verbose_name': 'واریزی\u200cهای روزانه',
                'verbose_name_plural': 'واریزی\u200cهای روزانه',
            },
        ),
    ]
