# Generated by Django 2.2.24 on 2021-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210928_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccountingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta')])),
                ('trade_fees', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='کارمزدهای معاملات')),
                ('deposits', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='برداشت\u200cها')),
                ('withdraws', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='واریزها')),
                ('wallet_balances_sum', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مجموع موجودی کیف\u200cهای پول')),
            ],
            options={
                'verbose_name': 'گزارش سند روزانه',
                'verbose_name_plural': 'گزارش سند روزانه',
            },
        ),
        migrations.AlterField(
            model_name='dailycustomersstats',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta')], verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report',
            field=models.IntegerField(choices=[(0, 'سایر'), (1, 'گزارش درآمد کاربران از معرفی دوستان'), (2, 'گزارش کارمزد کل'), (3, 'گزارش کارمزد روزانه'), (4, 'گزارش کارمزد کاربران'), (5, 'گزارش عملکرد درگاهها'), (6, 'گزارش کاربران ماه'), (7, '\u200cاعلانات معاملات بات\u200cها')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Splitted'), (2, 'Overall'), (3, 'Export'), (4, 'Pending')], default=0),
        ),
        migrations.AlterField(
            model_name='walletsstats',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta')]),
        ),
    ]
