# Generated by Django 2.2.24 on 2021-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20211018_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywithdraw',
            name='gateway_fee',
            field=models.IntegerField(default=0, verbose_name='کارمزد درگاه'),
            preserve_default=False,
        ),
    ]
