# Generated by Django 2.2.24 on 2021-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_dailywithdraw_gateway_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywithdraw',
            name='bank_transfer',
            field=models.CharField(max_length=20, verbose_name='شناسه انتقال'),
        ),
    ]
