# Generated by Django 2.2.26 on 2022-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20211221_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='شناسه مرجع'),
        ),
        migrations.AlterField(
            model_name='dailyshetabdeposit',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'In progress'), (2, 'Ready to verify'), (3, 'Failed'), (4, 'Success'), (5, 'Expired'), (6, 'Reversed')], default=0, verbose_name='وضیعت پرداخت'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyshetabdeposit',
            unique_together={('broker', 'gateway_pk')},
        ),
        migrations.RemoveField(
            model_name='dailyshetabdeposit',
            name='currency',
        ),
    ]
