# Generated by Django 2.2.26 on 2022-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20220207_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywithdraw',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='dailywithdraw',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dailywithdraw',
            name='transferred_amount',
        ),
        migrations.AddField(
            model_name='dailywithdraw',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initialized'), (1, 'Cancelling'), (2, 'Cancelled'), (3, 'In progress'), (4, 'Transferred'), (5, 'Failed')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='bank_transfer',
            field=models.CharField(max_length=20, unique=True, verbose_name='شناسه انتقال'),
        ),
        migrations.AlterField(
            model_name='dailywithdraw',
            name='transfer_pk',
            field=models.CharField(max_length=70, unique=True, verbose_name='شناسه درگاه'),
        ),
    ]
