# Generated by Django 2.2.25 on 2022-02-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_auto_20220208_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCustomersStats',
        ),
    ]
