# Generated by Django 3.2.23 on 2024-07-13 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20230221_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJibitDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'IN_PROGRESS'), (1, 'WAITING_FOR_MERCHANT_VERIFY'), (2, 'FAILED'), (3, 'SUCCESSFUL'), (4, 'ACCOUNT_PROCESSING')], default=0, verbose_name='وضعیت')),
                ('bank', models.CharField(max_length=15, verbose_name='بانک')),
                ('external_reference_number', models.CharField(max_length=50, verbose_name='شناسه یکتای جیبیت')),
                ('bank_reference_number', models.CharField(help_text='شناسه رسید بانکی، receipt_id', max_length=255, verbose_name='کد رهگیری بانک')),
                ('payment_id', models.CharField(max_length=40, verbose_name='شناسه واریز جیبیت')),
                ('merchant_reference_number', models.CharField(help_text='NA.bank_account_id, آیدی حساب بانکی کاربر در نوبیتکس', max_length=50, verbose_name='آیدی نوبیتکس')),
                ('source_identifier', models.CharField(max_length=50, verbose_name='شبای کاربر')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('destination_account_identifier', models.CharField(max_length=50, verbose_name='شبای جیبیت')),
                ('bank_raw_timestamp', models.CharField(max_length=50, verbose_name='تاریخ ایجاد در بانک')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.bankdeposit')),
                ('jibit_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shetab.jibitdeposit')),
            ],
        ),
    ]
