# Generated by Django 4.2.3 on 2024-02-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networkproviders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetBlockStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_processed_block', models.IntegerField(null=True)),
                ('min_available_block', models.IntegerField(null=True)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='networkproviders.network')),
            ],
        ),
    ]
