# Generated by Django 4.2.3 on 2024-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getblockstats',
            name='fetched_latest_block',
            field=models.IntegerField(null=True),
        ),
    ]
