# Generated by Django 4.2.3 on 2024-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_getblockstats_fetched_latest_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='getblockstats',
            name='latest_rechecked_block_processed',
            field=models.IntegerField(null=True),
        ),
    ]
