# Generated by Django 4.2.3 on 2024-12-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_getblockstats_latest_rechecked_block_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getblockstats',
            old_name='fetched_latest_block',
            new_name='latest_fetched_block',
        ),
    ]
