# Generated by Django 4.2.3 on 2025-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_rename_fetched_latest_block_getblockstats_latest_fetched_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getblockstats',
            name='latest_fetched_block',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getblockstats',
            name='latest_processed_block',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getblockstats',
            name='latest_rechecked_block_processed',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getblockstats',
            name='min_available_block',
            field=models.BigIntegerField(null=True),
        ),
    ]
