# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('accounts', '0001_nobitex2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authtoken.Token')),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('last_use', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
