# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20180521_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=25),
        ),
    ]
