# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20180531_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
