# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_requires_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (10, 'Inactive'), (20, 'Suspicious'), (30, 'Blocked'), (90, 'Verified'), (91, 'Active'), (92, 'Trusted'), (100, 'System'), (101, 'Bot'), (102, 'Staff')], default=0),
        ),
    ]
