# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='status',
            field=models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
    ]
