# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20180905_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت بانکی'},
        ),
    ]
