# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-22 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20180906_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationprofile',
            name='bank_account_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید اطلاعات بانکی'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید ایمیل'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='identity_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید هویت'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='mobile_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید موبایل'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید تلفن و آدرس'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
