# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180922_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_activity', models.DateTimeField(db_index=True)),
                ('last_trade', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
