# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_apiusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusage',
            options={'verbose_name': 'api usage', 'verbose_name_plural': 'api usage'},
        ),
    ]
