# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20181111_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='last_trade',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
