# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20181114_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankfeesh',
            name='document',
        ),
        migrations.RemoveField(
            model_name='bankfeesh',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankFeesh',
        ),
    ]
