# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20181208_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.IntegerField(choices=[(10, 'Withdraw'), (11, 'Shetab Deposit')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محدودیت کاربر',
                'verbose_name_plural': 'محدودیت کاربر',
            },
        ),
    ]
