# Generated by Django 2.1.4 on 2019-02-18 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userreferral',
            unique_together={('parent', 'child')},
        ),
    ]
