# Generated by Django 2.1.5 on 2019-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='considerations',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
