# Generated by Django 2.1.5 on 2019-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_verificationrequest_considerations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='این ملاحظات برای کاربر قابل مشاهده نیست', null=True, verbose_name='ملاحظات ادمین'),
        ),
    ]
