# Generated by Django 2.1.8 on 2019-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20190314_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
