# Generated by Django 2.1.4 on 2019-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_user_social_login_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestriction',
            name='restriction',
            field=models.IntegerField(choices=[(10, 'Withdraw'), (11, 'Shetab Deposit'), (12, 'Gateway')]),
        ),
    ]
