# Generated by Django 2.1.8 on 2019-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20190509_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (10, 'Inactive'), (20, 'Suspicious'), (30, 'Blocked'), (40, 'Level0'), (42, 'Level1P'), (44, 'Level1'), (46, 'Level2'), (90, 'Verified'), (91, 'Active'), (92, 'Trusted'), (99, 'Nobitex'), (100, 'System'), (101, 'Bot'), (102, 'Staff')], default=0),
        ),
    ]
