# Generated by Django 2.1.8 on 2019-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20190621_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='این ملاحظات برای کاربر قابل مشاهده نیست', null=True, verbose_name='ملاحظات ادمین'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='این ملاحظات برای کاربر قابل مشاهده نیست', null=True, verbose_name='ملاحظات ادمین'),
        ),
    ]
