# Generated by Django 2.1.8 on 2019-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190622_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestriction',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='این ملاحظات برای کاربر قابل مشاهده نیست', null=True, verbose_name='ملاحظات ادمین'),
        ),
    ]
