# Generated by Django 2.1.8 on 2019-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_userrestriction_considerations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestriction',
            name='restriction',
            field=models.IntegerField(choices=[(10, 'Withdraw'), (11, 'Shetab Deposit'), (12, 'Gateway'), (13, 'Trading')]),
        ),
    ]
