# Generated by Django 2.1.9 on 2019-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20190624_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationprofile',
            name='selfie_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید سلفی'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Identity'), (2, 'Address'), (3, 'Selfie')], verbose_name='Request Type'),
        ),
    ]
