# Generated by Django 2.1.8 on 2019-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationprofile',
            name='mobile_identity_confirmed',
            field=models.BooleanField(null=True, default=None, verbose_name='تایید هویت صاحب موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (10, 'Inactive'), (20, 'Suspicious'), (30, 'Blocked'), (40, 'Level0'), (42, 'Level1P'), (44, 'Level1'), (46, 'Level2'), (90, 'Level3'), (91, 'Active'), (92, 'Trusted'), (99, 'Nobitex'), (100, 'System'), (101, 'Bot'), (102, 'Staff')], default=0),
        ),
    ]
