# Generated by Django 2.1.9 on 2019-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20190702_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='api_verification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='api_verification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
