# Generated by Django 2.1.10 on 2019-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20190707_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
