# Generated by Django 2.1.10 on 2019-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_user_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='api_verification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
