# Generated by Django 2.1.10 on 2019-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_verificationrequest_api_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان ها', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'تنظیمات کاربر', 'verbose_name_plural': 'تنظیمات کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userreferral',
            options={'verbose_name': 'ارجاع کاربر', 'verbose_name_plural': 'ارجاع کاربر'},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={'verbose_name': 'پیامک کاربر', 'verbose_name_plural': 'پیامک کاربر'},
        ),
        migrations.AddField(
            model_name='userreferral',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='referral_share',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
