# Generated by Django 2.1.10 on 2019-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20190801_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusage',
            options={'verbose_name': 'استفاده کاربر از API', 'verbose_name_plural': 'استفاده کاربر از API'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'verbose_name': 'تلاش برای ورود', 'verbose_name_plural': 'تلاش برای ورود'},
        ),
        migrations.AlterField(
            model_name='usersms',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Manual SMS'), (1, 'Verify Phone'), (2, 'Verify Withdraw')]),
        ),
    ]
