# Generated by Django 2.1.10 on 2019-08-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20190804_2203'),
        ('accounts', '0061_auto_20190806_1218'),
    ]

    operations = [
    ]
