# Generated by Django 2.1.11 on 2019-08-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_merge_20190806_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
