# Generated by Django 2.1.11 on 2019-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20190809_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='kv_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='kv_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
