# Generated by Django 2.1.11 on 2019-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20190818_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersms',
            name='template',
            field=models.IntegerField(blank=True, choices=[(0, 'پیش\u200cفرض'), (6816, 'به نوبیتکس خوش آمدید . کد تایید عضویت شما : [VerificationCode] '), (3065, 'کد تایید شما در سایت نوبیتکس [VerificationCode] است ')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersms',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Manual SMS'), (1, 'Verify Phone'), (2, 'Verify Withdraw'), (3, 'Process')]),
        ),
    ]
