# Generated by Django 2.1.14 on 2019-11-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190823_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_fee_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='base_maker_fee_usdt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userrestriction',
            name='restriction',
            field=models.IntegerField(choices=[(10, 'Withdraw'), (11, 'Shetab Deposit'), (12, 'Gateway'), (13, 'Trading'), (14, 'Withdraw Coin'), (15, 'Withdraw Rial')]),
        ),
        migrations.AlterField(
            model_name='usersms',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Manual SMS'), (1, 'Verify Phone'), (2, 'Verify Withdraw'), (3, 'Process'), (4, 'android')]),
        ),
    ]
