# Generated by Django 2.1.14 on 2019-12-08 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20191120_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'Trader')])),
                ('date_from', models.DateTimeField(db_index=True, verbose_name='تاریخ شروع')),
                ('date_to', models.DateTimeField(db_index=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال؟')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طرح\u200cهای ویژه',
                'verbose_name_plural': 'طرح\u200cهای ویژه',
            },
        ),
    ]
