# Generated by Django 2.1.14 on 2019-12-22 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
