# Generated by Django 2.1.14 on 2020-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20200203_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusage',
            options={'verbose_name': 'وضعیت کاربر', 'verbose_name_plural': 'وضعیت کاربر'},
        ),
        migrations.AddField(
            model_name='apiusage',
            name='app_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='last_app_signal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='last_web_signal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='web_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.IntegerField(blank=True, choices=[(10, 'بانک\u200cمرکزی'), (11, 'صنعت\u200cو\u200cمعدن'), (12, 'ملت'), (13, 'رفاه'), (14, 'مسکن'), (15, 'سپه'), (16, 'کشاورزی'), (17, 'ملی'), (18, 'تجارت'), (19, 'صادرات'), (20, 'توسعه\u200cصادرات'), (21, 'پست\u200cبانک'), (22, 'توسعه\u200cتعاون'), (51, 'موسسه\u200cاعتباری\u200cتوسعه'), (52, 'قوامین'), (53, 'کار\u200cآفرین'), (54, 'پارسیان'), (55, 'اقتصاد\u200cنوین'), (56, 'سامان'), (57, 'پاسارگاد'), (58, 'سرمایه'), (59, 'سینا'), (60, 'مهر\u200cایران'), (61, 'شهر'), (62, 'آینده'), (63, 'انصار'), (64, 'گردشگری'), (65, 'حکمت\u200cایرانیان'), (66, 'دی'), (69, 'ایران\u200cزمین'), (70, 'رسالت'), (73, 'کوثر'), (75, 'موسسه\u200cملل'), (78, 'خاورمیانه'), (80, 'موسسه\u200cنور')], help_text='شناسه بانک', null=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='bank_id',
            field=models.IntegerField(blank=True, choices=[(10, 'بانک\u200cمرکزی'), (11, 'صنعت\u200cو\u200cمعدن'), (12, 'ملت'), (13, 'رفاه'), (14, 'مسکن'), (15, 'سپه'), (16, 'کشاورزی'), (17, 'ملی'), (18, 'تجارت'), (19, 'صادرات'), (20, 'توسعه\u200cصادرات'), (21, 'پست\u200cبانک'), (22, 'توسعه\u200cتعاون'), (51, 'موسسه\u200cاعتباری\u200cتوسعه'), (52, 'قوامین'), (53, 'کار\u200cآفرین'), (54, 'پارسیان'), (55, 'اقتصاد\u200cنوین'), (56, 'سامان'), (57, 'پاسارگاد'), (58, 'سرمایه'), (59, 'سینا'), (60, 'مهر\u200cایران'), (61, 'شهر'), (62, 'آینده'), (63, 'انصار'), (64, 'گردشگری'), (65, 'حکمت\u200cایرانیان'), (66, 'دی'), (69, 'ایران\u200cزمین'), (70, 'رسالت'), (73, 'کوثر'), (75, 'موسسه\u200cملل'), (78, 'خاورمیانه'), (80, 'موسسه\u200cنور')], help_text='شناسه بانک', null=True),
        ),
    ]
