# Generated by Django 2.1.15 on 2020-02-26 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20200211_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoiceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tp', models.IntegerField(choices=[(0, 'Manual message'), (1, 'Verify Phone')])),
                ('to', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('delivery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_voice_message_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام صوتی',
                'verbose_name_plural': 'پیام صوتی',
            },
        ),
        migrations.AddField(
            model_name='verificationprofile',
            name='phone_code_confirmed',
            field=models.BooleanField(null=True, default=False, verbose_name='تایید خودکار تلفن'),
        ),
    ]
