# Generated by Django 2.1.15 on 2020-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_auto_20200226_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersms',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersms',
            name='provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
