# Generated by Django 2.1.15 on 2020-03-17 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0073_auto_20200226_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consideration', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'ملاحظات پشتیبانی',
                'verbose_name_plural': 'ملاحظات پشتیبانی',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserActionLog', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'تاریخچه فعالیت\u200cهای پشتیبانی',
                'verbose_name_plural': 'تاریخچه فعالیت\u200cهای پشتیبانی',
            },
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': [('view_bank_account', 'Can view bank account'), ('accept_bank_account', 'Can accept bank account'), ('reject_bank_account', 'Can reject bank account'), ('view_bank_account_status', 'Can view bank account status'), ('bank_account_status_update', 'Can update bank account status')], 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'permissions': [('view_card', 'Can view page card'), ('accept_card', 'Can accept card'), ('reject_card', 'Can reject card'), ('view_card_status', 'Can view card request status'), ('card_status_update', 'Can update card request status')], 'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت بانکی'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('view_notifications', 'Can view notification'), ('send_notification', 'Can send notification')], 'verbose_name': 'اعلان ها', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'Can view users list'), ('view_user_info', 'Can view user information'), ('edit_user_info', 'Can edit user info')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userrestriction',
            options={'permissions': [('view_user_restriction', 'Can view user restriction'), ('edit_user_restriction', 'Can edit user restriction')], 'verbose_name': 'محدودیت کاربر', 'verbose_name_plural': 'محدودیت کاربر'},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={'permissions': [('view_user_sms', 'Can view user sms'), ('send_user_sms', 'Can send sms')], 'verbose_name': 'پیامک کاربر', 'verbose_name_plural': 'پیامک کاربر'},
        ),
        migrations.AlterModelOptions(
            name='uservoicemessage',
            options={'permissions': [('view_voice_message', 'Can view voice message'), ('send_voice_message', 'Can send voice message')], 'verbose_name': 'پیام صوتی', 'verbose_name_plural': 'پیام صوتی'},
        ),
        migrations.AlterModelOptions(
            name='verificationprofile',
            options={'permissions': [('view_verification_profile', 'Can view verification profile'), ('view_email_confirm', 'Can view email confirmed'), ('accept_email_confirm', 'Can accept email confirm'), ('reject_email_confirm', 'Can reject email_confirm'), ('view_mobile_confirm', 'Can view mobile confirmed'), ('accept_mobile_confirm', 'Can accept mobile_confirm'), ('reject_mobile_confirm', 'Can reject mobile confirm'), ('view_identity_confirm', 'Can view identity confirm'), ('accept_identity_confirm', 'Can accept identity confirm'), ('reject_identity_confirm', 'Can reject identity confirm'), ('view_phone_confirm', 'Can view phone confirm'), ('accept_phone_confirm', 'Can accept phone confirm'), ('reject_phone_confirm', 'Can reject phone confirm')], 'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'permissions': [('view_verification_request', 'Can view verification request'), ('accept_verification_request', 'Can accept verification request'), ('reject_verification_request', 'Can reject verification request'), ('verification_request_status', 'Can verification request status'), ('verification_request_status_update', 'Can update verification request status')], 'verbose_name': 'درخواست تایید هویت', 'verbose_name_plural': 'درخواست تایید هویت'},
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')], null=True),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_action_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminconsideration',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin_consideration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminconsideration',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_admin_consideration', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='adminconsideration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consideration', to=settings.AUTH_USER_MODEL),
        ),
    ]
