# Generated by Django 2.1.15 on 2020-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_auto_20200317_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': [('view_bank_account', 'نمایش اطلاعات بانکی'), ('accept_bank_account', 'تایید اطلاعات بانکی'), ('reject_bank_account', 'رد کردن اطلاعات بانکی'), ('view_bank_account_status', 'نمایش استعلام اطلاعات بانکی'), ('bank_account_status_update', 'استعلام مجدد اطلاعات بانکی')], 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'permissions': [('view_card', 'نمایش کارت بانکی'), ('accept_card', 'تایید کارت بانکی'), ('reject_card', 'رد کردن کارت بانکی'), ('view_card_status', 'نمایش استعلام کارت بانکی'), ('card_status_update', 'استعلام مجدد کارت بانکی')], 'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت بانکی'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('view_notifications', 'نمایش اعلان\u200cها'), ('send_notification', 'ارسال اعلان')], 'verbose_name': 'اعلان\u200cها', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('edit_user_info', 'ویرایش اطلاعات کاربر')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userrestriction',
            options={'permissions': [('view_user_restriction', 'نمایش محدودیت های کاربر'), ('edit_user_restriction', 'ویرایش محدودیت های کاربر')], 'verbose_name': 'محدودیت کاربر', 'verbose_name_plural': 'محدودیت کاربر'},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={'permissions': [('view_user_sms', 'نمایش پیام کوتاه'), ('send_user_sms', 'ارسال پیام کوتاه')], 'verbose_name': 'پیامک کاربر', 'verbose_name_plural': 'پیامک کاربر'},
        ),
        migrations.AlterModelOptions(
            name='uservoicemessage',
            options={'permissions': [('view_voice_message', 'نمایش پیام صوتی'), ('send_voice_message', 'ارسال پیام صوتی')], 'verbose_name': 'پیام صوتی', 'verbose_name_plural': 'پیام صوتی'},
        ),
        migrations.AlterModelOptions(
            name='verificationprofile',
            options={'permissions': [('view_verification_profile', 'نمایش پروفایل تایید هویت'), ('view_email_confirm', 'نمایش وضعیت تایید ایمیل'), ('accept_email_confirm', 'تایید ایمیل '), ('reject_email_confirm', 'رد کردن ایمیل'), ('view_mobile_confirm', 'نمایش وضعیت تایید'), ('accept_mobile_confirm', 'تایید شماره موبایل'), ('reject_mobile_confirm', 'رد کردن شماره موبایل'), ('view_identity_confirm', 'نمایش وضعیت تایید اطلاعات هویتی'), ('accept_identity_confirm', 'تایید اطلاعات هویتی'), ('reject_identity_confirm', 'رد اطلاعات هویتی'), ('view_phone_confirm', 'نمایش وضعیت تایید تلفن'), ('accept_phone_confirm', 'تایید تلفن'), ('reject_phone_confirm', 'رد کردن تلفن')], 'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'permissions': [('view_verification_request', 'نمایش درخواست تایید'), ('accept_verification_request', 'تایید درخواست تایید'), ('reject_verification_request', 'رد کردن درخواست تایید'), ('verification_request_status', 'نمایش استعلام درخواست تایید'), ('verification_request_status_update', 'استعلام مجدد درخواست تایید')], 'verbose_name': 'درخواست تایید هویت', 'verbose_name_plural': 'درخواست تایید هویت'},
        ),
    ]
