# Generated by Django 2.1.15 on 2020-03-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_auto_20200323_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreferral',
            options={'permissions': [('user_referral_view', 'نمایش ارجاع کاربر'), ('user_referral_edit', 'ویرایش معرف')], 'verbose_name': 'ارجاع کاربر', 'verbose_name_plural': 'ارجاع کاربر'},
        ),
    ]
