# Generated by Django 2.1.15 on 2020-05-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_auto_20200415_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش دیف کاربر'), ('user_report_balance', 'گزارش موجودی کاربر'), ('user_report_deposits', 'گزارش واریزهای کاربر'), ('user_report_withdraws', 'گزارش برداشت\u200cهای کاربر'), ('user_report_transactions', 'گزارش تراکنش\u200cهای کاربر'), ('user_2fa_view', 'نمایش مدیریت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
    ]
