# Generated by Django 2.2.13 on 2020-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_auto_20200516_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
