# Generated by Django 2.2.13 on 2020-06-25 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_auto_20200608_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='date_from',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Trader')], verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
