# Generated by Django 2.2.13 on 2020-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20200625_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplan',
            options={'verbose_name': 'پلن کاربر', 'verbose_name_plural': 'پلن کاربر'},
        ),
        migrations.AlterField(
            model_name='userplan',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
    ]
