# Generated by Django 2.2.13 on 2020-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_auto_20200625_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='plan',
        ),
        migrations.AddField(
            model_name='userplan',
            name='type',
            field=models.IntegerField(choices=[(1, 'Trader')], default=None, verbose_name='پلن'),
            preserve_default=False,
        ),
    ]
