# Generated by Django 2.2.13 on 2020-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_auto_20200625_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='kv_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (10, 'Inactive'), (20, 'Suspicious'), (30, 'Blocked'), (40, 'Level0'), (42, 'Level1P'), (44, 'Level1'), (45, 'Trader'), (46, 'Level2'), (90, 'Level3'), (91, 'Active'), (92, 'Trusted'), (99, 'Nobitex'), (100, 'System'), (101, 'Bot'), (102, 'Staff')], default=0),
        ),
    ]
