# Generated by Django 2.2.14 on 2020-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_auto_20200625_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
