# Generated by Django 2.2.14 on 2020-07-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20200704_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='child_referral_share',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='سهم child'),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_share',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='سهم parent'),
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_share', models.IntegerField(blank=True, default=0, help_text='درصد', null=True, verbose_name='سهم کاربر')),
                ('friend_share', models.IntegerField(blank=True, default=0, help_text='درصد', null=True, verbose_name='سهم دوست')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referral_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طرح معرف',
                'verbose_name_plural': 'طرح معرف',
            },
        ),
        migrations.AddField(
            model_name='userreferral',
            name='referral_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referrals', to='accounts.ReferralProgram'),
        ),
    ]
