# Generated by Django 2.2.14 on 2020-07-15 09:18

from django.db import migrations


def create_referral_program(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    ReferralProgram = apps.get_model('accounts', 'ReferralProgram')
    UserReferral = apps.get_model('accounts', 'UserReferral')

    users = User.objects.filter(referral_code__isnull=False)
    for user in users:
        referral_program = ReferralProgram.objects.create(
            user=user,
            user_share=30,
            friend_share=0,
            referral_code=user.referral_code,
        )
        user_referrals = UserReferral.objects.filter(parent=user)
        user_referrals.update(referral_program=referral_program, child_referral_share=0)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20200714_1630_squashed_0086_auto_20200715_0044'),
    ]
    operations = [
        migrations.RunPython(create_referral_program)
    ]
