# Generated by Django 2.2.14 on 2020-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20200715_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'permissions': [('view_bank_account', 'نمایش لیست اطلاعات بانکی'), ('accept_bank_account', 'تایید اطلاعات بانکی'), ('reject_bank_account', 'رد کردن اطلاعات بانکی'), ('view_bank_account_status', 'نمایش وضعیت استعلام اطلاعات بانکی'), ('bank_account_status_update', 'استعلام مجدد اطلاعات بانکی')], 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'permissions': [('view_card', 'نمایش لیست کارت\u200cهای بانکی'), ('accept_card', 'تایید کارت بانکی'), ('reject_card', 'رد کردن کارت بانکی'), ('view_card_status', 'نمایش وضعیت استعلام کارت بانکی'), ('card_status_update', 'استعلام مجدد کارت بانکی')], 'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت بانکی'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('view_notifications', 'نمایش لیست اعلان\u200cها'), ('send_notification', 'ارسال اعلان')], 'verbose_name': 'اعلان\u200cها', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='referralprogram',
            options={'verbose_name': 'لینک ریفرال', 'verbose_name_plural': 'لینک ریفرال'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش خلاصه وضعیت'), ('user_report_balance', 'گزارش موجودی'), ('user_report_deposits', 'گزارش واریزها'), ('user_report_withdraws', 'گزارش برداشت\u200cها'), ('user_report_transactions', 'گزارش تراکنش\u200cها'), ('user_2fa_view', 'نمایش مدیریت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی'), ('user_email_send', 'ارسال ایمیل به کاربران'), ('user_email_view', 'نمایش لیست ایمیل های کاربران'), ('user_bank_deposit_edit_status', 'ویرایش واریزهای بانکی'), ('user_bank_deposit_view', 'نمایش لیست واریزهای بانکی'), ('user_call', 'ثبت تماس با کاربر'), ('user_call_successful', 'تماس موفق با کاربر'), ('user_call_missed', 'تماس ناموفق با کاربر'), ('management_menu', 'منوی مدیریت'), ('deposit_refund', 'عودت واریزها شتابی')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'verbose_name': 'طرح\u200cهای ویژه', 'verbose_name_plural': 'طرح\u200cهای ویژه'},
        ),
        migrations.AlterModelOptions(
            name='userreferral',
            options={'permissions': [('user_referral_view', 'نمایش لیست ارجاع کاربر'), ('user_referral_edit', 'ویرایش معرف')], 'verbose_name': 'ارجاع کاربر', 'verbose_name_plural': 'ارجاع کاربر'},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={'permissions': [('view_user_sms', 'نمایش لیست پیام\u200cهای کوتاه'), ('send_user_sms', 'ارسال پیام کوتاه')], 'verbose_name': 'پیامک کاربر', 'verbose_name_plural': 'پیامک کاربر'},
        ),
        migrations.AlterModelOptions(
            name='uservoicemessage',
            options={'permissions': [('view_voice_message', 'نمایش لیست پیام\u200cهای صوتی'), ('send_voice_message', 'ارسال پیام صوتی')], 'verbose_name': 'پیام صوتی', 'verbose_name_plural': 'پیام صوتی'},
        ),
        migrations.AlterModelOptions(
            name='verificationprofile',
            options={'permissions': [('view_verification_profile', 'نمایش پروفایل احراز هویت'), ('view_email_confirm', 'نمایش وضعیت احراز ایمیل'), ('accept_email_confirm', 'تایید ایمیل '), ('reject_email_confirm', 'رد کردن ایمیل'), ('view_mobile_confirm', 'نمایش وضعیت احراز شماره موبایل'), ('accept_mobile_confirm', 'تایید شماره موبایل'), ('reject_mobile_confirm', 'رد کردن شماره موبایل'), ('view_identity_confirm', 'نمایش وضعیت احراز اطلاعات هویتی'), ('accept_identity_confirm', 'تایید اطلاعات هویتی'), ('reject_identity_confirm', 'رد اطلاعات هویتی'), ('view_phone_confirm', 'نمایش وضعیت احراز شماره تلفن'), ('accept_phone_confirm', 'تایید تلفن'), ('reject_phone_confirm', 'رد کردن تلفن')], 'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'permissions': [('view_verification_request', 'نمایش احراز مدارک هویتی'), ('accept_verification_request', 'تایید مدارک هویتی'), ('reject_verification_request', 'رد کردن مدارک هویتی'), ('verification_request_status', 'نمایش وضعیت استعلام مدارک هویتی'), ('verification_request_status_update', 'استعلام مجدد مدارک هویتی')], 'verbose_name': 'درخواست تایید هویت', 'verbose_name_plural': 'درخواست تایید هویت'},
        ),
        migrations.RemoveField(
            model_name='referralprogram',
            name='note',
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='friend_share',
            field=models.IntegerField(default=0, help_text='درصد', verbose_name='سهم کاربر دعوت شده'),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='referral_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='user_share',
            field=models.IntegerField(help_text='درصد', verbose_name='سهم معرف'),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='child_referral_share',
            field=models.IntegerField(default=0, verbose_name='سهم کاربر دعوت شده'),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_share',
            field=models.IntegerField(default=0, verbose_name='سهم معرف'),
        ),
        migrations.AlterUniqueTogether(
            name='userreferral',
            unique_together=set(),
        ),
    ]
