# Generated by Django 2.2.14 on 2020-08-10 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_auto_20200721_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=31, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'db_table': 'accounts_tags',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_users', to='accounts.Tag', verbose_name='برچسب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برچسب\u200cکاربر',
                'verbose_name_plural': 'برچسب\u200cهای کاربران',
                'db_table': 'accounts_users_tags',
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tags', through='accounts.UserTag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب\u200cها'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=63, unique=True, verbose_name='نام'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usertag',
            table=None,
        ),
    ]
