# Generated by Django 2.2.14 on 2020-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_users_tags_squashed_0090_users_tags_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش خلاصه وضعیت'), ('user_report_balance', 'گزارش موجودی'), ('user_report_deposits', 'گزارش واریزها'), ('user_report_withdraws', 'گزارش برداشت\u200cها'), ('user_report_transactions', 'گزارش تراکنش\u200cها'), ('user_report_orders', 'گزارش معاملات'), ('user_report_profits', 'گزارش سود و زیان'), ('user_2fa_view', 'نمایش مدیریت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی'), ('user_email_send', 'ارسال ایمیل به کاربران'), ('user_email_view', 'نمایش لیست ایمیل های کاربران'), ('user_bank_deposit_edit_status', 'ویرایش واریزهای بانکی'), ('user_bank_deposit_view', 'نمایش لیست واریزهای بانکی'), ('user_bank_deposit_edit', 'ویرایش واریزهای بانکی'), ('user_call', 'ثبت تماس با کاربر'), ('user_call_successful', 'تماس موفق با کاربر'), ('user_call_missed', 'تماس ناموفق با کاربر'), ('management_menu', 'منوی مدیریت'), ('deposit_refund', 'عودت واریزها شتابی'), ('user_report_fee', 'گزارش کارمزد'), ('user_deactivation', 'غیر فعال سازی کاربر')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=63, unique=True, verbose_name='نام'),
        ),
    ]
