# Generated by Django 2.2.14 on 2020-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20200926_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertag',
            options={'verbose_name': 'برچسب کاربر', 'verbose_name_plural': 'برچسب\u200cهای کاربران'},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
