# Generated by Django 2.2.12 on 2020-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20201103_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_bots_overview', 'بررسی بات\u200cها'), ('excel_bots_overview', 'دانلود گزارش بات\u200cها')]},
        )
    ]
