# Generated by Django 2.2.16 on 2020-11-17 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_auto_20201116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestriction',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
