# Generated by Django 2.2.12 on 2020-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_auto_20201117_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('setting_bots_overview', 'تنظیمات بات\u200cهای بازارگردان')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        )
    ]
