# Generated by Django 2.2.17 on 2020-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_auto_20201122_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('view_sensitive_user_info', 'نمایش اطلاعات کاربر حساس'), ('view_user_sensitive_info', 'مشاهده\u200cی اطلاعات حساس کاربران'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش خلاصه وضعیت'), ('user_report_balance', 'گزارش موجودی'), ('user_report_deposits', 'گزارش واریزها'), ('user_report_withdraws', 'گزارش برداشت\u200cها'), ('user_report_transactions', 'گزارش تراکنش\u200cها'), ('user_report_orders', 'گزارش معاملات'), ('user_report_profits', 'گزارش سود و زیان'), ('user_2fa_view', 'نمایش وضعیت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی'), ('user_email_send', 'ارسال ایمیل به کاربران'), ('user_email_view', 'نمایش لیست ایمیل های کاربران'), ('user_bank_deposit_edit_status', 'تایید واریزهای بانکی'), ('user_bank_deposit_view', 'نمایش لیست واریزهای بانکی'), ('user_bank_deposit_edit', 'ویرایش واریزهای بانکی'), ('user_call', 'ثبت تماس با کاربر'), ('user_call_successful', 'تماس موفق با کاربر'), ('user_call_missed', 'تماس ناموفق با کاربر'), ('management_menu', 'مشاهده گزینه\u200cهای منوی مدیریتی'), ('system_settings_direct_management', 'مدیریت مستقیم تنظیمات سیستم'), ('system_settings_rial_settlement', 'مدیریت تنظیمات تسویه\u200cی ریالی'), ('system_settings_usd_value', 'مدیریت تنظیمات قیمت دلار'), ('system_nodes_management', 'مدیریت نودها'), ('deposit_refund', 'عودت واریزهای شتابی'), ('system_settings_shetab_deposit_backend', 'مدیریت تنظیمات درگاه پرداخت شتابی'), ('user_report_fee', 'گزارش کارمزد'), ('user_deactivation', 'غیر فعال سازی کاربر'), ('user_refresh_deposit', 'بررسی مجدد واریزهای کاربر'), ('user_sync_shetab_deposit', 'بررسی مجدد واریز شتابی'), ('user_tag_manage', 'مدیریت برچسب\u200cها'), ('view_bots_overview', 'گزارش عملکرد بات\u200cهای بازارگردان'), ('setting_bots_overview', 'تنظیمات بات\u200cهای بازارگردان')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userreferral',
            options={'permissions': [('user_referral_view', 'گزارش طرح معرفی دوستان'), ('user_referral_edit', 'ویرایش معرف کاربر')], 'verbose_name': 'ارجاع کاربر', 'verbose_name_plural': 'ارجاع کاربر'},
        ),
        migrations.AlterModelOptions(
            name='verificationprofile',
            options={'permissions': [('view_verification_profile', 'نمایش پروفایل احراز هویت'), ('view_email_confirm', 'نمایش وضعیت احراز ایمیل'), ('accept_email_confirm', 'تایید ایمیل '), ('reject_email_confirm', 'رد کردن ایمیل'), ('view_mobile_confirm', 'نمایش وضعیت احراز شماره موبایل'), ('mobile_confirm_update', 'استعلام مجدد احراز شماره موبایل'), ('accept_mobile_confirm', 'تایید شماره موبایل'), ('reject_mobile_confirm', 'رد کردن شماره موبایل'), ('view_identity_confirm', 'نمایش وضعیت احراز اطلاعات هویتی'), ('accept_identity_confirm', 'تایید اطلاعات هویتی'), ('reject_identity_confirm', 'رد اطلاعات هویتی'), ('view_phone_confirm', 'نمایش وضعیت احراز شماره تلفن'), ('accept_phone_confirm', 'تایید تلفن'), ('reject_phone_confirm', 'رد کردن تلفن')], 'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'permissions': [('view_verification_request', 'نمایش احراز مدارک هویتی'), ('accept_verification_request', 'تایید مدارک هویتی'), ('reject_verification_request', 'رد کردن مدارک هویتی'), ('verification_request_status', 'نمایش وضعیت استعلام مدارک هویتی'), ('verification_request_status_update', 'استعلام مجدد مدارک هویتی'), ('view_verification_stats', 'مشاهده آمار احراز هویت')], 'verbose_name': 'درخواست تایید هویت', 'verbose_name_plural': 'درخواست تایید هویت'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
