# Generated by Django 2.2.17 on 2020-12-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_auto_20201125_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('view_sensitive_user_info', 'نمایش اطلاعات کاربر حساس'), ('view_user_sensitive_info', 'مشاهده\u200cی اطلاعات حساس کاربران'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش خلاصه وضعیت'), ('user_report_balance', 'گزارش موجودی'), ('user_report_deposits', 'گزارش واریزها'), ('user_report_withdraws', 'گزارش برداشت\u200cها'), ('user_report_transactions', 'گزارش تراکنش\u200cها'), ('user_report_orders', 'گزارش معاملات'), ('user_report_profits', 'گزارش سود و زیان'), ('user_2fa_view', 'نمایش وضعیت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی'), ('user_email_send', 'ارسال ایمیل به کاربران'), ('user_email_view', 'نمایش لیست ایمیل های کاربران'), ('user_bank_deposit_edit_status', 'تایید واریزهای بانکی'), ('user_bank_deposit_view', 'نمایش لیست واریزهای بانکی'), ('user_bank_deposit_edit', 'ویرایش واریزهای بانکی'), ('user_call', 'ثبت تماس با کاربر'), ('user_call_successful', 'تماس موفق با کاربر'), ('user_mobile_call_successful', 'تماس موفق با همراه کاربر'), ('user_call_missed', 'تماس ناموفق با کاربر'), ('user_mobile_call_missed', 'تماس ناموفق با همراه کاربر'), ('management_menu', 'مشاهده گزینه\u200cهای منوی مدیریتی'), ('system_settings_direct_management', 'مدیریت مستقیم تنظیمات سیستم'), ('system_settings_rial_settlement', 'مدیریت تنظیمات تسویه\u200cی ریالی'), ('system_settings_usd_value', 'مدیریت تنظیمات قیمت دلار'), ('system_nodes_management', 'مدیریت نودها'), ('deposit_refund', 'عودت واریزهای شتابی'), ('system_settings_shetab_deposit_backend', 'مدیریت تنظیمات درگاه پرداخت شتابی'), ('user_report_fee', 'گزارش کارمزد'), ('user_deactivation', 'غیر فعال سازی کاربر'), ('user_refresh_deposit', 'بررسی مجدد واریزهای کاربر'), ('user_sync_shetab_deposit', 'بررسی مجدد واریز شتابی'), ('user_tag_manage', 'مدیریت برچسب\u200cها'), ('view_bots_overview', 'گزارش عملکرد بات\u200cهای بازارگردان'), ('setting_bots_overview', 'تنظیمات بات\u200cهای بازارگردان')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
    ]
