# Generated by Django 2.2.17 on 2020-12-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_auto_20201125_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_to_fcm',
            field=models.BooleanField(default=False, null=True),
        )
    ]
