# Generated by Django 2.2.16 on 2020-12-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20201208_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestrictionRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_restriction_removals', to=settings.AUTH_USER_MODEL)),
                ('restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_removals', to='accounts.UserRestriction')),
            ],
        ),
    ]
