# Generated by Django 2.2.17 on 2020-12-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_auto_20201219_1908'),
        ('accounts', '0096_add_fcm_sent_notification'),
    ]

    operations = [
    ]
