# Generated by Django 2.2.17 on 2021-02-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_merge_20201230_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('otp_type', models.IntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')])),
                ('otp_usage', models.IntegerField(choices=[(1, 'TFA Removal')])),
                ('otp_status', models.IntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')], default=1)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف کاربر',
                'verbose_name_plural': 'کدهای یکبار مصرف کاربر',
                'unique_together': {('user', 'otp_type', 'code')},
            },
        ),
    ]
