# Generated by Django 2.2.17 on 2021-02-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_usage',
            field=models.IntegerField(blank=True, choices=[(1, 'TFA Removal'), (2, 'Email Verification')], null=True),
        )
    ]
