# Generated by Django 2.2.17 on 2021-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_user_otp_nullable_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_usage',
            field=models.IntegerField(blank=True, choices=[(1, 'TFA Removal'), (2, 'Email Verification'), (3, 'Generic')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userotp',
            unique_together=set(),
        ),
    ]
