# Generated by Django 2.2.20 on 2021-04-13 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_merge_20201230_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'غیر فعال سازی دوعاملی'), (2, 'اعمال محدودیت کاربر'), (3, 'افزودن مجوز برداشت'), (4, 'حذف محدودیت'), (5, 'افزودن تراکنش دستی'), (6, 'افزودن درخواست برداشت'), (7, 'رد کردن درخواست برداشت'), (8, 'حذف مجوز برداشت'), (9, 'غیرفعال کردن آدرس ولت'), (10, 'ثبت دستی واریز رمزارز'), (11, 'ویرایش واریز شتابی'), (12, 'ویرایش واریزهای بانکی'), (13, 'افزودن تراکنش')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
