# Generated by Django 2.2.17 on 2021-05-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_user_otp_remove_code_unique_restriction'),
        ('accounts', '0102_auto_20210413_2238'),
    ]

    operations = [
    ]
