# Generated by Django 2.2.19 on 2021-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_auto_20210413_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی'),
        ),
    ]
