# Generated by Django 2.2.20 on 2021-04-26 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_auto_20210420_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date', models.DateTimeField(default=datetime.date(2021, 4, 25))),
                ('total_buy_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('total_sell_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('total_sell_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_total_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_total_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_total_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users_list', 'نمایش لیست کاربران'), ('view_user_info', 'نمایش اطلاعات کاربر'), ('view_sensitive_user_info', 'نمایش اطلاعات کاربر حساس'), ('view_user_sensitive_info', 'مشاهده\u200cی اطلاعات حساس کاربران'), ('edit_user_info', 'ویرایش اطلاعات کاربر'), ('user_report_diff', 'گزارش خلاصه وضعیت'), ('user_report_balance', 'گزارش موجودی'), ('user_report_deposits', 'گزارش واریزها'), ('user_report_withdraws', 'گزارش برداشت\u200cها'), ('user_report_transactions', 'گزارش تراکنش\u200cها'), ('user_report_orders', 'گزارش معاملات'), ('user_report_active_orders', 'گزارش سفارش\u200cهای باز'), ('user_report_profits', 'گزارش سود و زیان'), ('user_2fa_view', 'نمایش وضعیت شناسایی دوعاملی'), ('user_2fa_edit', 'ویرایش مدیریت شناسایی دوعاملی'), ('user_email_send', 'ارسال ایمیل به کاربران'), ('user_email_view', 'نمایش لیست ایمیل های کاربران'), ('user_bank_deposit_edit_status', 'تایید واریزهای بانکی'), ('user_bank_deposit_view', 'نمایش لیست واریزهای بانکی'), ('user_bank_deposit_edit', 'ویرایش واریزهای بانکی'), ('user_call', 'ثبت تماس با کاربر'), ('user_call_successful', 'تماس موفق با کاربر'), ('user_mobile_call_successful', 'تماس موفق با همراه کاربر'), ('user_call_missed', 'تماس ناموفق با کاربر'), ('user_mobile_call_missed', 'تماس ناموفق با همراه کاربر'), ('user_video_call_successful', 'تماس تصویری موفق با کاربر'), ('management_menu', 'مشاهده گزینه\u200cهای منوی مدیریتی'), ('system_settings_direct_management', 'مدیریت مستقیم تنظیمات سیستم'), ('system_settings_rial_settlement', 'مدیریت تنظیمات تسویه\u200cی ریالی'), ('system_settings_usd_value', 'مدیریت تنظیمات قیمت دلار'), ('system_nodes_management', 'مدیریت نودها'), ('deposit_refund', 'عودت واریزهای شتابی'), ('system_settings_shetab_deposit_backend', 'مدیریت تنظیمات درگاه پرداخت شتابی'), ('user_report_fee', 'گزارش کارمزد'), ('user_deactivation', 'غیر فعال سازی کاربر'), ('user_refresh_deposit', 'بررسی مجدد واریزهای کاربر'), ('user_disable_wallet_address', 'غیر فعال کردن آدرس های واریز'), ('user_sync_shetab_deposit', 'بررسی مجدد واریز شتابی'), ('user_tag_manage', 'مدیریت برچسب\u200cها'), ('view_bots_overview', 'گزارش عملکرد بات\u200cهای بازارگردان'), ('setting_bots_overview', 'تنظیمات بات\u200cهای بازارگردان'), ('high_level_user_edit', 'تغییر اطلاعات کاربر سطح یک و بالاتر'), ('can_change_user_level_zero_to_one', 'تغییر سطح کاربر از صفر به یک'), ('can_change_user_level_one_to_two', 'تغییر سطح کاربر از یک به دو'), ('can_change_user_level_two_to_higher', 'تغییر سطح کاربر از دو به بالا'), ('change_staff_password', 'تغییر رمز پشتیبان'), ('view_user_changes', 'مشاهده\u200c\u200cی تغییرات اعمال شده بر کاربر'), ('view_admin_panel', 'مشاهده\u200c\u200cی پنل ادمین'), ('view_supports_list', 'مشاهده لیست پشتیبان ها'), ('can_add_support', 'تعریف پشتیبان'), ('create_reject_address', 'ساخت آدرس رد')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AddField(
            model_name='user',
            name='requires_daily_profit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfitWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.IntegerField()),
                ('wallet_name', models.CharField(max_length=30)),
                ('buy_amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('buy_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('buy_average', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_wallet_current_balance', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_wallet_submitted_total_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_wallet_expected_total_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('even_rounded_price', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_balance_profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_balance_profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('expected_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_profit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='accounts.UserProfit')),
            ],
        ),
        migrations.AddField(
            model_name='userprofit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_profits', to=settings.AUTH_USER_MODEL),
        ),
    ]
