# Generated by Django 2.2.17 on 2021-04-28 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0107_auto_20210426_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requires_daily_profit',
        ),
    ]
