# Generated by Django 2.2.20 on 2021-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_auto_20210428_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfit',
        ),
        migrations.DeleteModel(
            name='UserProfitWallet',
        ),
    ]
