# Generated by Django 2.2.23 on 2021-06-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20210511_1714'),
        ('accounts', '0103_merge_20210529_0343'),
    ]

    operations = [
    ]
