# Generated by Django 2.2.23 on 2021-06-12 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_merge_20210603_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='KYC_Docs/Files/%Y-%m-%d/', verbose_name='فایل مدرک')),
                ('explanations', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدارک تکمیلی کاربر',
                'verbose_name_plural': 'مدارک تکمیلی کاربر',
            },
        ),
    ]
