# Generated by Django 2.2.23 on 2021-06-20 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_userdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='user',
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to='accounts.UploadedFile', verbose_name='فایل مدرک'),
        ),
    ]
