# Generated by Django 2.2.22 on 2021-06-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_auto_20210620_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
