# Generated by Django 2.2.22 on 2021-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_auto_20210707_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Normal Tag'), (1, 'Auto Tag'), (2, 'KYC Tag')], default=0),
        ),
    ]
