# Generated by Django 2.2.22 on 2021-08-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_auto_20210710_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
