# Generated by Django 2.2.24 on 2021-09-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_auto_20210804_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='action_type',
            field=models.IntegerField(null=True),
        ),
    ]
