# Generated by Django 2.2.25 on 2022-02-09 21:18

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_auto_20210907_2345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Normal'), (4096, 'Open'), (8192, 'Beta'), (12288, 'Alpha'), (16384, 'Closed'), (20480, 'Dev')], db_index=True, null=True, verbose_name='Test Track'),
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت بانکی'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان\u200cها', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userreferral',
            options={'verbose_name': 'ارجاع کاربر', 'verbose_name_plural': 'ارجاع کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userrestriction',
            options={'verbose_name': 'محدودیت کاربر', 'verbose_name_plural': 'محدودیت کاربر'},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={'verbose_name': 'پیامک کاربر', 'verbose_name_plural': 'پیامک کاربر'},
        ),
        migrations.AlterModelOptions(
            name='uservoicemessage',
            options={'verbose_name': 'پیام صوتی', 'verbose_name_plural': 'پیام صوتی'},
        ),
        migrations.AlterModelOptions(
            name='verificationprofile',
            options={'verbose_name': 'احراز هویت', 'verbose_name_plural': 'احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'verbose_name': 'درخواست تایید هویت', 'verbose_name_plural': 'درخواست تایید هویت'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Normal Tag'), (1, 'Auto Tag'), (2, 'KYC Tag'), (3, 'Junk Tag')], default=0),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='action',
            field=models.IntegerField(choices=[(1, 'غیر فعال سازی دوعاملی'), (2, 'اعمال محدودیت کاربر'), (3, 'افزودن مجوز برداشت'), (4, 'حذف محدودیت'), (5, 'افزودن تراکنش دستی'), (6, 'افزودن درخواست برداشت'), (7, 'رد کردن درخواست برداشت'), (8, 'حذف مجوز برداشت'), (9, 'غیرفعال کردن آدرس ولت'), (10, 'ثبت دستی واریز رمزارز'), (11, 'ویرایش واریز شتابی'), (12, 'ویرایش واریزهای بانکی'), (13, 'افزودن تراکنش'), (14, 'فعالسازی شناسه دوعاملی')]),
        ),
        migrations.AlterField(
            model_name='usersms',
            name='template',
            field=models.IntegerField(blank=True, choices=[(0, 'پیش\u200cفرض'), (6816, 'به نوبیتکس خوش آمدید . کد تایید عضویت شما : [VerificationCode] '), (3065, 'کد تایید شما در سایت نوبیتکس [VerificationCode] است '), (54043, 'درخواست فعال سازی شناسه دوعاملی نوبیتکس\nکد: [VerificationCode]'), (51443, 'درخواست غیرفعالسازی شناسه دوعاملی نوبیتکس\nکد: [VerificationCode]'), (51444, 'نوبیتکس\nدرخواست برداشت [Fund]\nکد تایید: [VerificationCode]\nلغو اضطراری: https://nobitex.ir/sos/[CancelCode]'), (55503, 'نوبیتکسی عزیز\nلطفا ایمیل ارسال شده از واحد احراز هویت را بررسی نمایید.')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersms',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Manual SMS'), (1, 'Verify Phone'), (2, 'Verify Withdraw'), (3, 'Process'), (4, 'android'), (7, 'Enable TFA'), (5, 'Disable TFA'), (6, 'Price Alert')]),
        ),
        migrations.AddField(
            model_name='user',
            name='national_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سریال کارت ملی'),
        ),
        migrations.AddField(
            model_name='verificationprofile',
            name='identity_captcha_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید کپچا'),
        ),
        migrations.AddField(
            model_name='verificationprofile',
            name='identity_liveness_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید لایونس'),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', JSONField(verbose_name='دسته بندی ها')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته بندی کاربر',
                'verbose_name_plural': 'دسته بندی های کاربران',
            },
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='status',
            field=models.IntegerField(choices=[(0, 'بدون وضعیت'), (1, 'تایید شده'), (2, 'رد شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='userrestrictionremoval',
            name='ends_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Identity'), (2, 'Address'), (3, 'Selfie'), (4, 'Liveness')], verbose_name='Request Type'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='tp',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'KYCVideo'), (3, 'KYCMainImage'), (4, 'KYCImage')], default=1, verbose_name='File Type'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('labels', JSONField(blank=True, db_index=True, null=True)),
                ('properties', JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربر',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usersms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
