# Generated by Django 2.2.28 on 2022-05-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_auto_20211002_0819_squashed_0133_merge_20220210_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webengage_cuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
