# Generated by Django 2.2.26 on 2022-06-25 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_auto_20220528_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ChangeMobileRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Old Mobile OTP Failed'), (2, 'Old Mobile OTP OK'), (3, 'New Mobile Identity Failed'), (4, 'New Mobile OTP Failed'), (5, 'Old Mobile Not Found'), (6, 'Success')], default=0)),
                ('old_mobile', models.CharField(max_length=12, null=True)),
                ('new_mobile', models.CharField(max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
