# Generated by Django 2.2.26 on 2022-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_auto_20220625_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='changemobilerequest',
            name='new_mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='changemobilerequest',
            name='old_mobile',
            field=models.CharField(max_length=12),
        ),
    ]
