# Generated by Django 2.2.24 on 2022-05-31 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_auto_20211002_0819_squashed_0133_merge_20220210_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
