# Generated by Django 2.2.24 on 2022-07-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_auto_20220531_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconsideration',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
