# Generated by Django 2.2.24 on 2022-07-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0148_auto_20220714_1246'),
    ]

    operations = [
    ]
