# Generated by Django 2.2.28 on 2022-07-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0149_auto_20220723_1926'),
        ('accounts', '0124_auto_20220702_2341'),
    ]

    operations = [
    ]
