# Generated by Django 2.2.26 on 2022-08-17 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0151_auto_20220803_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
