# Generated by Django 2.2.28 on 2022-09-20 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0152_auto_20220816_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
