# Generated by Django 2.2.28 on 2022-10-03 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.accounts.models
import exchange.base.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0153_auto_20220920_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiPhishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_phishing_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='antiphishing',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('user',), name='unique_active_anti_phishing'),
        ),
    ]
