# Generated by Django 2.2.28 on 2022-08-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0153_auto_20220817_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.IntegerField(blank=True, choices=[(1, 'سهامی خاص'), (2, 'شرکت سهامی عام'), (3, 'شرکت سهامی خاص'), (4, 'شرکت با مسئولیت محدود'), (5, 'شرکت تضامنی'), (6, 'شرکت نسبی'), (7, 'شرکت تعاونی'), (8, 'شرکت غیرتجاری')], default=None, null=True)),
                ('activity_field', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to=settings.AUTH_USER_MODEL)),
                ('main_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reguler_owner', models.ManyToManyField(blank=True, related_name='_companydetail_reguler_owner_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
