# Generated by Django 2.2.28 on 2022-08-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0154_auto_20220820_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='reguler_owner',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='regular_owners',
            field=models.ManyToManyField(blank=True, related_name='_companydetail_regular_owners_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
