# Generated by Django 2.2.28 on 2022-10-11 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0155_auto_20220820_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
           ]
