# Generated by Django 2.2.28 on 2022-10-11 12:19

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    user_model = apps.get_model('accounts', 'user')
    for row in user_model.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0159_add_uuid_field_user'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
