# Generated by Django 2.2.28 on 2022-10-11 12:19
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0160_populate_uuid_values'),
    ]

    operations = [
         migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                            ),
    ]
