# Generated by Django 2.2.28 on 2022-10-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0161_auto_20221011_1549'),
        ('accounts', '0154_auto_20221003_1713'),
    ]

    operations = [
    ]
