# Generated by Django 2.2.28 on 2022-10-19 17:20
# This migration fixes inconsistencies with admin project,
#  if you have already run admin migrations, just fake this:
#  ./manage.py migrate accounts 0163_auto_20221019_2050 --fake

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0162_merge_20221019_0125'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', exchange.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', exchange.accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='document_type',
            field=models.IntegerField(blank=True, choices=[(1, 'کارت ملی'), (2, 'آگهی تاسیس'), (3, 'معرفی\u200cنامه'), (4, 'کد اقتصادی')], null=True, verbose_name='نوع مدرک'),
        ),
        migrations.AddField(
            model_name='usersms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersms',
            name='carrier',
            field=models.IntegerField(blank=True, choices=[(0, 'رست فول اس ام اس'), (1, 'فینوتکست')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersms',
            name='tracking_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uservoicemessage',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_message_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
