# Generated by Django 2.2.28 on 2023-07-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.base.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0163_auto_20221019_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_from_bank_card',
            field=models.BooleanField(default=False),
        ),
    ]
