# Generated by Django 2.2.28 on 2023-11-20 22:22
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ('accounts', '0164_add_is_from_bank_card_field_to_BankAccount'),
        ('accounts', '0165_user_merge_request'),
        ('accounts', '0167_auto_20230816_1423'),
        ('accounts', '0168_auto_20230819_2134'),
        ('accounts', '0169_auto_20230819_2323'),
    ]

    dependencies = [
        ('accounts', '0163_auto_20221019_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_from_bank_card',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserMergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Requested'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Failed'), (5, 'Need approval'), (6, 'Email OTP sent'), (7, 'New Mobile OTP sent'), (8, 'Old Mobile OTP sent')], verbose_name='وضعیت درخواست')),
                ('merge_by', models.SmallIntegerField(choices=[(1, 'Email'), (2, 'Mobile')], verbose_name='نوع درخواست')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ادغام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اصلی')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثانوی')),
            ],
            options={
                'verbose_name': 'درخواست ادغام کاربران',
                'verbose_name_plural': 'درخواست\u200cهای ادغام کاربران',
            },
        ),
        migrations.AddField(
            model_name='adminconsideration',
            name='user_consideration',
            field=models.TextField(blank=True, help_text='در پنل کاربر قابل نمایش خواهد بود', null=True),
        ),
    ]
