# Generated by Django 2.2.28 on 2023-07-11 17:28
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0164_add_is_from_bank_card_field_to_BankAccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Requested'), (2, 'Rejected'), (3, 'Accepted'), (4, 'Failed'), (5, 'Need approval'), (6, 'Email OTP sent'), (7, 'New Mobile OTP sent'), (8, 'Old Mobile OTP sent')], verbose_name='وضعیت درخواست')),
                ('merge_by', models.SmallIntegerField(choices=[(1, 'Email'), (2, 'Mobile')], verbose_name='نوع درخواست')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ادغام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اصلی')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثانوی')),
            ],
            options={
                'verbose_name': 'درخواست ادغام کاربران',
                'verbose_name_plural': 'درخواست\u200cهای ادغام کاربران',
            },
        ),
    ]
