# Generated by Django 2.2.28 on 2023-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0165_user_merge_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconsideration',
            name='is_visible_to_user',
            field=models.BooleanField(null=True, help_text='در پنل کاربر قابل نمایش خواهد بود'),
        ),
    ]
