# Generated by Django 2.2.28 on 2023-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0167_auto_20230816_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconsideration',
            name='is_visible_to_user',
        ),
        migrations.AddField(
            model_name='adminconsideration',
            name='user_consideration',
            field=models.TextField(default='', help_text='در پنل کاربر قابل نمایش خواهد بود'),
        ),
    ]
