# Generated by Django 2.2.28 on 2023-08-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.base.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0168_auto_20230819_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconsideration',
            name='user_consideration',
            field=models.TextField(blank=True, help_text='در پنل کاربر قابل نمایش خواهد بود', null=True),
        ),
    ]
