# Generated by Django 2.2.28 on 2023-08-27 18:17

from django.db import migrations, models
from django.db.models import OuterRef, Q, Subquery
from django.db.models.functions import Coalesce

from exchange.accounts.models import VerificationRequest


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0169_auto_20230819_2323'),
    ]

    def set_default_address_value(apps, schema_editor):
        verification_profile = apps.get_model('accounts', 'verificationprofile')
        db_alias = schema_editor.connection.alias
        vr_subquery = Coalesce(
            Subquery(
                VerificationRequest.objects.filter(
                    user_id=OuterRef('user_id'),
                    tp=VerificationRequest.TYPES.address,
                )
                .order_by('-created_at')
                .values('status')[:1]
            ),
            0,
        )
        verification_profile.objects.using(db_alias).annotate(last_vr_status=vr_subquery,).filter(
            Q(user__user_type__gte=46)
            | Q(phone_confirmed=True)
            | (
                Q(user__city__isnull=False, user__address__isnull=False)
                & ~Q(last_vr_status=VerificationRequest.STATUS.rejected)
            ),
        ).update(address_confirmed=True)

    operations = [
        migrations.AddField(
            model_name='verificationprofile',
            name='address_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید اطلاعات سکونتی'),
        ),
        migrations.AlterField(
            model_name='verificationprofile',
            name='phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید تلفن'),
        ),
        migrations.RunPython(set_default_address_value),
    ]
