# Generated by Django 2.2.28 on 2023-10-25 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0170_auto_20230827_2147'),
    ]
    operations = [
        migrations.CreateModel(
            name='UserLevelChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'from_level',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Normal'),
                            (10, 'Inactive'),
                            (20, 'Suspicious'),
                            (30, 'Blocked'),
                            (40, 'Level0'),
                            (42, 'Level1P'),
                            (44, 'Level1'),
                            (45, 'Trader'),
                            (46, 'Level2'),
                            (90, 'Level3'),
                            (91, 'Active'),
                            (92, 'Trusted'),
                            (99, 'Nobitex'),
                            (100, 'System'),
                            (101, 'Bot'),
                            (102, 'Staff'),
                        ]
                    ),
                ),
                (
                    'to_level',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Normal'),
                            (10, 'Inactive'),
                            (20, 'Suspicious'),
                            (30, 'Blocked'),
                            (40, 'Level0'),
                            (42, 'Level1P'),
                            (44, 'Level1'),
                            (45, 'Trader'),
                            (46, 'Level2'),
                            (90, 'Level3'),
                            (91, 'Active'),
                            (92, 'Trusted'),
                            (99, 'Nobitex'),
                            (100, 'System'),
                            (101, 'Bot'),
                            (102, 'Staff'),
                        ]
                    ),
                ),
                (
                    'changed_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_type_histories',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
