# Generated by Django 3.2.22 on 2024-02-21 14:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0171_auto_20231025_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeLevel3Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[(1, 'Requested'), (2, 'Pre-conditions Approved'), (3, 'Rejected'), (4, 'Approved')],
                        default=1,
                        verbose_name='وضعیت درخواست',
                    ),
                ),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('closed_at', models.DateTimeField(null=True, verbose_name='تاریخ تصمیم پشتیبان')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='upgrade_level3_requests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='upgradelevel3request',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', [1, 2])), fields=('user',), name='unique_active_user_request'
            ),
        ),
    ]
