# Generated by Django 3.2 on 2024-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0172_auto_20240224_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestriction',
            name='description',
            field=models.TextField(blank=True, help_text='این توضیحات برای نمایش به کاربر میباشد', null=True),
        ),
    ]
