# Generated by Django 4.2.16 on 2024-10-06 15:11

import functools

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.base.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0173_auto_20240521_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestrictionChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.PositiveSmallIntegerField(choices=[(1, 'Added'), (2, 'Removed')])),
                ('change_by_service', models.CharField(choices=[('abc', 'ABC'), ('admin', 'ADMIN')], max_length=50)),
                (
                    'restriction',
                    models.IntegerField(
                        choices=[
                            (10, 'Withdraw'),
                            (11, 'Shetab Deposit'),
                            (12, 'Gateway'),
                            (13, 'Trading'),
                            (14, 'Withdraw Coin'),
                            (15, 'Withdraw Rial'),
                            (16, 'Position'),
                            (17, 'Leverage'),
                            (18, 'مشارکت استیکینگ'),
                            (19, 'تغییر وضعیت تمدید خودکار استیکینگ'),
                            (20, 'لغو آنی استیکینگ'),
                            (21, 'Login restricted to Iran Only'),
                            (22, 'Change Mobile'),
                        ]
                    ),
                ),
                ('ref_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userrestriction',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrestriction',
            name='source',
            field=models.CharField(blank=True, choices=[('abc', 'ABC'), ('admin', 'ADMIN')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='userrestriction',
            constraint=models.UniqueConstraint(
                condition=models.Q(('ref_id__isnull', False), ('source__isnull', False)),
                fields=('user', 'restriction', 'source', 'ref_id'),
                name='user_restriction_unique_user_restriction_source_ref_id',
            ),
        ),
        migrations.AddField(
            model_name='userrestrictionchangehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrestrictionchangehistory',
            name='user_restriction',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrestriction'
            ),
        ),
    ]
