# Generated by Django 4.2.16 on 2024-10-08 12:19

import functools

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.base.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0174_userrestrictionchangehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='archive_folder_id',
            field=models.SmallIntegerField(
                blank=True, default=0, help_text='Folder id in cold file storage', null=True
            ),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='checksum',
            field=models.BinaryField(blank=True, help_text='sha1sum of file content', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(blank=True, default=0, help_text='File size in bytes', null=True),
        ),
    ]
