# Generated by Django 4.2.16 on 2024-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0175_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='object_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
