# Generated by Django 4.2.17 on 2025-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0176_alter_filed_objec_id_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprogram',
            name='agenda',
            field=models.IntegerField(
                choices=[(0, 'default'), (1, 'campaign')], default=0, null=False, verbose_name='بابت'
            ),
        ),
    ]
