# Generated by Django 4.2.18 on 2025-01-25 11:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0177_alter_referralprogram_agenda'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number', 'confirmed'], name='accounts_ba_account_43e708_idx'),
        ),
    ]
