# Generated by Django 4.2.18 on 2025-02-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0178_alter_user_unique_together_alter_bankaccount_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='shaba_number',
            field=models.CharField(db_index=True, max_length=26),
        ),
    ]
