import pytest
from decimal import Decimal
from unittest import TestCase

from exchange.base.models import Currencies
from exchange.blockchain.api.near.near_explorer_interface import NearExplorerInterface
from exchange.blockchain.api.near.near_1rpc import Near1RpcAPI
from exchange.blockchain.tests.api.general_test.general_test_from_explorer import TestFromExplorer


class TestNearBlocksApiCalls(TestCase):
    api = Near1RpcAPI
    txs_hash = ['EYf7MFDneobGfVWXwjJGbc7gSJWsafUbPxfap5BVBVx',
                '7EzTx2oZzwV1G7pynayHZKPJcTaN6Ra37UiaGEDD2QxE']

    @classmethod
    def check_general_response(cls, response, keys):
        if set(response.keys()).issubset(keys):
            return True
        return False

    @pytest.mark.slow
    def test_get_tx_details_api(self):
        response_keys = {'jsonrpc', 'result', 'id'}
        result_keys = {'final_execution_status', 'receipts_outcome', 'status', 'transaction', 'transaction_outcome'}
        transaction_keys = {'actions', 'hash', 'nonce', 'public_key', 'receiver_id', 'signature', 'signer_id'}
        for tx_hash in self.txs_hash:
            get_tx_details_response = self.api.get_tx_details(tx_hash)
            assert self.check_general_response(get_tx_details_response, response_keys)
            assert get_tx_details_response.get('result')
            assert isinstance(get_tx_details_response.get('result'), dict)
            result = get_tx_details_response.get('result')
            assert self.check_general_response(result, result_keys)
            assert result.get('transaction')
            assert isinstance(result.get('transaction'), dict)
            transaction = result.get('transaction')
            assert self.check_general_response(transaction, transaction_keys)


class TestNearBlocksNearFromExplorer(TestFromExplorer):
    api = Near1RpcAPI
    txs_hash = ['ErWASMPmXEEv1SLpniksjmz691MhcVpizPxHWMrX4LDs',
                'EYf7MFDneobGfVWXwjJGbc7gSJWsafUbPxfap5BVBVx',
                'FYa6W6XvKrjQk2p62SRQs1SHCz4pDVBapDwPFo3iW48f',
                '7EzTx2oZzwV1G7pynayHZKPJcTaN6Ra37UiaGEDD2QxE',
                '2sNimouD5gtJoAmuzk8cRNP2bbRmbREHWw1BeMDQYdbG']
    explorerInterface = NearExplorerInterface
    currencies = Currencies.near
    symbol = 'NEAR'

    @classmethod
    def test_get_tx_details(cls):
        tx_details_mock_responses = [
            {'jsonrpc': '2.0', 'result': {'final_execution_status': 'FINAL', 'receipts_outcome': [
                {'block_hash': '9q5AaDzT9ueW36j7m5Mogyeg272oGe3RM4X16Nw8wPU9',
                 'id': 'HHm3VMn8AEBitm5Ys5s5YVqzcq1QMMY2cefFqFSGKHtc',
                 'outcome': {'executor_id': 'd3642d5c2418c9ebb3868378b3de26dfb9eca3a3889e441a40c432f40ec121a9',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': ['DFbZrfsujVNQwtpLpcQo2t2zz9EQzs4XAXpPSLi8YzdC'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '417494768750000000000'},
                 'proof': [{'direction': 'Right', 'hash': 'Drxf86FwkZzDzoan1Awbhq3PQkfSjRDA5j8EKNqAnPqP'},
                           {'direction': 'Left', 'hash': 'V8ozGv8TWMHnhNxknfnHFxUzb39Z4ZfHL6Xj1E5ZHRH'},
                           {'direction': 'Right', 'hash': '7MCRCpWUCrnLRxtbvPBGc7RDyfEiVkv9NZqfwhJfPKST'},
                           {'direction': 'Right', 'hash': 'EtpqcG1Jk4xRkvMcfud6aAidZYNJeBFtETYFsYjnGHvq'},
                           {'direction': 'Left', 'hash': 'EAgQSry2j8daeAuy9n3pN9EmbFbZHo6TyJW4uj1VHzk'},
                           {'direction': 'Right', 'hash': '13gjYYx8eC1NKYDQimqdEQCw5AsEQpsEwSXkjr3tephR'}]},
                {'block_hash': 'B6p3BWp8qpkEpBSf5YBEvZe9N3psmkpPNuoi7x8g3eQk',
                 'id': 'DFbZrfsujVNQwtpLpcQo2t2zz9EQzs4XAXpPSLi8YzdC',
                 'outcome': {'executor_id': 'ccb91e1db61e8d7e1d4ae3e043001140132959a86ee35a548b6563a46284a6ea',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': 'C3wSFMWp7VgmyV1XEjof1NUqeoY8GwaAwWpDrUcX1rsi'},
                           {'direction': 'Right', 'hash': 'AK1WEFcyEwpojhUAGK5HugPKvM1r5du56Vqt5oNrnZC4'},
                           {'direction': 'Left', 'hash': '5s6wskdKfF3cH1ZYgG3CNM8ucBADKexaz7CQJc9JezU'},
                           {'direction': 'Right', 'hash': '8VTY8k4JTwB4XfRYErDcsWYTufLx8hrGBBfinR4jvLh5'},
                           {'direction': 'Right', 'hash': '5feDAfY8eRetysT1kRRNnn3JtbtEzYi1noKWmk1HonkX'}]}],
                                          'status': {'SuccessValue': ''}, 'transaction': {
                    'actions': [{'Transfer': {'deposit': '1988000000000000000000000'}}],
                    'hash': 'ErWASMPmXEEv1SLpniksjmz691MhcVpizPxHWMrX4LDs', 'nonce': 255920,
                    'public_key': 'ed25519:En9tageboTje614y9hgq1S2TwbZsxUaxEn9dmEkz2m4u',
                    'receiver_id': 'd3642d5c2418c9ebb3868378b3de26dfb9eca3a3889e441a40c432f40ec121a9',
                    'signature': 'ed25519:3Q5y3YmyuLBXRYR3m25TdgjC5uRHkQa1SVdu6BY33wdwhVUXbM4NtQyTNwya3fqeaUiMeAXmD3keqvfoZUdUay5b',
                    'signer_id': 'ccb91e1db61e8d7e1d4ae3e043001140132959a86ee35a548b6563a46284a6ea'},
                                          'transaction_outcome': {
                                              'block_hash': 'AFHrQKAk2tuwtsek1rgF6gLg6StJ7dW3qaUFNLXe6Tt1',
                                              'id': 'ErWASMPmXEEv1SLpniksjmz691MhcVpizPxHWMrX4LDs', 'outcome': {
                                                  'executor_id': 'ccb91e1db61e8d7e1d4ae3e043001140132959a86ee35a548b6563a46284a6ea',
                                                  'gas_burnt': 4174947687500, 'logs': [],
                                                  'metadata': {'gas_profile': None, 'version': 1},
                                                  'receipt_ids': ['HHm3VMn8AEBitm5Ys5s5YVqzcq1QMMY2cefFqFSGKHtc'],
                                                  'status': {
                                                      'SuccessReceiptId': 'HHm3VMn8AEBitm5Ys5s5YVqzcq1QMMY2cefFqFSGKHtc'},
                                                  'tokens_burnt': '417494768750000000000'}, 'proof': [
                                                  {'direction': 'Left',
                                                   'hash': '9VsYrcxAcwJcM3jAPr5sr1GMKrpf4xm1jNAQKqpSwjVE'},
                                                  {'direction': 'Left',
                                                   'hash': 'GzoWhHAR9FT2dVmU443WrD1faBQHhFtF7n2N2vtBAE7Y'},
                                                  {'direction': 'Right',
                                                   'hash': '8YZH83dyUohx8Xws16SGBuU8j9jzoGKh2z9YrQ4FhW8z'},
                                                  {'direction': 'Right',
                                                   'hash': '8dSiAs4d9DsF8cVrVMc5EMUVcQFSzj3Xujn2UnanVCbx'},
                                                  {'direction': 'Right',
                                                   'hash': 'AvP6UJZFdJPdBcooFN1T2YY1WJVxYoXGZdB6XvqNG6SN'}]}},
             'id': 'dontcare'},
            {'jsonrpc': '2.0', 'result': {'final_execution_status': 'FINAL', 'receipts_outcome': [
                {'block_hash': 'BQWAaQ6HKAbZNqLHPFRYxJAhnUA21pdzoFVPTdWXmtKN',
                 'id': 'D63fsxjhVCVTyxNF4CfQuMXRhURqgnRb6WDVXHqNv19h',
                 'outcome': {'executor_id': 'e9b2fd9f3a6280ab37f6ce6909f4487aa86e76be3627c83583c0c69a11dd0fe1',
                             'gas_burnt': 424555062500, 'logs': [], 'metadata': {'gas_profile': [
                         {'cost': 'ALT_BN128_G1_MULTIEXP_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_MULTIEXP_ELEMENT', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_SUM_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_SUM_ELEMENT', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_PAIRING_CHECK_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_PAIRING_CHECK_ELEMENT', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'}, {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ECRECOVER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ED25519_VERIFY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ED25519_VERIFY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK256_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK256_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK512_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK512_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_AND_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_AND_PER_PROMISE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_RETURN', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'RIPEMD160_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'RIPEMD160_BLOCK', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'SHA256_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'SHA256_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_HAS_KEY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_HAS_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_FROM_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_PREFIX_BASE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_PREFIX_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_RANGE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_TO_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_RET_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF16_DECODING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF16_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF8_DECODING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF8_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'VALIDATOR_STAKE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'VALIDATOR_TOTAL_STAKE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'}],
                                                                                 'version': 2},
                             'receipt_ids': ['BPBgZWThVnzbqvnTa4DVJ3BG3pDU1hntadHvhA7pd1nc'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '42455506250000000000'},
                 'proof': [{'direction': 'Left', 'hash': '3YBrx1uewP17SHyRW9pcP8FpWQ6rKFWG4CfQaQV8T6Sg'},
                           {'direction': 'Right', 'hash': 'DM1hwSwmqaND8uyFCPUr2AoEin6wE378swGtDroc5edc'}]},
                {'block_hash': 'Hhb4d2YojQdvHcrKTEsrZnpVwW5JpE8cjBGycvuW1kN7',
                 'id': 'BPBgZWThVnzbqvnTa4DVJ3BG3pDU1hntadHvhA7pd1nc',
                 'outcome': {'executor_id': 'eb3c2bfd6bf357f433be30292d78b23f948ee75f63baca2cc5f56cff1751c294',
                             'gas_burnt': 424555062500, 'logs': [], 'metadata': {'gas_profile': [
                         {'cost': 'ALT_BN128_G1_MULTIEXP_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_MULTIEXP_ELEMENT', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_SUM_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_G1_SUM_ELEMENT', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_PAIRING_CHECK_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ALT_BN128_PAIRING_CHECK_ELEMENT', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'}, {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ECRECOVER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ED25519_VERIFY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'ED25519_VERIFY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK256_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK256_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK512_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'KECCAK512_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_AND_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_AND_PER_PROMISE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'PROMISE_RETURN', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'RIPEMD160_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'RIPEMD160_BLOCK', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'SHA256_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'SHA256_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_HAS_KEY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_HAS_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_FROM_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_PREFIX_BASE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_PREFIX_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_RANGE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_CREATE_TO_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_ITER_NEXT_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_REMOVE_RET_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF16_DECODING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF16_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF8_DECODING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'UTF8_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'VALIDATOR_STAKE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'VALIDATOR_TOTAL_STAKE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'},
                         {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '0'}],
                                                                                 'version': 2}, 'receipt_ids': [],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Right', 'hash': '3f5ky7XJviEgxghEVVYo9Qcyz9MEGAjrP4AmV38dc9JR'}]}],
                                          'status': {'SuccessValue': ''}, 'transaction': {
                    'actions': [{'Transfer': {'deposit': '999000000000000000000000'}}],
                    'hash': 'EYf7MFDneobGfVWXwjJGbc7gSJWsafUbPxfap5BVBVx', 'nonce': 67507218001057,
                    'public_key': 'ed25519:GqG2Twersq7ic5kBweSGqaHR6mmo4DEMwZBzteKg7cro',
                    'receiver_id': 'e9b2fd9f3a6280ab37f6ce6909f4487aa86e76be3627c83583c0c69a11dd0fe1',
                    'signature': 'ed25519:5TQUqcwj5GLjAZxejX5NQNN8PyNpb73nsGxvRbcMrwERhrJMUGkcYTRsNdUwVP43ASR12U87aFm71nHN7on7t6LD',
                    'signer_id': 'eb3c2bfd6bf357f433be30292d78b23f948ee75f63baca2cc5f56cff1751c294'},
                                          'transaction_outcome': {
                                              'block_hash': 'BHZEPqAEg3PRZQGg1nbpEbhHbY4GXd78aHrjDFLuzfL8',
                                              'id': 'EYf7MFDneobGfVWXwjJGbc7gSJWsafUbPxfap5BVBVx', 'outcome': {
                                                  'executor_id': 'eb3c2bfd6bf357f433be30292d78b23f948ee75f63baca2cc5f56cff1751c294',
                                                  'gas_burnt': 424555062500, 'logs': [],
                                                  'metadata': {'gas_profile': None, 'version': 1},
                                                  'receipt_ids': ['D63fsxjhVCVTyxNF4CfQuMXRhURqgnRb6WDVXHqNv19h'],
                                                  'status': {
                                                      'SuccessReceiptId': 'D63fsxjhVCVTyxNF4CfQuMXRhURqgnRb6WDVXHqNv19h'},
                                                  'tokens_burnt': '42455506250000000000'}, 'proof': [
                                                  {'direction': 'Right',
                                                   'hash': 'C6fhNwA2eimM9GaZbpwTHJqU8UxREJFo8kNR7fHywifN'},
                                                  {'direction': 'Right',
                                                   'hash': 'HDbR5xfJLZxmUZeroCgj6Akvmgj2dMaSUm2sASrWGhRw'}]}},
             'id': 'dontcare'},
            {'jsonrpc': '2.0', 'result': {'final_execution_status': 'FINAL', 'receipts_outcome': [
                {'block_hash': 'HAac5cug2mLRQUewmmy7wZwxzw4VFGzQEmTzztC45AbJ',
                 'id': 'ALzSQuQKHjLkX54xp983sY2jnGckrT4vRLXNaHZMK6mV',
                 'outcome': {'executor_id': 'i6221756207.tg', 'gas_burnt': 2628104346588, 'logs': [],
                             'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': ['G1ym9s6UWEs93K7cAYgEw3nUJfCnCnUi5BRBFUNuD5Pe',
                                             '9JgyYoBQyKTPjPTqe1rSvtqmDhBqwvyo3juAf84hoLPJ'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '262810434658800000000'},
                 'proof': [{'direction': 'Left', 'hash': '4BCM7Ns7sThyovP7e9iCSXCUzUYyPiufcsjqYak7Vkyo'},
                           {'direction': 'Right', 'hash': 'AuJZeqpaJ6oLnkkNHc2xT9YmmbX9bYoYk61MiFbiHfBz'},
                           {'direction': 'Right', 'hash': 'JDBP1QVqENyUG3Pnd6GSQuv3RRd4KJ5k2rRVrqnUhghV'},
                           {'direction': 'Right', 'hash': 'DTfZ5KGPvKLE8fd2EKciMEEPDoyyU37ADngdekEdJp2S'},
                           {'direction': 'Left', 'hash': 'AC8siKuyQJ2tnz2pXWrVDm7U4Cw7vJQbb4QV8vDr1XAx'},
                           {'direction': 'Right', 'hash': '3NWMmHFVLHbdcXmxYUkVAkwSajrbzwaPmJZwG6HWzS68'},
                           {'direction': 'Left', 'hash': '932f5GuRDFuZPY7WoXGBwmXfSvdSNasho674eRhBBrJf'}]},
                {'block_hash': 'C9Y7x21TLbcQv8Dyj1pADa8MT2N4WUCJ4TQpVnWMk4dp',
                 'id': 'G1ym9s6UWEs93K7cAYgEw3nUJfCnCnUi5BRBFUNuD5Pe',
                 'outcome': {'executor_id': 'game.hot.tg', 'gas_burnt': 4477252869910,
                             'logs': ['Charged 27000 HOT to cover gas price',
                                      'EVENT_JSON:{"standard":"nep141","version":"1.0.0","event":"ft_mint","data":[{"owner_id":"i6221756207.tg","amount":"63000"}]}',
                                      'EVENT_JSON:{"standard":"nep141","version":"1.0.0","event":"ft_mint","data":[{"owner_id":"rabbimcdanielss.tg","amount":"12600"}]}',
                                      'EVENT_JSON:{"standard":"nep141","version":"1.0.0","event":"ft_mint","data":[{"owner_id":"cminerbox.tg","amount":"3150"}]}'],
                             'metadata': {'gas_profile': [
                                 {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '14827014216'},
                                 {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '35445963'},
                                 {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '72099286500'},
                                 {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '14173252200'},
                                 {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '5398305519'},
                                 {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '171000000000'},
                                 {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '62636716800'},
                                 {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3405994368'},
                                 {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '40274642976'},
                                 {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '88015866'},
                                 {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '563568457500'},
                                 {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3188110899'},
                                 {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3231938880'},
                                 {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '320983680000'},
                                 {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '9667309407'},
                                 {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '5850077961'},
                                 {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '9336580239'},
                                 {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '434752810002'},
                                 {'cost': 'UTF8_DECODING_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '12447116244'},
                                 {'cost': 'UTF8_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '119256415911'},
                                 {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '80393134272'},
                                 {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '47664512637'},
                                 {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '2475908748'},
                                 {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '48713882262'},
                                 {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3679913952'}], 'version': 3},
                             'receipt_ids': ['6xBkdG4ALv32BkFcxHxb9AfsYWfFCS3ZFyEuUohrP9vf'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '447725286991000000000'},
                 'proof': [{'direction': 'Left', 'hash': '92z9Zj7iRHdATrJBErvrkXCMR1ShbXT6hZ6cdUxjtAeQ'},
                           {'direction': 'Right', 'hash': 'DQaHeUzN2m55FLpLNMLGhCMFAR9rKBDZtPdAosFAyfgP'},
                           {'direction': 'Left', 'hash': '4i7zvGjnGT5kfgPNtx73YoxVWtUS3PEp5tdcRLDvpznV'},
                           {'direction': 'Left', 'hash': 'EaFnGzS2vJXEDr8eDRoeZMkvxFQrUV3GeqieJm6khENE'},
                           {'direction': 'Right', 'hash': '42RE6psVy1jZj1j1FAcwyeTKQpycdZAtu7BxksxdXxnX'},
                           {'direction': 'Left', 'hash': '8vLRBqvacssJR6RKYnZfqEPqP42SZcCzsGztLWrcfyvX'},
                           {'direction': 'Right', 'hash': 'W66w7iaxQZWrFhwEWMNF6xLxmD49MWSNNPonZZyGU42'},
                           {'direction': 'Left', 'hash': '9pBrMQqRbdGKLYD7SwM7nRc4PADMVsgR42GrYtVMuDSS'}]},
                {'block_hash': 'Et4jBekKDHV2SA9fyym3b6kiJDbUD7ZVeJU9GSk61dNs',
                 'id': '6xBkdG4ALv32BkFcxHxb9AfsYWfFCS3ZFyEuUohrP9vf',
                 'outcome': {'executor_id': '0-relay.hot.tg', 'gas_burnt': 223182562500, 'logs': [],
                             'metadata': {'gas_profile': [], 'version': 3}, 'receipt_ids': [],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': '5UW1xx4JU1TyUuiTR6T8W31YkgNh22bEsmYCDCZXH8tL'},
                           {'direction': 'Left', 'hash': 'CzzFWLRo8thxJEf3kARPKHQCb6qgJMWTcYVix61RzJWB'},
                           {'direction': 'Right', 'hash': 'FXJpdJSVVDbE8frqiCfiNwjaqZumd7QQBR1vgRUJM6vd'},
                           {'direction': 'Left', 'hash': '3MnciMgyQh5fCUZCHNy84Et6mcejoAAqkfD7Mz2yb7jv'},
                           {'direction': 'Left', 'hash': '3VQXnnEnSgivyxo42U2Y2x3pomLRwbXeWupXd1A9xiFe'},
                           {'direction': 'Right', 'hash': 'CGSYq6LXP7paac6EGgFj6JMqJo9x5TQ9pSVUWoVHSAGN'},
                           {'direction': 'Left', 'hash': 'E9Ud2DKYH2LTXSz43sVZripgpuQQKoWs71vwr1UmcGGW'},
                           {'direction': 'Right', 'hash': 'Dn893AtJzTBGv9wBFgqwDBFtmNQR8Hnm3216Nbv61r9p'}]},
                {'block_hash': 'F2NPnQdHTP3KX79TikZwibNz13iBxfogcJmyJTB2Rrqe',
                 'id': '9JgyYoBQyKTPjPTqe1rSvtqmDhBqwvyo3juAf84hoLPJ',
                 'outcome': {'executor_id': '0-relay.hot.tg', 'gas_burnt': 223182562500, 'logs': [],
                             'metadata': {'gas_profile': [], 'version': 3}, 'receipt_ids': [],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Right', 'hash': '38LWwbYQqaKxpuX1wQbzN8cKCVN9tU4wHKe6QxTfNJpY'},
                           {'direction': 'Left', 'hash': 'BurjZepuDrgjyLSMaLdNJrqzkFdLHhw2onTAfNvwpX7K'},
                           {'direction': 'Right', 'hash': '6v47EciAy4yjNej1juh5fg6rwxAa9djogfyXLN3sfvgQ'},
                           {'direction': 'Right', 'hash': 'Aib2njXMVsLYfxssxaP2FvW6ZN4QKkXj2wsDyAEYcXhH'},
                           {'direction': 'Left', 'hash': 'Bmg6MXLNdgqaA1cmgfwptJj9je3gjbawAsjPuKBbGZ2V'},
                           {'direction': 'Left', 'hash': 'EKDzH4iU3sFaDJyoFRpbJnExRmAhAGC1pJcxnqsTVg7b'},
                           {'direction': 'Left', 'hash': '6YzX2GKdpuzuVPjyErMFH7jimtXgQwp4NXCpcPAbBfUC'},
                           {'direction': 'Right', 'hash': 'F9HmAkpkFxvgy1SosevNifhYXT5zGDo2dWWeh2ZKSF3N'}]}],
                                          'status': {'SuccessValue': ''}, 'transaction': {'actions': [{'Delegate': {
                    'delegate_action': {'actions': [{'FunctionCall': {
                        'args': 'eyJjaGFyZ2VfZ2FzX2ZlZSI6dHJ1ZSwiY3NyZiI6IjdWYW1uZ3dwemtwdVlBeFhHaE1Wc2JlUmZTREFHd3VlWVlaaW90dGZUZHlOIn0=',
                        'deposit': '0', 'gas': 30000000000000, 'method_name': 'claim'}}], 'max_block_height': 116305075,
                                        'nonce': 111922897002030,
                                        'public_key': 'ed25519:CA5Ux9kHc71F4YZkMJchvRHGYtk4BK1oyj7uwHM2rVFz',
                                        'receiver_id': 'game.hot.tg', 'sender_id': 'i6221756207.tg'},
                    'signature': 'ed25519:5ANwnFyifBCX7vA1w3ZbYnpVXFXXq2EjeEh34FHjRkCYfDtEwZzn3LJLioMwEBfbYMR1A15bW33uJBETLz8fCMTV'}}],
                                                                                          'hash': 'FYa6W6XvKrjQk2p62SRQs1SHCz4pDVBapDwPFo3iW48f',
                                                                                          'nonce': 114310680048439,
                                                                                          'public_key': 'ed25519:9Hy4wYxBFLNJAcqN7aHFeSeBCLsFQXDK9wWGvwKWt8R7',
                                                                                          'receiver_id': 'i6221756207.tg',
                                                                                          'signature': 'ed25519:2xrG6qxY8dupExQRUoV79YcWeJkFDvuZFjA4HMsvH8B59tJX4RG1Fnfy9hKaunff3ZMMcbNesJdn3hdWdBtXHmmV',
                                                                                          'signer_id': '0-relay.hot.tg'},
                                          'transaction_outcome': {
                                              'block_hash': '6WMV1mHpMaCdPNTUUHsk1pUNjPVsLGNbXzzezpVTDSJs',
                                              'id': 'FYa6W6XvKrjQk2p62SRQs1SHCz4pDVBapDwPFo3iW48f',
                                              'outcome': {'executor_id': '0-relay.hot.tg', 'gas_burnt': 2628104346588,
                                                          'logs': [], 'metadata': {'gas_profile': None, 'version': 1},
                                                          'receipt_ids': [
                                                              'ALzSQuQKHjLkX54xp983sY2jnGckrT4vRLXNaHZMK6mV'],
                                                          'status': {
                                                              'SuccessReceiptId': 'ALzSQuQKHjLkX54xp983sY2jnGckrT4vRLXNaHZMK6mV'},
                                                          'tokens_burnt': '262810434658800000000'}, 'proof': [
                                                  {'direction': 'Left',
                                                   'hash': 'BEePy6ZxGLK2qEiULR8EMfstVDCPEdgEf8Xg4ALjvSN3'},
                                                  {'direction': 'Right',
                                                   'hash': 'EBzeZbN58DUBNePoMreCaa7GtSqEnq7CGAASvtmcL2Ei'},
                                                  {'direction': 'Right',
                                                   'hash': '4nnAzRzckfY3emjwbgCHkNzVF5wJEa89HjgStdDz848n'},
                                                  {'direction': 'Right',
                                                   'hash': '5M1stjLderjhRdoG9yXSUForti7kZP19hn9Fk8YhfeAs'},
                                                  {'direction': 'Left',
                                                   'hash': 'DiYFWiDQ3Rum9UozqoG9AJkWmLnNJ4a34GDBU8jadcqr'},
                                                  {'direction': 'Right',
                                                   'hash': '41y1xH39w5hQhkydFXsfva6jpo245MqZb7dpdhe8kmNN'},
                                                  {'direction': 'Right',
                                                   'hash': 'B3wfsUkupy2RUU2mLHiaYhT8Httms1ww6qQHADAScXYD'}]}},
             'id': 'dontcare'},
            {'jsonrpc': '2.0', 'result': {'final_execution_status': 'FINAL', 'receipts_outcome': [
                {'block_hash': 'GSQNZVK9xcynzQHsDtdkDXT5ko9kNcUYnEccabfRN9n',
                 'id': 'WnGdLKjAn7Hcr7rDKqN3cZJQCm4eTfgJXX3eAzedz6S',
                 'outcome': {'executor_id': 'wrap.near', 'gas_burnt': 8755443305235, 'logs': [
                     'Transfer 1000000000000000000000000 from 49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c to v2.ref-finance.near'],
                             'metadata': {'gas_profile': [{'cost': 'FUNCTION_CALL_BASE', 'cost_category': 'ACTION_COST',
                                                           'gas_used': '4639723000000'},
                                                          {'cost': 'FUNCTION_CALL_BYTE', 'cost_category': 'ACTION_COST',
                                                           'gas_used': '1656827094'},
                                                          {'cost': 'NEW_ACTION_RECEIPT', 'cost_category': 'ACTION_COST',
                                                           'gas_used': '289092464624'},
                                                          {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '9002115774'}, {'cost': 'CONTRACT_LOADING_BASE',
                                                                                       'cost_category': 'WASM_HOST_COST',
                                                                                       'gas_used': '35445963'},
                                                          {'cost': 'CONTRACT_LOADING_BYTES',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '40234218750'},
                                                          {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '3543313050'},
                                                          {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '1676246457'},
                                                          {'cost': 'PROMISE_RETURN', 'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '560152386'}, {'cost': 'READ_CACHED_TRIE_NODE',
                                                                                      'cost_category': 'WASM_HOST_COST',
                                                                                      'gas_used': '57000000000'},
                                                          {'cost': 'READ_MEMORY_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '49587400800'}, {'cost': 'READ_MEMORY_BYTE',
                                                                                        'cost_category': 'WASM_HOST_COST',
                                                                                        'gas_used': '4519784937'},
                                                          {'cost': 'READ_REGISTER_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '20137321488'}, {'cost': 'READ_REGISTER_BYTE',
                                                                                        'cost_category': 'WASM_HOST_COST',
                                                                                        'gas_used': '66825036'},
                                                          {'cost': 'STORAGE_READ_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '169070537250'},
                                                          {'cost': 'STORAGE_READ_KEY_BYTE',
                                                           'cost_category': 'WASM_HOST_COST', 'gas_used': '3033348234'},
                                                          {'cost': 'STORAGE_READ_VALUE_BYTE',
                                                           'cost_category': 'WASM_HOST_COST', 'gas_used': '342271305'},
                                                          {'cost': 'STORAGE_WRITE_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '192590208000'},
                                                          {'cost': 'STORAGE_WRITE_EVICTED_BYTE',
                                                           'cost_category': 'WASM_HOST_COST', 'gas_used': '1959155727'},
                                                          {'cost': 'STORAGE_WRITE_KEY_BYTE',
                                                           'cost_category': 'WASM_HOST_COST', 'gas_used': '6907320966'},
                                                          {'cost': 'STORAGE_WRITE_VALUE_BYTE',
                                                           'cost_category': 'WASM_HOST_COST', 'gas_used': '1892130879'},
                                                          {'cost': 'TOUCHING_TRIE_NODE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '515262589632'}, {'cost': 'UTF8_DECODING_BASE',
                                                                                         'cost_category': 'WASM_HOST_COST',
                                                                                         'gas_used': '9335337183'},
                                                          {'cost': 'UTF8_DECODING_BYTE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '45194974245'}, {'cost': 'WASM_INSTRUCTION',
                                                                                        'cost_category': 'WASM_HOST_COST',
                                                                                        'gas_used': '208316882664'},
                                                          {'cost': 'WRITE_MEMORY_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '25234153749'}, {'cost': 'WRITE_MEMORY_BYTE',
                                                                                        'cost_category': 'WASM_HOST_COST',
                                                                                        'gas_used': '1890297768'},
                                                          {'cost': 'WRITE_REGISTER_BASE',
                                                           'cost_category': 'WASM_HOST_COST',
                                                           'gas_used': '25789702374'}, {'cost': 'WRITE_REGISTER_BYTE',
                                                                                        'cost_category': 'WASM_HOST_COST',
                                                                                        'gas_used': '2687705748'}],
                                          'version': 3}, 'receipt_ids': ['5HBu6cJu7KEvqzpnBk2YKvBGfXqBnTzr5p1b1MSvy58F',
                                                                         'HvKDaQETtjXM57EAisgTsNaXz6hEZ88b5K5gJGuDEWnS',
                                                                         '6hLhXjWnhnDGtmYgr9ZbV4dtEJ9BQ7oqhwF7BJ9W8Lek'],
                             'status': {'SuccessReceiptId': 'HvKDaQETtjXM57EAisgTsNaXz6hEZ88b5K5gJGuDEWnS'},
                             'tokens_burnt': '875544330523500000000'},
                 'proof': [{'direction': 'Right', 'hash': '13zw3VWVaEAJLwpsLc1Wo92mpNcFPHQjrqWp7qSv4JDM'},
                           {'direction': 'Left', 'hash': '7AeRHiiLyfcYus42RhhKYrH6cCfb7YHMwJqxrvZrx9Df'},
                           {'direction': 'Right', 'hash': '2zU6PYiQKXQj3geWv4TPG7fCkk96Z6DF7X6tcyWVhFcp'},
                           {'direction': 'Left', 'hash': 'AP9Q9AuZKskhu4N1yf5ihv4n2q9FnWP8rjjSkamBjkgy'},
                           {'direction': 'Left', 'hash': 'Cr35gshj8zqGrmfRkZoJs1nmtPRAi2sEE9PyzpHWRoKM'},
                           {'direction': 'Right', 'hash': 'AuFk4XYYsp9G6mzbMBV6PgjfXzVMo4RtbhQbYYeNT4Vk'}]},
                {'block_hash': '7cFUHxLCoyo4bNQy4ZSA8ZzntQACnXamsmS36U4N9MWc',
                 'id': '5HBu6cJu7KEvqzpnBk2YKvBGfXqBnTzr5p1b1MSvy58F',
                 'outcome': {'executor_id': 'v2.ref-finance.near', 'gas_burnt': 17581269862945, 'logs': [
                     'Swapped 1000000000000000000000000 wrap.near for 1120260 dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near',
                     'Exchange v2.ref-finance.near got 3514546900189143446 shares, No referral fee',
                     'Swapped 1120260 dac17f958d2ee523a2206206994597c13d831ec7.factory.bridge.near for 1119696 17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1, total fee 560, admin fee 112',
                     'Exchange v2.ref-finance.near got 112024980844317193946 shares, No referral fee'], 'metadata': {
                     'gas_profile': [
                         {'cost': 'FUNCTION_CALL_BASE', 'cost_category': 'ACTION_COST', 'gas_used': '4639723000000'},
                         {'cost': 'FUNCTION_CALL_BYTE', 'cost_category': 'ACTION_COST', 'gas_used': '742330088'},
                         {'cost': 'NEW_ACTION_RECEIPT', 'cost_category': 'ACTION_COST', 'gas_used': '289092464624'},
                         {'cost': 'NEW_DATA_RECEIPT_BYTE', 'cost_category': 'ACTION_COST', 'gas_used': '103272066'},
                         {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '36008463096'},
                         {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '35445963'},
                         {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '160704302250'},
                         {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '14173252200'},
                         {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '5979052323'},
                         {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '503880000000'},
                         {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '219228508800'},
                         {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '13734216129'},
                         {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '80549285952'},
                         {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '299234232'},
                         {'cost': 'STORAGE_HAS_KEY_BASE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '162119689875'},
                         {'cost': 'STORAGE_HAS_KEY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '4649417595'},
                         {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '1521634835250'},
                         {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '23926308009'},
                         {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '9067384080'},
                         {'cost': 'STORAGE_REMOVE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '481257274500'},
                         {'cost': 'STORAGE_REMOVE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '9784418304'},
                         {'cost': 'STORAGE_REMOVE_RET_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '2502347652'},
                         {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '1027147776000'},
                         {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '30447207036'},
                         {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '25726246455'},
                         {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                          'gas_used': '36136597935'},
                         {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '660180192966'},
                         {'cost': 'UTF8_DECODING_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '18670674366'},
                         {'cost': 'UTF8_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '156287136744'},
                         {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST', 'gas_used': '4784163234312'},
                         {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '92525230413'},
                         {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '8312952144'},
                         {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '120351944412'},
                         {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '12932920728'}],
                     'version': 3}, 'receipt_ids': ['2KGjWBW6YMPkDhvCbDfSNaqG419NRtZC3UwGaNkeV31U',
                                                    'HfkN5z5RfmRJ9JEd467f725Nz7GMARED9fWab9Rz1tht',
                                                    '3E1mNwRodLZfPFAUpHvMAANNZ5o2Zgk6EFmsDLAzKd6u'],
                             'status': {'SuccessValue': 'IjAi'}, 'tokens_burnt': '1758126986294500000000'},
                 'proof': [{'direction': 'Right', 'hash': 'Eyeo7kkQzVAh7V8QiXuTpy8PDXsANk2zQEsyv48szGpH'},
                           {'direction': 'Left', 'hash': 'GSfPxc7EMtdmw1sBtTsvju9W3rJAttGJkLaDeXfDiSK5'},
                           {'direction': 'Left', 'hash': '5FVk3sqJUUjgbPnwrQRD21xJWZrBEATmdPfLZ7WYijsF'},
                           {'direction': 'Right', 'hash': 'C6QFR36y4DNuEWH9CQuGhre9NY91YcfBB5BdJaFMeMS9'},
                           {'direction': 'Right', 'hash': '2Tdy6vkApoQk1Qv6avVL6gjvyfaohBQTPGyoXvuGPwkY'}]},
                {'block_hash': '9RNjE6dbminjUBsG2XHiRJotriFrmH4zkjwYMRfEQ1hG',
                 'id': '2KGjWBW6YMPkDhvCbDfSNaqG419NRtZC3UwGaNkeV31U',
                 'outcome': {'executor_id': '17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1',
                             'gas_burnt': 3972173062249, 'logs': [
                         'EVENT_JSON:{"standard":"nep141","version":"1.0.0","event":"ft_transfer","data":[{"old_owner_id":"v2.ref-finance.near","new_owner_id":"49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c","amount":"1119696"}]}'],
                             'metadata': {'gas_profile': [
                                 {'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '9796420107'},
                                 {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '35445963'},
                                 {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '67866592500'},
                                 {'cost': 'LOG_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '3543313050'},
                                 {'cost': 'LOG_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '2916932811'},
                                 {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '61560000000'},
                                 {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '41757811200'},
                                 {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3014457069'},
                                 {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '30205982232'},
                                 {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '50463744'},
                                 {'cost': 'SHA256_BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '9081940500'},
                                 {'cost': 'SHA256_BYTE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '2435852451'},
                                 {'cost': 'STORAGE_HAS_KEY_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '108079793250'},
                                 {'cost': 'STORAGE_HAS_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '1970614080'},
                                 {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '281784228750'},
                                 {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3280968498'},
                                 {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '1486916325'},
                                 {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '192590208000'},
                                 {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '6519813321'},
                                 {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '6907320966'},
                                 {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '6296763417'},
                                 {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '450854765928'},
                                 {'cost': 'UTF8_DECODING_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '3111779061'},
                                 {'cost': 'UTF8_DECODING_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '64439285859'},
                                 {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '106651392012'},
                                 {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '36449333193'},
                                 {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '1438151616'},
                                 {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '37251792318'},
                                 {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                  'gas_used': '2596468212'}], 'version': 3},
                             'receipt_ids': ['4H63uHUFKK9b1yXcXyT64q2L2iTc8nugctEcDr3WbF4B'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '397217306224900000000'},
                 'proof': [{'direction': 'Left', 'hash': '8ToGD4wq29Wdjoh1hB2dKncuorjtwvSBh6hoEwRiXhRi'},
                           {'direction': 'Right', 'hash': 'JCTxRpc23h6AFTk7VA1qqkbDToJ2Rm3MkmjwGhoAFd3R'},
                           {'direction': 'Right', 'hash': 'Eg3qAEuxUwfS2Tg8aM7CqeqcGy8bmx3JirDsQexeerLh'}]},
                {'block_hash': '9Qvnf86T7SRaqstFeZxeoMjEtHpfAm4fhuxLk4Y1Kzgv',
                 'id': '4H63uHUFKK9b1yXcXyT64q2L2iTc8nugctEcDr3WbF4B',
                 'outcome': {'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Right', 'hash': '8tq58ZH8fQVzGN9Bkw7wdmSQvL9fPmcsUEEsDM3icQCr'},
                           {'direction': 'Left', 'hash': '7NqRWPgjGP4VGxiPmsQXM8t1WQYu5UYb5rmwzEAF3NQd'},
                           {'direction': 'Right', 'hash': '8xNSQ6d1X5z762sQ2Nfgr7ccmBkP4LJUYMvqNx8VwNFV'},
                           {'direction': 'Right', 'hash': '3v6pR2KHkcvT6QY2Kd6sBX22Qb5NeWB2B7fdhhJ37yzv'}]},
                {'block_hash': '9Qvnf86T7SRaqstFeZxeoMjEtHpfAm4fhuxLk4Y1Kzgv',
                 'id': 'HfkN5z5RfmRJ9JEd467f725Nz7GMARED9fWab9Rz1tht',
                 'outcome': {'executor_id': 'v2.ref-finance.near', 'gas_burnt': 3038703180217, 'logs': [], 'metadata': {
                     'gas_profile': [{'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '5030594109'},
                                     {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '35445963'},
                                     {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '160704302250'},
                                     {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '11400000000'},
                                     {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '10439452800'},
                                     {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '638623944'},
                                     {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '12585825930'},
                                     {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '35876568'},
                                     {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '56356845750'},
                                     {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '154762665'},
                                     {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '836039745'},
                                     {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '64196736000'},
                                     {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '4785478743'},
                                     {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '352414335'},
                                     {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '4621762311'},
                                     {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '177121515186'},
                                     {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '64020289872'},
                                     {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '16822769166'},
                                     {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '1035033360'},
                                     {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '17193134916'},
                                     {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '1950202332'}], 'version': 3},
                             'receipt_ids': ['HTkoBrmEuGTaBgSNMQpMDgMjDZH1KgYsTHpm95pRK1xB'],
                             'status': {'SuccessValue': 'IjExMTk2OTYi'}, 'tokens_burnt': '303870318021700000000'},
                 'proof': [{'direction': 'Left', 'hash': '5TxhsLTRBzt7FVubBmwhv8WgRt1yUTmzFVwr3J6JKkwQ'},
                           {'direction': 'Right', 'hash': 'GDipnKqnx9Pe7wz9HC3ub3ebjm11Nk2wtTY4GeVqvcx3'},
                           {'direction': 'Left', 'hash': '6yrAyTQhB4csSSuC3ANgsgeYtkN32vTRkQZSyjKzaji9'},
                           {'direction': 'Right', 'hash': '3iZb8jyT29fMBAfLgLnQotLD15xe7Kpo1QqYAstdoUW5'}]},
                {'block_hash': 'AUFGE2LevMBV83ahRFEpR9y6BYqDigFLu43uQK29CXtK',
                 'id': 'HTkoBrmEuGTaBgSNMQpMDgMjDZH1KgYsTHpm95pRK1xB',
                 'outcome': {'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': 'AforXhdk8kE5buXUGR1nTeQyocQAmJa4jCNGakP4g9sy'}]},
                {'block_hash': '9RNjE6dbminjUBsG2XHiRJotriFrmH4zkjwYMRfEQ1hG',
                 'id': '3E1mNwRodLZfPFAUpHvMAANNZ5o2Zgk6EFmsDLAzKd6u',
                 'outcome': {'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Right', 'hash': '25NwNL2PVNf8FrFxdoaYciPsWsUAjQhHWy9CwzDgfuaU'},
                           {'direction': 'Left', 'hash': '3G94LWWUuwJqfmjg383Vte2MSjDVikZZXiuZXdJTaepV'},
                           {'direction': 'Right', 'hash': 'Eg3qAEuxUwfS2Tg8aM7CqeqcGy8bmx3JirDsQexeerLh'}]},
                {'block_hash': '9RNjE6dbminjUBsG2XHiRJotriFrmH4zkjwYMRfEQ1hG',
                 'id': 'HvKDaQETtjXM57EAisgTsNaXz6hEZ88b5K5gJGuDEWnS',
                 'outcome': {'executor_id': 'wrap.near', 'gas_burnt': 2828631355066, 'logs': [], 'metadata': {
                     'gas_profile': [{'cost': 'BASE', 'cost_category': 'WASM_HOST_COST', 'gas_used': '4765825998'},
                                     {'cost': 'CONTRACT_LOADING_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '35445963'},
                                     {'cost': 'CONTRACT_LOADING_BYTES', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '40234218750'},
                                     {'cost': 'READ_CACHED_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '11400000000'},
                                     {'cost': 'READ_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '10439452800'},
                                     {'cost': 'READ_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '250887978'},
                                     {'cost': 'READ_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '12585825930'},
                                     {'cost': 'READ_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '20008086'},
                                     {'cost': 'STORAGE_READ_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '56356845750'},
                                     {'cost': 'STORAGE_READ_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '154762665'},
                                     {'cost': 'STORAGE_READ_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '162719145'},
                                     {'cost': 'STORAGE_WRITE_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '64196736000'},
                                     {'cost': 'STORAGE_WRITE_EVICTED_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '931401903'},
                                     {'cost': 'STORAGE_WRITE_KEY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '352414335'},
                                     {'cost': 'STORAGE_WRITE_VALUE_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '899537631'},
                                     {'cost': 'TOUCHING_TRIE_NODE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '112713691482'},
                                     {'cost': 'WASM_INSTRUCTION', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '49331627004'},
                                     {'cost': 'WRITE_MEMORY_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '16822769166'},
                                     {'cost': 'WRITE_MEMORY_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '596506068'},
                                     {'cost': 'WRITE_REGISTER_BASE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '17193134916'},
                                     {'cost': 'WRITE_REGISTER_BYTE', 'cost_category': 'WASM_HOST_COST',
                                      'gas_used': '881962848'}], 'version': 3},
                             'receipt_ids': ['34DQp1Hg7a3yMtwamwSSpvu9kUV5deStPGXXhNBAZ3H6'],
                             'status': {'SuccessValue': 'IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAi'},
                             'tokens_burnt': '282863135506600000000'},
                 'proof': [{'direction': 'Right', 'hash': '9RrtsqoecCazMoqGa4BinRyjKqW9LVAmonekKpBtJ45x'},
                           {'direction': 'Right', 'hash': 'qNq8ULWSyqwKdiQP6ntVteFNYuSgCFU9wN83PvG7sdy'},
                           {'direction': 'Left', 'hash': 'DiPj93AMj4QPU6dFywuyhk81FTHF5QQSWcuf2SLnD2bx'},
                           {'direction': 'Right', 'hash': '55hE55u1C2pBjedLPBGJ7c54ZLFA4VZaLDBaAQuf8hgT'},
                           {'direction': 'Left', 'hash': 'Azt8eWWbpNzevWJn5FfRjERUTec6ra3xr2TeVzg5m4Pd'}]},
                {'block_hash': '9Qvnf86T7SRaqstFeZxeoMjEtHpfAm4fhuxLk4Y1Kzgv',
                 'id': '34DQp1Hg7a3yMtwamwSSpvu9kUV5deStPGXXhNBAZ3H6',
                 'outcome': {'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': 'By5qb8rn3tNzTt39RTFuTc3BVgwz4E93Qh1VdV1wbNPr'}]},
                {'block_hash': 'HVFavmn5MqDKDfcuML3xKoiA34HeKE2i5N1ZByLD55HU',
                 'id': '6hLhXjWnhnDGtmYgr9ZbV4dtEJ9BQ7oqhwF7BJ9W8Lek',
                 'outcome': {'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': 'FwedbcgwxzxZ2N8So2bumvF4zVgrGub5HXqaSeHXHBXG'},
                           {'direction': 'Right', 'hash': '4D831VAgaWLC6kuj6hMCRLP6dKdjrAPV3DCiiAi7iMP4'},
                           {'direction': 'Right', 'hash': 'H9MYvmBUQ4V1TPQvQ1Hv6eDLroF9jm2qXq5UV3p5gq74'}]}],
                                          'status': {'SuccessValue': 'IjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAi'},
                                          'transaction': {'actions': [{'FunctionCall': {
                                              'args': 'eyJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwibXNnIjoie1wiZm9yY2VcIjowLFwiYWN0aW9uc1wiOlt7XCJwb29sX2lkXCI6NCxcInRva2VuX2luXCI6XCJ3cmFwLm5lYXJcIixcInRva2VuX291dFwiOlwiZGFjMTdmOTU4ZDJlZTUyM2EyMjA2MjA2OTk0NTk3YzEzZDgzMWVjNy5mYWN0b3J5LmJyaWRnZS5uZWFyXCIsXCJhbW91bnRfaW5cIjpcIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBcIixcIm1pbl9hbW91bnRfb3V0XCI6XCIwXCJ9LHtcInBvb2xfaWRcIjo0MTc5LFwidG9rZW5faW5cIjpcImRhYzE3Zjk1OGQyZWU1MjNhMjIwNjIwNjk5NDU5N2MxM2Q4MzFlYzcuZmFjdG9yeS5icmlkZ2UubmVhclwiLFwidG9rZW5fb3V0XCI6XCIxNzIwODYyOGY4NGY1ZDZhZDMzZjBkYTNiYmJlYjI3ZmZjYjM5OGVhYzUwMWEzMWJkNmFkMjAxMWUzNjEzM2ExXCIsXCJtaW5fYW1vdW50X291dFwiOlwiMTExNDA5OFwifV19IiwicmVjZWl2ZXJfaWQiOiJ2Mi5yZWYtZmluYW5jZS5uZWFyIn0=',
                                              'deposit': '1', 'gas': 180000000000000,
                                              'method_name': 'ft_transfer_call'}}],
                                                          'hash': '7EzTx2oZzwV1G7pynayHZKPJcTaN6Ra37UiaGEDD2QxE',
                                                          'nonce': 79540996000038,
                                                          'public_key': 'ed25519:5xzZbJ17bcfaXrASdvxHFbwJAiiN4H2GnhC68rzeD43V',
                                                          'receiver_id': 'wrap.near',
                                                          'signature': 'ed25519:61vAPJtaXdF1J4EPajuGqDR4N6Kib4rcb6p2UtgmGmizsJSFnUf1jxVrq1TF7w4PqBJkGSYhqJk2akeKdEGPtvf4',
                                                          'signer_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c'},
                                          'transaction_outcome': {
                                              'block_hash': 'GvdPe8QFdhJFw1m3DdsUE8nqaSfzWzqomEmcFdMRuVRY',
                                              'id': '7EzTx2oZzwV1G7pynayHZKPJcTaN6Ra37UiaGEDD2QxE', 'outcome': {
                                                  'executor_id': '49c6c71594ad38c52e4292e1141b36064bf08d0fe2ddb13333a2fed13b9dec8c',
                                                  'gas_burnt': 2429101573152, 'logs': [],
                                                  'metadata': {'gas_profile': None, 'version': 1},
                                                  'receipt_ids': ['WnGdLKjAn7Hcr7rDKqN3cZJQCm4eTfgJXX3eAzedz6S'],
                                                  'status': {
                                                      'SuccessReceiptId': 'WnGdLKjAn7Hcr7rDKqN3cZJQCm4eTfgJXX3eAzedz6S'},
                                                  'tokens_burnt': '242910157315200000000'}, 'proof': [
                                                  {'direction': 'Left',
                                                   'hash': '9ckHzUmNpUuXusfuvZ3ZhtBN4PvtniQVkJmL6m5xanZU'},
                                                  {'direction': 'Right',
                                                   'hash': 'Hgybyx9mDL9Amd8yJLpAjAaT6nTpm7s98MqadcPquFPC'},
                                                  {'direction': 'Right',
                                                   'hash': '6Zyg2qBhMHkw9ZoXNVnrbaajVCfWGPHpbSxtAUAVrJgo'}]}},
             'id': 'dontcare'},
            {'jsonrpc': '2.0', 'result': {'final_execution_status': 'FINAL', 'receipts_outcome': [
                {'block_hash': '4R34Nju9o3HnWN9wXRp8XbqYoosYN7J4gPFzuxEedENm',
                 'id': 'CGjKeA6VPauMNBkYaxQB3pjHgWTHv5HKsUdsuWn13rci',
                 'outcome': {'executor_id': '7eee5392d8c77b279a329f168ff336b22911f02e850ab518d199c946667de01c',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': ['A8noi3q1Spyw5Myk9jyTvU5TDVKqN5y3VkWvu7TKZtvz'],
                             'status': {'SuccessValue': ''}, 'tokens_burnt': '417494768750000000000'},
                 'proof': [{'direction': 'Right', 'hash': 'DdKmSCgEWVBVru1Q1UFY3Cdm1mwbKi1na2i8xKG6neC3'},
                           {'direction': 'Right', 'hash': '38rgQphMHgUxmWhjN3BX6BhxmLwNiMhnRxL5S8DccCP2'},
                           {'direction': 'Right', 'hash': 'BTrpLPCv3mjwRQAAG5mxRJQNFVArs8LnpSHnT88qjqDm'},
                           {'direction': 'Left', 'hash': 'JC3xNNrRbKzMwMPuucXCaWn9HR5Ds2SMaNzcrqx41w5k'},
                           {'direction': 'Right', 'hash': '5YQtA8oNrhZfxck6EyVGHwfYFKnKxZvhzoTMYJ11XtyC'},
                           {'direction': 'Left', 'hash': 'He8coPAtvaXx35YtEpYFA5T64M1NxUvm6VuiLzBuG2j8'},
                           {'direction': 'Right', 'hash': 'Brk2Yz541o92PoytGa3KxYukQCPE8WFyrJbkm62UntZL'},
                           {'direction': 'Right', 'hash': 'BVTHUM7M8M4gXPr5SHoJzhMbG2V9kTD2sfncfYmMpY9x'}]},
                {'block_hash': 'H9krqez5mKGbPjWcHefAftjPDysstUVgjsew9J4ym1sm',
                 'id': 'A8noi3q1Spyw5Myk9jyTvU5TDVKqN5y3VkWvu7TKZtvz',
                 'outcome': {'executor_id': '830b4be03355f3fe84fcaebf3f56531f30b93d66b95608722b1fff0a0eaca1bd',
                             'gas_burnt': 4174947687500, 'logs': [], 'metadata': {'gas_profile': [], 'version': 3},
                             'receipt_ids': [], 'status': {'SuccessValue': ''}, 'tokens_burnt': '0'},
                 'proof': [{'direction': 'Left', 'hash': '5uihyXxcfDkEvKdDHV3PZvp6e1J9pTTRDkraKAbocJcu'},
                           {'direction': 'Left', 'hash': 'Be7Ur1PUNRWaizTGscCB6R9hEgR7GXGAjh4LBfAucH4N'},
                           {'direction': 'Left', 'hash': 'EW6TC7mZDMuxzkxLtVABupJt1tEmEUtm3MEZeM8SJFvg'},
                           {'direction': 'Right', 'hash': 'AUX3hG8YZKfBoAU14biuoLXfQGYwP6XA7fQ9c8pRaWZ'},
                           {'direction': 'Right', 'hash': 'FiNn3pnZKSp4BgZQPUCf7nxW8kQq72pNkPftR1WB3P9j'},
                           {'direction': 'Left', 'hash': '7XaugNc4azECzmJhEnMhaJzTFvmxjB1z2BvcnsD2YtPm'},
                           {'direction': 'Right', 'hash': '7xuPhNtBarMXyDWsVbgeyk89Ev4ZEFKaq82k2eJbgMJg'}]}],
                                          'status': {'SuccessValue': ''}, 'transaction': {
                    'actions': [{'Transfer': {'deposit': '11534573998150000000000000000'}}],
                    'hash': '2sNimouD5gtJoAmuzk8cRNP2bbRmbREHWw1BeMDQYdbG', 'nonce': 1717,
                    'public_key': 'ed25519:9pYQ9CxJ2efJWxJFV39nZtKwqpPMb7ipfpkSjfbXiQBv',
                    'receiver_id': '7eee5392d8c77b279a329f168ff336b22911f02e850ab518d199c946667de01c',
                    'signature': 'ed25519:3xYjjCn94qefELuhBKeSsXQtEyHKjWySko6kPsUBjWsszcsx1bVosFQBjB1LUD8rAnaUzcAoMQXc9tgoSAMkUyXu',
                    'signer_id': '830b4be03355f3fe84fcaebf3f56531f30b93d66b95608722b1fff0a0eaca1bd'},
                                          'transaction_outcome': {
                                              'block_hash': '67yxppMTdQZDvDiZLhLu7YdaLzeEipZBZcWLeNtYusDc',
                                              'id': '2sNimouD5gtJoAmuzk8cRNP2bbRmbREHWw1BeMDQYdbG', 'outcome': {
                                                  'executor_id': '830b4be03355f3fe84fcaebf3f56531f30b93d66b95608722b1fff0a0eaca1bd',
                                                  'gas_burnt': 4174947687500, 'logs': [],
                                                  'metadata': {'gas_profile': None, 'version': 1},
                                                  'receipt_ids': ['CGjKeA6VPauMNBkYaxQB3pjHgWTHv5HKsUdsuWn13rci'],
                                                  'status': {
                                                      'SuccessReceiptId': 'CGjKeA6VPauMNBkYaxQB3pjHgWTHv5HKsUdsuWn13rci'},
                                                  'tokens_burnt': '417494768750000000000'}, 'proof': [
                                                  {'direction': 'Left',
                                                   'hash': '5qWQXKmgLacxdwn5kRGFh7TiHyhUZLki4FVLRrFQe3Wg'},
                                                  {'direction': 'Right',
                                                   'hash': 'ZTJXms6VPiMGD3DDtvQ5Kqzu834m7HWM6BEKHejbgrE'},
                                                  {'direction': 'Right',
                                                   'hash': '9pJTsjzg25h8GKPGokZbBTeCtNmjz5hwhXPDX4kccPSM'},
                                                  {'direction': 'Right',
                                                   'hash': '6dcCLRhGQ1Hg3yHWz9pPwg5fbRR24FgxhoNQWdyvuQSy'},
                                                  {'direction': 'Left',
                                                   'hash': 'BLqDEWx7ELC5p5CFwYgPLN5LLfvA3953chJqqY5XSVjo'},
                                                  {'direction': 'Right',
                                                   'hash': '2c3PtesULfFVmvE3WADXnLRcJQyYTwshCMNZPicFupV3'},
                                                  {'direction': 'Right',
                                                   'hash': 'HCveDTHxYfNe7uxBiAG7VebFyTTuDrMMjpDrgmVpzPKQ'},
                                                  {'direction': 'Right',
                                                   'hash': '7DzgkKNfZxGYpR8tENYctTGz6ZyqDNQtGiPHixhAiFrN'}]}},
             'id': 'dontcare'}
        ]
        expected_txs_details = [
            {'hash': 'ErWASMPmXEEv1SLpniksjmz691MhcVpizPxHWMrX4LDs', 'success': True, 'block': None, 'date': None,
             'fees': None, 'memo': None, 'confirmations': 0, 'raw': None, 'inputs': [], 'outputs': [], 'transfers': [
                {'type': 'MainCoin', 'symbol': 'NEAR', 'currency': 84,
                 'from': 'ccb91e1db61e8d7e1d4ae3e043001140132959a86ee35a548b6563a46284a6ea',
                 'to': 'd3642d5c2418c9ebb3868378b3de26dfb9eca3a3889e441a40c432f40ec121a9',
                 'value': Decimal('1.988000000000000000000000'), 'is_valid': True,  'memo': None,'token': None}]},
            {'hash': 'EYf7MFDneobGfVWXwjJGbc7gSJWsafUbPxfap5BVBVx', 'success': True, 'block': None, 'date': None,
             'fees': None, 'memo': None, 'confirmations': 0, 'raw': None, 'inputs': [], 'outputs': [], 'transfers': [
                {'type': 'MainCoin', 'symbol': 'NEAR', 'currency': 84,
                 'from': 'eb3c2bfd6bf357f433be30292d78b23f948ee75f63baca2cc5f56cff1751c294',
                 'to': 'e9b2fd9f3a6280ab37f6ce6909f4487aa86e76be3627c83583c0c69a11dd0fe1',
                 'value': Decimal('0.999000000000000000000000'), 'is_valid': True,  'memo': None,'token': None}]},
            {'success': False},
            {'success': False},
            {'hash': '2sNimouD5gtJoAmuzk8cRNP2bbRmbREHWw1BeMDQYdbG', 'success': True, 'block': None, 'date': None,
             'fees': None, 'memo': None, 'confirmations': 0, 'raw': None, 'inputs': [], 'outputs': [], 'transfers': [
                {'type': 'MainCoin', 'symbol': 'NEAR', 'currency': 84,
                 'from': '830b4be03355f3fe84fcaebf3f56531f30b93d66b95608722b1fff0a0eaca1bd',
                 'to': '7eee5392d8c77b279a329f168ff336b22911f02e850ab518d199c946667de01c',
                 'value': Decimal('11534.573998150000000000000000'), 'is_valid': True,  'memo': None,'token': None}]}
        ]
        cls.get_tx_details(tx_details_mock_responses, expected_txs_details)
