# Generated by Django 4.2.3 on 2025-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('network', models.CharField(max_length=10)),
                ('reward_date', models.DateField(db_index=True)),
                ('staked_amount', models.CharField(max_length=100)),
                ('reward_amount', models.CharField(max_length=100)),
                ('reward_rate', models.CharField(max_length=50)),
                ('validators', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('wallet_address', 'network', 'reward_date')},
            },
        ),
    ]
