# Generated by Django 2.1.4 on 2019-02-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('initial_balance', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقه',
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(db_index=True, decimal_places=10, max_digits=20)),
                ('is_active', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competition.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شرکت در مسابقه',
                'verbose_name_plural': 'شرکت در مسابقه',
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitionregistration',
            unique_together={('competition', 'user')},
        ),
    ]
