# Generated by Django 2.1.4 on 2019-02-12 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionregistration',
            name='current_balance',
            field=models.DecimalField(db_index=True, decimal_places=10, default=Decimal('0'), max_digits=20),
        ),
    ]
