# Generated by Django 2.1.4 on 2019-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20190212_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='initial_balance_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
