# Generated by Django 2.1.5 on 2019-02-19 10:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_competition_initial_balance_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='gift_balance',
            field=models.DecimalField(db_index=True, decimal_places=10, default=Decimal('0'), max_digits=20),
        ),
    ]
