# Generated by Django 2.1.7 on 2019-03-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competitionregistration_gift_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='resets_count',
            field=models.IntegerField(default=0),
        ),
    ]
