# Generated by Django 2.1.10 on 2019-07-16 18:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competitionregistration_resets_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionregistration',
            name='current_balance',
            field=models.DecimalField(db_index=True, decimal_places=10, default=Decimal('0'), max_digits=30),
        ),
    ]
