TIME_METRICS_WITH_NO_LABELS = [
    'orderbook_round',
    'depth_chart_all_round',
    'finnotext_send',
    'finnotext_otp',
    'finnotext_inquiry',
    'finnotech_getToken',
    'finnotech_refreshToken',
    'webengage_event',
    'webengage_dsn',
    'auto_kyc_asr',
    'auto_kyc_authorization',
    'transaction_history_csv',
    'transaction_history_pagination',
    'portfolio_daily_initial_balances_milliseconds',
    'portfolio_daily_final_balances_milliseconds',
    'portfolio_daily_wallet_balances_milliseconds',
    'portfolio_daily_total_deposits_milliseconds',
    'portfolio_daily_total_withdraws_milliseconds',
    'portfolio_daily_total_pool_balances_milliseconds',
    'portfolio_daily_total_external_earning_balances_milliseconds',
    'portfolio_monthly_query_milliseconds',
    'checker_check_recent_trades',
    'checker_check_wallets',
    'checker_check_recent_transactions',
    'socialtrade_update_leader_profits_milliseconds',
    'transaction_history_task_export_milliseconds',
    'transaction_history_task_query_milliseconds',
    'mark_prices_update_milliseconds',
    'tara_renewToken',
    'tara_createAccount',
    'tara_getTraceNumber',
    'tara_chargeAccount',
    'tara_dischargeAccount',
    'tara_checkUserBalance',
    'tara_totalInstallments',
    'tara_accountTransactionInquiry',
    'vency_create_account',
    'vency_get_order',
    'vency_cancel_order',
    'vency_calculator',
    'azki_renewToken',
    'azki_createAccount',
    'azki_calculator',
    'azki_getOptions',
    'abc_account_userProfile',
    'abc_liquidate',
    'abc_liquidateMarginCall',
    'abc_withdrawRequest',
    'abc_processWalletTransferLog',
    'abc_createApiLog',
    'abc_debit_recon',
    'abc_debit_recon_ftp_process',
    'abc_debit_recon_settlements_evaluation',
    'abc_debit_recon_settlements_process',
    'abc_parsian_issuerGetRequest',
    'abc_parsian_issue_child_card',
    'abc_parsian_get_province',
    'abc_parsian_get_cities',
    'abc_parsian_debit_card_otp_request',
    'abc_parsian_debit_card_hash_pan',
    'abc_parsian_debit_card_otp_verify',
    'abc_parsian_debit_card_suspend',
    'abc_debit_invoice',
    'abc_debit_invoice_email',
    'abc_market_stats',
    'abc_account_userAddRestriction',
    'abc_account_userRemoveRestriction',
    'abc_wallet_walletTransfer',
    'abc_wallet_walletList',
    'abc_rial_withdraw_request',
    'abc_transaction_batchCreate',
    'liquidate_positions',
    'liquidate_positions_task',
    'xchange_create_user_trade',
    'xchange_settlement',
    'manage_active_positions',
    'manage_inactive_positions',
    'orders_cancel_batch',
    'notification_fcm_time',
    'notification_telegram_time',
    'market_candles',
    'create_pool_pnl_transactions_time',
    'liquidator_check_external_broker_service_status_time',
    'liquidator_process_pending_requests_time',
    'liquidator_create_order_time',
    'liquidator_create_internal_order_time',
    'liquidator_create_external_order_time',
    'liquidator_check_internal_liquidations_status_time',
    'liquidator_check_external_liquidations_status_time',
    'liquidator_update_external_liquidation_time',
    'liquidator_update_liquidation_requests_time',
    'liquidator_submit_external_wallet_trx_time',
    'liquidator_retry_failed_external_wallet_trx_time',
    'liquidator_update_periodic_metrics_time',
]

TIME_METRICS_WITH_LABELS = {
    'orderbook_calculation': ['stage_name', 'symbol', 'type'],
    'match_waiting_seconds': ['symbol'],
    'matcher_duration_milliseconds': ['symbol', 'has_trade', 'step'],
    'matching_time': ['step'],
    'commit_trade_async': ['symbol'],
    'update_recent_trades_cache': ['symbol'],
    'matching_round': ['full'],
    'matcher_markets_query_milliseconds': ['full'],
    'matcher_get_orders': ['symbol'],
    'matcher_match_time': ['symbol'],
    'staking': ['tp', 'name'],
    'abc_db_lock_wait': ['name'],
    'balancer': [
        'tp',  # mainQuery, fetchLastTransaction, lastBalanceBySum, updateTransaction
    ],
    'order_list_query_milliseconds': ['trade_type'],
    'portfolio_save_milliseconds': ['batch_size'],
    'margin_system_settlement_interval_milliseconds': ['status'],
    'integrations_JibitIdentity_duration': ['service'],
    'verification_success_request_v2': ['provider', 'service'],
    'metric_convert_marketmaker_services_time': ['server', 'service_name'],
    'consumer_process_time': ['consumer'],  # Consumer metric
    'consumer_e2e_latency': ['consumer'],  # Consumer metric
    'api_process_time': ['api', 'server', 'status_code'],  # API metric
    'cron_process_time': ['app', 'cron', 'success'],  # Cron Metrics
    'transaction_process_time': ['method'],
    'metric_notification_sms_time': ['third_party', 'type'],
    'metric_smsir_api_time': ['version', 'api'],  # smsir APIs
    'metric_sms_provider_api_process_time': ['version', 'api'],
    'withdraw_request_to_confirm_duration': ['validity'],
    'publisher_process_time': ['function'],
    'direct_debit_provider_time': ['provider', 'service_name', 'bank'],
    'tradeprocessor_process_time': ['function'],
    'margin_tasks_process_time': ['task'],
    'cobanking_thirdparty_services_time': ['provider', 'method', 'result'],
    'cobank_deposit_settlement_lag': ['bank'],
    'matcher_process_time': ['function'],
}

COUNTER_METRICS_WITH_LABELS = {
    'login': [
        'status',  # restrictedIP, badIP, badPass, badUser, badOTP, ok
        'captcha',
        'country',
        'otp',
        'remember',
        'device',
    ],
    'login_social': [
        'service',  # google
        'status',  # restrictedIP, failed, invalid, outdated, disabled, badOTP, ok
        'cause',  # name of the exception class, - if no exception
    ],
    'signup': ['tp', 'channel', 'status'],
    'signup_email_confirm_link': ['status'],
    'captcha': ['tp', 'status'],
    'rawcaptcha': ['tp', 'status', 'usage'],
    'integrations_errors': ['service_name', 'subservice_name', 'type'],
    'integrations_calls': ['service_name', 'subservice_name'],
    'api_price_data': ['service', 'status'],
    'api_voice_message': ['service', 'status'],
    'orderbook_active_orders_total': ['symbol', 'side'],
    'matcher_trades_total': ['symbol'],
    'matcher_failures_total': ['symbol'],
    'matcher_runs_total': ['tp'],
    'balancer': [
        'tp',  # availableWalletBalance, availableLastTransaction, lastBalanceBySum, lastBalanceIsZero, updateTransaction
    ],
    'matcher_slow_round_total': ['ge'],
    'position_old_version_requests': ['endpoint'],
    'telegram_message': [
        'status',  # sent, ignored, retried, failed
    ],
    'notification_telegram_message_count': [
        'status',  # sent, ignored, retried, failed
    ],
    'notification_fcm_count': [
        'status',  # sent, failed
    ],
    'cdn_prices_error_total': ['error', 'status', 'exchange'],
    'mark_price_spread_sum': ['exchange', 'symbol'],
    'mark_price_spread_count': ['exchange', 'symbol'],
    'convert_marketmaker_services': ['server', 'service_name', 'type'],
    'abc_errors': ['service_name', 'subservice_name', 'type'],
    'abc_calls': ['service_name', 'subservice_name'],
    'abc_get_wallets': ['type'],
    'convert_services': ['service_name', 'type'],
    'amount_gt_pool_available_balance': ['symbol', 'side'],
    'direct_debit_provider_calls': ['provider', 'service_name', 'bank', 'status'],
    'trade_processor_runs_total': ['status'],
    'integrations_JibitIdentity': ['service', 'status'],
    'verification': ['service', 'provider', 'status', 'provider_priority'],
    'verification_no_provider': ['service', 'is_jibit_active', 'is_finnotech_active'],
    'fcm_duplicate_device': ['device_type'],
    'verification_api_failed': ['provider'],
    'market_order': ['status'],
    'margin_liquidated_positions_count': ['src', 'dst', 'side'],
    'margin_liquidated_positions_sum': ['src', 'dst', 'side'],
    'websocket_publisher': [
        'error_classname',  # classname of the error
    ],
    'consumer_process_count': ['consumer'],  # Consumer metric
    'api_process_count': ['api', 'server', 'status_code'],  # API metric
    'api_process_result_count': ['api', 'server', 'result'],
    'cron_process_count': ['app', 'cron', 'success'],  # Cron Metrics
    'transaction_process_count': ['method'],
    'notification_sms_count': ['third_party', 'type', 'status'],
    'smsir_api_counter': ['version', 'result', 'template'],
    'sms_provider_api_counter': ['version', 'result', 'template'],
    'send_email_counter': ['backend', 'priority', 'template'],
    'withdraw_count': ['currency', 'network', 'status'],
    'change_user_type': ['new_type'],
    'kyc_verification': ['verification_type', 'status'],
    'upload_file_size': ['status', 'type'],
    'publisher_process_count': ['function'],
    'tradeprocessor_process_count': ['function'],
    'margin_tasks_process_count': ['task'],
    'matcher_process_count': ['function'],
    'cobanking_thirdparty_services_count': ['provider', 'method', 'result'],
    'cobanking_core_services_count': ['service', 'provider', 'bank', 'status'],
    'coinmarketcap_map_api_error_codes': ['status_code'],
    'pool_pnl_positions_count': ['object_name'],
    'liquidator_external_market_errors': ['metric_name', 'status_code'],
    'liquidator_external_market_calls': ['metric_name'],
    'fcm_send': ['status'],
}

COUNTER_METRICS_WITH_NO_LABELS = ['email_verification_request_for_confirmed_user', 'matcher_run_total_time']
