# Generated by Django 2.2.28 on 2022-07-09 09:01

from django.db import migrations, models
import exchange.integrations.models.fata


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FataAPICallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=16)),
                ('inquiry_type', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('inquiry_value', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('inquiry_result', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FataLoginToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('key', models.CharField(default=exchange.integrations.models.fata.generate_key, editable=False, max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
