# Generated by Django 2.2.24 on 2022-11-08 11:55

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0104_auto_20221016_1353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رمز\u200cارز')),
                ('type', models.IntegerField(choices=[(1, 'پشتیبانی شده'), (2, 'پشتیبانی نشده'), (3, 'جعلی')], verbose_name='نوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'ارز بازیابی',
                'verbose_name_plural': 'ارز بازیابی',
            },
        ),
        migrations.CreateModel(
            name='RecoveryNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شبکه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'شبکه بازیابی',
                'verbose_name_plural': 'شبکه بازیابی',
            },
        ),
        migrations.CreateModel(
            name='RecoveryCurrencyNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('unsupported', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_networks', related_query_name='currency_networks', to='recovery.RecoveryCurrency')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_currencies', related_query_name='network_currencies', to='recovery.RecoveryNetwork')),
            ],
            options={
                'unique_together': {('currency', 'network')},
            },
        ),
        migrations.AddField(
            model_name='recoverycurrency',
            name='networks',
            field=models.ManyToManyField(related_name='currencies', related_query_name='currencies', through='recovery.RecoveryCurrencyNetwork', to='recovery.RecoveryNetwork'),
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='مقدار')),
                ('deposit_hash', models.CharField(max_length=200, verbose_name='هش تراکنش')),
                ('return_address', models.CharField(max_length=200, verbose_name='آدرس بازگشت')),
                ('inconsistency', models.BooleanField(default=False, verbose_name='ناسازگاری')),
                ('status', models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده'), (3, 'تایید اولیه')], default=0)),
                ('currency_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', related_query_name='recoveries', to='recovery.RecoveryCurrencyNetwork', verbose_name='ارز، شبکه')),
                ('deposit_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', related_query_name='recoveries', to='wallet.WalletDepositAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', related_query_name='recoveries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازیابی',
                'verbose_name_plural': 'بازیابی',
            },
        ),
        migrations.AlterUniqueTogether(
            name='recoverycurrency',
            unique_together={('type', 'name')},
        ),
    ]
