# Generated by Django 2.2.24 on 2022-11-28 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0104_auto_20221016_1353'),
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='کارمزد'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='is_rial_fee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recovery',
            name='recovery_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک بازیابی'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction', verbose_name='تراکنش'),
        ),
    ]
