# Generated by Django 2.2.24 on 2022-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_auto_20221128_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='is_rial_fee',
            field=models.BooleanField(default=False),
        ),
    ]
