# Generated by Django 2.2.28 on 2022-12-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0163_auto_20221019_2050'),
        ('recovery', '0003_auto_20221128_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_image', to='accounts.UploadedFile', verbose_name='اسکرین ولت'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ممو'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='deposit_hash',
            field=models.CharField(max_length=200, unique=True, verbose_name='هش تراکنش'),
        ),
        migrations.AlterField(
            model_name='recoverynetwork',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام شبکه'),
        ),
    ]
