# Generated by Django 2.2.28 on 2022-12-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_auto_20221204_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='recovery_hash',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='هش بازیابی'),
        ),
    ]
