# Generated by Django 2.2.28 on 2023-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0005_auto_20221210_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recoverycurrency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recoverycurrency',
            name='networks',
        ),
        migrations.AlterUniqueTogether(
            name='recoverycurrencynetwork',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recoverycurrencynetwork',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='recoverycurrencynetwork',
            name='network',
        ),
        migrations.DeleteModel(
            name='Recovery',
        ),
        migrations.DeleteModel(
            name='RecoveryCurrency',
        ),
        migrations.DeleteModel(
            name='RecoveryCurrencyNetwork',
        ),
        migrations.DeleteModel(
            name='RecoveryNetwork',
        ),
    ]
