# Generated by Django 2.2.24 on 2023-05-21 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0110_auto_20230517_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recovery', '0006_auto_20230520_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام رمز\u200cارز')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('contract', models.CharField(max_length=200, unique=True, verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'رمزارز بازیابی',
                'verbose_name_plural': 'رمزارز بازیابی',
            },
        ),
        migrations.CreateModel(
            name='RecoveryNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام شبکه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'شبکه بازیابی',
                'verbose_name_plural': 'شبکه بازیابی',
            },
        ),
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین تغییر وضعیت')),
                ('contract', models.CharField(max_length=200, verbose_name='قرارداد')),
                ('currency', models.CharField(max_length=50, verbose_name='نام رمز\u200cارز')),
                ('network', models.CharField(max_length=50, verbose_name='نام شبکه')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'جدید'), (2, 'تایید اولیه'), (3, 'تایید نهایی'), (4, 'آماده برای بازیابی'), (5, 'انجام شده'), (6, 'رد شده'), (7, 'غیرقابل بازیابی')], default=1)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('deposit_tag', models.IntegerField(blank=True, null=True, verbose_name='تگ')),
                ('deposit_hash', models.CharField(max_length=200, verbose_name='هش تراکنش')),
                ('return_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس بازگشت')),
                ('return_tag', models.IntegerField(blank=True, null=True, verbose_name='تگ بازگشت')),
                ('recovery_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک بازیابی')),
                ('recovery_hash', models.CharField(blank=True, max_length=200, null=True, verbose_name='هش بازیابی')),
                ('deposit_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', related_query_name='recoveries', to='wallet.WalletDepositAddress')),
            ],
            options={
                'verbose_name': 'درخواست بازیابی',
                'verbose_name_plural': 'درخواست بازیابی',
            },
        ),
        migrations.CreateModel(
            name='RecoveryTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.PositiveSmallIntegerField(choices=[(1, 'کسر کارمزد')], default=1)),
                ('recovery_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recovery.RecoveryRequest', verbose_name='درخواست بازیابی')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.Transaction', verbose_name='تراکنش')),
            ],
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='transactions',
            field=models.ManyToManyField(through='recovery.RecoveryTransaction', to='wallet.Transaction', verbose_name='تراکنش\u200cها'),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', related_query_name='recoveries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
