# Generated by Django 2.2.24 on 2023-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0007_auto_20230521_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryrequest',
            name='inconsistency',
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='is_inconsistent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recoverycurrency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام رمز\u200cارز'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='deposit_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='return_address',
            field=models.CharField(default='', max_length=200, verbose_name='آدرس بازگشت'),
            preserve_default=False,
        ),
    ]
