# Generated by Django 2.2.24 on 2023-05-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_auto_20220904_0020'),
        ('recovery', '0008_auto_20230522_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryrequest',
            name='block_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.Order'),
        ),
    ]
