# Generated by Django 2.2.24 on 2023-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0009_recoveryrequest_block_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='مقدار'),
            preserve_default=False,
        ),
    ]
