# Generated by Django 2.2.28 on 2023-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0010_recoverytransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverynetwork',
            name='fee',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='کارمزد شبکه'),
            preserve_default=False,
        ),
    ]
