# Generated by Django 2.2.24 on 2023-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0011_recoverynetwork_fee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recoveryrequest',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status__in=[6, 7]), fields=('user', 'deposit_hash'), name='unique_user_deposit_hash'),
        ),
    ]
