# Generated by Django 2.2.24 on 2023-05-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0012_auto_20230528_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryrequest',
            name='is_inconsistent',
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='block_order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='market.Order'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recoverytransaction',
            constraint=models.UniqueConstraint(fields=('recovery_request', 'tp'), name='unique_recovery_request_tp'),
        ),
    ]
