# Generated by Django 2.2.24 on 2023-06-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0013_auto_20230531_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryrequest',
            name='block_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Order'),
        ),
    ]
