# Generated by Django 2.2.24 on 2023-07-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0014_auto_20230613_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryrequest',
            name='deposit_tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='return_tag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تگ بازگشت'),
        ),
    ]
