# Generated by Django 2.2.28 on 2023-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0015_auto_20230719_1235'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recoveryrequest',
            name='unique_user_deposit_hash',
        ),
        migrations.AddConstraint(
            model_name='recoveryrequest',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status__in=[6, 8]), fields=('user', 'deposit_hash'), name='unique_user_deposit_hash'),
        ),
    ]
