# Generated by Django 4.2.14 on 2024-10-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_ordermatching__buy_order_ordermatching__sell_order'),
        ('recovery', '0016_auto_20231105_1440'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='recoveryrequest',
                    name='block_order',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.order', to_field='_id'),
                ),
            ],
            state_operations=[],
        ),
    ]
