# Generated by Django 3.2.23 on 2024-12-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recovery', '0017_alter_recoveryrequest_block_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDepositRequestReInquiryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manual_deposit_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.manualdepositrequest', verbose_name='واریز دستی')),
            ],
        ),
    ]
