# Generated by Django 3.2.23 on 2025-01-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0018_auto_20241208_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=30, verbose_name='مقدار'),
        ),
    ]
