# Generated by Django 4.2.19 on 2025-03-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0020_remove_recoverycurrency_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoveryrejectreasons',
            old_name='reseans',
            new_name='reasons',
        ),
        migrations.AlterField(
            model_name='recoveryrejectreasons',
            name='recovery',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reject_reasons',
                to='recovery.recoveryrequest',
            ),
        ),
    ]
