# Generated by Django 4.2.19 on 2025-04-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0021_rename_reseans_recoveryrejectreasons_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryrequest',
            name='currency_tmp',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='recovery.recoverycurrency',
                verbose_name='رمز ارز',
            ),
        ),
        migrations.AddField(
            model_name='recoveryrequest',
            name='network_tmp',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='recovery.recoverynetwork',
                verbose_name='نام شبکه',
            ),
        ),
        migrations.AlterField(
            model_name='recoveryrequest',
            name='contract',
            field=models.CharField(max_length=200, null=True, verbose_name='قرارداد'),
        ),
    ]
