# Generated by Django 4.2.19 on 2025-04-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0022_recoveryrequest_currency_tmp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryrequest',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='recoveryrequest',
            name='network',
        ),
        migrations.RenameField(model_name='recoveryrequest', old_name='currency_tmp', new_name='currency'),
        migrations.RenameField(model_name='recoveryrequest', old_name='network_tmp', new_name='network'),
    ]
