# Generated by Django 2.2.13 on 2020-06-05 18:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_source', models.CharField(db_index=True, max_length=200)),
                ('owner_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('content', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_source', models.CharField(db_index=True, max_length=200)),
                ('owner_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('content', jsonfield.fields.JSONField()),
            ],
        ),
    ]
