# Generated by Django 2.2.13 on 2020-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='owner_id',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='owner_source',
            new_name='ownerSource',
        ),
        migrations.RenameField(
            model_name='studytemplate',
            old_name='owner_id',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='studytemplate',
            old_name='owner_source',
            new_name='ownerSource',
        ),
        migrations.AlterField(
            model_name='chart',
            name='ownerId',
            field=models.CharField(db_column='owner_id', db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chart',
            name='ownerSource',
            field=models.CharField(db_column='owner_source', db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studytemplate',
            name='ownerId',
            field=models.CharField(db_column='owner_id', db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studytemplate',
            name='ownerSource',
            field=models.CharField(db_column='owner_source', db_index=True, max_length=200),
        ),
    ]
