# Generated by Django 4.2.16 on 2024-10-19 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0002_auto_20200625_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='charts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
