# Generated by Django 4.2.17 on 2025-01-12 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0003_chart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytemplate',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='study_templates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
