# Generated by Django 4.2.17 on 2025-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_studytemplate_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studytemplate',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_studytemplate_user_name_asdji29a'),
        ),
    ]
