# Generated by Django 2.2.26 on 2022-09-10 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0101_auto_20220904_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کیف\u200cپول مشارکت',
                'verbose_name_plural': 'کیف\u200cپول\u200cهای مشارکت',
            },
        ),
        migrations.CreateModel(
            name='PoolDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('delegation_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='pool.DelegationWallet', verbose_name='کیف\u200cپول مشارکت')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'مشارکت در استخر',
                'verbose_name_plural': 'مشارکت\u200cهای استخر',
            },
        ),
        migrations.CreateModel(
            name='LiquidityPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph')], unique=True, verbose_name='ارز')),
                ('capacity', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='ظرفیت مشارکت')),
                ('filled_capacity', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ظرفیت پرشده')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال؟')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'استخر مشارکت',
                'verbose_name_plural': 'استخرهای مشارکت',
            },
        ),
        migrations.AddField(
            model_name='delegationwallet',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_wallets', to='pool.LiquidityPool', verbose_name='استخر'),
        ),
        migrations.AddField(
            model_name='delegationwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_wallets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddConstraint(
            model_name='liquiditypool',
            constraint=models.CheckConstraint(check=models.Q(('filled_capacity__gte', 0), ('filled_capacity__lte', django.db.models.expressions.F('capacity'))), name='pool_capacity_limit'),
        ),
        migrations.AddConstraint(
            model_name='delegationwallet',
            constraint=models.CheckConstraint(check=models.Q(balance__gte=0), name='delegation_non_negative_balance'),
        ),
        migrations.AlterUniqueTogether(
            name='delegationwallet',
            unique_together={('pool', 'user')},
        ),
    ]
