# Generated by Django 2.2.28 on 2023-02-07 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0002_auto_20221106_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='خصوصی؟'),
        ),
        migrations.CreateModel(
            name='PoolAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.SmallIntegerField(choices=[(1, 'Liquidity Provider'), (2, 'Trader')], verbose_name='نوع دسترسی')),
                ('user_type', models.SmallIntegerField(blank=True, choices=[(0, 'Normal'), (10, 'Inactive'), (20, 'Suspicious'), (30, 'Blocked'), (40, 'Level0'), (42, 'Level1P'), (44, 'Level1'), (45, 'Trader'), (46, 'Level2'), (90, 'Level3'), (91, 'Active'), (92, 'Trusted'), (99, 'Nobitex'), (100, 'System'), (101, 'Bot'), (102, 'Staff')], null=True, verbose_name='سطح کاربری')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('liquidity_pool', models.ForeignKey(limit_choices_to={'is_private': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pool_accesses', related_query_name='pool_access', to='pool.LiquidityPool', verbose_name=' استخر مشارکت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سطح دسترسی به استخر مشارکت',
                'verbose_name_plural': 'سطوح دسترسی به استخر مشارکت',
            },
        ),
    ]
