# Generated by Django 2.2.28 on 2023-02-12 16:42
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20230207_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegationwallet',
            unique_together=set(),
        ),
        migrations.RenameModel(
            old_name='PoolDelegation',
            new_name='DelegationTransaction',
        ),
        migrations.RenameModel(
            old_name='DelegationWallet',
            new_name='UserDelegation',
        ),
        migrations.RenameField(
            model_name='delegationtransaction',
            old_name='delegation_wallet',
            new_name='user_delegation',
        ),
        migrations.AlterField(
            model_name='userdelegation',
            name='pool',
            field=models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='user_delegations', to='pool.LiquidityPool', verbose_name='استخر'),
        ),
        migrations.AlterField(
            model_name='userdelegation',
            name='user',
            field=models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='user_delegations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='userdelegation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن'),
        ),
        migrations.AddConstraint(
            model_name='userdelegation',
            constraint=models.UniqueConstraint(condition=models.Q(closed_at=None), fields=('pool', 'user'), name='unique_active_user_delegation'),
        ),
    ]
