# Generated by Django 2.2.26 on 2023-02-27 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_auto_20230212_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='min_available_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=2, verbose_name='نسبت ظرفیت آزاد کمینه'),
        ),
    ]
