# Generated by Django 2.2.28 on 2023-03-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_liquiditypool_min_available_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='current_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='سود دوره فعلی'),
        ),
        migrations.CreateModel(
            name='PoolProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='تاریخ شروع')),
                ('to_date', models.DateField(verbose_name='تاریخ پایان')),
                ('currency', models.SmallIntegerField(choices=[(2, '﷼'), (13, 'Tether')], verbose_name='ارز')),
                ('position_profit', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='سود حاصل از موقعیت\u200cها')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profits', to='pool.LiquidityPool', verbose_name='استخر')),
            ],
            options={
                'verbose_name': 'سود استخر',
                'verbose_name_plural': 'سودهای استخر',
                'unique_together': {('from_date', 'pool', 'currency')},
            },
        ),
    ]
