# Generated by Django 2.2.28 on 2023-03-07 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_pool_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationRevokeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Paid')], default=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'درخواست لغو مشارکت',
                'verbose_name_plural': 'درخواست\u200cهای لغو مشارکت',
            },
        ),
        migrations.RemoveConstraint(
            model_name='liquiditypool',
            name='pool_capacity_limit',
        ),
        migrations.AddField(
            model_name='liquiditypool',
            name='revoked_capacity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ظرفیت پر نشده\u200cی لغو مشارکت'),
        ),
        migrations.AddConstraint(
            model_name='liquiditypool',
            constraint=models.CheckConstraint(check=models.Q(('filled_capacity__gte', 0), ('filled_capacity__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('capacity'), '+', django.db.models.expressions.F('revoked_capacity')))), name='pool_capacity_limit'),
        ),
        migrations.AddField(
            model_name='delegationrevokerequest',
            name='delegation_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegation_revoke_request', to='pool.DelegationTransaction', verbose_name='تراکنش لغو مشارکت'),
        ),
        migrations.AddField(
            model_name='delegationrevokerequest',
            name='user_delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_revoke_requests', related_query_name='delegation_revoke_request', to='pool.UserDelegation', verbose_name='کیف\u200cپول مشارکت'),
        ),
        migrations.AddIndex(
            model_name='delegationrevokerequest',
            index=models.Index(condition=models.Q(status=1), fields=['user_delegation'], name='delegation_revoke_request_id'),
        ),
    ]
