# Generated by Django 2.2.28 on 2023-03-12 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0007_delegation_revoke_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolUnfilledCapacityAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست ارسال نوتیف')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال نوتیف')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unfilled_capacity_alerts', related_query_name='unfilled_capacity_alert', to='pool.LiquidityPool', verbose_name='استخر مشارکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوتیف ظرفیت خالی استخر',
                'verbose_name_plural': 'نوتیف\u200cهای ظرفیت خالی استخر',
            },
        ),
        migrations.AddConstraint(
            model_name='poolunfilledcapacityalert',
            constraint=models.UniqueConstraint(condition=models.Q(sent_at=None), fields=('pool', 'user'), name='unique_active_notification'),
        ),
    ]
