# Generated by Django 2.2.28 on 2023-03-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_unfilled_alert'),
        ('market', '0041_client_order_id_squashed_0043_auto_20230121_1244'),
        ('wallet', '0107_auto_20230403_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolprofit',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='_poolprofit_orders_+', to='market.Order', verbose_name='سفارشات تبدیل به ریال'),
        ),
        migrations.AddField(
            model_name='poolprofit',
            name='rial_value',
            field=models.DecimalField(decimal_places=0, max_digits=25, null=True, verbose_name='سود به ریال'),
        ),
        migrations.AddField(
            model_name='poolprofit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction', verbose_name='تراکنش'),
        ),
        migrations.CreateModel(
            name='UserDelegationProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='تاریخ شروع')),
                ('to_date', models.DateField(verbose_name='تاریخ پایان')),
                ('delegation_score', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='امتیاز مشارکت')),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='مقدار سود')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction', verbose_name='تراکنش')),
                ('user_delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profits', to='pool.UserDelegation', verbose_name='مشارکت')),
            ],
            options={
                'verbose_name': 'سود مشارکت کاربر',
                'verbose_name_plural': 'سودهای مشارکت کاربر',
            },
        ),
    ]
