# Generated by Django 2.2.28 on 2023-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_auto_20230317_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='apr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سود تقریبی سالیانه'),
        ),
    ]
