# Generated by Django 2.2.28 on 2023-03-18 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_auto_20230318_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdelegation',
            name='total_profit',
            field=models.DecimalField(decimal_places=0, default=Decimal(0), max_digits=25, verbose_name='سود کلی'),
        ),
    ]
