# Generated by Django 2.2.28 on 2023-04-17 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_auto_20230318_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMinimumAvailableRatioAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال نوتیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.LiquidityPool', verbose_name='استخر مشارکت')),
            ],
            options={
                'verbose_name': 'نوتیف کمینه نسبت ظرفیت دردسترس',
                'verbose_name_plural': 'نوتیف\u200cهای کمینه نسبت ظرفیت دردسترس',
            },
        ),
    ]
