# Generated by Django 2.2.28 on 2023-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_pool_minimum_available_ratio_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فعال\u200cسازی'),
        ),
    ]
