# Generated by Django 2.2.28 on 2023-05-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_add_activated_at_in_pool'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdelegationprofit',
            unique_together={('from_date', 'user_delegation')},
        ),
    ]
