# Generated by Django 3.2.19 on 2023-05-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_auto_20230502_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='تاریخ شروع')),
                ('to_date', models.DateField(verbose_name='تاریخ پایان')),
                ('apr', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='سود تقریبی سالیانه')),
                ('balance', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='موجودی پایان دوره')),
                ('total_delegators', models.PositiveIntegerField(verbose_name='تعداد مشارکت کننده')),
                ('avg_balance', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='نسبت کل امتیازات به تعداد روز')),
                ('capacity', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='ظرفیت پایان دوره')),
                ('total_profit_in_rial', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='سود کل دوره به ریال')),
                ('token_price', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='فیمت توکن استخر')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.liquiditypool', verbose_name='استخر مشارکت')),
            ],
            options={
                'verbose_name': 'آمار استخر',
                'verbose_name_plural': 'آمار استخر',
            },
        ),
    ]
