# Generated by Django 2.2.26 on 2023-05-28 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0015_pool_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolItemChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_field', models.TextField(verbose_name='نام فیلد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تغییر')),
                ('old_value', models.TextField(verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(verbose_name='مقدار جدید')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.LiquidityPool', verbose_name='استخر مشارکت')),
            ],
            options={
                'verbose_name': 'تغییر ایتم های استخر مشارکت',
            },
        ),
    ]
