# Generated by Django 2.2.26 on 2023-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_auto_20230528_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolitemchange',
            old_name='name_of_field',
            new_name='name',
        ),
    ]
