# Generated by Django 2.2.28 on 2023-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0017_auto_20230530_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditypool',
            name='max_leverage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='اهرم بیشینه'),
        ),
    ]
