# Generated by Django 2.2.28 on 2023-07-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0018_liquiditypool_max_leverage'),
        ('market', '0044_auto_20230726_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquiditypool',
            name='max_leverage',
        ),
    ]
