# Generated by Django 4.2.13 on 2024-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0019_auto_20230726_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationrevokerequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='delegationtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='poolprofit',
            name='position_profit',
            field=models.DecimalField(decimal_places=10, max_digits=30, verbose_name='سود حاصل از موقعیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='poolprofit',
            name='rial_value',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True, verbose_name='سود به ریال'),
        ),
    ]
