# Generated by Django 4.2.14 on 2024-09-08 13:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_alter_market_dst_currency_alter_market_src_currency_and_more'),
        ('pool', '0020_auto_20240824_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationrevokerequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='delegationtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='liquiditypool',
            name='capacity',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='ظرفیت مشارکت'),
        ),
        migrations.AlterField(
            model_name='liquiditypool',
            name='current_profit',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=22, verbose_name='سود دوره فعلی'
            ),
        ),
        migrations.AlterField(
            model_name='liquiditypool',
            name='filled_capacity',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=25, verbose_name='ظرفیت پرشده'
            ),
        ),
        migrations.AlterField(
            model_name='liquiditypool',
            name='revoked_capacity',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=25, verbose_name='ظرفیت پر نشده\u200cی لغو مشارکت'
            ),
        ),
        migrations.AlterField(
            model_name='poolprofit',
            name='position_profit',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='سود حاصل از موقعیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='poolprofit',
            name='rial_value',
            field=models.DecimalField(decimal_places=0, max_digits=22, null=True, verbose_name='سود به ریال'),
        ),
        migrations.AlterField(
            model_name='poolstat',
            name='avg_balance',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='نسبت کل امتیازات به تعداد روز'),
        ),
        migrations.AlterField(
            model_name='poolstat',
            name='balance',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='موجودی پایان دوره'),
        ),
        migrations.AlterField(
            model_name='poolstat',
            name='capacity',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='ظرفیت پایان دوره'),
        ),
        migrations.AlterField(
            model_name='poolstat',
            name='token_price',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='فیمت توکن استخر'),
        ),
        migrations.AlterField(
            model_name='poolstat',
            name='total_profit_in_rial',
            field=models.DecimalField(decimal_places=0, max_digits=25, verbose_name='سود کل دوره به ریال'),
        ),
        migrations.AlterField(
            model_name='userdelegationprofit',
            name='amount',
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='مقدار سود'
            ),
        ),
    ]
