# Generated by Django 4.2.14 on 2024-10-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_ordermatching__buy_order_ordermatching__sell_order'),
        ('pool', '0021_alter_delegationrevokerequest_amount_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PoolProfit_orders',
                    fields=[
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order')),
                    ],
                ),
            ],
        ),
        migrations.AlterField(
            model_name='poolprofit_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', to_field='_id'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='PoolProfit_orders',
                ),
            ],
        ),
    ]
