# Generated by Django 4.2.13 on 2025-06-11 11:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0022_alter_poolprofit_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelegationLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverage', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=2, verbose_name='اهرم')),
                ('order_type', models.IntegerField(choices=[(1, 'Sell'), (2, 'Buy')], verbose_name='نوع')),
                ('limitation', models.DecimalField(decimal_places=10, max_digits=22)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelegationLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_level', models.PositiveSmallIntegerField()),
                ('leverage', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=2, verbose_name='اهرم')),
                ('order_type', models.IntegerField(choices=[(1, 'Sell'), (2, 'Buy')], verbose_name='نوع')),
                ('limitation', models.DecimalField(decimal_places=10, max_digits=22)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userdelegationlimit',
            constraint=models.UniqueConstraint(fields=('user', 'market', 'order_type', 'leverage'), name='unique_user_and_market_per_leverage_and_order_type'),
        ),
        migrations.AddConstraint(
            model_name='delegationlimit',
            constraint=models.UniqueConstraint(fields=('vip_level', 'market', 'order_type', 'leverage'), name='unique_vip_level_and_market_per_leverage_and_order_type'),
        ),
    ]
