# Generated by Django 4.2.21 on 2025-05-19 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.apikey.models.permission


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('ip_addresses_whitelist', models.JSONField(default=list)),
                ('permission_bits', models.IntegerField(default=exchange.apikey.models.permission.Permission['NONE'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
