# Generated by Django 2.1.11 on 2019-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190809_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.TextField(help_text='آی\u200cپی یا محدوده آی\u200cپی', max_length=20)),
                ('range_begin', models.IntegerField(default=0, help_text='معادل عددی شروع گستره، اختیاری')),
                ('range_end', models.IntegerField(default=0, help_text='معادل عددی پایان گستره، اختیاری')),
                ('country', models.CharField(default='UN', help_text='نام دو حرفی کشور به حروف بزرگ', max_length=2)),
            ],
        ),
    ]
