# Generated by Django 2.1.11 on 2019-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_knownip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knownip',
            options={'verbose_name': 'آدرس IP', 'verbose_name_plural': 'آدرس IP'},
        ),
        migrations.AlterField(
            model_name='knownip',
            name='ip_range',
            field=models.CharField(help_text='آی\u200cپی یا محدوده آی\u200cپی', max_length=20),
        ),
    ]
