# Generated by Django 2.1.11 on 2019-10-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0004_auto_20190828_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آی\u200cپی کاربر',
                'verbose_name_plural': 'آی\u200cپی کاربر',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userip',
            unique_together={('user', 'ip')},
        ),
    ]
