# Generated by Django 2.1.11 on 2019-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20191022_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='country',
            field=models.CharField(blank=True, help_text='نام دو حرفی کشور به حروف بزرگ', max_length=2, null=True),
        ),
    ]
