# Generated by Django 2.1.11 on 2019-10-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_userip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownip',
            name='city',
            field=models.CharField(default='UN', help_text='نام شهر', max_length=100),
        ),
        migrations.AddField(
            model_name='userip',
            name='city',
            field=models.CharField(default='UN', help_text='نام شهر', max_length=100),
        ),
    ]
