# Generated by Django 2.2.24 on 2021-09-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0007_auto_20191028_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCancelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_code', models.CharField(db_index=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد لغو اضطراری برداشت',
                'verbose_name_plural': 'کد لغو اضطراری برداشت',
            },
        ),
    ]
