# Generated by Django 2.2.24 on 2021-09-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_emergencycancelcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycancelcode',
            name='cancel_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencycancelcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
