# Generated by Django 2.2.24 on 2022-03-07 06:51

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0009_auto_20210922_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('allocated_by', models.ForeignKey(on_delete=models.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان')),
            ],
            options={
                'verbose_name': 'لیست سیاه آی\u200cپی',
                'verbose_name_plural': 'لیست سیاه آی\u200cپی',
            },
        ),
    ]
