# Generated by Django 2.2.24 on 2022-03-12 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20220307_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipblacklist',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان'),
        ),
    ]
