# Generated by Django 2.2.26 on 2022-03-12 15:24
from django.conf import settings
from django.db import migrations
from exchange.accounts.models import User


BLACKLISTED_IPS = {'85.97.3.179', '85.97.65.164', '188.121.122.27'}


def create_ip_blacklist(apps, schema_editor):
    IPBlackList = apps.get_model('security', 'IPBlackList')
    system_user = User.objects.filter(pk=1000, username='system-1000').first()

    if not system_user:
        return

    system_user = User.get_generic_system_user()
    for ip in BLACKLISTED_IPS:
        IPBlackList.objects.get_or_create(ip=ip, is_active=True, allocated_by_id=system_user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_auto_20220312_1314'),
    ]

    operations = [
        migrations.RunPython(create_ip_blacklist),
    ]
