# Generated by Django 2.2.28 on 2022-08-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_blacklist_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='ip_country',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
