# Generated by Django 2.2.28 on 2022-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('security', '0013_auto_20220822_2109'), ('security', '0014_auto_20220823_1147')]

    dependencies = [
        ('security', '0012_blacklist_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='ip_country',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
