# Generated by Django 2.2.28 on 2022-08-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_auto_20220822_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(blank=True, db_column='email', max_length=100),
        ),
    ]
