# Generated by Django 2.2.28 on 2023-03-07 10:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0013_add_ip_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('agent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('address_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='security.AddressBook')),
                ('last_login_attempt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='security.LoginAttempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='addressbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(is_removed=False), fields=('address', 'address_book'), name='unique_if_not_deleted'),
        ),
    ]
