# Generated by Django 2.2.28 on 2023-05-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_auto_20230307_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='whitelist_mode',
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addressbookitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='WhiteListModeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('address_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_mode_logs', to='security.AddressBook')),
                ('last_login_attempt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='security.LoginAttempt')),
            ],
        ),
    ]
