# Generated by Django 2.2.28 on 2023-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_auto_20230522_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookitem',
            name='network',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
