# Generated by Django 2.2.28 on 2023-06-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_auto_20230531_2157'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addressbookitem',
            name='unique_if_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='addressbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(is_removed=False), fields=('address', 'address_book', 'network'), name='unique_if_not_deleted'),
        ),
    ]
