# Generated by Django 2.2.28 on 2023-07-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_auto_20230606_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbookitem',
            name='last_login_attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='security.LoginAttempt'),
        ),
        migrations.AlterField(
            model_name='whitelistmodelog',
            name='last_login_attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='security.LoginAttempt'),
        ),
    ]
