# Generated by Django 2.2.28 on 2023-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_auto_20230709_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookitem',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
