# Generated by Django 2.2.28 on 2023-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_auto_20230713_1254'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addressbookitem',
            name='unique_if_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='addressbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('tag', None)), fields=('address', 'address_book', 'network'), name='addrssbk_unique_if_not_deleted_no_tag'),
        ),
        migrations.AddConstraint(
            model_name='addressbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('tag__isnull', False)), fields=('address', 'address_book', 'network', 'tag'), name='addrssbk_unique_if_not_deleted_tag'),
        ),
    ]
