# Generated by Django 2.2.28 on 2023-10-16 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('xchange', '0001_initial'),
        ('xchange', '0002_auto_20211229_1503'),
        ('xchange', '0003_auto_20211229_2000'),
        ('xchange', '0004_auto_20221101_1544'),
        ('xchange', '0005_auto_20230704_1255'),
        ('xchange', '0006_auto_20230715_1153'),
        ('xchange', '0007_remove_exchangetrade_dst_currency_price_in_usdt'),
    ]

    dependencies = [
        ('wallet', '0066_merge_20210529_0345'),
        ('market', '0024_auto_20210103_0222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_sell', models.BooleanField()),
                (
                    'src_currency',
                    models.IntegerField(
                        choices=[
                            (0, 'unknown'),
                            (1, 'USD'),
                            (2, '﷼'),
                            (10, 'Bitcoin'),
                            (11, 'Ethereum'),
                            (12, 'Litecoin'),
                            (13, 'Tether'),
                            (14, 'Ripple'),
                            (15, 'BitcoinCash'),
                            (16, 'BinanceCoin'),
                            (17, 'EOS'),
                            (18, 'Dogecoin'),
                            (19, 'Stellar'),
                            (20, 'TRON'),
                            (21, 'Cardano'),
                            (22, 'Monero'),
                            (23, 'NEM'),
                            (24, 'IOTA'),
                            (25, 'EthereumClassic'),
                            (26, 'Dash'),
                            (27, 'Zcash'),
                            (28, 'Neo'),
                            (29, 'Qtum'),
                            (30, 'Tezos'),
                            (31, 'Paymon'),
                            (32, 'Chainlink'),
                            (33, 'Dai'),
                            (34, 'Polkadot'),
                            (35, 'Uniswap'),
                            (36, 'Aave'),
                            (37, 'Solana'),
                            (38, 'Polygon'),
                            (39, 'Filecoin'),
                            (40, 'Graph'),
                            (41, 'Theta'),
                            (42, '1000SHIB'),
                        ],
                        verbose_name='ارز مبدا',
                    ),
                ),
                (
                    'dst_currency',
                    models.IntegerField(
                        choices=[
                            (0, 'unknown'),
                            (1, 'USD'),
                            (2, '﷼'),
                            (10, 'Bitcoin'),
                            (11, 'Ethereum'),
                            (12, 'Litecoin'),
                            (13, 'Tether'),
                            (14, 'Ripple'),
                            (15, 'BitcoinCash'),
                            (16, 'BinanceCoin'),
                            (17, 'EOS'),
                            (18, 'Dogecoin'),
                            (19, 'Stellar'),
                            (20, 'TRON'),
                            (21, 'Cardano'),
                            (22, 'Monero'),
                            (23, 'NEM'),
                            (24, 'IOTA'),
                            (25, 'EthereumClassic'),
                            (26, 'Dash'),
                            (27, 'Zcash'),
                            (28, 'Neo'),
                            (29, 'Qtum'),
                            (30, 'Tezos'),
                            (31, 'Paymon'),
                            (32, 'Chainlink'),
                            (33, 'Dai'),
                            (34, 'Polkadot'),
                            (35, 'Uniswap'),
                            (36, 'Aave'),
                            (37, 'Solana'),
                            (38, 'Polygon'),
                            (39, 'Filecoin'),
                            (40, 'Graph'),
                            (41, 'Theta'),
                            (42, '1000SHIB'),
                        ],
                        verbose_name='ارز مقصد',
                    ),
                ),
                ('price', models.DecimalField(decimal_places=10, max_digits=25)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    'dst_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wallet.Transaction',
                    ),
                ),
                (
                    'src_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wallet.Transaction',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'
                    ),
                ),
                ('settlement_reference', models.CharField(default='', max_length=64)),
                (
                    'system_dst_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wallet.Transaction',
                    ),
                ),
                (
                    'system_src_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wallet.Transaction',
                    ),
                ),
            ],
            options={
                'verbose_name': 'معامله صرافی',
                'verbose_name_plural': 'معامله صرافی',
            },
        ),
    ]
