# Generated by Django 2.2.19 on 2021-06-02 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0066_merge_20210529_0345'),
        ('market', '0024_auto_20210103_0222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Done'), (2, 'Canceled')], db_index=True, default=0, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_sell', models.BooleanField()),
                ('src_currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مبدا')),
                ('dst_currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مقصد')),
                ('price', models.DecimalField(decimal_places=10, max_digits=25)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('dst_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
            ],
            options={
                'verbose_name': 'معامله صرافی',
                'verbose_name_plural': 'معامله صرافی',
            },
        ),
        migrations.CreateModel(
            name='ExchangeTradeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Failed'), (2, 'Done'), (3, 'Canceled'), (4, 'Check'), (5, 'Merged'), (10, 'waiting')], db_index=True, default=0)),
                ('execution_result', models.TextField(blank=True, null=True)),
                ('fills', models.TextField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.ExchangeConnectionConfig')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xchange.ExchangeTrade')),
            ],
            options={
                'verbose_name': 'تسویه معامله صرافی',
                'verbose_name_plural': 'تسویه معامله صرافی',
            },
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xchange.ExchangeTradeSettlement', verbose_name='تسویه بایننس'),
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='src_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction'),
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
