# Generated by Django 2.2 on 2024-01-20 08:10

from django.db import migrations, models
import exchange.base.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0001_initial_squashed_0007_remove_exchangetrade_dst_currency_price_in_usdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketMakerTrade',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xchange.exchangetrade',),
        ),
        migrations.RenameField(
            model_name='exchangetrade',
            old_name='amount',
            new_name='dst_amount',
        ),
        migrations.RemoveField(
            model_name='exchangetrade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exchangetrade',
            name='settlement_reference',
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='client_order_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='quote_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='src_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangetrade',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=exchange.base.calendar.ir_now),
        ),
    ]
