# Generated by Django 2.2.24 on 2021-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0002_auto_20211229_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradesettlement',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Failed'), (2, 'Done'), (3, 'Canceled'), (5, 'Merged')], db_index=True, default=0),
        ),
    ]
