# Generated by Django 2.2 on 2024-01-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0003_add_market_status_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetrade',
            name='quote_id',
            field=models.CharField(max_length=64),
        ),
    ]
