# Generated by Django 2.2.28 on 2022-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0003_auto_20211229_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangetrade',
            name='status',
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='dst_currency_price_in_usdt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
