# Generated by Django 2.2.28 on 2023-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0004_auto_20221101_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeTradeSettlement',
        ),
    ]
