# Generated by Django 2.2 on 2024-01-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0004_auto_20240129_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'نامعلوم'), (10, 'موفق'), (20, 'ناموفق')], default=0),
        ),
    ]
