# Generated by Django 2.2.28 on 2023-07-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0005_auto_20230704_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='settlement_reference',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='system_dst_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction'),
        ),
        migrations.AddField(
            model_name='exchangetrade',
            name='system_src_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction'),
        ),
    ]
