# Generated by Django 3.2.23 on 2024-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0005_auto_20240131_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetrade',
            name='client_order_id',
            field=models.CharField(max_length=64),
        ),
    ]
