# Generated by Django 2.2.28 on 2023-07-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0006_auto_20230715_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangetrade',
            name='dst_currency_price_in_usdt',
        ),
    ]
