# Generated by Django 3.2.25 on 2024-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0006_increase_client_order_id_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketstatus',
            name='base_precision',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketstatus',
            name='quote_precision',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
