# Generated by Django 4.2.16 on 2024-10-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xchange', '0007_increase-precision-fields-max-digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstatus',
            name='exchange_side',
            field=models.SmallIntegerField(
                choices=[(1, 'both_side'), (2, 'buy_only'), (3, 'sell_only'), (4, 'closed')],
                default=1,
            ),
        ),
    ]
