# Generated by Django 4.2.13 on 2024-11-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0008_marketstatus_exchange_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(help_text='Interval in hours')),
                ('max_amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sell', models.BooleanField()),
                ('limit_type', models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'Entire Market')])),
            ],
        ),
        migrations.AddIndex(
            model_name='exchangetrade',
            index=models.Index(
                fields=['src_currency', 'dst_currency', 'created_at', 'status', 'is_sell', 'user_id'],
                name='xchange_exc_src_cur_4e5a95_idx',
            ),
        ),
        migrations.AddField(
            model_name='marketlimitation',
            name='market',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='xchange.marketstatus'
            ),
        ),
    ]
