# Generated by Django 4.2.13 on 2024-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0009_marketlimitation_alter_exchangetrade_dst_currency_and_more'),
    ]
    operations = [
        migrations.AddConstraint(
            model_name='marketlimitation',
            constraint=models.UniqueConstraint(
                fields=('market', 'is_sell', 'limit_type'), name='market_is_sell_limit_type_unique_together'
            ),
        ),
    ]
