# Generated by Django 4.2.13 on 2024-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0010_add_constraint_to_marketlimitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketMakerTrade',
        ),
    ]
