# Generated by Django 4.2.16 on 2024-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0011_delete_marketmakertrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='convert_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
