# Generated by Django 4.2.13 on 2025-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0012_exchangetrade_convert_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangetrade',
            index=models.Index(fields=['created_at'], name='xchange_exc_created_80d854_idx'),
        ),
    ]
