# Generated by Django 4.2.13 on 2024-12-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0013_alter_exchangetrade_dst_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'discrepancy_type',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'مغایرت در نوع کوین مبدا'),
                            (2, 'مغایرت در نوع کوین مقصد'),
                            (3, 'مغایرت در مقدار کوین مبدا'),
                            (4, 'مغایرت در مقدار کوین مقصد'),
                            (5, 'مغایرت در نوع معامله'),
                            (6, 'مغایرت در وضعیت انجام معامله'),
                            (7, 'معامله ناموجود سمت بازارگردان'),
                            (8, 'معامله ناموجود سمت نوبیتکس'),
                        ],
                        null=True,
                    ),
                ),
                ('status', models.SmallIntegerField(choices=[(1, 'Solved'), (2, 'Unsolved')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='MarketMakerTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_id', models.CharField(max_length=255)),
                ('quote_id', models.CharField(max_length=255, null=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_sell', models.BooleanField()),
                (
                    'base_currency',
                    models.IntegerField(choices=[]),
                ),
                (
                    'quote_currency',
                    models.IntegerField(choices=[]),
                ),
                (
                    'reference_currency',
                    models.IntegerField(choices=[]),
                ),
                ('reference_currency_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('destination_currency_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at_market_maker', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tradediff',
            name='exchange_trade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exchange_trades',
                to='xchange.exchangetrade',
            ),
        ),
        migrations.AddField(
            model_name='tradediff',
            name='market_maker_trade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='market_maker_trades',
                to='xchange.marketmakertrade',
            ),
        ),
    ]
