# Generated by Django 4.2.19 on 2025-04-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0014_add_tradediff_and_marketmakertrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketmakertrade',
            name='created_at_market_maker',
        ),
        migrations.AddField(
            model_name='marketmakertrade',
            name='market_maker_created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='marketmakertrade',
            name='market_maker_response',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='base_currency',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='client_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='convert_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='destination_currency_amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='is_sell',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='quote_currency',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='reference_currency',
            field=models.IntegerField(choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='reference_currency_amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='marketmakertrade',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradediff',
            name='exchange_trade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trade_diffs',
                to='xchange.exchangetrade',
            ),
        ),
        migrations.AlterField(
            model_name='tradediff',
            name='market_maker_trade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='trade_diffs',
                to='xchange.marketmakertrade',
            ),
        ),
    ]
