# Generated by Django 4.2.19 on 2025-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchange', '0015_remove_marketmakertrade_created_at_market_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetrade',
            name='user_agent',
            field=models.IntegerField(
                blank=True,
                choices=[],
                null=True,
            ),
        ),
    ]
