# Generated by Django 4.2.16 on 2025-04-14 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.base.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0140_alter_userprofitdaily_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xchange', '0016_exchangetrade_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallAssetConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=exchange.base.calendar.ir_now)),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[(0, 'ثبت شده'), (10, 'در حال پردازش'), (20, 'موفق'), (30, 'ناموفق')],
                        default=0,
                    ),
                ),
                (
                    'src_currency',
                    models.IntegerField(
                        choices=[],
                        verbose_name='ارز مبدا',
                    ),
                ),
                (
                    'dst_currency',
                    models.IntegerField(
                        choices=[],
                        verbose_name='ارز مقصد',
                    ),
                ),
                ('src_amount', models.DecimalField(decimal_places=10, max_digits=22)),
                ('dst_amount', models.DecimalField(decimal_places=10, max_digits=22)),
                (
                    'dst_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wallet.transaction',
                    ),
                ),
                (
                    'related_batch_trade',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='xchange.exchangetrade',
                    ),
                ),
                (
                    'src_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wallet.transaction',
                    ),
                ),
                (
                    'system_dst_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wallet.transaction',
                    ),
                ),
                (
                    'system_src_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wallet.transaction',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='کاربر',
                    ),
                ),
            ],
            options={
                'verbose_name': 'تبدیل دارایی اندک صرافی',
                'verbose_name_plural': 'تبدیل دارایی اندک صرافی',
                'indexes': [
                    models.Index(
                        fields=['src_currency', 'dst_currency', 'status'],
                        name='xchange_sma_src_cur_ec2231_idx',
                    ),
                    models.Index(fields=['related_batch_trade', 'status'], name='xchange_sma_exchang_2ea47d_idx'),
                ],
            },
        ),
    ]
