# Generated by Django 4.2.3 on 2024-02-04 18:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('max_block_per_req', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('support_batch', models.BooleanField(default=False)),
                ('max_batch_block', models.SmallIntegerField(default=1)),
                ('supported_operations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('balance', 'Balance'), ('tx_details', 'Tx Details'), ('address_txs', 'Address Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=15), size=None)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkproviders.network')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDefaultProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('balance', 'Balance'), ('tx_details', 'Tx Details'), ('address_txs', 'Address Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=15)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkproviders.network')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkproviders.provider')),
            ],
            options={
                'unique_together': {('operation', 'network')},
            },
        ),
    ]
