# Generated by Django 4.2.3 on 2024-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='max_block_per_req',
            new_name='block_limit_per_req',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='max_batch_block',
        ),
        migrations.AddField(
            model_name='provider',
            name='batch_block_limit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
