# Generated by Django 4.2.3 on 2024-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='use_db',
            field=models.BooleanField(default=False),
        ),
    ]
