# Generated by Django 4.2.3 on 2024-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0002_network_use_db'),
        ('networkproviders', '0002_rename_max_block_per_req_network_block_limit_per_req_and_more'),
    ]

    operations = [
    ]
