# Generated by Django 3.2 on 2024-03-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0003_merge_20240213_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('use_proxy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='default_url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='networkproviders.url'),
        ),
        migrations.AddField(
            model_name='provider',
            name='urls',
            field=models.ManyToManyField(related_name='providers', to='networkproviders.URL'),
        ),
    ]
