# Generated by Django 4.2.3 on 2024-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0004_auto_20240305_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
