# Generated by Django 4.2.3 on 2024-04-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0005_alter_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='default_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networkproviders.url'),
        ),
    ]
