# Generated by Django 4.2.3 on 2024-05-29 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0007_alter_provider_default_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='explorer_interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdefaultprovider',
            name='operation',
            field=models.CharField(choices=[('balance', 'Balance'), ('token_balance', 'Token Balance'), ('tx_details', 'Tx Details'), ('address_txs', 'Address Txs'), ('token_txs', 'Token Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=15),
        ),
        migrations.AlterField(
            model_name='provider',
            name='supported_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('balance', 'Balance'), ('token_balance', 'Token Balance'), ('tx_details', 'Tx Details'), ('address_txs', 'Address Txs'), ('token_txs', 'Token Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=15), size=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
