# Generated by Django 4.2.13 on 2024-07-21 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0008_provider_explorer_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdefaultprovider',
            name='operation',
            field=models.CharField(choices=[('balance', 'Balance'), ('token_balance', 'Token Balance'), ('tx_details', 'Tx Details'), ('token_tx_details', 'Token Tx Details'), ('address_txs', 'Address Txs'), ('token_txs', 'Token Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=32),
        ),
        migrations.AlterField(
            model_name='provider',
            name='supported_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('balance', 'Balance'), ('token_balance', 'Token Balance'), ('tx_details', 'Tx Details'), ('token_tx_details', 'Token Tx Details'), ('address_txs', 'Address Txs'), ('token_txs', 'Token Txs'), ('block_txs', 'Block Txs'), ('block_head', 'Block Head')], max_length=32), size=None),
        ),
    ]
