# Generated by Django 4.2.3 on 2024-12-15 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0009_alter_networkdefaultprovider_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkdefaultprovider",
            name="set_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
