# Generated by Django 4.2.3 on 2025-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0009_alter_networkdefaultprovider_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="save_address_txs",
            field=models.BooleanField(default=False),
        ),
    ]
