# Generated by Django 4.2.3 on 2024-12-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0010_networkdefaultprovider_set_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("balance", "Balance"),
                            ("token_balance", "Token Balance"),
                            ("tx_details", "Tx Details"),
                            ("token_tx_details", "Token Tx Details"),
                            ("address_txs", "Address Txs"),
                            ("token_txs", "Token Txs"),
                            ("block_txs", "Block Txs"),
                            ("block_head", "Block Head"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networkproviders.network",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networkproviders.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "network", "operation")},
            },
        ),
    ]
