# Generated by Django 4.2.3 on 2025-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0010_network_save_address_txs'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.CharField(blank=True, choices=[('memo_based', 'Memo Based'), ('account_based', 'Account Based'), ('utxo_based', 'UTXO Based')], max_length=20, null=True),
        ),
    ]
