# Generated by Django 4.2.3 on 2024-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0011_providerservicestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="block_time",
            field=models.PositiveIntegerField(default=1.0),
        ),
    ]
