# Generated by Django 4.2.3 on 2025-02-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0010_network_save_address_txs'),
        ('networkproviders', '0012_network_block_time'),
    ]

    operations = [
    ]
