# Generated by Django 4.2.3 on 2025-03-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0013_merge_20250225_2130"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerservicestatus",
            name="last_status",
            field=models.CharField(
                blank=True,
                choices=[("healthy", "Healthy"), ("unhealthy", "Unhealthy")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerservicestatus",
            name="last_status_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
