# Generated by Django 4.2.20 on 2025-04-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0014_providerservicestatus_last_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerservicestatus",
            name="last_status_details",
        ),
    ]
