# Generated by Django 4.2.20 on 2025-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0011_network_type'),
        ('networkproviders', '0015_remove_providerservicestatus_last_status_details'),
    ]

    operations = [
    ]
