# Generated by Django 2.2.24 on 2021-09-05 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queueitem',
            unique_together={('user', 'feature')},
        ),
    ]
