# Generated by Django 2.2.28 on 2022-07-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebEngageSMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('text', models.TextField(verbose_name='متن پیامک')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'sent to ssp'), (3, 'succeeded'), (4, 'failed')], default=1)),
                ('message_id', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
