# Generated by Django 2.2.28 on 2022-07-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0001_initial'),
    ]

    operations = []
