# Generated by Django 2.2.26 on 2022-08-13 06:13

import uuid

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0002_webengageauthtoken_token_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebEngageEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('subject', models.CharField(max_length=1000, null=True)),
                ('message', models.TextField()),
                ('html_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(max_length=40)),
                ('request_content', JSONField()),
            ],
        ),
    ]
