# Generated by Django 2.2.28 on 2022-09-14 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0003_webengageemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebEngageSMSBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'sent to ssp'), (3, 'failed to send to ssp'), (4, 'inquired')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='webengagesmslog',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'sent to ssp'), (3, 'succeeded'), (4, 'failed'), (5, 'failed to send to ssp')], default=1),
        ),
        migrations.AddField(
            model_name='webengagesmslog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='web_engage.WebEngageSMSBatch'),
        ),
    ]
