# Generated by Django 2.2.28 on 2022-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0004_auto_20220914_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='webengagesmsbatch',
            name='call_logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webengagesmsbatch',
            name='inquiry_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
