# Generated by Django 2.2.28 on 2022-11-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0005_auto_20221101_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webengageemaillog',
            old_name='request_content',
            new_name='custom_data',
        ),
        migrations.RemoveField(
            model_name='webengageemaillog',
            name='message_id',
        ),
        migrations.AddField(
            model_name='webengageemaillog',
            name='from_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='webengageemaillog',
            name='from_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webengageemaillog',
            name='reply_to',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webengageemaillog',
            name='track_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='WebEngageEmailRecipientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(db_index=True, max_length=200)),
                ('subject_type', models.IntegerField(choices=[(1, 'Normal'), (2, 'CC'), (3, 'BCC')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=200, null=True)),
                ('message_id', models.CharField(max_length=200, null=True)),
                ('email_body', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipients', to='web_engage.WebEngageEmailLog')),
            ],
        ),
    ]
