# Generated by Django 3.2.23 on 2024-01-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_engage', '0006_auto_20221114_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webengageemailrecipientlog',
            name='email_body',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipients',
                to='web_engage.webengageemaillog',
            ),
        ),
    ]
