from decimal import Decimal
from enum import Enum

PAGE_SIZE_IN_FETCH_DEPOSITS = 100
DEFAULT_MIN_DEPOSIT_AMOUNT = Decimal('2_000_0')

RETRY_ACTIVATION_CONTRACTS_COUNT_DOWN = 60
RETRY_ACTIVATION_CONTRACTS_COUNT = 3

CONTRACT_EXPIRES_AT_OFFSET_MINUTES = 2


class FaraboomContractStatus(Enum):
    INITIALIZING = 'INITIALIZING'
    ACTIVE = 'ACTIVE'
    DEACTIVE = 'DEACTIVE'
    WAITING_FOR_CONFIRM = 'WAITING_FOR_CONFIRM'
    CANCELLED = 'CANCELLED'
    EXPIRED = 'EXPIRED'
