# Generated by Django 2.1.10 on 2019-08-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_fee', models.DecimalField(decimal_places=2, help_text='درصد', max_digits=5)),
                ('total_discount', models.IntegerField(blank=True, help_text='﷼', null=True)),
                ('used_discount', models.IntegerField(default=0, help_text='﷼')),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, help_text='علت اعمال تخفیف', max_length=500, null=True, verbose_name='توضیحات')),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feediscounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخفیف کارمزد',
                'verbose_name_plural': 'تخفیف کارمزد',
            },
        ),
    ]
