# Generated by Django 2.2.28 on 2022-12-05 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0002_auto_20201125_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام تخفیف')),
                ('description', models.TextField(blank=True, help_text='توضیحات', null=True, verbose_name='توضیحات')),
                ('webengage_campid', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Finished')], default=0, verbose_name='وضعیت')),
                ('currency', models.IntegerField(blank=True, choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis')], null=True, verbose_name='ارز هدف')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('percent', models.IntegerField(blank=True, default=100, null=True, verbose_name='درصد تخفیف')),
                ('amount_rls', models.IntegerField(blank=True, default=0, null=True, verbose_name='مقدار ریالی تخفیف')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان')),
                ('budget', models.IntegerField(default=0, verbose_name='بودجه\u200cی کمپین تخفیفی')),
                ('budget_remain', models.IntegerField(default=0, verbose_name='بودجه\u200cی باقی\u200cمانده\u200cی کمپین تخفیفی')),
            ],
        ),
        migrations.AlterField(
            model_name='feediscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feediscounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rls', models.IntegerField(blank=True, null=True, verbose_name='مقدار ریالی تخفیف')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ فعال شدن تخفیف')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Discount', verbose_name='تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ تراکنش')),
                ('user_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.UserDiscount', verbose_name='تخفیفات کاربر')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('budget_remain__gte', 0), ('budget_remain__lte', django.db.models.expressions.F('budget'))), name='check_budget_remain'),
        ),
    ]
