# Generated by Django 2.2.28 on 2022-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20221205_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='discounttransactionlog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userdiscount',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='webengage_campid',
        ),
        migrations.AddField(
            model_name='discount',
            name='webengage_campaign_id',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='شناسه\u200cی کمپین در webengage'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount_rls',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=25, null=True, verbose_name='مقدار ریالی تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='budget',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='بودجه\u200cی کمپین تخفیفی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='budget_remain',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='بودجه\u200cی باقی\u200cمانده\u200cی کمپین تخفیفی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.IntegerField(blank=True, choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis'), (122, 'Aptos')], null=True, verbose_name='ارز هدف'),
        ),
        migrations.AlterField(
            model_name='discounttransactionlog',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='مبلغ تراکنش'),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='amount_rls',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='مقدار ریالی تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount_rls',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='مقدار ریالی تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بودجه\u200cی کمپین تخفیفی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='budget_remain',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='بودجه\u200cی باقی\u200cمانده\u200cی کمپین تخفیفی'),
        ),
        migrations.AlterField(
            model_name='discounttransactionlog',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ تراکنش'),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='amount_rls',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='مقدار ریالی تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='discounttransactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
