# Generated by Django 2.2.28 on 2023-02-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_discount_1401q4'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttransactionlog',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='discounttransactionlog',
            name='user_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_transaction_log', to='promotions.UserDiscount', verbose_name='تخفیفات کاربر'),
        ),
    ]
