# Generated by Django 3.2.23 on 2024-01-17 12:00

import django.contrib.postgres.fields
from django.db import migrations, models

import exchange.promotions.models


class Migration(migrations.Migration):
    dependencies = [
        ('promotions', '0004_auto_20230220_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='trade_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[(1, 'Spot'), (2, 'Margin'), (3, 'Credit')], default=1
                ),
                default=exchange.promotions.models.default_trade_types,
                size=None,
            ),
        ),
    ]
