# Generated by Django 2.2.28 on 2022-12-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20221218_1030_squashed_0006_auto_20221218_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ توقف فعالیت'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Finished'), (3, 'Disabled')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount', to='promotions.Discount', verbose_name='تخفیف'),
        ),
        migrations.CreateModel(
            name='UserDiscountBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', JSONField(blank=True, null=True, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Discount', verbose_name='تخفیف')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UploadedFile', verbose_name='فایل')),
            ],
        ),
        migrations.AddField(
            model_name='userdiscount',
            name='discount_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_discounts', to='promotions.UserDiscountBatch'),
        ),
    ]
