# Generated by Django 2.2.28 on 2022-12-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_auto_20221224_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscountbatch',
            name='admin',
        ),
    ]
