# Generated by Django 2.2.17 on 2020-12-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('fcm', '0001_fcm_initial'), ('fcm', '0002_auto_20201205_1544'), ('fcm', '0003_auto_20201208_2136'), ('fcm', '0004_auto_20201209_2340')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='FCM registration token')),
                ('device_type', models.IntegerField(choices=[(0, 'None'), (1, 'Web'), (2, 'Android'), (3, 'iOS')], default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'دستگاه FCM',
                'verbose_name_plural': 'دستگاه FCM',
            },
        ),
    ]
