# Generated by Django 2.2.17 on 2020-12-08 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0002_auto_20201205_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmdevice',
            options={'verbose_name': 'دستگاه FCM', 'verbose_name_plural': 'دستگاه FCM'},
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Web'), (2, 'Android'), (3, 'iOS')], default=0),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='token',
            field=models.CharField(max_length=255, verbose_name='FCM registration token'),
        ),
    ]
