# Generated by Django 2.2.17 on 2020-12-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0003_auto_20201208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='FCM registration token'),
        ),
    ]
