# Generated by Django 4.2.16 on 2025-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20230608_2009'),
        ('corporate_banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdpartyLog',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('integrations.apicalllog',),
        ),
        migrations.AddField(
            model_name='cobankstatement',
            name='provider_statement_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cobankstatement',
            name='source_account',
            field=models.CharField(
                blank=True, help_text='The account from which the transaction was initiated.', max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name='cobankstatement',
            name='transaction_datetime',
            field=models.DateTimeField(
                blank=True, help_text='Date and time when the bank recorded this transaction.', null=True
            ),
        ),
        migrations.AddConstraint(
            model_name='cobankstatement',
            constraint=models.UniqueConstraint(
                fields=('provider_statement_id', 'destination_account'), name='cobank_statement_uniqueness'
            ),
        ),
    ]
