# Generated by Django 4.2.16 on 2025-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0002_thirdpartylog_cobankstatement_provider_statement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobankstatement',
            name='api_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='cobankstatement',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
    ]
