# Generated by Django 4.2.16 on 2025-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0003_cobankstatement_api_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobankstatement',
            name='tracing_number',
            field=models.CharField(blank=True, help_text='Bank-assigned tracing number.', max_length=100, null=True, db_index=True),
        ),
    ]
