# Generated by Django 4.2.13 on 2025-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0004_alter_cobankstatement_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobankstatement',
            name='source_iban',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddIndex(
            model_name='cobankstatement',
            index=models.Index(
                models.F('tp'),
                models.F('source_iban'),
                models.F('transaction_datetime'),
                name='cobankstatement_iban_index',
            ),
        ),
    ]
