# Generated by Django 4.2.19 on 2025-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0005_cobankstatement_source_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobankaccount',
            name='provider_bank_id',
            field=models.CharField(help_text='Our bank account database ID belonging to provider', max_length=64),
        ),
    ]
