# Generated by Django 4.2.17 on 2025-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0006_alter_cobankaccount_provider_bank_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobankstatement',
            name='source_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cobankstatement',
            name='provider_statement_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
