# Generated by Django 4.2.17 on 2025-04-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0007_cobankstatement_source_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoBankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('provider_is_active', models.BooleanField(default=True)),
                ('provider_card_id', models.CharField(help_text='Our bank card database ID belonging to provider', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_banking.cobankaccount')),
            ],
            options={
                'verbose_name': 'کارت\u200cهای بانکی کوبنک',
                'verbose_name_plural': 'کارت\u200cهای بانکی کوبنک',
            },
        ),
    ]
