# Generated by Django 4.2.18 on 2025-04-22 10:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import exchange.base.calendar


class Migration(migrations.Migration):
    dependencies = [
        ('corporate_banking', '0008_alter_cobankstatement_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoBankRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'New'),
                            (2, 'Invalid'),
                            (3, 'Request sent to provider'),
                            (4, 'Pending on provider side'),
                            (5, 'Executed by provider'),
                            (6, 'Cancel requested'),
                            (7, 'Canceled by us'),
                            (8, 'Unknown'),
                        ],
                        default=1,
                    ),
                ),
                ('retry', models.SmallIntegerField(default=0)),
                (
                    'provider_response',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(default=dict), blank=True, default=list, null=True, size=None
                    ),
                ),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                (
                    'statement',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, to='corporate_banking.cobankstatement'
                    ),
                ),
            ],
            options={
                'verbose_name': 'درخواست\u200cهای بازپرداخت',
                'verbose_name_plural': 'درخواست\u200cهای بازپرداخت',
                'indexes': [models.Index(fields=['status', 'created_at'], name='refund_status_created_idx')],
            },
        ),
    ]
