# Generated by Django 4.2.17 on 2025-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0009_create_cobankrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobankcard',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
