# Generated by Django 4.2.21 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_banking', '0010_cobankcard_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cobankstatement',
            index=models.Index(models.F('tp'), models.F('status'), name='cobankstatement_status_index'),
        ),
    ]
