# Generated by Django 2.2.26 on 2022-08-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exchange.base.calendar
from exchange.base.fields import RoundedDecimalField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0034_order_trade_type'),
        ('wallet', '0101_auto_20220904_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_currency', models.PositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'ElrondEGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant')], verbose_name='ارز مبدا')),
                ('dst_currency', models.PositiveSmallIntegerField(choices=[(2, '﷼'), (13, 'Tether')], verbose_name='ارز مقصد')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Open'), (2, 'Closed'), (3, 'Liquidated'), (4, 'Canceled'), (5, 'Expired')], db_index=True, default=0, verbose_name='وضعیت')),
                ('margin_type', models.PositiveSmallIntegerField(choices=[(1, 'Isolated Margin'), (2, 'Cross Margin')], default=1, verbose_name='نوع وثیقه')),
                ('collateral', RoundedDecimalField(decimal_places=10, max_digits=30, verbose_name='وثیقه')),
                ('liability', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='تعهد')),
                (
                    'earned_amount',
                    models.DecimalField(
                        decimal_places=10, default=0, max_digits=30, verbose_name='مقدار دریافتی از معاملات'
                    ),
                ),
                (
                    'liquidation_price',
                    RoundedDecimalField(
                        blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='قیمت انحلال'
                    ),
                ),
                (
                    'pnl',
                    RoundedDecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='سود و زیان'
                    ),
                ),
            ],
            options={
                'verbose_name': 'موقعیت',
                'verbose_name_plural': 'موقعیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PositionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='market.Order', verbose_name='سفارش')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='margin.Position', verbose_name='موقعیت')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='orders',
            field=models.ManyToManyField(related_query_name='position', through='margin.PositionOrder', to='market.Order', verbose_name='سفارش\u200cها'),
        ),
        migrations.AddField(
            model_name='position',
            name='pnl_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction', verbose_name='تراکنش PNL'),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='PositionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=exchange.base.calendar.ir_today, verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='margin.Position', verbose_name='موقعیت')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Transaction', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'کارمزد موقعیت',
                'verbose_name_plural': 'کارمزدهای موقعیت',
                'unique_together': {('position', 'date')},
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(status__in=(0, 1)), fields=('user', 'src_currency', 'dst_currency'), name='unique_active_position_for_user'),
        ),
    ]
