# Generated by Django 2.2.26 on 2022-09-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0035_auto_20220904_0020'),
        ('margin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginOrderChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Order',
                                   verbose_name='سفارش')),
            ],
        ),
    ]
