# Generated by Django 2.2.26 on 2022-10-01 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('margin', '0002_auto_20220916_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('market_price', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='قیمت بازار')),
                (
                    'liquidation_price',
                    models.DecimalField(decimal_places=10, max_digits=25, verbose_name='قیمت انحلال'),
                ),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده؟')),
                ('is_solved', models.BooleanField(default=False, verbose_name='برطرف شده؟')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_calls',
                                               to='margin.Position', verbose_name='موقعیت')),
            ],
            options={
                'verbose_name': 'اعلان موقعیت',
                'verbose_name_plural': 'اعلان\u200cهای موقعیت',
            },
        ),
    ]
