# Generated by Django 2.2.26 on 2022-10-08 13:36

from django.db import migrations, models

from exchange.base.fields import RoundedDecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0003_margincall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='liability',
        ),
        migrations.AddField(
            model_name='position',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن'),
        ),
        migrations.AddField(
            model_name='position',
            name='delegated_amount',
            field=models.DecimalField(
                decimal_places=10, default=0, max_digits=30, verbose_name='مقدار وکالت\u200cگرفته'
            ),
        ),
        migrations.AddField(
            model_name='position',
            name='entry_price',
            field=RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='میانگین قیمت باز شدن'
            ),
        ),
        migrations.AddField(
            model_name='position',
            name='exit_price',
            field=RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='میانگین قیمت بسته شدن'
            ),
        ),
        migrations.AddField(
            model_name='position',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ باز شدن'),
        ),
    ]
