# Generated by Django 2.2.26 on 2022-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0004_auto_20221008_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='blocked_collateral',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True, verbose_name='وثیقه سفارش'),
        ),
    ]
