# Generated by Django 2.2.26 on 2022-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0005_positionorder_blocked_collateral'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_active_position_for_user',
        ),
        migrations.AlterIndexTogether(
            name='position',
            index_together={('src_currency', 'dst_currency')},
        ),
    ]
