# Generated by Django 2.2.26 on 2022-11-06 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0007_auto_20221106_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionCollateralChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('old_value', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='مقدار قبلی')),
                ('new_value', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='مقدار جدید')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_changes', to='margin.Position', verbose_name='موقعیت')),
            ],
            options={
                'verbose_name': 'تغییر وثیقه موقعیت',
                'verbose_name_plural': 'تغییرات وثیقه موقعیت',
            },
        ),
    ]
