# Generated by Django 2.2.26 on 2022-11-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0008_positioncollateralchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginorderchange',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='untracked_changes', to='market.Order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='margin.Position', verbose_name='موقعیت'),
        ),
    ]
