# Generated by Django 2.2.26 on 2023-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0009_auto_20221113_1507'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(check=models.Q(collateral__gte=0), name='position_positive_collateral'),
        ),
    ]
