# Generated by Django 2.2.28 on 2023-05-03 08:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0010_auto_20230111_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='leverage',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=2, verbose_name='اهرم'),
        ),
    ]
