# Generated by Django 2.2.28 on 2023-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0011_position_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='side',
            field=models.SmallIntegerField(choices=[(1, 'Sell'), (2, 'Buy')], default=1, verbose_name='جهت'),
            preserve_default=False,
        ),
    ]
