# Generated by Django 2.2.28 on 2023-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0012_position_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='freezed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ متوقف (لیکویید یا منقضی) شدن'),
        ),
    ]
