# Generated by Django 3.2.22 on 2024-01-17 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0013_position_freezed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, 'New'), (1, 'Open'), (2, 'Closed'), (3, 'Liquidated'), (4, 'Canceled'), (5, 'Expired')],
                default=0,
                verbose_name='وضعیت',
            ),
        ),
        migrations.AlterIndexTogether(
            name='position',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(
                condition=models.Q(('pnl__isnull', True)),
                fields=['user', 'side', 'src_currency', 'dst_currency'],
                name='user_active_positions',
            ),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(
                condition=models.Q(('pnl__isnull', True)),
                fields=['status', 'created_at'],
                name='system_active_positions',
            ),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(
                condition=models.Q(('pnl__isnull', False)),
                fields=['side', 'src_currency', 'dst_currency', 'closed_at'],
                name='system_past_positions',
            ),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(condition=models.Q(('status', 4)), fields=['id'], name='system_canceled_positions'),
        ),
    ]
