# Generated by Django 4.2.13 on 2024-07-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0001_initial'),
        ('margin', '0014_auto_20240117_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLiquidationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش شده؟')),
                (
                    'liquidation_request',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='liquidator.liquidationrequest',
                        verbose_name='درخواست لیکویید کردن',
                    ),
                ),
                (
                    'position',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='margin.position',
                        verbose_name='موقعیت',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='liquidation_requests',
            field=models.ManyToManyField(
                related_query_name='+',
                through='margin.PositionLiquidationRequest',
                to='liquidator.liquidationrequest',
                verbose_name='درخواست\u200cهای لیکویید کردن',
            ),
        ),
        migrations.AddConstraint(
            model_name='positionliquidationrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_processed', False)),
                fields=('position',),
                name='unique_unprocessed_liquidation_request_per_position',
            ),
        ),
    ]
