# Generated by Django 4.2.13 on 2024-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margin', '0015_positionliquidationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionfee',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار'),
        ),
    ]
