# Generated by Django 4.2.14 on 2024-09-08 13:33

from django.db import migrations, models

import exchange.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0005_liquidation_market_type_and_more'),
        ('margin', '0016_auto_20240824_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margincall',
            name='liquidation_price',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='قیمت انحلال'),
        ),
        migrations.AlterField(
            model_name='margincall',
            name='market_price',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='قیمت بازار'),
        ),
        migrations.AlterField(
            model_name='position',
            name='collateral',
            field=exchange.base.fields.RoundedDecimalField(decimal_places=10, max_digits=22, verbose_name='وثیقه'),
        ),
        migrations.AlterField(
            model_name='position',
            name='delegated_amount',
            field=models.DecimalField(
                decimal_places=10, default=0, max_digits=22, verbose_name='مقدار وکالت\u200cگرفته'
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='earned_amount',
            field=models.DecimalField(
                decimal_places=10, default=0, max_digits=22, verbose_name='مقدار دریافتی از معاملات'
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='entry_price',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='میانگین قیمت باز شدن'
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='exit_price',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='میانگین قیمت بسته شدن'
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='liquidation_price',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='قیمت انحلال'
            ),
        ),
        migrations.AlterField(
            model_name='position',
            name='pnl',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='سود و زیان'
            ),
        ),
        migrations.AlterField(
            model_name='positioncollateralchange',
            name='new_value',
            field=exchange.base.fields.RoundedDecimalField(decimal_places=10, max_digits=22, verbose_name='مقدار جدید'),
        ),
        migrations.AlterField(
            model_name='positioncollateralchange',
            name='old_value',
            field=exchange.base.fields.RoundedDecimalField(decimal_places=10, max_digits=22, verbose_name='مقدار قبلی'),
        ),
        migrations.AlterField(
            model_name='positionfee',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='blocked_collateral',
            field=models.DecimalField(decimal_places=10, max_digits=22, null=True, verbose_name='وثیقه سفارش'),
        ),
    ]
