# Generated by Django 4.2.14 on 2024-09-28 12:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0053_order__id_order__pair'),
        ('margin', '0017_alter_margincall_liquidation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionorder',
            name='_order',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
        ),
        migrations.RunSQL(
            sql='CREATE FUNCTION sync_margin_order() RETURNS TRIGGER AS '
                '$$BEGIN NEW._order_id := NEW.order_id; RETURN NEW; END$$ LANGUAGE plpgsql;',
            reverse_sql='DROP FUNCTION sync_margin_order();',
        ),
        migrations.RunSQL(
            sql='CREATE TRIGGER sync_margin_positionorder_trigger BEFORE INSERT ON margin_positionorder '
                'FOR EACH ROW EXECUTE FUNCTION sync_margin_order();',
            reverse_sql='DROP TRIGGER sync_margin_positionorder_trigger ON margin_positionorder;',
        ),
    ]
