# Generated by Django 4.2.14 on 2024-10-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_ordermatching__buy_order_ordermatching__sell_order'),
        ('margin', '0018_marginorderchange__order_positionorder__order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionorder',
            name='order',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='positionorder',
                    name='_order',
                    field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id', verbose_name='سفارش'),
                ),
            ],
        ),
        migrations.RenameField(
            model_name='positionorder',
            old_name='_order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='positionorder',
            name='order',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id', verbose_name='سفارش'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='positionorder',
                    name='order',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', verbose_name='سفارش'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='DROP TRIGGER sync_margin_positionorder_trigger ON margin_positionorder;',
        ),
        migrations.RunSQL(
            sql='DROP FUNCTION sync_margin_order();',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='marginorderchange',
                    name='order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.order', to_field='_id'),
                ),
            ],
            state_operations=[],
        ),
    ]
