# Generated by Django 4.2.14 on 2024-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0008_alter_liquidation_options_and_more'),
        ('margin', '0019_remove_positionorder__order_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='position',
            index=models.Index(
                condition=models.Q(('status', 1)),
                fields=['src_currency', 'dst_currency', 'side', 'liquidation_price'],
                name='idx_liquidate_positions',
            ),
        ),
    ]
