# Generated by Django 4.2.13 on 2025-03-05 07:52

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('margin', '0020_alter_position_liquidation_requests_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='position',
            index=models.Index(
                condition=models.Q(
                    ('side', 2),
                    models.Q(
                        ('pnl__isnull', True),
                        models.Q(('pnl__isnull', False), ('pnl__gt', 0), ('pnl_transaction__isnull', True)),
                        _connector='OR',
                    ),
                    ('earned_amount__gt', 0),
                ),
                fields=['side', 'earned_amount', 'pnl', 'pnl_transaction'],
                name='idx_pool_unsettled_positions',
            ),
        ),
    ]
