# Generated by Django 4.2.13 on 2025-05-06 12:26
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('margin', '0021_add_pool_unsettled_positions_idx'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='position',
            index=models.Index(
                condition=models.Q(
                    ('pnl__isnull', False), ('pnl_transaction__isnull', True), models.Q(('pnl', 0), _negated=True)
                ),
                fields=['id'],
                name='idx_margin_position_unsettled1',
            ),
        ),
    ]
