# Generated by Django 4.2.13 on 2024-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20240212_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedorderlog',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار ارز'),
        ),
    ]
