# Generated by Django 4.2.13 on 2024-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20240824_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedorderlog',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
