# Generated by Django 4.2.14 on 2024-07-24 11:04

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='market_order',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='market.order',
                verbose_name='سفارش داخلی',
            ),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='fee',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='filled_amount',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='مقدار پر شده'
            ),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='filled_total_price',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='ارزش نهایی'
            ),
        ),
    ]
