# Generated by Django 4.2.14 on 2024-08-04 10:49

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0002_alter_liquidation_market_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='paid_amount',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='مقدار پرداخت شده'
            ),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='paid_total_price',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='ارزش پرداخت شده'
            ),
        ),
    ]
