# Generated by Django 4.2.14 on 2024-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0003_alter_liquidation_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidation',
            name='market_order',
        ),
        migrations.AddField(
            model_name='liquidation',
            name='order_id',
            field=models.CharField(default='', max_length=32, verbose_name='شناسه سفارش لیکویید'),
        ),
    ]
