# Generated by Django 4.2.14 on 2024-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0004_remove_liquidation_market_order_liquidation_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='market_type',
            field=models.SmallIntegerField(
                choices=[(1, 'Internal'), (2, 'External')], default=1, verbose_name='بازار سفارش گذاری'
            ),
        ),
    ]
