# Generated by Django 4.2.16 on 2024-10-09 11:37

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0005_liquidation_market_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='primary_price',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=30, verbose_name='قیمت اولیه'
            ),
        ),
    ]
