# Generated by Django 4.2.16 on 2024-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0006_liquidation_primary_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
