# Generated by Django 4.2.16 on 2024-11-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0007_alter_liquidation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidation',
            options={'verbose_name': 'تسویه', 'verbose_name_plural': 'تسویه\u200cها'},
        ),
        migrations.AddIndex(
            model_name='liquidation',
            index=models.Index(fields=['status', 'created_at'], name='status_created_at_liqs'),
        ),
    ]
