# Generated by Django 4.2.17 on 2025-02-09 11:30

from django.db import migrations, models


def change_empty_strings_to_null(apps, schema_editor):
    Liquidation = apps.get_model('liquidator', 'Liquidation')
    Liquidation.objects.filter(tracking_id='').update(tracking_id=None)


def reverse_empty_strings_change(apps, schema_editor):
    Liquidation = apps.get_model('liquidator', 'Liquidation')
    Liquidation.objects.filter(tracking_id__isnull=True).update(tracking_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0008_alter_liquidation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidation',
            old_name='order_id',
            new_name='tracking_id',
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پیگیری سفارش لیکویید'),
        ),
        migrations.RunPython(change_empty_strings_to_null, reverse_code=reverse_empty_strings_change),
        migrations.AlterField(
            model_name='liquidation',
            name='tracking_id',
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name='کد پیگیری سفارش لیکویید'
            ),
        ),
    ]
