# Generated by Django 4.2.17 on 2025-02-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0009_rename_order_id_liquidation_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='order',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='market.order',
            ),
        ),
    ]
