# Generated by Django 4.2.17 on 2025-03-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('liquidator', '0010_liquidation_order'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE liquidator_liquidation_liquidation_requests RENAME COLUMN liquidationrequest_id TO liquidation_request_id",
                    reverse_sql="ALTER TABLE liquidator_liquidation_liquidation_requests RENAME COLUMN liquidation_request_id TO liquidationrequest_id",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE liquidator_liquidation_liquidation_requests RENAME TO liquidator_liquidationrequestliquidationassociation",
                    reverse_sql="ALTER TABLE liquidator_liquidationrequestliquidationassociation RENAME TO liquidator_liquidation_liquidation_requests",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LiquidationRequestLiquidationAssociation',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        (
                            'liquidation',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='liquidation_request_associations',
                                to='liquidator.liquidation',
                            ),
                        ),
                        (
                            'liquidation_request',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='liquidation_associations',
                                to='liquidator.liquidationrequest',
                            ),
                        ),
                    ],
                    options={
                        'unique_together': {('liquidation_request', 'liquidation')},
                    },
                ),
                migrations.AlterField(
                    model_name='liquidation',
                    name='liquidation_requests',
                    field=models.ManyToManyField(
                        related_name='liquidations',
                        through='liquidator.LiquidationRequestLiquidationAssociation',
                        to='liquidator.liquidationrequest',
                        verbose_name='درخواست\u200cهای لیکویید',
                    ),
                ),
            ],
        )
    ]
