# Generated by Django 4.2.17 on 2025-03-16 14:56

from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0011_add_liquidationrequest_liquidation_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationrequestliquidationassociation',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30),
        ),
        migrations.AddField(
            model_name='liquidationrequestliquidationassociation',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=30),
        ),
    ]
