# Generated by Django 4.2.17 on 2025-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0012_liquidationrequestliquidationassociation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationrequest',
            name='service',
            field=models.SmallIntegerField(choices=[(1, 'margin'), (2, 'abc')], default=1),
        ),
    ]
