# Generated by Django 4.2.17 on 2025-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidator', '0013_liquidationrequest_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'pending'),
                    (2, 'in progress'),
                    (3, 'done'),
                    (4, 'waiting for transactions'),
                    (5, 'transactions failed'),
                ],
                db_index=True,
                default=1,
                verbose_name='وضعیت',
            ),
        ),
    ]
