# Generated by Django 2.1.8 on 2019-06-17 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

from exchange.base.fields import RoundedDecimalField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('redirect', models.URLField(max_length=600)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='موبایل')),
                ('factor_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره فاکتور')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.IntegerField(default=0)),
                ('code_description', models.CharField(blank=True, default='', max_length=1000)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('method', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('domain', models.URLField(max_length=250, verbose_name='دامنه')),
                ('site_name', models.CharField(max_length=250, verbose_name='نام پذیرنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token', models.CharField(blank=True, default='', max_length=200)),
                ('refund_address', models.CharField(blank=True, default='', max_length=300)),
                ('reference_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingWalletRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=100)),
                ('uri', models.CharField(blank=True, max_length=400, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('crypto_amount', models.BigIntegerField(verbose_name='مقدار ارز دیجیتال')),
                ('expiry', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان اعتبار')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('unknown', 'unknown'), ('paid', 'paid'), ('expired', 'expired'), ('partial', 'partial'), ('unconfirmed', 'unconfirmed')], default='unknown', max_length=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(db_index=True)),
                ('tp', models.IntegerField(choices=[(10, 'Bitcoin'), (12, 'Litcoin')], default=10)),
                ('rate', RoundedDecimalField(decimal_places=10, max_digits=20, verbose_name='نرخ تبدیل')),
                ('tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('settle', models.BooleanField(default=False)),
                ('create_order', models.BooleanField(default=False)),
                ('pg_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_request', to='gateway.PaymentGatewayInvoice', verbose_name='درخواست درگاه')),
            ],
        ),
        migrations.AddField(
            model_name='paymentrequestrefund',
            name='pg_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.PendingWalletRequest'),
        ),
        migrations.AddField(
            model_name='paymentgatewaylog',
            name='pg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.PaymentGatewayUser'),
        ),
        migrations.AddField(
            model_name='paymentgatewayinvoice',
            name='pg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.PaymentGatewayUser', verbose_name='کاربر درگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='pendingwalletrequest',
            unique_together={('pg_req', 'tp'), ('req_id', 'tp')},
        ),
    ]
