# Generated by Django 2.1.8 on 2019-07-07 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayuser',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
