# Generated by Django 2.1.8 on 2019-07-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_paymentgatewayuser_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewayinvoice',
            options={'verbose_name': 'درخواست درگاه', 'verbose_name_plural': 'درخواست درگاه'},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewaylog',
            options={'verbose_name': 'لاگ سیستم', 'verbose_name_plural': 'لاگ سیستم'},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewayuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='paymentrequestrefund',
            options={'verbose_name': 'درخواست بازگشت وجه', 'verbose_name_plural': 'درخواست بازگشت وجه'},
        ),
        migrations.AlterModelOptions(
            name='pendingwalletrequest',
            options={'verbose_name': 'وضعیت پرداخت', 'verbose_name_plural': 'وضعیت پرداخت'},
        ),
        migrations.AlterField(
            model_name='pendingwalletrequest',
            name='req_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingwalletrequest',
            name='tp',
            field=models.IntegerField(choices=[(10, 'Bitcoin'), (12, 'Litcoin'), (14, 'Ripple')], default=10),
        ),
    ]
