# Generated by Django 2.1.8 on 2019-08-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20190731_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewayinvoice',
            options={'verbose_name': 'درخواست\u200cهای ثبت شده', 'verbose_name_plural': 'درخواست\u200cهای ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewaylog',
            options={'verbose_name': 'لاگ درگاه', 'verbose_name_plural': 'لاگ درگاه'},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewayuser',
            options={'verbose_name': 'درگاه', 'verbose_name_plural': 'درگاه'},
        ),
        migrations.AlterModelOptions(
            name='pendingwalletrequest',
            options={'verbose_name': 'درخواست\u200c ولت\u200cها', 'verbose_name_plural': 'درخواست\u200c ولت\u200cها'},
        ),
        migrations.AddField(
            model_name='paymentgatewayinvoice',
            name='amount_tether',
            field=models.PositiveIntegerField(null=True, verbose_name='مقدار دلاری'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayinvoice',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='مقدار ریالی'),
        ),
    ]
