# Generated by Django 2.1.8 on 2019-09-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190823_0002'),
        ('gateway', '0004_auto_20190831_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayuser',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.UploadedFile'),
        ),
    ]
