# Generated by Django 2.1.12 on 2019-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_paymentgatewayuser_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayuser',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgatewayuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده')], default=0),
        ),
    ]
