# Generated by Django 2.1.12 on 2019-09-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20190917_1717'),
        ('gateway', '0006_auto_20190912_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwalletrequest',
            name='settle_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction', verbose_name='تراکنش تسویه'),
        ),
    ]
