# Generated by Django 2.1.12 on 2019-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_pendingwalletrequest_settle_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayuser',
            name='domain',
            field=models.CharField(max_length=250, verbose_name='دامنه'),
        ),
    ]
