# Generated by Django 3.2.23 on 2023-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0047_auto_20231009_1152'),
        ('asset_backed_credit', '0001_initial_squashed_0002_auto_20231118_1717_squashed_0007_merge_20231202_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='orders',
            field=models.ManyToManyField(
                blank=True, related_name='_asset_backed_credit_assettodebtmargincall_orders_+', to='market.Order'
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='orders',
            field=models.ManyToManyField(
                blank=True, related_name='_asset_backed_credit_settlementtransaction_orders_+', to='market.Order'
            ),
        ),
        migrations.DeleteModel(
            name='LiquidationRequest',
        ),
    ]
