# Generated by Django 3.2.23 on 2023-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0002_auto_20231203_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingapicalllog',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='incomingapicalllog',
            unique_together=set(),
        ),
    ]
