# Generated by Django 3.2.22 on 2023-12-15 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_backed_credit', '0003_auto_20231210_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingapicalllog',
            name='provider',
            field=models.SmallIntegerField(choices=[(1, 'تارا')], null=True, verbose_name='ارائه دهنده'),
        ),
        migrations.AlterField(
            model_name='incomingapicalllog',
            name='service',
            field=models.SmallIntegerField(choices=[(1, 'اعتبار'), (2, 'وام'), (3, 'دبیت')], null=True, verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='incomingapicalllog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='outgoingapicalllog',
            name='provider',
            field=models.SmallIntegerField(choices=[(1, 'تارا')], null=True, verbose_name='ارائه دهنده'),
        ),
        migrations.AlterField(
            model_name='outgoingapicalllog',
            name='service',
            field=models.SmallIntegerField(choices=[(1, 'اعتبار'), (2, 'وام'), (3, 'دبیت')], null=True, verbose_name='سرویس'),
        ),
    ]
