# Generated by Django 2.2.28 on 2023-12-19 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0121_merge_20231211_1423'),
        ('asset_backed_credit', '0004_auto_20231215_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlementtransaction',
            name='provider_transaction_datetime',
        ),
        migrations.RemoveField(
            model_name='settlementtransaction',
            name='user_transaction_datetime',
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='insurance_withdraw_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='wallet.Transaction',
                verbose_name='تراکنش کسر از اکانت بیمه\u200cی نوبیتکس',
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='transaction_datetime',
            field=models.DateTimeField(null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.CreateModel(
            name='UserOperationLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_released', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قفل عملیات کاربر',
                'verbose_name_plural': 'قفل عملیات کاربران',
            },
        ),
        migrations.AddConstraint(
            model_name='useroperationlock',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_released=False), fields=('user',), name='unique_active_operation_per_user'
            ),
        ),
    ]
