# Generated by Django 2.2.28 on 2023-12-25 10:57

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0005_auto_20231219_2051'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userservice',
            constraint=models.CheckConstraint(
                check=models.Q(current_debt__gte=Decimal('0')), name='current_debt_positivity'
            ),
        ),
    ]
