# Generated by Django 2.2.28 on 2023-12-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0006_auto_20231225_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='status',
        ),
    ]
