# Generated by Django 3.2.22 on 2023-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0007_auto_20231225_1825'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userservice',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('user', 'service'), name='unique_active_user_service'),
        ),
    ]
