# Generated by Django 3.2.23 on 2023-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0008_auto_20231226_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره کاربری'),
        ),
    ]
