# Generated by Django 3.2.23 on 2023-12-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0009_auto_20231227_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    'user_service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.userservice',
                    ),
                ),
            ],
        ),
    ]
