# Generated by Django 3.2.23 on 2024-01-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0010_auto_20231226_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementtransaction',
            name='insurance_withdraw_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش کسر از اکانت بیمه\u200cی نوبیتکس',
            ),
        ),
        migrations.AlterField(
            model_name='settlementtransaction',
            name='provider_deposit_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش تسویه با سرویس\u200cدهنده',
            ),
        ),
        migrations.AlterField(
            model_name='settlementtransaction',
            name='user_service',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='settlement_transactions',
                to='asset_backed_credit.userservice',
                verbose_name='سرویس اعتباری',
            ),
        ),
        migrations.AlterField(
            model_name='settlementtransaction',
            name='user_withdraw_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش تسویه با کاربر',
            ),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='user_service_permission',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='user_service',
                to='asset_backed_credit.userservicepermission',
                verbose_name='مجوز',
            ),
        ),
        migrations.AlterField(
            model_name='userservicepermission',
            name='user_otp',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='accounts.userotp',
                verbose_name='کد تایید',
            ),
        ),
    ]
