# Generated by Django 3.2.23 on 2024-01-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0011_auto_20240103_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='provider_withdraw_requests',
            field=models.ManyToManyField(related_name='_asset_backed_credit_settlementtransaction_provider_withdraw_requests_+', to='wallet.WithdrawRequest', verbose_name='درخواست\u200cهای برداشت سرویس\u200cدهنده'),
        ),
    ]
