# Generated by Django 3.2.23 on 2024-01-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0012_auto_20240119_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOperationLock',
        ),
    ]
