# Generated by Django 3.2.23 on 2024-02-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_backed_credit', '0013_delete_useroperationlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingapicalllog',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='کاربر',
            ),
        ),
        migrations.AlterField(
            model_name='debtchangelog',
            name='user_service',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='debt_change_logs',
                to='asset_backed_credit.userservice',
            ),
        ),
        migrations.AlterField(
            model_name='incomingapicalllog',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name='کاربر',
            ),
        ),
    ]
