# Generated by Django 3.2.23 on 2024-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0014_auto_20240205_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='is_liquidation_notif_sent',
            field=models.BooleanField(default=False, verbose_name='نوتیف لیکویدشن ارسال شده؟'),
        ),
        migrations.RenameField(
            model_name='assettodebtmargincall',
            old_name='is_sent',
            new_name='is_margin_call_sent',
        ),
    ]
