# Generated by Django 3.2.23 on 2024-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0015_auto_20240206_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='status',
            field=models.SmallIntegerField(
                choices=[(1, 'initiated'), (2, 'confirmed'), (3, 'rejected')], default=2, verbose_name='وضعیت تسویه'
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='settlementtransaction',
            index=models.Index(
                condition=models.Q(('trace_id__isnull', False)), fields=['trace_id'], name='trace_id_idx'
            ),
        ),
    ]
