# Generated by Django 3.2.23 on 2024-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0016_auto_20240218_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='liquidated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='کارمزد'),
        ),
        migrations.AddField(
            model_name='service',
            name='interest',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='بهره'),
        ),
        migrations.AlterField(
            model_name='assettodebtmargincall',
            name='is_margin_call_sent',
            field=models.BooleanField(default=False, verbose_name='نوتیف مارجین کال ارسال شده؟'),
        ),
    ]
