# Generated by Django 3.2.25 on 2024-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0017_auto_20240302_1851'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='settlementtransaction',
            name='trace_id_idx',
        ),
        migrations.AddConstraint(
            model_name='settlementtransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(('trace_id__isnull', False)), fields=('trace_id',), name='unique_trace_id'
            ),
        ),
    ]
