# Generated by Django 3.2.25 on 2024-03-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0018_auto_20240310_1758'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='settlementtransaction',
            name='unique_trace_id',
        ),
        migrations.RemoveField(
            model_name='settlementtransaction',
            name='trace_id',
        ),
        migrations.CreateModel(
            name='DebitSettlementTransaction',
            fields=[
                (
                    'settlementtransaction_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='asset_backed_credit.settlementtransaction',
                    ),
                ),
                ('pan', models.CharField(max_length=16)),
                ('rrn', models.CharField(max_length=32)),
                ('trace_id', models.CharField(max_length=32)),
                ('terminal_id', models.CharField(max_length=32)),
                ('rid', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'تراکنش تسویه نقدی',
                'verbose_name_plural': 'تراکنش\u200cهای تسویه نقدی',
            },
            bases=('asset_backed_credit.settlementtransaction',),
        ),
        migrations.AddConstraint(
            model_name='debitsettlementtransaction',
            constraint=models.UniqueConstraint(fields=('pan', 'trace_id', 'terminal_id'), name='unique_id'),
        ),
    ]
