# Generated by Django 3.2.25 on 2024-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0019_auto_20240324_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='status',
            field=models.SmallIntegerField(
                choices=[(10, 'initiated'), (20, 'settled'), (30, 'expired'), (40, 'closed')],
                default=10,
                verbose_name='وضعیت',
            ),
        ),
        migrations.AlterField(
            model_name='debitsettlementtransaction',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
