# Generated by Django 3.2.25 on 2024-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0020_auto_20240402_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtchangelog',
            name='type',
            field=models.SmallIntegerField(
                choices=[(1, 'current'), (2, 'initial')], default=1, verbose_name='نوع بدهی'
            ),
            preserve_default=False,
        ),
    ]
