# Generated by Django 3.2.25 on 2024-05-18 14:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0021_auto_20240413_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userservice',
            name='extra_info',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
