# Generated by Django 3.2.25 on 2024-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0022_auto_20240518_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='last_action',
            field=models.SmallIntegerField(
                choices=[(10, 'noop'), (20, 'discharged'), (30, 'liquidated')],
                default=10,
                verbose_name='آخرین اقدام سیستمی',
            ),
        ),
    ]
