# Generated by Django 3.2.25 on 2024-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0023_auto_20240519_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
