# Generated by Django 4.2.13 on 2024-07-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0024_auto_20240605_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                (
                    'uid',
                    models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='incomingapicalllog',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='outgoingapicalllog',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userfinancialservicelimit',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userservice',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
    ]
