# Generated by Django 4.2.14 on 2024-07-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0025_internaluser_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userservice',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='مبلغ افساط'),
        ),
        migrations.AddField(
            model_name='userservice',
            name='installment_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت افساط'),
        ),
        migrations.AddField(
            model_name='userservice',
            name='principal',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='مبلغ وام'),
        ),
        migrations.AddField(
            model_name='userservice',
            name='total_repayment',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='مبلغ بازپرداخت نهایی'),
        )
    ]
