# Generated by Django 4.2.14 on 2024-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0026_service_options_userservice_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contract_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
