# Generated by Django 4.2.14 on 2024-08-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0027_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='provider_fee_percent',
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='هزینه سرویس دهنده به درصد'
            ),
        ),
        migrations.AddField(
            model_name='userservice',
            name='provider_fee_amount',
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='هزینه سرویس دهنده'
            ),
        ),
    ]
