# Generated by Django 4.2.15 on 2024-09-08 11:02

import django.db.models.deletion
from django.db import migrations, models

import exchange.base.calendar
import exchange.base.storages


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0028_userservice_provider_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.IntegerField(
                        choices=[(1, 'new'), (2, 'success'), (3, 'error')], default=1, verbose_name='وضعیت'
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                (
                    'settlement',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='asset_backed_credit.settlementtransaction',
                        verbose_name='تراکنش تسویه',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.IntegerField(
                        choices=[(1, 'initiated'), (2, 'processed'), (3, 'no_file_existed')],
                        default=1,
                        verbose_name='وضعیت',
                    ),
                ),
                ('recon_date', models.DateTimeField(verbose_name='تاریخ مغایرت')),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now, verbose_name='تاریخ ایجاد')),
                ('closed_at', models.DateTimeField(null=True, verbose_name='تاریخ بسته شدن')),
                (
                    'file',
                    models.FileField(storage=exchange.base.storages.get_private_s3_storage, upload_to='debit_recon'),
                ),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='asset_backed_credit.service',
                        verbose_name='سرویس\u200cدهنده',
                    ),
                ),
            ],
        ),
    ]
