# Generated by Django 4.2.15 on 2024-09-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0029_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='user_reverse_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برگشت\u200c به کاربر',
            ),
        ),
    ]
