# Generated by Django 4.2.16 on 2024-09-24 03:47

import django.db.models.deletion
from django.db import migrations, models


def update_limit_types(apps, schema_editor):
    UserFinancialServiceLimit = apps.get_model('asset_backed_credit', 'UserFinancialServiceLimit')
    UserFinancialServiceLimit.objects.filter(tp=1).update(tp=10)
    UserFinancialServiceLimit.objects.filter(tp=2).update(tp=20)
    UserFinancialServiceLimit.objects.filter(tp=3).update(tp=60)
    UserFinancialServiceLimit.objects.filter(tp=4).update(tp=90)


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0030_settlementtransaction_user_reverse_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancialservicelimit',
            name='min_limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfinancialservicelimit',
            name='service_provider',
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, 'تارا'),
                    (2, 'پرداخت\u200cنوین'),
                    (3, 'ونسی'),
                    (4, 'ویپاد'),
                    (5, 'تاپ'),
                    (6, 'بالون'),
                    (7, 'مانی'),
                    (8, 'دیجی\u200cپی'),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='userfinancialservicelimit',
            name='service_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'اعتبار'), (2, 'وام'), (3, 'دبیت')], null=True),
        ),
        migrations.AlterField(
            model_name='userfinancialservicelimit',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
        migrations.AlterField(
            model_name='userfinancialservicelimit',
            name='limit',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userfinancialservicelimit',
            name='tp',
            field=models.SmallIntegerField(
                choices=[
                    (10, 'User'),
                    (20, 'User Service'),
                    (30, 'User ServiceProvider'),
                    (40, 'User ServiceType'),
                    (50, 'UserType'),
                    (60, 'UserType Service'),
                    (70, 'UserType ServiceProvider'),
                    (80, 'UserType ServiceType'),
                    (90, 'Service'),
                    (100, 'ServiceProvider'),
                    (110, 'ServiceType'),
                ]
            ),
        ),
        migrations.RunPython(update_limit_types, reverse_code=migrations.RunPython.noop),
    ]
