# Generated by Django 4.2.16 on 2024-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0031_userfinancialservicelimit_min_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfinancialservicelimit',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='null_checks',
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='limit_positivity',
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='unique_per_user_limit',
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='unique_per_user_service_limit',
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='unique_per_service_user_type_limit',
        ),
        migrations.RemoveConstraint(
            model_name='userfinancialservicelimit',
            name='unique_per_service',
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True),
                    ('service_provider__isnull', True),
                    ('service_type__isnull', True),
                    ('user_type__isnull', True),
                ),
                fields=('user',),
                name='abc_userfinancialservicelimit_unique_user_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service_provider__isnull', True), ('service_type__isnull', True), ('user_type__isnull', True)
                ),
                fields=('user', 'service'),
                name='abc_userfinancialservicelimit_unique_user_service_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True), ('service_type__isnull', True), ('user_type__isnull', True)
                ),
                fields=('user', 'service_provider'),
                name='abc_userfinancialservicelimit_unique_user_service_provider_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True), ('service_provider__isnull', True), ('user_type__isnull', True)
                ),
                fields=('user', 'service_type'),
                name='abc_userfinancialservicelimit_unique_user_service_type_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True),
                    ('service_provider__isnull', True),
                    ('service_type__isnull', True),
                    ('user__isnull', True),
                ),
                fields=('user_type',),
                name='abc_userfinancialservicelimit_unique_user_type_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service_provider__isnull', True), ('service_type__isnull', True), ('user__isnull', True)
                ),
                fields=('user_type', 'service'),
                name='abc_userfinancialservicelimit_unique_user_type_service_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(('service__isnull', True), ('service_type__isnull', True), ('user__isnull', True)),
                fields=('user_type', 'service_provider'),
                name='abc_userfinancialservicelimit_unique_user_type_service_provider_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True), ('service_provider__isnull', True), ('user__isnull', True)
                ),
                fields=('user_type', 'service_type'),
                name='abc_userfinancialservicelimit_unique_user_type_service_type_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service_provider__isnull', True),
                    ('service_type__isnull', True),
                    ('user__isnull', True),
                    ('user_type__isnull', True),
                ),
                fields=('service',),
                name='abc_userfinancialservicelimit_unique_service_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True),
                    ('service_type__isnull', True),
                    ('user__isnull', True),
                    ('user_type__isnull', True),
                ),
                fields=('service_provider',),
                name='abc_userfinancialservicelimit_unique_service_provider_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('service__isnull', True),
                    ('service_provider__isnull', True),
                    ('user__isnull', True),
                    ('user_type__isnull', True),
                ),
                fields=('service_type',),
                name='abc_userfinancialservicelimit_unique_service_type_limit',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', True),
                        ('tp', 10),
                        ('user__isnull', False),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', False),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', True),
                        ('tp', 20),
                        ('user__isnull', False),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', False),
                        ('service_type__isnull', True),
                        ('tp', 30),
                        ('user__isnull', False),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', False),
                        ('tp', 40),
                        ('user__isnull', False),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', True),
                        ('tp', 50),
                        ('user__isnull', True),
                        ('user_type__isnull', False),
                    ),
                    models.Q(
                        ('service__isnull', False),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', True),
                        ('tp', 60),
                        ('user__isnull', True),
                        ('user_type__isnull', False),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', False),
                        ('service_type__isnull', True),
                        ('tp', 70),
                        ('user__isnull', True),
                        ('user_type__isnull', False),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', False),
                        ('tp', 80),
                        ('user__isnull', True),
                        ('user_type__isnull', False),
                    ),
                    models.Q(
                        ('service__isnull', False),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', True),
                        ('tp', 90),
                        ('user__isnull', True),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', False),
                        ('service_type__isnull', True),
                        ('tp', 100),
                        ('user__isnull', True),
                        ('user_type__isnull', True),
                    ),
                    models.Q(
                        ('service__isnull', True),
                        ('service_provider__isnull', True),
                        ('service_type__isnull', False),
                        ('tp', 110),
                        ('user__isnull', True),
                        ('user_type__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='abc_userfinancialservicelimit_null_checks_per_limit_type',
            ),
        ),
        migrations.AddConstraint(
            model_name='userfinancialservicelimit',
            constraint=models.CheckConstraint(
                check=models.Q(('min_limit__lte', models.F('limit'))),
                name='abc_userfinancialservicelimit_min_limit_lte_limit',
            ),
        ),
    ]
