# Generated by Django 4.2.16 on 2024-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0032_alter_userfinancialservicelimit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='is_adjustment_notif_sent',
            field=models.BooleanField(default=False, verbose_name='نوتیف اجاستمنت ارسال شده؟'),
        ),
    ]
