# Generated by Django 4.2.16 on 2024-09-24 10:24
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_backed_credit', '0033_assettodebtmargincall_is_adjustment_notif_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'idempotency',
                    models.UUIDField(default=uuid.uuid4, unique=True, editable=False, null=False, blank=False),
                ),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Done'), (3, 'Rejected')], default=1)),
                (
                    'src_wallet_type',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                (
                    'dst_wallet_type',
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ('transfer_items', models.JSONField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_code', models.SmallIntegerField(blank=True, null=True)),
                ('api_called_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'internal_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.internaluser'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
