# Generated by Django 4.2.16 on 2024-10-08 10:43
from django.conf import settings
from django.db import migrations


def create_digipay_limit(apps, schema_editor):
    if not settings.IS_TESTNET:
        return

    UserFinancialServiceLimit = apps.get_model('asset_backed_credit', 'UserFinancialServiceLimit')
    Service = apps.get_model('asset_backed_credit', 'Service')

    service = Service.objects.filter(provider=8, tp=2).first()
    if service is None:
        return

    UserFinancialServiceLimit.objects.get_or_create(tp=90, service=service, defaults={'limit': 1_000_000_000})


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0034_wallet_transfer_log'),
    ]

    operations = [
        migrations.RunPython(create_digipay_limit, reverse_code=migrations.RunPython.noop),
    ]
