# Generated by Django 4.2.16 on 2024-10-15 10:37
from django.conf import settings
from django.db import migrations


def set_limit_on_service_types(apps, schema_editor):
    UserFinancialServiceLimit = apps.get_model('asset_backed_credit', 'UserFinancialServiceLimit')

    UserFinancialServiceLimit.objects.update_or_create(
        tp=110,  # service_type
        user=None,
        user_type=None,
        service=None,
        service_provider=None,
        service_type=1,  # credit
        defaults={'min_limit': 5_000_000, 'limit': 200_000_000},
    )

    UserFinancialServiceLimit.objects.update_or_create(
        tp=110,  # service_type
        user=None,
        user_type=None,
        service=None,
        service_provider=None,
        service_type=2,  # loan
        defaults={'min_limit': 50_000_000, 'limit': 500_000_000},
    )

    UserFinancialServiceLimit.objects.update_or_create(
        tp=110,  # service_type
        user=None,
        user_type=None,
        service=None,
        service_provider=None,
        service_type=3,  # debit
        defaults={'min_limit': 10_000, 'limit': 100_000_000},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0036_auto_20240928_1149'),
    ]

    operations = []
    if settings.IS_TESTNET:
        operations.append(migrations.RunPython(set_limit_on_service_types, reverse_code=migrations.RunPython.noop))
