# Generated by Django 4.2.16 on 2024-09-24 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_ordermatching__buy_order_ordermatching__sell_order'),
        ('asset_backed_credit', '0037_auto_20241015_1407'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AssetToDebtMarginCall_orders',
                    fields=[
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order')),
                    ],
                ),
                migrations.CreateModel(
                    name='SettlementTransaction_orders',
                    fields=[
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order')),
                    ],
                ),
            ],
        ),
        migrations.AlterField(
            model_name='assettodebtmargincall_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', to_field='_id'),
        ),
        migrations.AlterField(
            model_name='settlementtransaction_orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order', to_field='_id'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='AssetToDebtMarginCall_orders',
                ),
                migrations.DeleteModel(
                    name='SettlementTransaction_orders',
                ),
            ],
        ),
    ]
