# Generated by Django 4.2.16 on 2024-10-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import exchange.base.calendar


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_backed_credit', '0038_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=20, unique=True)),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'requested'),
                            (10, 'registered'),
                            (20, 'issued'),
                            (30, 'restricted'),
                            (40, 'expired'),
                        ],
                        default=0,
                    ),
                ),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('updated_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('provider_info', models.JSONField(blank=True, default=dict)),
                (
                    'internal_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='asset_backed_credit.internaluser',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    'user_service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='card',
                        to='asset_backed_credit.userservice',
                    ),
                ),
            ],
        ),
    ]
