# Generated by Django 4.2.16 on 2024-09-29 14:33
from datetime import date

from django.db import migrations
from django.db.models import Count


def update_last_action(apps, schema_editor):
    AssetToDebtMarginCall = apps.get_model('asset_backed_credit', 'AssetToDebtMarginCall')

    AssetToDebtMarginCall.objects.filter(
        orders__isnull=False,last_action=10, created_at__date__lte=date(year=2023, month=6, day=23)
    ).update(last_action=30)


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0039_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.RunPython(update_last_action, reverse_code=migrations.RunPython.noop, atomic=True),
    ]
