# Generated by Django 4.2.16 on 2024-10-23 13:10

from django.db import migrations

from exchange.asset_backed_credit.models import Service


def set_pan_by_user_service_account_number(apps, schema_editor):
    UserService = apps.get_model('asset_backed_credit', 'UserService')
    Card = apps.get_model('asset_backed_credit', 'Card')

    user_services = UserService.objects.filter(
        account_number__isnull=False, service__tp=Service.TYPES.debit
    ).select_related('user')
    for user_service in user_services:
        Card.objects.create(
            pan=user_service.account_number,
            status=20,
            user_service=user_service,
            user=user_service.user,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0040_update_margin_call_last_action'),
    ]

    operations = [migrations.RunPython(set_pan_by_user_service_account_number, reverse_code=migrations.RunPython.noop)]
