# Generated by Django 4.2.16 on 2024-10-20 10:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0041_alter_assettodebtmargincall_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWithdrawRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'provider',
                    models.SmallIntegerField(
                        choices=[
                            (1, 'تارا'),
                            (2, 'پرداخت\u200cنوین'),
                            (3, 'ونسی'),
                            (4, 'ویپاد'),
                            (5, 'تاپ'),
                            (6, 'بالون'),
                            (7, 'مانی'),
                            (8, 'دیجی\u200cپی'),
                        ]
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Done')], default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('external_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='provider_withdraw_request_log',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='settlement_transactions',
                to='asset_backed_credit.providerwithdrawrequestlog',
            ),
        ),
    ]
