# Generated by Django 4.2.16 on 2024-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0042_providerwithdrawrequestlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='remaining_rial_wallet_balance',
            field=models.BigIntegerField(blank=True,null=True, verbose_name='موجودی ریالی ولت بعد از انجام تراکنش'),
        ),
    ]
