# Generated by Django 4.2.16 on 2024-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0044_update_margin_call_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerwithdrawrequestlog',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
