# Generated by Django 4.2.16 on 2024-11-09 14:33

from django.db import migrations


def add_change_mobile_user_restriction(apps, schema_editor):
    UserService = apps.get_model('asset_backed_credit', 'UserService')
    UserRestriction = apps.get_model('accounts', 'UserRestriction')

    active_tara_user_services = UserService.objects.filter(
        service__provider=1, service__is_active=True, closed_at__isnull=True
    ).select_for_update()

    for user_service in active_tara_user_services:
        UserRestriction.objects.get_or_create(
            user=user_service.user,
            restriction=22,
            source='abc',
            ref_id=user_service.id,
            defaults={'considerations': 'به دلیل فعال بودن اکانت تارا،‌کاربر امکان ویرایش شماره موبایل را ندارد'},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0175_alter_user_unique_together_and_more'),
        ('asset_backed_credit', '0045_alter_providerwithdrawrequestlog_amount'),
    ]

    operations = [
        migrations.RunPython(add_change_mobile_user_restriction, reverse_code=migrations.RunPython.noop, atomic=True),
    ]
