# Generated by Django 4.2.16 on 2024-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0046_add_change_mobile_user_restriction_to_active_tara_user_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransferlog',
            name='retry',
            field=models.SmallIntegerField(default=0),
        )
    ]
