# Generated by Django 4.2.16 on 2024-11-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0047_wallettransferlog_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransferlog',
            name='internal_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
    ]
