# Generated by Django 4.2.16 on 2024-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0048_alter_assettodebtmargincall_orders_alter_card_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
