# Generated by Django 4.2.16 on 2024-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0049_alter_assettodebtmargincall_orders_alter_card_pan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransferlog',
            name='external_transfer_id',
            field=models.BigIntegerField(blank=True, null=True),
        )
    ]
