# Generated by Django 4.2.16 on 2024-11-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0050_wallettransferlog_external_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransferlog',
            name='failed_permanently_reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        )
    ]
