# Generated by Django 4.2.16 on 2024-12-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0051_wallettransferlog_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
