# Generated by Django 4.2.16 on 2024-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0052_service_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='national_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='user_type',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 'Normal'),
                    (10, 'Inactive'),
                    (20, 'Suspicious'),
                    (30, 'Blocked'),
                    (40, 'Level0'),
                    (42, 'Level1P'),
                    (44, 'Level1'),
                    (45, 'Trader'),
                    (46, 'Level2'),
                    (90, 'Level3'),
                    (91, 'Active'),
                    (92, 'Trusted'),
                    (99, 'Nobitex'),
                    (100, 'System'),
                    (101, 'Bot'),
                    (102, 'Staff'),
                ],
                null=True,
            ),
        ),
    ]
