# Generated by Django 4.2.16 on 2024-10-27 13:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_backed_credit', '0053_internaluser_email_internaluser_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.SmallIntegerField(choices=[(1, 'Email'), (2, 'Mobile'), (3, 'Phone')])),
                ('usage', models.SmallIntegerField(choices=[(11, 'Grant Permission To Financial Service')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('send_api_response_code', models.SmallIntegerField(blank=True, null=True)),
                ('send_api_called_at', models.DateTimeField(null=True)),
                ('verify_api_response_code', models.SmallIntegerField(blank=True, null=True)),
                ('verify_api_called_at', models.DateTimeField(null=True)),
                (
                    'internal_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.internaluser', null=True
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
