# Generated by Django 4.2.16 on 2024-12-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0055_alter_assettodebtmargincall_orders_alter_card_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='سطح کارت', unique=True)),
                ('label', models.CharField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('per_transaction_amount_limit', models.BigIntegerField(help_text='محدودیت هر تراکنش')),
                ('daily_transaction_amount_limit', models.BigIntegerField(help_text='محدودیت مجموع تراکنش های روزانه')),
                (
                    'monthly_transaction_amount_limit',
                    models.BigIntegerField(help_text='محدودیت مجموع تراکنش های ماهانه'),
                ),
                ('cashback_percentage', models.DecimalField(decimal_places=5, help_text='درصد کش بک', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardTransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.PositiveSmallIntegerField(choices=[(1, 'daily'), (2, 'monthly')])),
                ('total', models.BigIntegerField(help_text='مجموع ریالی')),
                ('start_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransactionFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.BigIntegerField(help_text='شروع بازه مبلغ تراکنش')),
                ('max_amount', models.BigIntegerField(help_text='پایان بازه مبلغ تراکنش')),
                (
                    'fee_percentage',
                    models.DecimalField(decimal_places=5, help_text='درصد کارمزد مبلغ تراکنش', max_digits=10),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'level',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.cardsetting'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='setting',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='asset_backed_credit.cardsetting'
            ),
        ),
        migrations.AddConstraint(
            model_name='cardtransactionlimit',
            constraint=models.UniqueConstraint(
                fields=('tp', 'card'), name='abc_cardtransactionlimit_transaction_card_and_type_unique_constraint'
            ),
        ),
        migrations.AddConstraint(
            model_name='cardtransactionfeesetting',
            constraint=models.UniqueConstraint(
                fields=('level', 'min_amount', 'max_amount'),
                name='abc_cardtransactionfeesetting_level_and_amount_range_unique_constraint',
            ),
        ),
    ]
