# Generated by Django 4.2.16 on 2024-12-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0056_card_level_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsetting',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
