# Generated by Django 4.2.16 on 2024-12-24 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0057_card_limits_label_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaluser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='identity_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='mobile_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='mobile_identity_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
