# Generated by Django 4.2.16 on 2025-01-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0058_internal_user_verification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='birthdate_shamsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='requires_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
