# Generated by Django 4.2.17 on 2025-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0059_internaluser_birthday_shamsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
