# Generated by Django 4.2.17 on 2025-01-25 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0060_card_activated_at_card_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
