# Generated by Django 4.2.17 on 2025-01-25 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0061_transaction_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
