# Generated by Django 4.2.17 on 2025-02-09 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0062_alter_assettodebtmargincall_orders_alter_card_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='insurance_reverse_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برگشت کسر از اکانت بیمه\u200cی نوبیتکس',
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='provider_reverse_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برگشت تسویه با سرویس\u200cدهنده',
            ),
        ),
    ]
