# Generated by Django 4.2.16 on 2025-02-16 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0063_settlementtransaction_insurance_reverse_transaction_and_more'),
    ]

    operations = [
        # Drop InternalUser Foreign Keys
        migrations.RemoveField(
            model_name='assettodebtmargincall',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='incomingapicalllog',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='otplog',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='outgoingapicalllog',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='userfinancialservicelimit',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='userservicepermission',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='internal_user',
        ),
        migrations.RemoveField(
            model_name='wallettransferlog',
            name='internal_user',
        ),
    ]
