# Generated by Django 4.2.16 on 2025-02-16 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset_backed_credit', '0064_remove_internal_user_fks'),
    ]

    operations = [
        # Change InternalUser Primary Key
        migrations.AlterField(
            model_name='internaluser',
            name='uid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        # Add Foreign Key Relations to `id` field
        migrations.AddField(
            model_name='assettodebtmargincall',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='card',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
        migrations.AddField(
            model_name='incomingapicalllog',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='otplog',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
        migrations.AddField(
            model_name='outgoingapicalllog',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userfinancialservicelimit',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
        migrations.AddField(
            model_name='userservice',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='userservicepermission',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
                verbose_name='کاربر',
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wallets',
                to='asset_backed_credit.internaluser',
            ),
        ),
        migrations.AddField(
            model_name='wallettransferlog',
            name='internal_user',
            field=models.ForeignKey(
                to_field='id',
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.internaluser',
            ),
        ),
    ]
