# Generated by Django 4.2.17 on 2025-03-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0065_change_internal_user_pk_and_add_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementrecon',
            name='recon',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.recon',
                verbose_name='مغایرت\u200cگیری مربوطه',
            ),
        ),
    ]
