# Generated by Django 4.2.17 on 2025-04-19 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0066_settlementrecon_recon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='liquidation_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='liquidation_retry',
            field=models.SmallIntegerField(default=0),
        ),
    ]
