# Generated by Django 4.2.17 on 2025-04-16 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0067_settlementtransaction_liquidation_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementrecon',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='settlementrecon',
            name='settlement',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='asset_backed_credit.settlementtransaction',
                verbose_name='تراکنش تسویه',
            ),
        ),
    ]
