# Generated by Django 4.2.17 on 2025-04-22 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0068_settlementrecon_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='مقدار کارمزد تراکنش'),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='fee_deposit_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش کارمزد',
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='fee_reverse_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برگشت کارمزد',
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='user_fee_reverse_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برگشت کارمزد به کاربر',
            ),
        ),
        migrations.AddField(
            model_name='settlementtransaction',
            name='user_fee_withdraw_transaction',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='wallet.transaction',
                verbose_name='تراکنش برداشت کارمزد از کاربر',
            ),
        ),
    ]
