# Generated by Django 4.2.20 on 2025-06-09 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import exchange.base.storages


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backed_credit', '0070_alter_assettodebtmargincall_internal_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (2, 'Completed')], default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                (
                    'type',
                    models.IntegerField(
                        choices=[(0, 'All'), (1, 'Lock'), (2, 'Unlock'), (3, 'Settlement'), (4, 'Settlement Mismatch')],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'attachment_type',
                    models.IntegerField(
                        choices=[(1, 'Lock'), (2, 'Unlock'), (3, 'Settlement'), (4, 'Settlement Mismatch')]
                    ),
                ),
                (
                    'file',
                    models.FileField(storage=exchange.base.storages.get_private_s3_storage, upload_to='abc_report'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attachments',
                        to='asset_backed_credit.creditreport',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='creditreport',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_backed_credit.service'),
        ),
        migrations.AddConstraint(
            model_name='reportattachment',
            constraint=models.UniqueConstraint(
                fields=('report', 'attachment_type'), name='unique_per_report_attachment_type'
            ),
        ),
    ]
