# Generated by Django 2.2.28 on 2023-01-24 10:46

import uuid

import django.utils.timezone
from django.db import migrations, models


def disable_old_news(apps, schema_editor):
    News = apps.get_model('crm', 'News')
    News.objects.update(is_disabled=True)


class Migration(migrations.Migration):

    replaces = [
        ('crm', '0001_initial'),
        ('crm', '0002_auto_20191201_1937'),
        ('crm', '0003_auto_20230116_2047'),
        ('crm', '0004_auto_20230117_1549'),
        ('crm', '0005_news_image_name'),
        ('crm', '0006_auto_20230118_1558'),
        ('crm', '0007_auto_20230123_1442'),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='نام')),
                ('slug', models.TextField(db_index=True, max_length=50, unique=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('context', models.TextField(verbose_name='متن خبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد خبر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک خبر')),
                ('image', models.URLField(blank=True, null=True, verbose_name='لینک آپلود تصویر')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='غیرفعال')),
                (
                    'publish_at',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
                ),
                ('tags', models.ManyToManyField(related_name='news', to='crm.NewsTag')),
                ('image_name', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'اخبار',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.RunPython(disable_old_news),
    ]
