# Generated by Django 2.2.28 on 2023-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial_squashed_0007_auto_20230123_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=1000, null=True, verbose_name='زیر تیتر'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='color',
            field=models.CharField(max_length=7, null=True, verbose_name='رنگ'),
        ),
    ]
