# Generated by Django 2.1.14 on 2019-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='context',
            field=models.TextField(verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='تاریخ ایجاد خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='لینک آپلود تصویر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان خبر'),
        ),
    ]
