# Generated by Django 2.2.28 on 2023-01-16 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191201_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='غیرفعال'),
        ),
        migrations.AddField(
            model_name='news',
            name='publish_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
