# Generated by Django 2.2.28 on 2023-01-18 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20230117_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_name',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
