# Generated by Django 2.2.28 on 2023-01-18 12:28

from django.db import migrations


def disable_old_news(apps, schema_editor):
    News = apps.get_model('crm', 'News')
    News.objects.update(is_disabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_news_image_name'),
    ]

    operations = [migrations.RunPython(disable_old_news)]
