# Generated by Django 2.2.28 on 2023-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20230118_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='NewsTag',
        ),
        migrations.AlterField(
            model_name='news',
            name='image_name',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
