# Generated by Django 2.2.26 on 2022-03-03 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0094_auto_20220204_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftBatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'My Neighbor Alice'), (52, 'Alpha Finance Lab'), (53, 'Ankr'), (54, 'ARPA Chain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie Infinity'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'Basic Attention Token'), (63, 'Bella Protocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'Celer Network'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'Elrond eGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'Mask Network'), (83, 'Maker'), (84, 'NEAR Protocol'), (85, 'Ocean Protocol'), (86, 'Ontology'), (87, 'Reef Finance'), (88, 'SafePal'), (89, 'Synthetix Network Token'), (90, 'Sushi'), (91, 'Swipe'), (92, 'Alien Worlds'), (93, 'Unifi Protocol DAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa')], null=True)),
                ('number', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('receiver_email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('package_type', models.IntegerField(null=True)),
                ('redeem_code', models.CharField(max_length=100, unique=True)),
                ('gift_sentence', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'My Neighbor Alice'), (52, 'Alpha Finance Lab'), (53, 'Ankr'), (54, 'ARPA Chain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie Infinity'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'Basic Attention Token'), (63, 'Bella Protocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'Celer Network'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'Elrond eGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'Mask Network'), (83, 'Maker'), (84, 'NEAR Protocol'), (85, 'Ocean Protocol'), (86, 'Ontology'), (87, 'Reef Finance'), (88, 'SafePal'), (89, 'Synthetix Network Token'), (90, 'Sushi'), (91, 'Swipe'), (92, 'Alien Worlds'), (93, 'Unifi Protocol DAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa')])),
                ('gift_type', models.IntegerField(choices=[(0, 'Physical'), (1, 'Digital')])),
                ('gift_status', models.IntegerField(choices=[(0, 'New'), (1, 'Redeemed'), (2, 'Canceled')], default=0)),
                ('redeem_type', models.IntegerField(choices=[(0, 'Lightning'), (1, 'Internal')])),
                ('lnurl', models.CharField(max_length=300, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('redeem_date', models.DateTimeField(null=True)),
                ('initial_withdraw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.WithdrawRequest')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received_gift_cards', to=settings.AUTH_USER_MODEL)),
                ('redeem_withdraw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.WithdrawRequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gift_cards', to=settings.AUTH_USER_MODEL)),
                ('card_design', models.IntegerField(choices=[(0, 'Default')], default=0)),
                ('gift_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_gifts', to='gift.GiftBatchRequest')),
                ('redeemed_at', models.DateTimeField(null=True)),
                ('lnurl_key', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
