# Generated by Django 2.2.26 on 2022-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
