# Generated by Django 2.2.24 on 2022-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_auto_20220305_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbatchrequest',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='alternative_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس جایگزین'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='gift_status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Redeemed'), (2, 'Canceled'), (3, 'Confirmed')], default=0),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='gift_type',
            field=models.IntegerField(choices=[(0, 'Physical'), (1, 'Digital')], null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'User Confirmed'), (2, 'Confirmed')], default=0),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, null=True),
        ),
    ]
