# Generated by Django 2.2.26 on 2022-04-03 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_auto_20220308_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbatchrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='card_design',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Grand'), (2, 'Cute'), (3, 'Light'), (4, 'Mind')], default=0),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='gift_sentence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='package_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'First Package'), (2, 'Second Package'), (3, 'Third package'), (4, 'Fourth package'), (5, 'Fifth package')], null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='receiver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='redeem_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='redeem_type',
            field=models.IntegerField(choices=[(0, 'Lightning'), (1, 'Internal')], null=True),
        ),
        migrations.AlterField(
            model_name='giftbatchrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
    ]
