# Generated by Django 2.2.24 on 2022-04-18 12:35

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_auto_20220403_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbatchrequest',
            name='digital_info',
            field=JSONField(blank=True, null=True),
        ),
    ]
