# Generated by Django 2.2.27 on 2022-04-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0005_auto_20220418_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padro_order_id', models.CharField(max_length=200, null=True, verbose_name='کد سفارش پادرو')),
                ('source_city', models.CharField(max_length=20, verbose_name='کد شهر مبدا')),
                ('destination_city', models.CharField(max_length=20, verbose_name='کد شهر مقصد')),
                ('sender_name', models.CharField(max_length=250, verbose_name='نام فرستنده')),
                ('sender_postal_code', models.CharField(max_length=10, verbose_name='کد پستی فرستنده')),
                ('sender_address', models.TextField(verbose_name='آدرس فرستنده')),
                ('sender_phone_number', models.CharField(max_length=12, verbose_name='شماره موبایل فرستنده')),
                ('receiver_name', models.CharField(max_length=250, verbose_name='نام گیرنده')),
                ('receiver_postal_code', models.CharField(max_length=10, verbose_name='کد پستی گیرنده')),
                ('receiver_address', models.TextField(verbose_name='آدرس گیرنده')),
                ('receiver_phone_number', models.CharField(max_length=12, verbose_name='شماره موبایل گیرنده')),
                ('receiver_comment', models.TextField(verbose_name='پیام گیرنده')),
                ('provider_code', models.CharField(max_length=100, null=True, verbose_name='شناسه پروایدر')),
                ('provider_name', models.CharField(max_length=100, null=True, verbose_name='نام پروایدر')),
                ('price', models.DecimalField(decimal_places=10, max_digits=25, null=True, verbose_name='هزینه ارسال')),
                ('from_hours', models.IntegerField(null=True, verbose_name='زمان ارسال (از)')),
                ('to_hours', models.IntegerField(null=True, verbose_name='زمان ارسال (تا)')),
                ('service_type', models.CharField(max_length=100, null=True, verbose_name='نوع سرویس')),
                ('service_type_label', models.CharField(max_length=100, null=True, verbose_name='عنوان نوع سرویس')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('value', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='ارزش بسته')),
                ('width', models.IntegerField(verbose_name='عرض بسته')),
                ('height', models.IntegerField(verbose_name='طول بسته')),
                ('depth', models.IntegerField(verbose_name='ارتفاع بسته')),
                ('content', models.CharField(max_length=500, verbose_name='محتوای بسته')),
                ('postal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='gift.PostalOrder')),
            ],
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='postal_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift.PostalOrder'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='postal_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift.PostalOrder'),
        ),
    ]
