# Generated by Django 2.2.26 on 2022-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0006_auto_20220419_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbatchrequest',
            name='is_sealed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='is_sealed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
