# Generated by Django 2.2.27 on 2022-05-24 12:54

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0007_auto_20220508_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalorder',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='postal_order',
        ),
        migrations.RemoveField(
            model_name='postalorder',
            name='padro_order_id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parcel',
            name='name',
            field=models.CharField(
                default=datetime.datetime(2022, 5, 24, 12, 54, 43, 919650, tzinfo=datetime.timezone.utc),
                max_length=200,
                verbose_name='نام بسته',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postalorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='order_id',
            field=models.CharField(max_length=200, null=True, verbose_name='کد سفارش'),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='pickup_date',
            field=models.DateField(null=True, verbose_name='تاریخ جمع آوری'),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='pickup_from_hour',
            field=models.IntegerField(null=True, verbose_name='ساعت جمع آوری (از)'),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='pickup_to_hour',
            field=models.IntegerField(null=True, verbose_name='ساعت جمع آوری (تا)'),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='provider',
            field=models.IntegerField(choices=[(0, 'ارسال دستی'), (1, 'ارسال از طریق پادرو')], null=True, verbose_name='پروایدر'),
        ),
        migrations.AddField(
            model_name='postalorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'جدید'), (1, 'ثبت درخواست'), (2, 'تحویل به پست'), (3, 'تحویل شده'), (4, 'ناموفق')], default=0, null=False, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='PostalOrderParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_postal_orders', to='gift.Parcel', verbose_name='بسته پستی')),
                ('postal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_order_parcels', to='gift.PostalOrder', verbose_name='سفارش پستی')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='postal_orders',
            field=models.ManyToManyField(related_name='parcels', through='gift.PostalOrderParcel', to='gift.PostalOrder'),
        ),
    ]
