# Generated by Django 2.2.27 on 2022-05-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0008_auto_20220524_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftbatchrequest',
            name='postal_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_requests', to='gift.PostalOrder'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='postal_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='gift.PostalOrder'),
        ),
    ]
