# Generated by Django 2.2.27 on 2022-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0009_auto_20220529_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalorderparcel',
            name='parcel_num',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
