# Generated by Django 2.2.28 on 2023-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gift', '0010_auto_20220705_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='admin_note',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='gift_status',
            field=models.IntegerField(
                choices=[(-100, 'Review'), (0, 'New'), (1, 'Redeemed'), (2, 'Canceled'), (3, 'Confirmed'),
                         (4, 'Verified'), (5, 'Closed'), (6, 'Printed'), (7, 'Sent'), (8, 'Delivered')], default=0),
        ),
    ]
