# Generated by Django 2.2.28 on 2023-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gift', '0011_auto_20230225_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='gift_status',
            field=models.IntegerField(
                choices=[(100, 'Review'), (0, 'New'), (1, 'Redeemed'), (2, 'Canceled'), (3, 'Confirmed'),
                         (4, 'Verified'), (5, 'Closed'), (6, 'Printed'), (7, 'Sent'), (8, 'Delivered')], default=0),
        ),
    ]
