# Generated by Django 2.2.28 on 2023-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0012_auto_20230226_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='postal_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
