# Generated by Django 2.2.28 on 2023-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0013_auto_20230226_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftbatchrequest',
            name='postal_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
