# Generated by Django 2.2.28 on 2023-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0014_auto_20230228_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='postal_tracking_code',
        ),
    ]
