# Generated by Django 2.2.28 on 2023-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0015_auto_20230306_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بسته\u200cبندی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('weight', models.IntegerField(verbose_name='وزن بسته')),
                ('width', models.IntegerField(verbose_name='عرض بسته')),
                ('height', models.IntegerField(verbose_name='طول بسته')),
                ('depth', models.IntegerField(verbose_name='ارتفاع بسته')),
                ('can_batch_request', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(related_name='_giftpackages_images_+', to='accounts.UploadedFile', verbose_name='تصاویر')),
            ],
        ),
    ]
