# Generated by Django 2.2.28 on 2023-05-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('gift', '0016_auto_20230523_1600'),
    ]

    def create_card_design_objects(apps, schema_editor):
        CardDesign = apps.get_model('gift', 'CardDesign')

        card_design_choices = [
            ('default', 'Default'),
            ('grand', 'Grand'),
            ('cute', 'Cute'),
            ('light', 'Light'),
            ('mind', 'Mind'),
        ]

        for choice in card_design_choices:
            CardDesign.objects.get_or_create(title=choice[1], price=0, inventory=0)

    operations = [
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان طرح')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت', default=0)),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('back_image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='accounts.UploadedFile', verbose_name='تصویر پشت کارت')),
                ('front_image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='accounts.UploadedFile', verbose_name='تصویر روی کارت')),
                ('real_back_image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='accounts.UploadedFile', verbose_name='تصویر واقعی پشت کارت')),
                ('real_front_image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='accounts.UploadedFile', verbose_name='تصویر واقعی روی کارت')),
            ],
        ),
        migrations.RunPython(create_card_design_objects),
    ]
