# Generated by Django 2.2.28 on 2023-05-28 05:09

from django.db import migrations, models
import django.db.models.deletion


def set_card_design_foreign_key(apps, schema_editor):
    GiftCard = apps.get_model('gift', 'GiftCard')
    GiftBatchRequest = apps.get_model('gift', 'GiftBatchRequest')
    CardDesign = apps.get_model('gift', 'CardDesign')

    card_design_map = {
        0: CardDesign.objects.filter(title='Default').first(),
        1: CardDesign.objects.filter(title='Grand').first(),
        2: CardDesign.objects.filter(title='Cute').first(),
        3: CardDesign.objects.filter(title='Light').first(),
        4: CardDesign.objects.filter(title='Mind').first(),
    }

    for obj in GiftCard.objects.all():
        card_design = card_design_map.get(obj.card_design)
        obj.card_design_new = card_design
        obj.save()

    for obj in GiftBatchRequest.objects.all():
        card_design = card_design_map.get(obj.card_design)
        obj.card_design_new = card_design
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0017_auto_20230528_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='card_design_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gift.CardDesign'),
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='card_design_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gift.CardDesign'),
        ),
        migrations.RunPython(set_card_design_foreign_key),
        migrations.RemoveField(
            model_name='giftcard',
            name='card_design',
        ),
        migrations.RemoveField(
            model_name='giftbatchrequest',
            name='card_design',
        ),
        migrations.RenameField(
            model_name='giftcard',
            old_name='card_design_new',
            new_name='card_design',
        ),
        migrations.RenameField(
            model_name='giftbatchrequest',
            old_name='card_design_new',
            new_name='card_design',
        ),
    ]
