# Generated by Django 2.2.28 on 2023-06-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0018_auto_20230528_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftbatchrequest',
            name='package_type'
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='package_type'
        ),
        migrations.AddField(
            model_name='giftbatchrequest',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gift.GiftPackage'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gift.GiftPackage'),
        ),
    ]
