# Generated by Django 2.1.4 on 2018-12-12 19:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0040_userrestriction'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.IntegerField(choices=[(10, 'Deposit'), (20, 'Withdraw')])),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin')])),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletDepositAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to='wallet.Wallet')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('total_sent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency')},
        ),
        migrations.CreateModel(
            name='AvailableDepositAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin')])),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('used_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.WalletDepositAddress')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedWalletDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_deposits', to='wallet.WalletDepositAddress')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Transaction')),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('confirmations', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='availabledepositaddress',
            unique_together={('currency', 'address')},
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Verified'), (3, 'Accepted'), (4, 'Sent'), (5, 'Done'), (6, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explanations', models.TextField(blank=True, default='')),
                ('updates', models.TextField(blank=True, default='')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='wallet.Wallet')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='accounts.BankAccount')),
                ('blockchain_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست برداشت',
            },
        ),
        migrations.CreateModel(
            name='ShetabDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('status_code', models.IntegerField(default=-9999, verbose_name='وضعیت')),
                ('nextpay_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پیگیری')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction', verbose_name='تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shetab_deposits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_card_number', models.CharField(blank=True, max_length=50, verbose_name='شماره کارت')),
                ('broker', models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing')], default=1, verbose_name='درگاه پرداخت')),
                ('next_redirect_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس بازگشت')),
                ('fee', models.BigIntegerField(default=0, help_text='ریال', verbose_name='کارمزد')),
            ],
            options={
                'verbose_name': 'واریز شتابی',
                'verbose_name_plural': 'واریز شتابی',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tp',
            field=models.IntegerField(choices=[(10, 'Deposit'), (20, 'Withdraw'), (30, 'Buy'), (40, 'Sell'), (50, 'Fee')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tp',
            field=models.IntegerField(choices=[(10, 'Deposit'), (20, 'Withdraw'), (30, 'Buy'), (40, 'Sell'), (50, 'Fee'), (60, 'Manual')]),
        ),
        migrations.AlterField(
            model_name='availabledepositaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin'), (13, 'Tether(omni)')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin'), (13, 'Tether(omni)')]),
        ),
        migrations.AlterField(
            model_name='availabledepositaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin'), (13, 'Tether(omni)'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Etherium'), (12, 'Litecoin'), (13, 'Tether(omni)'), (21, 'Cardano')]),
        ),
        migrations.CreateModel(
            name='AutomaticWithdrawLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('withdraw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.WithdrawRequest')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.IntegerField(choices=[(10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (40, 'Electrum LTC'), (50, 'Parity')])),
                ('binance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('withdraw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='wallet.WithdrawRequest')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Failed'), (2, 'Done'), (3, 'Canceled'), (4, 'Sending'), (5, 'Waiting'), (6, 'Diff-Non-Zero'), (7, 'Accepted')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Verified'), (3, 'Accepted'), (4, 'Sent'), (5, 'Done'), (6, 'Rejected'), (7, 'Processing'), (8, 'Canceled')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'address')},
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Verified'), (3, 'Accepted'), (4, 'Sent'), (5, 'Done'), (6, 'Rejected'), (7, 'Processing'), (8, 'Canceled'), (9, 'Waiting')], default=1),
        ),
        migrations.CreateModel(
            name='AvailableHotWalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (21, 'Cardano')])),
                ('address', models.CharField(max_length=100, unique=True)),
                ('total_received', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('total_sent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_module',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('ref_module', 'ref_id')},
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='blockchain_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='withdraw_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.SystemBankAccount'),
        ),
        migrations.AlterField(
            model_name='availabledepositaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='target_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Internal')], default=0),
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده')], default=0)),
                ('receipt_id', models.CharField(max_length=10, verbose_name='شناسه رسید بانکی')),
                ('dst_bank_account', models.CharField(help_text='شماره حساب بانکی مقصد', max_length=50, verbose_name='حساب بانکی مقصد')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('deposited_at', models.DateField(db_index=True, help_text='تاریخ واریز', verbose_name='تاریخ واریز')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_file', to='accounts.UploadedFile', verbose_name='رسید پرداخت')),
                ('src_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount', verbose_name='حساب بانکی مبدا')),
            ],
            options={
                'verbose_name': 'واریز بانکی',
                'verbose_name_plural': 'واریز بانکی',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_module',
            field=models.IntegerField(blank=True, choices=[(30, 'ConfirmedWalletDeposit'), (31, 'ShetabDeposit'), (32, 'WithdrawRequest'), (33, 'InternalTransferDeposit'), (34, 'BankDeposit'), (41, 'TradeSellA'), (42, 'TradeSellB'), (43, 'TradeBuyA'), (44, 'TradeBuyB'), (45, 'TradeFeeA'), (46, 'TradeFeeB')], null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to=settings.AUTH_USER_MODEL),
        ),
    ]
