# Generated by Django 2.1.4 on 2018-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_nobitex2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='document',
        ),
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
