# Generated by Django 2.1.4 on 2018-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20181215_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='fee',
            field=models.BigIntegerField(default=0, help_text='ریال', verbose_name='کارمزد'),
        ),
    ]
