# Generated by Django 2.1.4 on 2018-12-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_bankdeposit_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt_id',
            field=models.CharField(max_length=25, verbose_name='شناسه رسید بانکی'),
        ),
    ]
