# Generated by Django 2.1.4 on 2018-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20181216_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt_id',
            field=models.CharField(max_length=25, unique=True, verbose_name='شناسه رسید بانکی'),
        ),
    ]
