# Generated by Django 2.1.4 on 2019-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20181218_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='binance_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
