# Generated by Django 2.1.4 on 2019-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20181218_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledepositaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='availablehotwalletaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')]),
        ),
    ]
