# Generated by Django 2.1.5 on 2019-01-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20190119_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDepositAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('dt_from', models.DateTimeField(db_index=True, verbose_name='از تاریخ')),
                ('dt_to', models.DateTimeField(db_index=True, verbose_name='تا تاریخ')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار واریز')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_addresses', to='wallet.Wallet')),
            ],
            options={
                'verbose_name': ('آدرس واریز اشتراکی',),
                'verbose_name_plural': ('آدرس واریز اشتراکی',),
            },
        ),
    ]
