# Generated by Django 2.1.5 on 2019-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_shareddepositaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddepositaddress',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
