# Generated by Django 2.1.5 on 2019-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20190123_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddepositaddress',
            name='address',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
