# Generated by Django 2.1.5 on 2019-01-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20190123_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareddepositaddress',
            options={'verbose_name': 'آدرس واریز اشتراکی', 'verbose_name_plural': 'آدرس واریز اشتراکی'},
        ),
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='shared_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_deposits', to='wallet.SharedDepositAddress'),
        ),
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_deposits', to='wallet.WalletDepositAddress'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'address', 'shared_address')},
        ),
    ]
