# Generated by Django 2.1.4 on 2019-02-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20190126_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDepositTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(unique=True, verbose_name='تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_received', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('total_sent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تگ\u200cهای واریز',
                'verbose_name_plural': 'تگ\u200cهای واریز',
            },
        ),
        migrations.AlterModelOptions(
            name='availabledepositaddress',
            options={'verbose_name': 'آدرس سرد', 'verbose_name_plural': 'آدرس سرد'},
        ),
        migrations.AlterModelOptions(
            name='availablehotwalletaddress',
            options={'verbose_name': 'کیف\u200c پول گرم', 'verbose_name_plural': 'کیف\u200c پول گرم'},
        ),
        migrations.AlterModelOptions(
            name='confirmedwalletdeposit',
            options={'verbose_name': 'واریز تایید شده', 'verbose_name_plural': 'واریز تایید شده'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول داخلی', 'verbose_name_plural': 'کیف پول داخلی'},
        ),
        migrations.AlterModelOptions(
            name='walletdepositaddress',
            options={'verbose_name': 'کیف پول سرد', 'verbose_name_plural': 'کیف پول سرد'},
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletdeposittag',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_tags', to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_deposits', to='wallet.WalletDepositTag'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'address', 'shared_address', 'tag')},
        ),
    ]
