# Generated by Django 2.1.4 on 2019-02-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20190126_1922'),
        ('wallet', '0006_auto_20190124_0004'),
    ]

    operations = [
    ]
