# Generated by Django 2.1.4 on 2019-02-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20190203_0502'),
        ('wallet', '0012_merge_20190203_1500'),
    ]

    operations = [
    ]
