# Generated by Django 2.1.4 on 2019-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_merge_20190204_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='tag',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
