# Generated by Django 2.1.4 on 2019-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20190206_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Fake'), (10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (40, 'Electrum LTC'), (50, 'Parity'), (60, 'Ripple API')]),
        ),
    ]
