# Generated by Django 2.1.7 on 2019-03-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20190212_1335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'shared_address'), ('tx_hash', 'address'), ('tx_hash', 'tag')},
        ),
    ]
