# Generated by Django 2.1.5 on 2019-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_auto_20190305_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablehotwalletaddress',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
