# Generated by Django 2.1.7 on 2019-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_auto_20190314_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='shetabdeposit',
            name='user_card_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='هش کارت'),
        ),
    ]
