# Generated by Django 2.1.8 on 2019-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_shetabdeposit_user_card_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shetabdeposit',
            name='gateway_redirect_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس انتقال به درگاه'),
        ),
        migrations.AlterField(
            model_name='shetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay')], default=1, verbose_name='درگاه پرداخت'),
        ),
    ]
