# Generated by Django 2.1.8 on 2019-05-09 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20190428_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
