# Generated by Django 2.1.8 on 2019-05-25 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_auto_20190509_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletdepositaddress',
            options={'verbose_name': 'آدرس واریز', 'verbose_name_plural': 'آدرس واریز'},
        ),
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
