# Generated by Django 2.1.8 on 2019-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_auto_20190525_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemColdAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')])),
                ('address', models.CharField(max_length=100)),
                ('total_received', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('total_sent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'کیف\u200c پول سرد سیستمی',
                'verbose_name_plural': 'کیف\u200c پول سرد سیستمی',
            },
        ),
    ]
