# Generated by Django 2.1.8 on 2019-06-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_systemcoldaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shetabdeposit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='shetabdeposit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShetabDeposit',
        ),
    ]
