# Generated by Django 2.1.8 on 2019-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_systemcoldaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='rial_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='ارزش ریالی'),
        ),
    ]
