# Generated by Django 2.1.8 on 2019-06-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_auto_20190619_2319'),
        ('wallet', '0023_withdrawrequest_rial_value'),
    ]

    operations = [
    ]
