# Generated by Django 2.1.9 on 2019-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_merge_20190625_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')], default=0),
        ),
        migrations.AddField(
            model_name='walletdepositaddress',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='walletdepositaddress',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='walletdepositaddress',
            unique_together={('currency', 'address')},
        ),
    ]
