# Generated by Django 2.1.9 on 2019-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_auto_20190705_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='rial_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='ارزش ریالی'),
        ),
    ]
