# Generated by Django 2.1.8 on 2019-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_auto_20190709_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='اولویت', verbose_name='اولویت'),
        ),
    ]
