# Generated by Django 2.1.8 on 2019-09-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_auto_20190827_1204'),
        ('wallet', '0029_auto_20190830_0023'),
    ]

    operations = [
    ]
