# Generated by Django 2.1.8 on 2019-09-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0030_merge_20190901_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tp',
            field=models.IntegerField(choices=[(10, 'Deposit'), (20, 'Withdraw'), (30, 'Buy'), (40, 'Sell'), (50, 'Fee'), (60, 'Manual'), (70, 'Gateway')]),
        ),
    ]
