# Generated by Django 2.1.11 on 2019-09-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_auto_20190901_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='last_deposit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletdepositaddress',
            name='last_deposit_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
