# Generated by Django 2.1.12 on 2019-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0031_auto_20190901_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Internal'), (2, 'Gateway')], default=0),
        ),
    ]
