# Generated by Django 2.1.11 on 2019-09-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20190913_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='last_update_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
