# Generated by Django 2.1.11 on 2019-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0033_walletdepositaddress_last_update_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='needs_update',
            field=models.BooleanField(default=False),
        ),
    ]
