# Generated by Django 2.1.11 on 2019-09-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20190917_1717'),
        ('wallet', '0034_walletdepositaddress_needs_update'),
    ]

    operations = [
    ]
