# Generated by Django 2.1.12 on 2019-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0035_merge_20190918_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcoldaddress',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
