# Generated by Django 2.1.13 on 2019-11-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0036_systemcoldaddress_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBlockedBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_module', models.IntegerField(blank=True, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('balance_blocked', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
            ],
            options={
                'verbose_name': 'موجودی بلوکه',
                'verbose_name_plural': 'موجودی بلوکه',
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_blocked',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_in_order',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='walletblockedbalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet'),
        ),
    ]
