# Generated by Django 2.1.15 on 2020-03-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0039_auto_20200229_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehotwalletaddress',
            name='last_update_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcoldaddress',
            name='last_update_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
