# Generated by Django 2.1.15 on 2020-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0040_auto_20200401_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedwalletdeposit',
            options={'permissions': [('confirmed_wallet_deposit_manual_create', 'ثبت دستی واریز رمزارز')], 'verbose_name': 'واریز تایید شده', 'verbose_name_plural': 'واریز تایید شده'},
        ),
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Fake'), (10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (40, 'Electrum LTC'), (50, 'Parity'), (60, 'Ripple API'), (70, 'Tether(ERC20)'), (80, 'Electron Cash'), (90, 'BNB API'), (100, 'Vandar API'), (110, 'TRX Hot Wallet')]),
        ),
    ]
