# Generated by Django 2.1.8 on 2020-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0041_auto_20200415_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
