# Generated by Django 2.1.8 on 2020-05-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0042_auto_20200422_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Fake'), (10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (40, 'Electrum LTC'), (50, 'Parity'), (60, 'Ripple API'), (70, 'Tether(ERC20)'), (80, 'Electron Cash'), (90, 'BNB API'), (100, 'Vandar API'), (110, 'TRX Hot Wallet'), (120, 'XLM Hot Wallet')]),
        ),
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='withdraw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_withdraw', to='wallet.WithdrawRequest'),
        ),
    ]
