# Generated by Django 2.2.13 on 2020-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0043_auto_20200507_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistWalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_update_check', models.DateTimeField(blank=True, null=True)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')])),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'لیست سیاه آدرس\u200cها',
                'verbose_name_plural': 'لیست سیاه آدرس\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_module',
            field=models.IntegerField(blank=True, choices=[(30, 'ConfirmedWalletDeposit'), (31, 'ShetabDeposit'), (32, 'WithdrawRequest'), (33, 'InternalTransferDeposit'), (34, 'BankDeposit'), (41, 'TradeSellA'), (42, 'TradeSellB'), (43, 'TradeBuyA'), (44, 'TradeBuyB'), (45, 'TradeFeeA'), (46, 'TradeFeeB'), (51, 'ReverseTransaction')], null=True),
        ),
    ]
