# Generated by Django 2.2.13 on 2020-06-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0044_auto_20200616_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_module',
            field=models.IntegerField(blank=True, choices=[(30, 'ConfirmedWalletDeposit'), (31, 'ShetabDeposit'), (32, 'WithdrawRequest'), (33, 'InternalTransferDeposit'), (34, 'BankDeposit'), (41, 'TradeSellA'), (42, 'TradeSellB'), (43, 'TradeBuyA'), (44, 'TradeBuyB'), (45, 'TradeFeeA'), (46, 'TradeFeeB'), (51, 'ReverseTransaction'), (52, 'Credit'), (61, 'TransferSrc'), (62, 'TransferDst')], null=True),
        ),
        migrations.CreateModel(
            name='WalletCreditBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('credit_change', models.DecimalField(decimal_places=10, max_digits=25)),
                ('credit_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'اعتبار کاربر',
                'verbose_name_plural': 'اعتبار کاربر',
            },
        ),
    ]
