# Generated by Django 2.2.14 on 2020-07-04 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0045_auto_20200626_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
