# Generated by Django 2.2.14 on 2020-07-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0046_withdrawrequest_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdepositaddress',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
