# Generated by Django 2.2.14 on 2020-08-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('wallet', '0048_transaction_balance'), ('wallet', '0049_transaction_remove_is_balance_calculated'),
        ('wallet', '0049_auto_20200829_0049'),
    ]

    dependencies = [
        ('wallet', '0047_auto_20200724_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
