# Generated by Django 2.2.14 on 2020-08-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0047_auto_20200724_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_balance_calculated',
            field=models.BooleanField(default=False),
        )
    ]
