# Generated by Django 2.2.14 on 2020-08-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0048_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_balance_calculated',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        )
    ]
