# Generated by Django 2.2.14 on 2020-08-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0048_auto_20200808_0006'),
        ('wallet', '0048_transaction_balance_squashed_0049_transaction_remove_is_balance_calculated'),
    ]

    operations = [
    ]
