# Generated by Django 2.2.14 on 2020-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0049_merge_20200829_0110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'address'), ('tx_hash', 'tag')},
        ),
        migrations.RemoveField(
            model_name='confirmedwalletdeposit',
            name='shared_address',
        ),
        migrations.DeleteModel(
            name='SharedDepositAddress',
        ),
    ]
