# Generated by Django 2.2.14 on 2020-09-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0050_auto_20200829_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
