# Generated by Django 2.2.14 on 2020-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0051_auto_20200909_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Fake'), (10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (40, 'Electrum LTC'), (50, 'Parity'), (60, 'Ripple API'), (70, 'Tether(ERC20)'), (71, 'Tether(TRC20)'), (80, 'Electron Cash'), (90, 'BNB API'), (100, 'Vandar API'), (110, 'TRX Hot Wallet'), (120, 'XLM Hot Wallet'), (130, 'PMN Hot Wallet')]),
        ),
    ]
