# Generated by Django 2.2.16 on 2020-12-22 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0054_auto_20201125_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequestPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_limit', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')])),
                ('is_active', models.BooleanField(default=True)),
                ('effective_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_request_permits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw_request_permits', to=settings.AUTH_USER_MODEL)),
                ('withdraw_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_request_permits', to='wallet.WithdrawRequest')),
            ],
            options={
                'permissions': [('withdraw_request_permit_manage', 'مدیریت مجوز\u200cهای برداشت')],
            },
        ),
    ]
