# Generated by Django 2.2.17 on 2020-12-29 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0055_auto_20201229_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
