# Generated by Django 2.2.17 on 2020-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0056_auto_20201229_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Verified'), (3, 'Accepted'), (4, 'Sent'), (5, 'Done'), (6, 'Rejected'), (7, 'Processing'), (8, 'Canceled'), (9, 'Waiting'), (10, 'Manual Accepted')], db_index=True, default=1),
        ),
    ]
