# Generated by Django 2.2.17 on 2020-12-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0057_auto_20201229_1442'),
        ('wallet', '0055_auto_20201222_1804'),
    ]

    operations = [
    ]
