# Generated by Django 2.2.17 on 2021-01-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0058_merge_20201230_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='_wallet',
            field=models.ForeignKey(blank=True, db_column='wallet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Wallet'),
        ),
    ]
