# Generated by Django 2.2.17 on 2021-02-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0059_auto_20210104_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequestLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.IntegerField(choices=[(1, 'dailyCoin'), (2, 'dailyRial'), (3, 'dailySummation'), (4, 'monthlySummation'), (5, 'dailyCurrency'), (6, 'monthlyCurrency')])),
                ('limitation', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محدودیت برداشت کاربر',
                'verbose_name_plural': 'محدودیت برداشت کاربر',
            },
        ),
    ]
