# Generated by Django 2.2.17 on 2021-01-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0059_auto_20210104_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance_in_order',
        ),
    ]
