# Generated by Django 2.2.17 on 2021-02-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0060_auto_20210128_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مبلغ تراکنش'),
        ),
    ]
