# Generated by Django 2.2.18 on 2021-04-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0060_auto_20210227_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='rial_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='ارزش ریالی'),
        ),
    ]
