# Generated by Django 2.2.17 on 2021-02-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0061_auto_20210224_2320'),
        ('wallet', '0060_auto_20210227_2238'),
    ]

    operations = [
    ]
