# Generated by Django 2.2.19 on 2021-05-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0061_auto_20210427_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledepositaddress',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Standard'), (2, 'Segwit')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='walletdepositaddress',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Standard'), (2, 'Segwit')], default=1, null=True),
        ),
    ]
