# Generated by Django 2.2.20 on 2021-05-12 12:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0062_merge_20210228_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfitMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date_year', models.IntegerField(default=2021)),
                ('report_date_month', models.IntegerField(default=4)),
                ('total_buy_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('total_sell_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('total_sell_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سود و ضرر ماهانه کاربر',
                'verbose_name_plural': 'سود و ضرر ماهانه کاربر',
                'unique_together': {('report_date_year', 'report_date_month', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserProfitDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date', models.DateField(default=datetime.date(2021, 5, 11))),
                ('buy_amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('buy_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_cost', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('sell_profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('buy_average', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_wallet_current_balance', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user_wallet_submitted_total_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('even_rounded_price', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_currency_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_buy_current_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_balance_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_balance_profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('submitted_total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'سود و ضرر روزانه',
                'verbose_name_plural': 'سود و ضرر روزانه',
                'unique_together': {('report_date', 'wallet')},
            },
        ),
    ]
