# Generated by Django 2.2.19 on 2021-05-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0062_merge_20210228_0154'),
        ('wallet', '0062_auto_20210504_1923'),
    ]

    operations = [
    ]
