# Generated by Django 2.2.18 on 2021-05-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0062_auto_20210504_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
