# Generated by Django 2.2.17 on 2021-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0063_auto_20210510_1646'),
        ('wallet', '0060_auto_20210128_1750'),
    ]

    operations = [
    ]
