# Generated by Django 2.2.20 on 2021-05-29 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0063_auto_20210512_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofitmonthly',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofitdaily',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='userprofitmonthly',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofitmonthly',
            name='report_date_month',
        ),
        migrations.RemoveField(
            model_name='userprofitmonthly',
            name='report_date_year',
        ),
    ]
