# Generated by Django 2.2.17 on 2021-05-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0061_auto_20210224_2320'),
        ('wallet', '0064_merge_20210519_0302'),
    ]

    operations = [
    ]
