# Generated by Django 2.2.17 on 2021-05-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0063_merge_20210505_0509'),
        ('wallet', '0065_merge_20210528_0357'),
    ]

    operations = [
    ]
