# Generated by Django 2.2.23 on 2021-06-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0066_merge_20210529_0345'),
        ('wallet', '0064_auto_20210529_2008'),
    ]

    operations = [
    ]
