# Generated by Django 2.2.19 on 2021-06-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0067_merge_20210603_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticwithdraw',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Fake'), (10, 'Binance'), (20, 'Electrum'), (30, 'Geth'), (31, 'Geth(ERC20)'), (40, 'Electrum LTC'), (50, 'Parity'), (60, 'Ripple API'), (70, 'Tether(ERC20)'), (71, 'Tether(TRC20)'), (80, 'Electron Cash'), (90, 'BNB API'), (100, 'Vandar API'), (110, 'TRX Hot Wallet'), (120, 'XLM Hot Wallet'), (130, 'PMN Hot Wallet'), (140, 'DOGE Hot Wallet'), (150, 'ETC Hot Wallet'), (160, 'EOS Hot Wallet'), (170, 'BSC Hot Wallet'), (171, 'BSC Hot Wallet(BEP20)'), (180, 'DOT Hot Wallet')]),
        ),
        migrations.AlterUniqueTogether(
            name='walletdepositaddress',
            unique_together={('currency', 'address', 'network')},
        ),
    ]
