# Generated by Django 2.2.22 on 2021-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0067_merge_20210603_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequestlimit',
            name='limitation',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
