# Generated by Django 2.2.20 on 2021-06-28 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0069_auto_20210628_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotalmonthlyprofit',
            name='total_profit_percentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
            preserve_default=False,
        ),
    ]
