# Generated by Django 2.2.19 on 2021-07-09 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0070_auto_20210628_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehotwalletaddress',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemcoldaddress',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
