# Generated by Django 2.2.22 on 2021-07-03 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0070_auto_20210628_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
