# Generated by Django 2.2.23 on 2021-06-29 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20210621_0848'),
        ('wallet', '0071_auto_20210703_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDepositRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'جدید'), (1, 'تایید شده'), (2, 'رد شده')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='مقدار')),
                ('tx_hash', models.CharField(max_length=100, unique=True, verbose_name='هش تراکنش')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits_address', to='wallet.WalletDepositAddress', verbose_name='آدرس واریز')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_image', to='accounts.UploadedFile', verbose_name='اسکرین ولت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits_wallet', to='wallet.Wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'درخواست واریز دستی',
                'verbose_name_plural': 'درخواست واریز دستی',
            },
        ),
    ]
