# Generated by Django 2.2.17 on 2021-07-11 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0075_manualdepositrequest'),
    ]

    operations = [
    ]
