# Generated by Django 2.2.24 on 2021-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0068_auto_20210619_1411'),
        ('wallet', '0076_auto_20210711_0542'),
        ('wallet', '0071_auto_20210709_2046'),
    ]

    operations = [
    ]
