# Generated by Django 2.2.24 on 2021-07-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0077_merge_20210712_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='invoice',
            field=models.CharField(blank=True, max_length=4300, null=True),
        ),
    ]
