# Generated by Django 2.2.24 on 2021-07-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0078_auto_20210724_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotalmonthlyprofit',
            name='first_day_total_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterUniqueTogether(
            name='userprofitmonthly',
            unique_together={('report_date', 'user')},
        ),
    ]
