# Generated by Django 2.2.24 on 2021-07-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0079_auto_20210725_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='invoice',
            field=models.CharField(blank=True, max_length=4300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='confirmedwalletdeposit',
            unique_together={('tx_hash', 'tag'), ('tx_hash', 'invoice'), ('tx_hash', 'address')},
        ),
    ]
