# Generated by Django 2.2.24 on 2021-08-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
         ('wallet', '0080_auto_20210727_1602'),
    ]

    database_operations = [
        migrations.AlterModelTable('UserTotalDailyProfit', 'portfolio_usertotaldailyprofit'),
        migrations.AlterModelTable('UserTotalMonthlyProfit', 'portfolio_usertotalmonthlyprofit')
    ]

    state_operations = [
        migrations.DeleteModel('UserTotalDailyProfit'),
        migrations.DeleteModel('UserTotalMonthlyProfit')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
