# Generated by Django 2.2.24 on 2021-09-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0081_auto_20210825_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='target_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
