# Generated by Django 2.2.24 on 2021-09-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0082_auto_20210909_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledepositaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='availablehotwalletaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blacklistwalletaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='tx_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='systemcoldaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='walletdepositaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
