# Generated by Django 2.2.24 on 2021-10-31 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0083_auto_20210909_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
