# Generated by Django 2.2.24 on 2021-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0084_auto_20211031_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='dst_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس مقصد'),
        ),
    ]
