# Generated by Django 2.2.24 on 2021-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0084_auto_20211031_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
