# Generated by Django 2.2.24 on 2021-11-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0085_auto_20211103_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualdepositrequest',
            name='dst_address',
        ),
    ]
