# Generated by Django 2.2.24 on 2021-11-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0086_auto_20211107_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='dst_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits_destination_address', to='wallet.WalletDepositAddress', verbose_name='آدرس مقصد'),
        ),
    ]
