# Generated by Django 2.2.24 on 2021-11-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0087_auto_20211107_1307'),
        ('wallet', '0086_auto_20211106_1410'),
    ]

    operations = [
    ]
