# Generated by Django 2.2.24 on 2021-11-19 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0088_merge_20211107_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualdepositrequest',
            name='dst_address',
        ),
    ]
