# Generated by Django 2.2.20 on 2021-11-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0090_auto_20211120_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='SupportWithdrawLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ثبت')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('allocated_by', models.ForeignKey(on_delete=models.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_allocations', to='wallet.Label')),
            ],
        ),
        migrations.AddField(
            model_name='supportwithdrawlabel',
            name='withdraw_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_label', to='wallet.WithdrawRequest'),
        ),
    ]
