# Generated by Django 2.2.20 on 2021-12-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0091_auto_20211127_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportwithdrawlabel',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='supportwithdrawlabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='supportwithdrawlabel',
            name='withdraw_request',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='SupportWithdrawLabel',
        ),
    ]
