# Generated by Django 2.2.24 on 2021-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0092_auto_20211201_1319'),
        ('wallet', '0089_auto_20211119_1826'),
    ]

    operations = [
    ]
