# Generated by Django 2.2.26 on 2022-02-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0093_merge_20211212_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledepositaddress',
            name='salt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='walletdepositaddress',
            name='salt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
