# Generated by Django 2.2.24 on 2022-02-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0094_auto_20220204_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequestlimit',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
