# Generated by Django 2.2.26 on 2022-04-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0095_auto_20220226_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='rial_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='ارزش ریالی'),
        )
    ]
