# Generated by Django 2.2.26 on 2022-05-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0096_auto_20220410_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='rechecked',
            field=models.BooleanField(default=False),
        ),
    ]
