# Generated by Django 2.2.26 on 2022-06-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0097_auto_20220523_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='rechecked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
