# Generated by Django 2.2.26 on 2022-08-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0098_auto_20220627_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablehotwalletaddress',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
