# Generated by Django 2.2.26 on 2022-08-23 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0099_auto_20220822_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Spot'), (2, 'Margin')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency', 'type')},
        ),
    ]
