# Generated by Django 2.2.24 on 2022-09-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20220904_1346'),
        ('wallet', '0100_auto_20220823_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='dst_system_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.DepositSystemBankAccount'),
        ),
    ]
