# Generated by Django 2.2.28 on 2022-09-28 11:36

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0101_auto_20220904_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='source_addresses',
            field=JSONField(blank=True, null=True),
        ),
    ]
