# Generated by Django 2.2.24 on 2022-10-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0101_auto_20220904_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='anomaly_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
