# Generated by Django 2.2.28 on 2022-10-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0102_auto_20221001_1721'),
        ('wallet', '0102_auto_20220928_1506'),
    ]

    operations = [
    ]
