# Generated by Django 2.2.24 on 2022-10-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0103_merge_20221008_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='is_deposit',
            field=models.BooleanField(default=True, verbose_name='واریز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='is_withdraw',
            field=models.BooleanField(default=True, verbose_name='برداشت'),
            preserve_default=False,
        ),
    ]
