# Generated by Django 2.2.28 on 2023-01-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0104_auto_20221016_1353'),
    ]

    operations = [

        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt_id',
            field=models.CharField(max_length=25, verbose_name='شناسه رسید بانکی'),
        ),
        migrations.AlterUniqueTogether(
            name='bankdeposit',
            unique_together={('receipt_id', 'deposited_at')},
        ),
    ]
