# Generated by Django 2.2.24 on 2023-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0105_auto_20230124_1626'),
    ]

    operations = [

        migrations.AlterField(
            model_name='manualdepositrequest',
            name='tx_hash',
            field=models.CharField(max_length=200, verbose_name='هش تراکنش'),
        ),

        migrations.AddConstraint(
            model_name='manualdepositrequest',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status=2), fields=('tx_hash',), name='unique_tx_hash'),
        ),

    ]
