# Generated by Django 2.2.28 on 2023-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0106_auto_20230311_1440'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabledepositaddress',
            index=models.Index(condition=models.Q(currency__in=[14, 16, 17, 19, 31, 56, 112]), fields=['currency'], name='idx_tagged_currencies_address'),
        ),
    ]
