# Generated by Django 2.2.28 on 2023-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0107_auto_20230403_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
