# Generated by Django 2.2.28 on 2023-05-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0109_auto_20230510_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdepositaddress',
            name='priority',
        ),
    ]
