# Generated by Django 2.2.28 on 2023-06-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0110_auto_20230517_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofitmonthly',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofitmonthly',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfitDaily',
        ),
        migrations.DeleteModel(
            name='UserProfitMonthly',
        ),
    ]
