# Generated by Django 2.2.28 on 2023-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0110_auto_20230517_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='image',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.UploadedFile'
            ),
        ),
    ]
