# Generated by Django 2.2.28 on 2023-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0112_wallet_transaction_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionhistoryfile',
            name='unique_file_name',
        ),
        migrations.RemoveField(
            model_name='transactionhistoryfile',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='transactionhistoryfile',
            name='file_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='نام فایل'),
        ),
    ]
