# Generated by Django 2.2.28 on 2023-07-03 22:42
import hashlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0113_auto_20230627_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistoryfile',
            name='checksum',
            field=models.CharField(default=hashlib.new('md5').hexdigest, max_length=64, verbose_name='هش تراکنش ها'),
        ),
    ]
