# Generated by Django 2.2.28 on 2023-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0114_wallet_transaction_history_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistoryfile',
            name='checksum',
            field=models.CharField(max_length=64, verbose_name='هش تراکنش ها'),
        ),

    ]
