# Generated by Django 2.2.28 on 2023-08-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0115_auto_20230809_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='contract_address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='walletdepositaddress',
            name='contract_address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='contract_address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='walletdepositaddress',
            unique_together={('currency', 'address', 'network', 'contract_address')},
        ),
    ]
