# Generated by Django 2.2.28 on 2023-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0116_auto_20230811_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistoryfile',
            name='checksum',
        ),
        migrations.AddField(
            model_name='transactionhistoryfile',
            name='tx_count',
            field=models.IntegerField(default=0, verbose_name='تعداد تراکنش ها'),
        ),
        migrations.RemoveField(
            model_name='transactionhistoryfile',
            name='tp',
        ),
        migrations.AddField(
            model_name='transactionhistoryfile',
            name='tps',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نوع تراکنش'),
        ),
    ]
