# Generated by Django 2.2.28 on 2023-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0117_auto_20230926_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistoryfile',
            name='file_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='نام فایل'),
        ),
    ]
