# Generated by Django 2.2.28 on 2023-10-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0118_auto_20231021_1431'),
        ('wallet', '0112_auto_20230829_0736'),
    ]

    operations = [
    ]
