# Generated by Django 3.2.22 on 2023-11-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0119_merge_20231021_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistwalletaddress',
            name='priority',
            field=models.SmallIntegerField(
                choices=[(100, 'Low Risk'), (200, 'Medium Risk'), (300, 'High Risk')], default=100
            ),
        ),
    ]
