# Generated by Django 3.2.23 on 2023-11-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0119_merge_20231021_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBulkTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Done'), (3, 'Rejected')], default=1)),
                ('rejection_reason', models.CharField(blank=True, max_length=256)),
                ('src_wallet_type', models.SmallIntegerField(choices=[(1, 'Spot'), (2, 'Margin'), (3, 'Credit')])),
                ('dst_wallet_type', models.SmallIntegerField(choices=[(1, 'Spot'), (2, 'Margin'), (3, 'Credit')])),
                ('currency_amounts', JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='walletbulktransferrequest',
            name='transactions',
            field=models.ManyToManyField(to='wallet.Transaction'),
        ),
        migrations.AddField(
            model_name='walletbulktransferrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
