# Generated by Django 2.2.28 on 2023-12-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0120_auto_20231105_1542'),
        ('wallet', '0120_auto_20231122_1834'),
    ]

    operations = []
