# Generated by Django 3.2.23 on 2024-03-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0121_merge_20231211_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt_id',
            field=models.CharField(max_length=255, verbose_name='شناسه رسید بانکی'),
        ),
    ]
