# Generated by Django 3.2.23 on 2024-03-18 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0122_auto_20240310_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankdeposit',
            unique_together={('receipt_id', 'deposited_at', 'user')},
        ),
    ]
