# Generated by Django 3.2.23 on 2024-06-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0124_auto_20240608_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdeposittag',
            name='tag',
            field=models.IntegerField(verbose_name='تگ'),
        ),
        migrations.AlterUniqueTogether(
            name='walletdeposittag',
            unique_together={('currency', 'tag')},
        ),
    ]
