# Generated by Django 4.2.13 on 2024-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0125_auto_20240611_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='is_auto_validated',
            field=models.BooleanField(default=False, verbose_name='تایید خودکار؟'),
        ),
    ]
