# Generated by Django 4.2.13 on 2024-08-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0126_alter_manual_deposit_request'),
    ]
    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='requester_service',
            field=models.CharField(blank=True, choices=[('abc', 'ABC'), ('admin', 'ADMIN')], max_length=50, null=True),
        ),
    ]
