# Generated by Django 3.2.23 on 2024-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0127_alter_confirmedwalletdeposit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDepositTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.PositiveSmallIntegerField(choices=[(1, 'کسر کارمزد کاربر')], default=1)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
            ],
        ),
        migrations.AddField(
            model_name='manualdepositrequest',
            name='tagged_deposit_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits_address', to='wallet.availabledepositaddress', verbose_name='آدرس واریز تگ دار'),
        ),
        migrations.AddField(
            model_name='manualdepositrequest',
            name='fee',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True, verbose_name='مقدار کارمزد'),
        ),
        migrations.AddField(
            model_name='manualdeposittransaction',
            name='manual_deposit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_deposit_transactions', to='wallet.manualdepositrequest'),
        ),
        migrations.AddField(
            model_name='manualdeposittransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddConstraint(
            model_name='manualdeposittransaction',
            constraint=models.UniqueConstraint(fields=('manual_deposit_request', 'tp'), name='unique_manual_deposit_request_tp'),
        ),
    ]
