# Generated by Django 4.2.13 on 2024-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0128_auto_20240814_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='withdrawrequestpermit',
            name='amount_limit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance_blocked',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
