# Generated by Django 4.2.15 on 2024-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0129_auto_20240824_1257'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(
                condition=models.Q(('status', 1)), fields=['wallet_id', 'created_at'], name='idx_withdraw_news'
            ),
        ),
    ]
