# Generated by Django 4.2.14 on 2024-09-08 13:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0130_alter_confirmedwalletdeposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedwalletdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='manualdepositrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='manualdepositrequest',
            name='fee',
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='مقدار کارمزد'
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='مبلغ تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance_blocked',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=22),
        ),
        migrations.AlterField(
            model_name='withdrawrequestlimit',
            name='limitation',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='withdrawrequestpermit',
            name='amount_limit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
    ]
