# Generated by Django 4.2.13 on 2024-09-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0131_alter_confirmedwalletdeposit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='is_deposit_valid',
            field=models.BooleanField(default=False, verbose_name='صحت واریز'),
        ),
        migrations.AddField(
            model_name='manualdepositrequest',
            name='is_withdraw_valid',
            field=models.BooleanField(default=False, verbose_name='صحت برداشت'),
        ),
    ]
