# Generated by Django 4.2.16 on 2024-09-28 09:36

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0132_auto_20240915_1309'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blacklistwalletaddress',
            index=models.Index(
                django.db.models.functions.text.Upper('address'), name='idx_wallet_blacklist_address_upper'
            ),
        ),
        migrations.RenameIndex(  # to be compatible with production db
            model_name='blacklistwalletaddress',
            new_name='idx_wallet_blacklist_address',
            old_name='idx_wallet_blacklist_address_upper',
        ),
    ]
