# Generated by Django 3.2.23 on 2024-10-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0133_alter_confirmedwalletdeposit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualdepositrequest',
            name='tag',
        ),
        migrations.AddField(
            model_name='manualdepositrequest',
            name='wallet_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_deposits', to='wallet.walletdeposittag'),
        ),
        migrations.RenameField(
            model_name='manualdepositrequest',
            old_name='wallet_tag',
            new_name='tag',
        ),
    ]
