# Generated by Django 4.2.16 on 2024-10-26 15:15

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('wallet', '0134_auto_20241007_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, choices=[('abc', 'ABC'), ('admin', 'ADMIN')], null=True),
        ),
        AddIndexConcurrently(
            model_name='transaction',
            index=models.Index(
                condition=models.Q(('service__isnull', False)),
                fields=['service', 'ref_module', 'ref_id'],
                name='wallet_transaction_idx_srv_ref',
            ),
        ),
    ]
