# Generated by Django 4.2.16 on 2024-11-17 20:31

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('wallet', '0135_add_service_to_transaction_'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='transaction',
            index=models.Index(fields=['created_at', 'wallet_id'], name='wallet_tran_created_2e5ede_idx'),
        ),
        migrations.RenameIndex(  # to be compatible with production db
            model_name='transaction',
            new_name='wallet_transaction_created_atـwallet_idx',
            old_name='wallet_tran_created_2e5ede_idx',
        ),
    ]
