# Generated by Django 4.2.16 on 2024-12-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0136_auto_20241118_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedwalletdeposit',
            name='tx_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
