# Generated by Django 3.2.23 on 2025-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0137_add_tx_datetime_field_to_confirmedwalletdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdepositrequest',
            name='created_by_chatbot',
            field=models.BooleanField(default=None, verbose_name='ایجاد شده توسط چت\u200cبات', blank=True, null=True),
        ),
    ]
