# Generated by Django 4.2.13 on 2025-01-20 06:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0138_auto_20250111_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequestRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitation', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'Stella'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, '1M_BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'MultiversX'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetworkCrystalv2'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFIMoney'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis'), (122, 'Aptos'), (123, 'Flare'), (124, 'Loopring'), (125, 'EthereumNameService'), (126, 'Livepeer'), (127, 'Golem'), (128, 'API3'), (129, 'aelf'), (130, 'DAOMaker'), (131, 'Civic'), (132, 'Numeraire'), (133, 'Storj'), (134, 'ConvexFinance'), (135, 'Status'), (136, 'SmoothLovePotion'), (137, '1M_APENFT'), (138, 'Serum'), (139, 'Aragon'), (140, 'Illuvium'), (141, 'Threshold'), (142, 'InternetComputer'), (143, 'Helium'), (144, '1B_BabyDoge'), (145, 'Toncoin'), (146, '100K_Floki'), (147, '0x'), (148, 'ImmutableX'), (149, 'MeasurableDataToken'), (150, 'Blur'), (151, 'Magic'), (152, 'Arbitrum'), (153, 'RocketPool'), (154, 'PAXGold'), (155, 'GMX'), (156, 'BitDAO'), (157, 'WrappedEther'), (158, 'SSVNetwork'), (159, 'Worldcoin'), (160, 'OMGNetwork'), (161, 'AdventureGold'), (162, 'RadiantCapital'), (163, 'JUST'), (164, 'Render'), (165, 'Biconomy'), (166, 'WOONetwork'), (167, 'SKALE'), (168, 'Fetch.AI'), (169, 'Galxe'), (170, 'SingularityNET'), (171, 'WAX'), (172, 'Tellor'), (173, 'ReserveRights'), (174, 'YieldGuildGames'), (175, 'BounceToken'), (176, 'Memecoin'), (177, 'UMA'), (178, 'BigTime'), (179, 'SPACEID'), (180, 'Orbs'), (181, 'PerpetualProtocol'), (182, 'Bancor'), (183, 'GodsUnchained'), (184, 'LooksRare'), (185, 'BadgerDAO'), (186, 'Ren'), (187, 'Verasity'), (188, 'Frontier'), (189, 'Ether.fi'), (190, 'Notcoin'), (191, '1M_Pepe'), (192, 'MANTRA'), (193, 'Aevo'), (194, 'Wormhole'), (195, 'LayerZero'), (196, 'Gravity'), (197, 'Ondo'), (198, 'DOGS'), (199, 'Catizen'), (200, 'HamsterKombat'), (201, 'TetherGold'), (202, 'EigenLayer'), (203, 'JasmyCoin'), (204, 'Ethena'), (205, 'Pendle'), (206, 'BinaryX'), (207, 'SuperVerse'), (208, 'Holo'), (209, 'OpenCampus'), (210, 'Safe'), (211, 'FraxShare'), (212, 'Wisdomise'), (213, 'TrustWalletToken'), (214, 'XEmpire'), (215, 'BananaGun'), (216, 'Major'), (217, 'Movement'), (218, 'Starknet'), (219, 'MetisDAO'), (220, 'Injective'), (221, 'Turbo'), (222, 'DeXe'), (223, 'PolyhedraNetwork'), (224, 'Aethir'), (225, 'CookieDAO'), (226, 'ChainGPT')])),
                ('network', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'محدودیت برداشت کلی',
                'verbose_name_plural': 'محدودیت برداشت کلی',
            },
        ),
    ]
