# Generated by Django 4.2.19 on 2025-04-05 08:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0139_withdrawrequestrestriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequestrestriction',
            name='tp',
            field=models.IntegerField(
                choices=[
                    (1, 'dailyCoin'),
                    (2, 'dailyRial'),
                    (3, 'dailySummation'),
                    (4, 'monthlySummation'),
                    (5, 'dailyCurrency'),
                    (6, 'monthlyCurrency'),
                ],
            ),
        ),
    ]
