# Generated by Django 2.1.4 on 2018-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_nobitex2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binancetrade',
            options={'verbose_name': 'معامله بایننس', 'verbose_name_plural': 'معامله بایننس'},
        ),
        migrations.AlterModelOptions(
            name='krakentrade',
            options={'verbose_name': 'معامله کراکن', 'verbose_name_plural': 'معامله کراکن'},
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='target_exchange',
            field=models.IntegerField(choices=[(0, 'Nobitex'), (1, 'Kraken'), (2, 'Binance')], default=0),
        ),
    ]
