# Generated by Django 2.1.4 on 2019-01-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181229_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='binancetrade',
            name='execution_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='krakentrade',
            name='execution_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
