# Generated by Django 2.1.5 on 2019-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190115_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatching',
            name='usdt_usd_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
