# Generated by Django 2.1.7 on 2019-03-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_ordermatching_usdt_usd_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='trade_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
