# Generated by Django 2.1.8 on 2019-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20190312_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancetrade',
            name='fills',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
