# Generated by Django 2.1.10 on 2019-07-30 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0007_auto_20190522_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralfee',
            name='referred_user',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
