# Generated by Django 2.1.11 on 2019-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20190731_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='matched_total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='ارزش مچ شده'),
        ),
        migrations.AlterField(
            model_name='market',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='market',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='ارزش دلار'),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='usdt_usd_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='نرخ تتر به دلار'),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')]),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (21, 'Cardano')]),
        ),
    ]
