# Generated by Django 2.1.11 on 2019-09-26 11:37

from decimal import Decimal

from django.db import migrations
from django.db.models import F, Q, Sum


def set_order_matched_total_price(apps, schema_editor):
    Order = apps.get_model('market', 'Order')
    OrderMatching = apps.get_model('market', 'OrderMatching')
    for order in Order.objects.filter(matched_amount__gt=Decimal('0')):
        matching_q = Q(sell_order=order) if order.order_type == 1 else Q(buy_order=order)
        matched_total_price = OrderMatching.objects.filter(matching_q).aggregate(
            sum=Sum(F('matched_amount') * F('matched_price'))
        )['sum'] or Decimal('0')
        order.matched_total_price = matched_total_price
        order.save(update_fields=['matched_total_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190926_1507'),
    ]

    operations = [
        migrations.RunPython(set_order_matched_total_price),
    ]
