# Generated by Django 2.1.15 on 2020-03-20 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0012_auto_20191207_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatching',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Market'),
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='market',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='market',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')]),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')]),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos')]),
        ),
    ]
