# Generated by Django 2.1.15 on 2020-03-20 00:28

from django.db import migrations


def fill_new_fields(apps, schema_editor):
    Market = apps.get_model('market', 'Market')
    OrderMatching = apps.get_model('market', 'OrderMatching')
    markets = Market.objects.all()
    trades = OrderMatching.objects.filter(market__isnull=True).select_related('sell_order', 'buy_order').order_by('created_at')
    for trade in trades:
        if trade.market:
            continue
        market = None
        for m in markets:
            if m.src_currency == trade.sell_order.src_currency and m.dst_currency == trade.sell_order.dst_currency:
                market = m
        if not market:
            print('Invalid market for OrderMatching#{}'.format(trade.pk))
            continue
        trade.market = market
        trade.buyer_id = trade.buy_order.user_id
        trade.seller_id = trade.sell_order.user_id
        trade.save(update_fields=['market', 'buyer_id', 'seller_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0013_auto_20200320_0341'),
    ]
    operations = [
        migrations.RunPython(fill_new_fields),
    ]
