# Generated by Django 2.1.15 on 2020-04-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0014_auto_20200320_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConnectionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('exchange', models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex']])),
                ('api_key', models.CharField(max_length=1000)),
                ('api_secret', models.CharField(max_length=1000)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کانفیگ اتصال به بایننس',
                'verbose_name_plural': 'کانفیگ اتصال به بایننس',
            },
        ),
        migrations.RemoveField(
            model_name='krakentrade',
            name='matching',
        ),
        migrations.RemoveField(
            model_name='krakentradelog',
            name='kraken_trade',
        ),
        migrations.RemoveField(
            model_name='krakentradelog',
            name='matching',
        ),
        migrations.AddField(
            model_name='binancetrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binancetrade',
            name='exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex']], default=2),
        ),
        migrations.AddField(
            model_name='binancetrade',
            name='should_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binancetrade',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='target_exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex']], default=0),
        ),
        migrations.AddField(
            model_name='binancetrade',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.ExchangeConnectionConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='binancetrade',
            unique_together={('matching', 'should_sell')},
        ),
        migrations.DeleteModel(
            name='KrakenTrade',
        ),
        migrations.DeleteModel(
            name='KrakenTradeLog',
        ),
    ]
