# Generated by Django 2.2.13 on 2020-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20200420_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradestatus',
            name='month_trades_total_trader',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='مجموع معاملات پلن تریدر'),
        ),
        migrations.AlterField(
            model_name='binancetrade',
            name='exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures']], default=2),
        ),
        migrations.AlterField(
            model_name='exchangeconnectionconfig',
            name='exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures']]),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='target_exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures']], default=0),
        ),
    ]
