# Generated by Django 2.2.13 on 2020-06-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200627_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='binancetrade',
            name='merged_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_trades', to='market.BinanceTrade'),
        ),
        migrations.AlterField(
            model_name='binancetrade',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Failed'), (2, 'Done'), (3, 'Canceled'), (4, 'Check'), (5, 'Merged'), (10, 'waiting')], default=0),
        ),
    ]
