# Generated by Django 2.2.14 on 2020-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200630_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='param1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='پارامتر یک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='execution_type',
            field=models.IntegerField(choices=[(1, 'Limit'), (2, 'Market'), (11, 'StopLimit'), (12, 'StopMarket')], default=1, verbose_name='دستور'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Done'), (3, 'Canceled'), (4, 'Inactive')], db_index=True, default=0, verbose_name='وضعیت'),
        ),
    ]
