# Generated by Django 2.2.14 on 2020-08-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0018_auto_20200718_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManualTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Sell'), (2, 'Buy')], verbose_name='نوع تراکنش')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='ارزش')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='تاریخ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش دستی کاربر',
                'verbose_name_plural': 'تراکنش\u200cهای دستی کاربر',
            },
        ),
    ]
