# Generated by Django 2.2.14 on 2020-08-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_usermanualtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='matched_total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ارزش مچ شده'),
        ),
    ]
