# Generated by Django 2.2.14 on 2020-08-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20200828_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancetrade',
            name='matching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.OrderMatching'),
        ),
    ]
