# Generated by Django 2.2.17 on 2020-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20200828_1942'),
    ]

    operations = [
    ]
