# Generated by Django 2.2.14 on 2020-09-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20200926_1505'),
        ('market', '0021_auto_20200828_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralfee',
            name='referral_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_fees', to='accounts.ReferralProgram'),
        ),
    ]
