# Generated by Django 2.2.17 on 2020-11-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20200926_1505'),
        ('market', '0022_auto_20201125_1320'),
    ]

    operations = [
    ]
