# Generated by Django 2.2.17 on 2021-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_merge_20201130_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binancetrade',
            name='exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures'], [6, 'BinanceMargin']], default=2),
        ),
        migrations.AlterField(
            model_name='exchangeconnectionconfig',
            name='exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures'], [6, 'BinanceMargin']]),
        ),
        migrations.AlterField(
            model_name='market',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='market',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='close_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')]),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='high_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='low_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='open_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='param1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True, verbose_name='پارامتر یک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='matched_price',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='target_exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures'], [6, 'BinanceMargin']], default=0),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')]),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot')]),
        ),
        migrations.AlterField(
            model_name='usermanualtransaction',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='ارزش'),
        ),
        migrations.AlterField(
            model_name='usertradestatus',
            name='month_trades_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usertradestatus',
            name='month_trades_total_trader',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='مجموع معاملات پلن تریدر'),
        ),
    ]
