# Generated by Django 2.2.20 on 2021-05-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20210103_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermatching',
            options={'permissions': [('view_total_commission_report', 'نمایش گزارش کارمزد کل')]},
        )
    ]
