# Generated by Django 2.2.24 on 2021-06-30 12:56

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20210524_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesAccountReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('report_data', JSONField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ExchangeConnectionConfig')),
            ],
            options={
                'verbose_name': 'گزارش حساب\u200cهای فیوچرز بایننس',
                'verbose_name_plural': 'گزارش حساب\u200cهای فیوچرز بایننس',
                'permissions': [('futures_report', 'گزارش حساب\u200cهای فیوچرز')],
            },
        ),
    ]
