# Generated by Django 2.2.24 on 2021-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20210630_1726'),
        ('market', '0025_ordercancellation'),
    ]

    operations = [
    ]
