# Generated by Django 2.2.24 on 2021-10-28 22:05

from django.db import migrations, models

from exchange.base.fields import RoundedDecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_auto_20210712_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatching',
            name='buy_fee_amount',
            field=RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.src_currency', max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='sell_fee_amount',
            field=RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.dst_currency', max_digits=20, null=True
            ),
        ),
    ]
