# Generated by Django 2.2.26 on 2022-03-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_auto_20220203_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.Order', verbose_name='زوج سفارش'),
        ),
    ]
