# Generated by Django 2.2.26 on 2022-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_auto_20220328_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconnectionconfig',
            name='api_passphrase',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
