# Generated by Django 2.2.26 on 2022-06-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20220409_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.IntegerField(choices=[(1, 'Minute'), (2, 'Hour'), (3, 'Day')])),
                ('start_time', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('close_price', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('low_price', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('high_price', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('trade_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('trade_total', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('price_lower_bound', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('price_upper_bound', models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
            ],
            options={
                'unique_together': {('market', 'start_time', 'resolution')},
            },
        ),
    ]
