# Generated by Django 2.2.26 on 2022-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_marketcandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Spot'), (2, 'Margin')], default=1, verbose_name='نوع معامله'),
        ),
    ]
