# Generated by Django 2.2.28 on 2022-09-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_order_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradestatus',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
