# Generated by Django 2.2.28 on 2022-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_auto_20220904_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatching',
            name='rial_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='ارزش ریالی'),
        ),
    ]
