# Generated by Django 2.2.26 on 2022-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_auto_20220927_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolinfo',
            name='has_no_volume',
        ),
        migrations.AddField(
            model_name='symbolinfo',
            name='visible_plots_set',
            field=models.CharField(default='ohlcv', max_length=5),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='has_daily',
            field=models.BooleanField(default=True),
        ),
    ]
