# Generated by Django 2.2.26 on 2022-12-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0037_auto_20221130_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolinfo',
            name='visible_plots_set',
        ),
        migrations.AddField(
            model_name='symbolinfo',
            name='has_no_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='symbolinfo',
            name='has_daily',
            field=models.BooleanField(default=False),
        ),
    ]
