# Generated by Django 2.2.28 on 2022-12-11 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0038_auto_20221207_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketsPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_markets', JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
