# Generated by Django 2.2.28 on 2022-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_auto_20221211_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketspreferences',
            name='favorite_markets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
