# Generated by Django 2.2.28 on 2023-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('market', '0041_client_order_id'), ('market', '0042_auto_20230108_1904'), ('market', '0043_auto_20230121_1244')]

    dependencies = [
        ('market', '0040_auto_20221213_0842'),
    ]

    operations = [
    ]
