# Generated by Django 2.2.26 on 2023-02-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_client_order_id_squashed_0043_auto_20230121_1244'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('order_type', 1), ('status', 1), models.Q(_negated=True, execution_type__in=(2, 12))), fields=['src_currency', 'dst_currency', 'price'], name='orderbook_asks'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('order_type', 2), ('status', 1), models.Q(_negated=True, execution_type__in=(2, 12))), fields=['src_currency', 'dst_currency', '-price'], name='orderbook_bids'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('execution_type__in', (2, 12)), ('status', 1)), fields=['src_currency', 'dst_currency'], name='market_execution_orders'),
        ),
    ]
