# Generated by Django 2.2.28 on 2023-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0042_auto_20230220_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شناسه سفارش کاربر'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=[0, 1, 4]), fields=('user', 'client_order_id'),
                name='unique_user_client_order_id',
            ),
        ),
    ]
