# Generated by Django 2.2.28 on 2023-07-26 06:21

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def transfer_margin_data(apps, schema_editor):
    Market = apps.get_model('market', 'Market')
    LiquidityPool = apps.get_model('pool', 'LiquidityPool')

    Market.objects.filter(
        src_currency__in=LiquidityPool.objects.filter(is_active=True).values_list('currency', flat=True)
    ).update(
        allow_margin=True,
        max_leverage=Subquery(
            LiquidityPool.objects.filter(currency=OuterRef('src_currency')).values('max_leverage')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_auto_20230621_1206'),
        ('pool', '0018_liquiditypool_max_leverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='pending_matchings',
        ),
        migrations.AddField(
            model_name='market',
            name='allow_margin',
            field=models.BooleanField(default=False, verbose_name='معامله تعهدی مجاز است؟'),
        ),
        migrations.AddField(
            model_name='market',
            name='max_leverage',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='اهرم بیشینه'),
        ),
        migrations.RunPython(code=transfer_margin_data, reverse_code=migrations.RunPython.noop),
    ]
