# Generated by Django 2.2.28 on 2023-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_auto_20230726_0951'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                condition=models.Q(('execution_type__in', (11, 12)), ('status', 4)),
                fields=['src_currency', 'dst_currency', 'order_type', 'param1'],
                name='inactive_stop_execution_orders',
            ),
        ),
    ]
