# Generated by Django 2.2.28 on 2023-10-09 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0045_auto_20230918_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binancetradelog',
            name='binance_trade',
        ),
        migrations.RemoveField(
            model_name='binancetradelog',
            name='matching',
        ),
        migrations.DeleteModel(
            name='BinanceTrade',
        ),
        migrations.DeleteModel(
            name='BinanceTradeLog',
        ),
    ]
