# Generated by Django 2.2.28 on 2023-10-09 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0046_auto_20231009_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeConnectionConfig',
        ),
    ]
