# Generated by Django 3.2.25 on 2024-03-08 20:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0047_auto_20231009_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermatching',
            name='dollar_rate',
        ),
        migrations.RemoveField(
            model_name='ordermatching',
            name='target_exchange',
        ),
        migrations.RemoveField(
            model_name='ordermatching',
            name='usdt_usd_rate',
        ),
    ]
