# Generated by Django 2.2.28 on 2024-03-22 10:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_auto_20240309_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCancellation',
        ),
    ]
