# Generated by Django 4.2.13 on 2024-08-24 09:17

from django.db import migrations, models

import exchange.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_auto_20240322_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='trade_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار ارز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='matched_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='مقدار مچ شده'),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='buy_fee_amount',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.src_currency', max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='matched_amount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='sell_fee_amount',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.dst_currency', max_digits=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name='referralfee',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='usermanualtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25, verbose_name='مقدار'),
        ),
    ]
