# Generated by Django 4.2.15 on 2024-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_auto_20240824_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcandle',
            name='trade_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
    ]
