# Generated by Django 4.2.14 on 2024-09-08 13:33

from decimal import Decimal

from django.db import migrations, models

import exchange.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_alter_market_dst_currency_alter_market_src_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcandle',
            name='close_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='high_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='low_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='open_price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='price_lower_bound',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='price_upper_bound',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='trade_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='trade_total',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='مقدار ارز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='matched_amount',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=22, verbose_name='مقدار مچ شده'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='matched_total_price',
            field=models.DecimalField(
                decimal_places=10, default=Decimal('0'), max_digits=22, verbose_name='ارزش مچ شده'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='param1',
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='پارامتر یک'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=22, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='buy_fee_amount',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.src_currency', max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='matched_amount',
            field=models.DecimalField(decimal_places=10, max_digits=22),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='matched_price',
            field=models.DecimalField(decimal_places=10, max_digits=22),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='rial_value',
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='ارزش ریالی'
            ),
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='sell_fee_amount',
            field=exchange.base.fields.RoundedDecimalField(
                blank=True, decimal_places=10, help_text='market.dst_currency', max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name='referralfee',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='usertradestatus',
            name='month_trades_total',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28),
        ),
    ]
