# Generated by Django 4.2.14 on 2024-09-28 11:59
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_alter_market_dst_currency_alter_market_src_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_id',
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='_pair',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.order', to_field='_id'),
        ),
        migrations.RunSQL(
            sql='CREATE FUNCTION sync_market_order_insert() RETURNS TRIGGER AS '
                '$$BEGIN NEW._id := NEW.id; NEW._pair_id := NEW.pair_id;  RETURN NEW; END$$ LANGUAGE plpgsql;',
            reverse_sql='DROP FUNCTION sync_market_order_insert();',
        ),
        migrations.RunSQL(
            sql='CREATE FUNCTION sync_market_order_update() RETURNS TRIGGER AS '
                '$$BEGIN IF NEW._id IS NOT NULL THEN NEW._pair_id := NEW.pair_id; END IF; RETURN NEW; END$$ '
                'LANGUAGE plpgsql;',
            reverse_sql='DROP FUNCTION sync_market_order_update();',
        ),
        migrations.RunSQL(
            sql='CREATE TRIGGER sync_market_order_insert_trigger BEFORE INSERT ON market_order '
                'FOR EACH ROW EXECUTE FUNCTION sync_market_order_insert();',
            reverse_sql='DROP TRIGGER sync_market_order_insert_trigger ON market_order;',
        ),
        migrations.RunSQL(
            sql='CREATE TRIGGER sync_market_order_update_trigger BEFORE UPDATE ON market_order '
                'FOR EACH ROW EXECUTE FUNCTION sync_market_order_update();',
            reverse_sql='DROP TRIGGER sync_market_order_update_trigger ON market_order;',
        ),
    ]
