# Generated by Django 4.2.14 on 2024-09-28 11:59
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0053_order__id_order__pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermatching',
            name='_buy_order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
        ),
        migrations.AddField(
            model_name='ordermatching',
            name='_sell_order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
        ),
        migrations.RunSQL(
            sql='CREATE FUNCTION sync_market_ordermatching() RETURNS TRIGGER AS '
                '$$BEGIN NEW._buy_order_id := NEW.buy_order_id; '
                'NEW._sell_order_id := NEW.sell_order_id; RETURN NEW; END$$ LANGUAGE plpgsql;',
            reverse_sql='DROP FUNCTION sync_market_ordermatching();',
        ),
        migrations.RunSQL(
            sql='CREATE TRIGGER sync_market_ordermatching_trigger BEFORE INSERT ON market_ordermatching '
                'FOR EACH ROW EXECUTE FUNCTION sync_market_ordermatching();',
            reverse_sql='DROP TRIGGER sync_market_ordermatching_trigger ON market_ordermatching;',
        ),
    ]
