# Generated by Django 4.2.14 on 2024-10-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_ordermatching__buy_order_ordermatching__sell_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='_pair',
                    field=models.OneToOneField(db_constraint=False, to_field='_id', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.Order', verbose_name='زوج سفارش'),
                ),
                migrations.AlterField(
                    model_name='ordermatching',
                    name='_buy_order',
                    field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
                ),
                migrations.AlterField(
                    model_name='ordermatching',
                    name='_sell_order',
                    field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pair',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='_pair',
            new_name='pair',
        ),
        migrations.RemoveField(
            model_name='ordermatching',
            name='buy_order',
        ),
        migrations.RenameField(
            model_name='ordermatching',
            old_name='_buy_order',
            new_name='buy_order',
        ),
        migrations.RemoveField(
            model_name='ordermatching',
            name='sell_order',
        ),
        migrations.RenameField(
            model_name='ordermatching',
            old_name='_sell_order',
            new_name='sell_order',
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='buy_order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermatching',
            name='sell_order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order', to_field='_id'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='pair',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.Order', verbose_name='زوج سفارش'),
                ),
                migrations.AlterField(
                    model_name='ordermatching',
                    name='buy_order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order'),
                ),
                migrations.AlterField(
                    model_name='ordermatching',
                    name='sell_order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.order'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE OR REPLACE FUNCTION sync_market_order_insert() RETURNS TRIGGER AS '
                '$$BEGIN NEW._id := NEW.id; RETURN NEW; END$$ LANGUAGE plpgsql;',
        ),
        migrations.RunSQL(
            sql='DROP TRIGGER sync_market_order_update_trigger ON market_order;',
        ),
        migrations.RunSQL(
            sql='DROP FUNCTION sync_market_order_update();',
        ),
        migrations.RunSQL(
            sql='DROP TRIGGER sync_market_ordermatching_trigger ON market_ordermatching;',
        ),
        migrations.RunSQL(
            sql='DROP FUNCTION sync_market_ordermatching();',
        ),
    ]
