# Generated by Django 4.2.14 on 2024-10-05 07:08
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('market', '0055_remove_order__pair_remove_ordermatching__buy_order_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX CONCURRENTLY market_order_pk ON "market_order" ("_id");',
            reverse_sql='DROP INDEX market_order_pk;'
        ),
    ]

