# Generated by Django 4.2.14 on 2024-10-05 07:08
from unittest.mock import patch

from django.db import migrations, models



class AlterFieldCreatePkUsingIndex(migrations.AlterField):
    sql_create_pk = "ALTER TABLE %(table)s ADD CONSTRAINT %(name)s PRIMARY KEY USING INDEX {using_index}"

    def __init__(self, model_name, name, field, pk_using_index):
        self.pk_using_index = pk_using_index
        super().__init__(model_name, name, field)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        with patch.object(schema_editor, 'sql_create_pk', self.sql_create_pk.format(using_index=self.pk_using_index)):
            super().database_forwards(app_label, schema_editor, from_state, to_state)



class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_add_order__id_index_concurrently'),
        ('asset_backed_credit', '0038_alter_assettodebtmargincall_orders_and_more'),
        ('margin', '0019_remove_positionorder__order_and_more'),
        ('pool', '0022_alter_poolprofit_orders'),
        ('recovery', '0017_alter_recoveryrequest_block_order_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE TEMPORARY TABLE market_order_id_seq_last_val AS SELECT NEXTVAL(\'market_order_id_seq\') + 100;',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # To keep unique index, make django forget about it
                migrations.AlterField(
                    model_name='order',
                    name='_id',
                    field=models.BigIntegerField(editable=False),
                ),
            ]
        ),
        migrations.RenameField(
            model_name='order',
            old_name='_id',
            new_name='id',
        ),
        AlterFieldCreatePkUsingIndex(
            model_name='order',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
            pk_using_index='market_order_pk',
        ),
        migrations.RunSQL(
            sql='SELECT setval(\'market_order_id_seq\', (SELECT * FROM "market_order_id_seq_last_val"));',
        ),
        migrations.RunSQL(
            sql='DROP TRIGGER sync_market_order_insert_trigger ON market_order;',
        ),
        migrations.RunSQL(
            sql='DROP FUNCTION sync_market_order_insert();',
        ),
    ]

