# Generated by Django 4.2 on 2025-02-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_remove_order_id_alter_order__id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolinfo',
            name='daily_multipliers',
            field=models.CharField(default='["1", "2", "3"]', max_length=255),
        ),
    ]
