# Generated by Django 4.2.3 on 2023-07-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={},
        ),
    ]
