# Generated by Django 4.2.3 on 2023-11-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_blockedjwt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedJWT',
        ),
    ]
