# Generated by Django 2.2.28 on 2022-11-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0104_auto_20221016_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'PGala2020')])),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('redeem_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Allowed'), (2, 'Confirmed'), (3, 'Done'), (4, 'Rejected')], default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('dst_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
                ('src_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست بازخرید',
                'verbose_name_plural': 'درخواست بازخرید',
            },
        ),
    ]
