# Generated by Django 2.2.28 on 2022-11-16 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redeemrequest',
            unique_together={('plan', 'user')},
        ),
    ]
