# Generated by Django 2.2.28 on 2022-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0002_auto_20221117_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemrequest',
            name='redeem_value',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
