# Generated by Django 2.2.28 on 2022-11-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0003_auto_20221117_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemrequest',
            name='has_sana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redeemrequest',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
