# Generated by Django 2.2.28 on 2023-05-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.base.calendar


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0109_auto_20230510_1107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('maximum_withdrawal_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=2)),
                ('credit_limit_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('credit_limit_in_usdt', models.DecimalField(decimal_places=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.SmallIntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Matic'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'MyNeighborAlice'), (52, 'AlphaFinanceLab'), (53, 'Ankr'), (54, 'ARPAChain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'BasicAttentionToken'), (63, 'BellaProtocol'), (64, 'Bluzelle'), (65, '1M_BitTorrent'), (66, 'Coin98'), (67, 'CelerNetwork'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'MultiversX'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'MaskNetwork'), (83, 'Maker'), (84, 'NEARProtocol'), (85, 'OceanProtocol'), (86, 'Ontology'), (87, 'ReefFinance'), (88, 'SafePal'), (89, 'SynthetixNetworkToken'), (90, 'Sushi'), (91, 'Swipe'), (92, 'AlienWorlds'), (93, 'UnifiProtocolDAO'), (94, 'yearn.finance'), (95, 'DFIMoney'), (96, 'Zilliqa'), (97, 'Mana'), (98, 'Sand'), (99, 'ApeCoin'), (100, 'Harmony'), (101, 'WrappedBitcoin'), (102, 'USDCoin'), (103, 'Algorand'), (104, 'Terra'), (105, 'Klaytn'), (106, 'STEPN'), (107, 'Chiliz'), (108, 'VeChain'), (109, 'Quant'), (110, 'BUSD'), (111, 'Flow'), (112, 'HederaHashgraph'), (113, 'PeggedGala'), (114, 'GalaErc20'), (115, 'EnjinCoin'), (116, 'Optimism'), (117, 'CurveDAO'), (118, 'PancakeSwap'), (119, 'LidoDAO'), (120, 'dYdX'), (121, 'Gnosis'), (122, 'Aptos'), (123, 'Flare'), (124, 'Loopring'), (125, 'EthereumNameService'), (126, 'Livepeer'), (127, 'Golem'), (128, 'API3'), (129, 'aelf'), (130, 'DAOMaker'), (131, 'Civic'), (132, 'Numeraire'), (133, 'Storj'), (134, 'ConvexFinance'), (135, 'Status'), (136, 'SmoothLovePotion'), (137, '1M_APENFT'), (138, 'Serum'), (139, 'Aragon'), (140, 'Illuvium'), (141, 'Threshold'), (142, 'InternetComputer'), (143, 'Helium'), (144, '1B_BabyDoge'), (145, 'Toncoin'), (146, '100K_Floki'), (147, '0x'), (148, 'ImmutableX'), (149, 'MeasurableDataToken'), (150, 'Blur'), (151, 'Magic')])),
                ('created_at', models.DateTimeField(default=exchange.base.calendar.ir_now)),
                ('tp', models.SmallIntegerField(choices=[(10, 'lend'), (20, 'repay')])),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.CreditPlan')),
                ('system_wallet_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
                ('user_wallet_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.Transaction')),
            ],
        ),
    ]
