FARABOOM_ERROR_CODES = {
    '002': 'ارز مبدا مقصد یکسان نیست/کد ارز مورد نظر در سیستم تعریف نشده.',
    '003': 'موجودی سپرده کافی نیست.',
    '004': 'سپرده متعلق به کاربر نیست/عدم امکان دسترسی به سپرده/عدم وجود حق برداشت/برداشت امکان پذیر نیست.',
    '027': 'مبلغ ورودی نامعتبر است.',
    '032': 'شماره سپرده نامعتبر است.',
    '071': 'ورودی ها صحیح نیستند.',
    '133': 'شناسه مشتری تکراری است.',
    '1028': 'کد ملی نامعتبر است.',
    '2000': 'خطای داخلی پروایدر',
    '2001': 'خطای سرور',
    '2002': 'شناسه مورد نظر یافت نشد/نامعتبر است.',
    '2006': 'قرارداد پیمان منقضی شده است.',
    '2008': 'تاریخ نامعتبر است.',
    '2013': 'تعداد تراکنش‌ها بیش از حد مجاز است.',
    '2014': 'قرارداد یافت نشد/نامعتبر است.',
    '2015': 'وضعیت موسسه نامعتبر است.',
    '2017': 'مقدار ثابت وارد شده نامعتبر است.',
    '2023': 'بانک مورد نظر یافت نشد.',
    '2024': 'وضعیت بانک نامعتبر است.',
    '2026': 'کاربر مجاز به انجام عملیات نیست.',
    '2046': 'این پیمان قبلا فعال شده است.',
    '2049': 'شماره پیگیری تکراریست.',
    '2050': 'گروه متناظر برای این موسسه غیرفعال است.',
    '2051': 'خطا در دریافت توکن بانک رخ داده است.',
    '2053': 'خطای دسترسی موسسه رخ داده است.',
    '2055': 'قرارداد مورد نظر به موسسه جاری تعلق ندارد.',
    '2066': 'اطلاعات مورد نیاز در هدر ارسال نشده است.',
    '2074': 'دریافت اطلاعات حساب مشتری با خطا مواجه شده است.',
    '2077': 'شماره موبایل الزامیست.',
    '2078': 'شماره موبایل نامعتبر است.',
    '2081': 'وضعیت قرارداد در حالت انتظار نمی‌باشد.',
    '2085': 'وضعیت قرارداد در حالت ایجاد شده نمي‌باشد.',
    '2087': 'ذخیره مشخصات مشتری با خطا مواجه شده است.',
    '2089': 'موسسه مورد نظر با بانک مربوطه قرارداد پیشفرضی ندارد.',
    '2090': 'موسسه مورد نظر قرارداد پیشفرض ندارد.',
    '2108': 'مبلغ تراکنش روزانه برای این کاربر از مقدار مجاز تعریف شده، بیشتر است.',
    '2110': 'شماره حساب فعالی برای این کاربر یافت نشد.',
    '2122': 'شناسه قرارداد نباید خالی باشد.',
    '2126': 'حداکثر مقدار مجاز تراکنش روزانه باید بزرگتر از حداکثر مقدار مجاز هر تراکنش باشد.',
    '2130': 'شماره سپرده خالی است.',
    '2156': 'کنسل شدن پیمان توسط کاربر در صفحه OAuth',
    '2167': 'بازه پیمان در این بانک نمی‌تواند بیشتر از یک سال باشد.',
    '2182': 'خطا در تغییر وضعیت قرارداد پیمان',
    '2184': 'تغییر واگذارکننده در قرارداد پیمان با خطا مواجه شد.',
    '2187': 'شماره قرارداد موسسه برای بلوبانک یافت نشد.',
    '2197': 'ذخیره شماره کارت در قرارداد پیمان با خطا مواجه شد.',
    '2203': 'آدرس بازگشتی وارد شده یافت نشد.',
    '2205': 'موسسه به بانک مورد نظر دسترسی ندارد.',
    '2226': 'مقادیر حداکثر مقدار مجاز هر تراکنش و حداکثر مقدار مجاز تراکنش روزانه نمیتوانند همزمان خالی باشند.',
    '2010': 'وضعیت قرارداد نامعتبر است.',
    '2011': 'شماره پیگیری مورد نظر یافت نشد/نامعتبر است.',
    '2035': 'کدملی که برای صاحب شماره موبایل ثبت شده است، با کدملی صاحب حساب انتخاب شده مغایرت دارد.',
    '2098': 'عدم تطابق شماره موبایل رخ داده است.',
    '2097': 'عدم تطابق کدملی رخ داده است.',
    '2016': 'وضعیت این پیمان قابل تغییر نیست.',
    '2165': 'مقدار فیلد زمان انقضا می‌بایست بزرگتر از زمان فعلی باشد.',
    '2183': 'مقدار وضعیت جدید نامعتبر است.',
    '2185': 'قرارداد پیمان قبلا لغو شده است.',
    '1515': 'شناسه پرداخت باید خالی باشد.',
    '1516': 'مقدار کارمزد باید خالی باشد.',
    '2003': 'محدودیت تعداد تراکنش روزانه برای این قرارداد رعایت نشده است.',
    '2004': 'محدودیت تعداد تراکنش ماهانه برای این قرارداد رعایت نشده است.',
    '2005': 'زمان پیمان شروع نشده است.',
    '2007': 'واگذارکننده به عنوان مشتری بانک موردنظر ثبت نشده است.',
    '2012': 'زمان انجام تراکنش برای این قرارداد نامعتبر است.',
    '2036': 'مبلغ تراکنش از مقدار مجاز تعریف شده، بیشتر است.',
    '2059': 'زمان تراکنش قبل از زمان مورد توافق در قرارداد است.',
    '2060': 'زمان تراکنش بعد از زمان مورد توافق در قرارداد است.',
    '2061': 'مقدار تراکنش از مقدار توافق شده کمتر است.',
    '2063': 'تعداد تراکنش های انجام شده از تعداد مجاز روزانه بیشتر است.',
    '2064': 'تعداد تراکنش های انجام شده از تعداد مجاز ماهانه بیشتر است.',
    '2135': 'کارت منقضی شده است/ کارت بسته شده است',
    '2218': 'کارت منقضی شده است/ کارت بسته شده است',
    '2149': 'موسسه مورد نظر در بانک انتخابی، حساب بانکی ندارد.',
    '2150': 'کارمزد اجباری است.',
    '2052': 'خطای دسترسی قرارداد رخ داده است.',
    '2057': 'بانک مبدا فعال نیست.',
    '2058': 'قرارداد مورد نظر فعال نیست.',
    '2062': 'مبلغ برداشت مستقیم بیشتر از حداکثر مبلغ برداشت در پیمان است.',
    '2082': 'پیمان در بانک مربوطه حساب ثبت شده‌ای ندارد.',
    '2148': 'برداشت آنی برای بانک‌های با حساب واسط قابل انجام نیست.',
    '2154': 'این پیمان در بانک لغو شده است.',
    '2056': 'موسسه مورد نظر فعال نیست.',
    '2065': 'سقف مبلغ برداشت برای این موسسه پر شده است.',
    '2121': 'زمان مجاز برای اجرا به پایان رسیده است.',
    '2175': 'شناسه پرداخت الزامی است.',
    '10005': 'توکن بانکی نامعتبر',
    '20950': 'حداکثر تعداد برداشت روزانه بیش از محدودیت در نظر گرفته شده در SLA است.',
    '20953': 'حداکثر مبلغ هر برداشت بیش از محدودیت در نظر گرفته شده در SLA است.',
    '10110': 'شماره سپرده مورد نظر وجود ندارد.',
    '20952': 'مجوز برداشت مستقیم قبلا لغو شده است.',
    '29003': 'سقف مبلغ برداشت برای این بانک پر شده است.',
    '2144': 'محدودیت مقداری روزانه نقض شده است',
    '2213': 'کاربر برای پذیرنده معتبر نمی باشد',
    '2200': 'امکان بروزرسانی برای این بانک در حال حاضر غیر فعال است.',
}

# these errors should return to the clients
FARABOOM_ERRORS_FOR_CLIENTS = {
    '004': {
        'code': 'DepositUnavailableError',
        'message': 'Deposit is not possible',
    },
    '2024': {
        'code': 'BankUnavailableError',
        'message': 'Bank status is not valid',
    },
    '2165': {
        'code': 'ToDateInvalidError',
        'message': 'toDate should be greater than now',
    },
    '2016': {
        'code': 'StatusUnchangedError',
        'message': 'The third-party could not change the status',
    },
    '2035': {
        'code': 'NationalCodeInvalidError',
        'message': "National code for the mobile number doesn't match the account owner's code",
    },
    '2098': {
        'code': 'MobileNumberInvalidError',
        'message': 'Mobile number mismatch occurred',
    },
    '2097': {
        'code': 'NationalCodeMismatchError',
        'message': 'National code mismatch occurred',
    },
    '2108': {
        'code': 'MaxTransactionAmountExceededError',
        'message': 'Max transaction amount exceeded',
    },
    '2013': {
        'code': 'MaxTransactionCountExceededError',
        'message': 'Max transaction count exceeded',
    },
    '2026': {
        'code': 'UserNotEligibleToDepositError',
        'message': 'User is not eligible to do a transaction',
    },
    '2046': {
        'code': 'ContractAlreadyActivatedError',
        'message': 'The contract is already activated',
    },
    '2167': {
        'code': 'EndDateInvalidError',
        'message': 'The duration of the contract in this bank cannot exceed one year',
    },
    '20952': {
        'code': 'DepositAuthAlreadyCanceledError',
        'message': 'The direct debit authorization has already been canceled.',
    },
    '2185': {
        'code': 'ContractAlreadyCanceledError',
        'message': 'The contract has already been canceled.',
    },
    '2110': {
        'code': 'NotValidAccountError',
        'message': 'Creating a contract on Transaction or Joint accounts is not allowed.',
    },
    '003': {
        'code': 'InsufficientBalanceError',
        'message': 'The account balance is insufficient.',
    },
    '2003': {
        'code': 'DailyTransactionCountLimitExceededError',
        'message': 'The daily transaction limit for this contract has been exceeded.',
    },
    '2004': {
        'code': 'MonthlyTransactionCountLimitExceededError',
        'message': 'The monthly transaction limit for this contract has been exceeded.',
    },
    '2005': {
        'code': 'ContractNotStartedError',
        'message': 'The contract period has not started yet.',
    },
    '2006': {
        'code': 'ContractExpiredError',
        'message': 'The contract has expired.',
    },
    '2036': {
        'code': 'TransactionAmountLimitExceededError',
        'message': 'The transaction amount exceeds the defined allowed limit.',
    },
    '2060': {
        'code': 'TransactionTimeError',
        'message': 'The transaction time is after the agreed-upon time in the contract.',
    },
    '2061': {
        'code': 'TransactionAmountError',
        'message': 'The transaction amount is below the agreed amount.',
    },
    '2063': {
        'code': 'DailyTransactionCountExceededError',
        'message': 'The number of transactions has exceeded the daily allowed limit.',
    },
    '2064': {
        'code': 'MonthlyTransactionCountExceededError',
        'message': 'The number of transactions has exceeded the monthly allowed limit.',
    },
    '2135': {
        'code': 'CardStatusError',
        'message': 'The card is either expired or closed.',
    },
    '2218': {
        'code': 'CardStatusError',
        'message': 'The card is either expired or closed.',
    },
    '2057': {
        'code': 'InactiveSourceBankError',
        'message': 'The source bank is not active.',
    },
    '2058': {
        'code': 'InactiveContractError',
        'message': 'The specified contract is not active.',
    },
    '2062': {
        'code': 'DirectDebitExceedsMaxAmountError',
        'message': 'The direct debit amount exceeds the contract’s maximum allowed amount.',
    },
    '2148': {
        'code': 'IntermediaryBankError',
        'message': 'Immediate withdrawal is not allowed for banks with intermediary accounts.',
    },
    '2154': {
        'code': 'ContractCanceledInBankError',
        'message': 'This contract has been canceled in the bank.',
    },
    '2010': {
        'code': 'ContractCanceledInBankError',
        'message': 'This contract has been canceled in the bank.',
    },
    '2213': {
        'code': 'ContractCanceledInBankError',
        'message': 'This contract has been canceled in the bank.',
    },
    '29003': {
        'code': 'MaxTransactionAmountExceededError',
        'message': 'Max transaction amount exceeded',
    },
    '2144': {
        'code': 'DailyAmountExceededError',
        'message': 'The amount is out of range of the total daily amount in your contract.',
    },
    '2200': {
        'code': 'StatusUnchangedError',
        'message': 'The third-party could not change the status',
    },
}
