# Generated by Django 3.2.23 on 2024-04-30 12:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('direct_debit', '0001_initial'),
        ('direct_debit', '0002_directdebitcontract'),
        ('direct_debit', '0003_auto_20240309_1654'),
        ('direct_debit', '0004_auto_20240310_1349'),
        ('direct_debit', '0005_auto_20240312_1336'),
        ('direct_debit', '0006_auto_20240318_1753'),
        ('direct_debit', '0007_auto_20240326_1656'),
        ('direct_debit', '0008_auto_20240407_1124'),
        ('direct_debit', '0009_dailydirectdeposit'),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0122_auto_20240310_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('daily_max_transaction_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('daily_max_transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بانک دایرکت دبیت',
                'verbose_name_plural': 'بانک دایرکت دبیت',
            },
        ),
        migrations.CreateModel(
            name='DirectDebitContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'status',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Created'),
                            (1, 'Initializing'),
                            (2, 'Waiting for confirmation'),
                            (3, 'Active'),
                            (4, 'Cancelled'),
                            (5, 'Expired'),
                            (6, 'Failed'),
                            (7, 'Deactive'),
                            (8, 'Waiting for update'),
                            (9, 'Replacedً'),
                        ],
                        default=0,
                    ),
                ),
                ('contract_code', models.CharField(max_length=50)),
                ('trace_id', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('daily_max_transaction_count', models.IntegerField(default=0)),
                (
                    'daily_max_transaction_amount',
                    models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
                ),
                (
                    'max_transaction_amount',
                    models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
                ),
                (
                    'bank',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='direct_debit_contracts',
                        to='direct_debit.directdebitbank',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='direct_debit_contracts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('bank_account_number', models.CharField(default='', max_length=50)),
                ('contract_id', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'پیمان واریز مستقیم',
                'verbose_name_plural': 'پیمان واریز مستقیم',
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='DirectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'In progress'), (1, 'Failed'), (2, 'Succeed'), (3, 'Reversed'), (4, 'Timeout')],
                        default=0,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(max_length=100)),
                ('deposited_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                (
                    'contract',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='direct_deposits',
                        to='direct_debit.directdebitcontract',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'
                    ),
                ),
                ('batch_id', models.CharField(default='', max_length=100)),
                (
                    'details',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None
                    ),
                ),
                ('reference_id', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'واریز مستقیم',
                'verbose_name_plural': 'واریز مستقیم',
            },
        ),
        migrations.AddConstraint(
            model_name='directdebitcontract',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 3)), fields=('user', 'bank'), name='unique_user_and_bank'
            ),
        ),
        migrations.CreateModel(
            name='DailyDirectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('destination_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_bank', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'IN_PROGRESS'), (1, 'FAILED'), (2, 'SUCCEED'), (3, 'REVERSED'), (4, 'TIMEOUT')],
                        default=0,
                    ),
                ),
                ('trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('server_date', models.DateTimeField(blank=True, null=True)),
                ('client_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'deposit',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='direct_debit.directdeposit'
                    ),
                ),
            ],
        ),
    ]
