# Generated by Django 3.2.22 on 2024-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DirectDebitBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('daily_max_transaction_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('daily_max_transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'بانک دایرکت دبیت',
                'verbose_name_plural': 'بانک دایرکت دبیت',
            },
        ),
    ]
