# Generated by Django 3.2 on 2024-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0001_initial_squashed_0009_dailydirectdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdeposit',
            name='deposited_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
