# Generated by Django 3.2.22 on 2024-03-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_debit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created')], default=0)),
                ('contract_code', models.CharField(max_length=50)),
                ('trace_id', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('daily_max_transaction_count', models.IntegerField(default=0)),
                (
                    'daily_max_transaction_amount',
                    models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
                ),
                (
                    'max_transaction_amount',
                    models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
                ),
                (
                    'bank',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='direct_debit_contracts',
                        to='direct_debit.directdebitbank',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='direct_debit_contracts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'پیمان واریز مستقیم',
                'verbose_name_plural': 'پیمان واریز مستقیم',
                'unique_together': {('user', 'bank')},
            },
        ),
    ]
