# Generated by Django 4.2.15 on 2024-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('direct_debit', '0002_auto_20240619_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitbank',
            name='max_transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, default=0),
        ),
    ]
