# Generated by Django 3.2 on 2024-03-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0002_directdebitcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitbank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='directdebitcontract',
            name='bank',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='direct_debit_contracts',
                to='direct_debit.directdebitbank',
            ),
        ),
        migrations.AlterField(
            model_name='directdebitcontract',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Initializing'),
                    (2, 'Waiting for confirmation'),
                    (3, 'Active'),
                    (4, 'Cancelled'),
                    (5, 'Expired'),
                    (6, 'Failed'),
                    (7, 'Deactive'),
                ],
                default=0,
            ),
        ),
    ]
