# Generated by Django 3.2.24 on 2024-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0003_auto_20240309_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitcontract',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directdebitcontract',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Initializing'),
                    (2, 'Waiting for confirmation'),
                    (3, 'Active'),
                    (4, 'Cancelled'),
                    (5, 'Expired'),
                    (6, 'Failed'),
                    (7, 'Deactive'),
                ],
                default=0,
            ),
        ),
    ]
