# Generated by Django 4.2.13 on 2024-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0003_directdebitbank_max_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitcontract',
            name='trace_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
