# Generated by Django 4.2.16 on 2024-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0004_alter_directdebitcontract_trace_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdeposit',
            name='third_party_response',
            field=models.JSONField(blank=True, default=dict),
        )
    ]
