# Generated by Django 3.2 on 2024-03-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0122_auto_20240310_1605'),
        ('direct_debit', '0004_auto_20240310_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitcontract',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Initializing'),
                    (2, 'Waiting for confirmation'),
                    (3, 'Active'),
                    (4, 'Cancelled'),
                    (5, 'Expired'),
                    (6, 'Failed'),
                    (7, 'Deactive'),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name='DirectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'In progress'), (1, 'Failed'), (2, 'Succeed'), (3, 'Reversed'), (4, 'Timeout')],
                        default=0,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(max_length=25)),
                ('deposited_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                (
                    'contract',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='direct_deposits',
                        to='direct_debit.directdebitcontract',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'
                    ),
                ),
            ],
            options={
                'verbose_name': 'واریز مستقیم',
                'verbose_name_plural': 'واریز مستقیم',
            },
        ),
    ]
