# Generated by Django 4.2.15 on 2024-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0005_directdeposit_third_party_response_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directdebitcontract',
            name='unique_user_and_bank',
        ),
        migrations.AddConstraint(
            model_name='directdebitcontract',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', [3, 1, 2])), fields=('user', 'bank'), name='unique_user_and_bank'
            ),
        ),
    ]
