# Generated by Django 3.2.22 on 2024-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0005_auto_20240312_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitcontract',
            name='contract_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
