# Generated by Django 3.2.22 on 2024-03-26 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0006_auto_20240318_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdebitcontract',
            name='location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='directdeposit',
            name='batch_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='directdeposit',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name='directdeposit',
            name='reference_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='directdeposit',
            name='trace_id',
            field=models.CharField(max_length=100),
        ),
    ]
