# Generated by Django 4.2.17 on 2025-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0006_remove_directdebitcontract_unique_user_and_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydirectdeposit',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directdeposit',
            name='trace_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
