# Generated by Django 3.2.24 on 2024-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0007_auto_20240326_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitcontract',
            name='status',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Created'),
                    (1, 'Initializing'),
                    (2, 'Waiting for confirmation'),
                    (3, 'Active'),
                    (4, 'Cancelled'),
                    (5, 'Expired'),
                    (6, 'Failed'),
                    (7, 'Deactive'),
                    (8, 'Waiting for update'),
                    (9, 'Replacedً'),
                ],
                default=0,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='directdebitcontract',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='directdebitcontract',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 3)), fields=('user', 'bank'), name='unique_user_and_bank'
            ),
        ),
    ]
