# Generated by Django 4.2.18 on 2025-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0007_alter_dailydirectdeposit_trace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydirectdeposit',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
