# Generated by Django 4.2.18 on 2025-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0008_alter_dailydirectdeposit_unique_traceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directdebitcontract',
            name='daily_max_transaction_amount',
        ),
    ]
