# Generated by Django 3.2 on 2024-04-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_debit', '0008_auto_20240407_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDirectDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('destination_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_bank', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'IN_PROGRESS'), (1, 'FAILED'), (2, 'SUCCEED'), (3, 'REVERSED'), (4, 'TIMEOUT')],
                        default=0,
                    ),
                ),
                ('trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('server_date', models.DateTimeField(blank=True, null=True)),
                ('client_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'deposit',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='direct_debit.directdeposit'
                    ),
                ),
            ],
        ),
    ]
