# Generated by Django 4.2.18 on 2025-03-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('direct_debit', '0009_remove_directdebitcontract_daily_max_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydirectdeposit',
            name='deposit',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='direct_debit.directdeposit',
            ),
        ),
    ]
