# Generated by Django 2.2.25 on 2021-12-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0121_auto_20211002_0819_squashed_0133_merge_20220210_0031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TicketingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('descriptions', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('members', models.ManyToManyField(related_name='ticketing_groups', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'باز'), (1, 'حل\u200cشده'), (2, 'هرزنامه'), (3, 'در انتظار')], verbose_name='وضعیت')),
                ('content', models.TextField(max_length=1000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاشناس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('files', models.ManyToManyField(blank=True, related_name='_ticket_files_+', to='accounts.UploadedFile', verbose_name='فایل\u200cهای پیوست')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.TicketingGroup', verbose_name='گروه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Topic', verbose_name='موضوع')),
            ],
        ),
    ]
