# Generated by Django 2.2.28 on 2022-04-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ticketing', '0001_initial'), ('ticketing', '0002_auto_20211230_1202'), ('ticketing', '0003_auto_20220116_1248'), ('ticketing', '0004_auto_20220130_1610'), ('ticketing', '0005_auto_20220205_1800'), ('ticketing', '0006_auto_20220326_1652'), ('ticketing', '0007_auto_20220326_1733'), ('ticketing', '0008_tag'), ('ticketing', '0009_ticket_tag'), ('ticketing', '0010_ticket_is_private'), ('ticketing', '0011_auto_20220417_1411')]

    initial = True

    dependencies = [
        ('accounts', '0121_auto_20211002_0819_squashed_0133_merge_20220210_0031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TicketingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('descriptions', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('members', models.ManyToManyField(related_name='ticketing_groups', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='محتوا')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'باز'), (1, 'حل\u200cشده'), (2, 'هرزنامه'), (3, 'در انتظار')], default=0, verbose_name='وضعیت')),
                ('content', models.TextField(max_length=1000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('files', models.ManyToManyField(blank=True, related_name='_ticket_files_+', to='accounts.UploadedFile', verbose_name='فایل\u200cهای پیوست')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.TicketingGroup', verbose_name='گروه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Topic', verbose_name='موضوع')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('log', 1), ('private_message', 2), ('comment', 3)])),
                ('content', models.TextField(max_length=1000)),
                ('actor', models.ForeignKey(on_delete=models.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ticketing.Ticket')),
            ],
        ),
        migrations.RunSQL(
            sql='ALTER SEQUENCE ticketing_ticket_id_seq RESTART WITH 1000000;',
        ),
        migrations.AddField(
            model_name='activity',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='_activity_files_+', to='accounts.UploadedFile', verbose_name='فایل\u200cهای پیوست'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'باز'), (1, 'بسته'), (2, 'اسپم')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='descriptions',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='topic',
            name='group_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.TicketingGroup', verbose_name='گروه مسئول'),
        ),
        migrations.CreateModel(
            name='TicketingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ticketing.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='ticketing.TicketingTag', verbose_name='برچسب\u200cها'),
        ),
    ]
