# Generated by Django 2.2.24 on 2022-05-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_squashed_0011_auto_20220417_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='call_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User', verbose_name='اطلاعات تماس'),
        ),
    ]
