# Generated by Django 2.2.24 on 2022-05-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20220522_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='call_reason',
        ),
    ]
