# Generated by Django 2.2.25 on 2022-01-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20220116_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='files',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state',
                 models.IntegerField(choices=[(0, 'باز'), (1, 'حل\u200cشده'), (2, 'هرزنامه'), (3, 'در انتظار')],
                                     default=0, verbose_name='وضعیت')),
                ('content', models.TextField(max_length=1000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('assigned_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                 to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('files', models.ManyToManyField(blank=True, related_name='_ticket_files_+', to='accounts.UploadedFile',
                                                 verbose_name='فایل\u200cهای پیوست')),
                ('group',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets',
                                   to='ticketing.TicketingGroup', verbose_name='گروه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                   to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Topic',
                                            verbose_name='موضوع')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('log', 1), ('private_message', 2), ('comment', 3)])),
                ('content', models.TextField(max_length=1000)),
                ('actor',
                 models.ForeignKey(on_delete=models.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities',
                                             to='ticketing.Ticket')),
            ],
        ),
        migrations.RunSQL(
            'ALTER SEQUENCE ticketing_ticket_id_seq RESTART WITH 1000000;'
        ),
    ]
