# Generated by Django 2.2.25 on 2022-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20220130_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='_activity_files_+', to='accounts.UploadedFile', verbose_name='فایل\u200cهای پیوست'),
        ),
    ]
