# Generated by Django 2.2.24 on 2022-05-31 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20220531_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[('log', 1), ('private_message', 2), ('comment', 3), ('report', 4)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'ارسال\u200cشده'), (1, 'در حال بررسی'), (2, 'پاسخ\u200cداده\u200cشده'), (3, 'بسته\u200cشده'), (4, 'اسپم')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.Topic', verbose_name='موضوع'),
        ),
    ]
