# Generated by Django 2.2.27 on 2022-03-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20220205_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='group_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.TicketingGroup'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'باز'), (1, 'بسته'), (2, 'اسپم')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='descriptions',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
