# Generated by Django 2.2.26 on 2022-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20220531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinggroup',
            name='descriptions',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='descriptions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
    ]
