# Generated by Django 2.2.27 on 2022-03-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20220326_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='group_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.TicketingGroup', verbose_name='گروه مسئول'),
        ),
    ]
