# Generated by Django 2.2.28 on 2022-07-13 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20220711_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='related_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
