# Generated by Django 2.2.25 on 2022-04-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20220326_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ticketing.Topic')),
            ],
        ),
    ]
