# Generated by Django 2.2.28 on 2022-07-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20220713_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(1, 'log'), (2, 'private_message'), (3, 'comment'), (4, 'report')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'ارسال\u200cشده'), (1, 'در حال بررسی'), (2, 'پاسخ\u200cداده\u200cشده'), (3, 'اسپم')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticketingtag',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ticketing.Topic'),
        ),
    ]
