# Generated by Django 2.2.24 on 2022-07-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0149_auto_20220723_1926'),
        ('ticketing', '0008_auto_20220719_1525'),
    ]

    operations = []
