# Generated by Django 2.2.25 on 2022-04-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.TicketingTag', verbose_name='برچسب'),
        ),
    ]
