# Generated by Django 2.2.24 on 2022-07-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_ticket_call_reason'),
    ]

    operations = []
