# Generated by Django 2.2.25 on 2022-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_ticket_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
