# Generated by Django 2.2.28 on 2022-07-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from exchange.accounts.models import User
from exchange.ticketing.models import Ticket


def fill_null_related_users(apps, schema_editor):
    if Ticket.objects.filter(related_user__isnull=True).exists():
        Ticket.objects.filter(related_user__isnull=True).update(
            related_user=User.objects.get_or_create(username='system-1000')[0]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_remove_ticket_call_reason'),
    ]

    operations = [
        migrations.RunPython(fill_null_related_users),
        migrations.AlterField(
            model_name='ticket',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
