# Generated by Django 2.2.28 on 2022-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_ticket_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='ticketing.TicketingTag', verbose_name='برچسب\u200cها'),
        ),
    ]
