# Generated by Django 2.2.26 on 2022-07-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('ticketing', '0011_auto_20220724_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_step', models.PositiveIntegerField(default=0)),
                ('maximum_open_ticket', models.PositiveIntegerField(default=0)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
