# Generated by Django 2.2.26 on 2022-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_ticketconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='TicketConfiguration',
            name='group',
        ),
        migrations.AddField(
            model_name='TicketConfiguration',
            name='group',
            field=models.OneToOneField(to='TicketingGroup', on_delete=models.CASCADE, unique=True),
        ),
    ]
