# Generated by Django 2.2.28 on 2022-08-13 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_ticketconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(100, 'عادی'), (200, 'فوری')], default=100, verbose_name='اولویت'),
        ),
    ]
