# Generated by Django 2.2.28 on 2022-08-14 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0014_auto_20220813_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_to',
            new_name='_assigned_to'
        )
    ]
