# Generated by Django 2.2.28 on 2022-08-23 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_auto_20220814_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(1, 'log'), (2, 'private_message'), (3, 'comment'), (4, 'report'), (5, 'delete_comment')]),
        ),
    ]
