# Generated by Django 2.2.26 on 2022-08-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0016_auto_20220823_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinggroup',
            name='members',
        ),
        migrations.AddField(
            model_name='ticketinggroup',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketing_groups', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه'),
        ),
        migrations.AddField(
            model_name='topic',
            name='members',
            field=models.ManyToManyField(related_name='ticketing_topics', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='group_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='ticketing.TicketingGroup', verbose_name='گروه مسئول'),
        ),
    ]
