# Generated by Django 2.2.28 on 2022-08-29 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_auto_20220827_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='waiting_time',
            field=models.DurationField(null=True),
        ),
    ]
