# Generated by Django 2.2.28 on 2022-09-03 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_auto_20220829_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketingtag',
            name='topic',
        ),
        migrations.AddField(
            model_name='ticketingtag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ticketing.TicketingGroup'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
    ]
