# Generated by Django 2.2.28 on 2022-09-06 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0019_auto_20220903_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.Topic', verbose_name='موضوع'),
        ),
    ]
