# Generated by Django 2.2.28 on 2022-09-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0020_auto_20220906_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketSatisfaction',
        ),
    ]
