# Generated by Django 2.2.28 on 2022-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0021_delete_ticketsatisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='seen_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='تاریخ مشاهده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(choices=[(1, 'ضعیف'), (2, 'بد نبود'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], null=True, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_note',
            field=models.TextField(blank=True, max_length=400, verbose_name='توضیحات'),
        ),
    ]
