# Generated by Django 2.2.28 on 2022-10-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0022_auto_20220912_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='topic',
            name='show_to_users',
            field=models.BooleanField(default=True, verbose_name='نمایش به کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'ارسال\u200cشده'), (1, 'در حال بررسی'), (2, 'پاسخ\u200cداده\u200cشده'), (3, 'اسپم'), (4, 'بسته')], default=0, verbose_name='وضعیت'),
        ),
    ]
