# Generated by Django 2.2.26 on 2022-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0023_auto_20221018_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='show_to_users',
            field=models.BooleanField(default=False, verbose_name='نمایش به کاربر'),
        ),
    ]
