# Generated by Django 2.2.26 on 2022-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0024_auto_20221120_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='readymessage',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
