# Generated by Django 2.2.28 on 2022-12-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0025_auto_20221206_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.IntegerField(choices=[(0, 'خیلی کم'), (50, 'کم'), (100, 'متوسط'), (150, 'زیاد'), (200, 'بسیار زیاد')], default=100),
        ),
    ]
