# Generated by Django 2.2.28 on 2023-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0026_auto_20221225_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketConfiguration',
        ),
    ]
