# Generated by Django 2.2.28 on 2023-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0027_auto_20230221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(
                choices=[
                    (0, 'ارسال\u200cشده'),
                    (1, 'در حال بررسی'),
                    (2, 'پاسخ\u200cداده\u200cشده'),
                    (3, 'اسپم'),
                    (4, 'بسته\u200cشده'),
                ],
                db_index=True,
                default=0,
                verbose_name='وضعیت',
            ),
        ),
    ]
