# Generated by Django 3.2.23 on 2024-01-29 10:33

from django.db import migrations, models

import exchange.ticketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0028_auto_20230418_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='_is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
