# Generated by Django 4.2.14 on 2024-11-13 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0175_alter_user_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0029_auto_20240129_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
