# Generated by Django 2.2.28 on 2023-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('socialtrade', '0001_leadership_request_squashed_0007_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='delete_reason',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'حذف به دلیل درخواست شما از طریق تیکت'),
                    (2, 'حذف به دلیل عدم فعالیت و ترید'),
                    (3, 'حذف به دلیل عدم انطباق با شرایط تریدر سوشال ترید'),
                ],
                null=True,
            ),
        ),
    ]
