# Generated by Django 2.2.28 on 2023-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0002_leader_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='system_fee_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
