# Generated by Django 2.2.28 on 2023-09-05 12:38

from decimal import Decimal

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0003_auto_20230813_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='gained_subscription_fees',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=36),
        ),
    ]
