# Generated by Django 2.2.28 on 2023-09-26 21:21

from decimal import Decimal

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0004_leader_gained_subscription_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='daily_profits',
            field=JSONField(null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='last_month_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4),
        ),
    ]
