# Generated by Django 2.2.28 on 2023-10-18 15:01

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0005_auto_20230927_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='last_month_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
