# Generated by Django 2.2.28 on 2023-10-28 15:39

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0006_auto_20231018_1831'),
        ('wallet', '0119_merge_20231021_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtradesubscription',
            name='leader_transaction',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wallet.Transaction'
            ),
        ),
        migrations.AlterField(
            model_name='socialtradesubscription',
            name='system_transaction',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wallet.Transaction'
            ),
        ),
        migrations.AlterField(
            model_name='socialtradesubscription',
            name='withdraw_transaction',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wallet.Transaction'
            ),
        ),
    ]
