# Generated by Django 2.2.28 on 2023-10-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0007_auto_20231028_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtradesubscription',
            name='is_renewed',
            field=models.BooleanField(null=True),
        ),
    ]
