# Generated by Django 2.2.28 on 2023-11-02 11:27

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0008_auto_20231028_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='daily_profits',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
