# Generated by Django 3.2.23 on 2024-01-20 12:27

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0009_auto_20231102_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTradeAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'image',
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(), upload_to='social_trade_avatars'
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leader',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='leadershiprequest',
            name='avatar',
        ),
        migrations.AddField(
            model_name='leader',
            name='avatar',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                related_name='+',
                to='socialtrade.socialtradeavatar',
            ),
        ),
        migrations.AddField(
            model_name='leadershiprequest',
            name='avatar',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                related_name='+',
                to='socialtrade.socialtradeavatar',
            ),
        ),
    ]
