# Generated by Django 3.2.23 on 2024-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0010_auto_20240120_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='delete_reason',
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, 'حذف به دلیل درخواست شما از طریق تیکت'),
                    (2, 'حذف به دلیل عدم فعالیت و ترید'),
                    (3, 'حذف به دلیل عدم انطباق با شرایط تریدر سوشال ترید'),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='leader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
