# Generated by Django 3.2.25 on 2024-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtrade', '0011_auto_20240204_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtradesubscription',
            name='is_notif_enabled',
            field=models.BooleanField(default=True, null=False, verbose_name='ارسال نوتیف؟'),
        ),
    ]
