"""Wallet Constants"""
from decimal import Decimal

from exchange.base.constants import MAX_PRECISION, MONETARY_DECIMAL_PLACES

TRANSACTION_MAX = Decimal('1E12') - MAX_PRECISION
TRANSACTION_MAX_DIGITS = TRANSACTION_MAX.adjusted() + 1 + MONETARY_DECIMAL_PLACES

BALANCE_MAX_DIGITS = TRANSACTION_MAX_DIGITS + 3  # i.e. 1000x tx

DEPOSIT_MAX_DIGITS = TRANSACTION_MAX_DIGITS
assert DEPOSIT_MAX_DIGITS <= BALANCE_MAX_DIGITS

WITHDRAW_MAX_DIGITS = TRANSACTION_MAX_DIGITS
assert WITHDRAW_MAX_DIGITS <= BALANCE_MAX_DIGITS
