# Generated by Django 4.2.13 on 2024-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('public', 'Public'), ('core', 'Core'), ('hot_cold', 'Hot Cold'), ('admin', 'Admin'), ('wallet_monitoring', 'Wallet Monitoring')], default='public', max_length=32)),
                ('blockchain_address', models.CharField(default='', max_length=200)),
                ('last_read_tx_created_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
