# Generated by Django 4.2.13 on 2024-10-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='last_read_tx_created_time',
            new_name='last_read_tx_created_at',
        ),
    ]
