# Generated by Django 4.2.13 on 2024-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_rename_last_read_tx_created_time_address_last_read_tx_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='blockchain_address',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.CharField(choices=[('public', 'Public'), ('core', 'Core'), ('hot_cold', 'Hot Cold'), ('admin', 'Admin'), ('wallet_monitoring', 'Wallet Monitoring')], db_index=True, default='public', max_length=32),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together={('blockchain_address', 'owner')},
        ),
    ]
