# Generated by Django 4.2.13 on 2024-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_address_blockchain_address_alter_address_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='currency',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='is_registered_highload_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='last_read_address_tx_created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='last_read_wallet_withdraw_created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
