# Generated by Django 4.2.13 on 2024-11-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('wallets', '0004_remove_address_last_read_tx_created_at_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='address',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='address',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networkproviders.network'),
        ),
        migrations.AlterIndexTogether(
            name='address',
            index_together={('network', 'blockchain_address', 'owner')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_read_tx_created_at',
        ),
    ]
