# Generated by Django 4.2.13 on 2024-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_address_index_together_address_network_and_more'),
    ]

    operations = [

    ]
