# Generated by Django 4.2.13 on 2024-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_address_unique_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
