# Generated by Django 4.2.3 on 2024-11-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_address_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
