# Generated by Django 4.2.3 on 2025-01-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("networkproviders", "0009_alter_networkdefaultprovider_operation_and_more"),
        ("wallets", "0008_delete_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="networkproviders.network",
                    ),
                ),
            ],
            options={
                "unique_together": {("network", "address")},
            },
        ),
    ]
