# Generated by Django 4.2.3 on 2025-01-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("networkproviders", "0010_network_save_address_txs"),
        ("wallets", "0009_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="networkproviders.network",
                    ),
                ),
            ],
            options={
                "unique_together": {("network", "address")},
            },
        ),
        migrations.DeleteModel(
            name="TransactionAddress",
        ),
    ]
