# Generated by Django 2.1.8 on 2019-06-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0023_auto_20190619_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShetabDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('status_code', models.IntegerField(default=-9999, verbose_name='وضعیت')),
                ('user_card_number', models.CharField(blank=True, max_length=50, verbose_name='شماره کارت')),
                ('user_card_hash', models.CharField(blank=True, max_length=100, verbose_name='هش کارت')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('fee', models.BigIntegerField(default=0, help_text='ریال', verbose_name='کارمزد')),
                ('broker', models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay')], default=1, verbose_name='درگاه پرداخت')),
                ('nextpay_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پیگیری')),
                ('gateway_redirect_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس انتقال به درگاه')),
                ('next_redirect_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس بازگشت')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction', verbose_name='تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shetab_deposits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واریز شتابی',
                'verbose_name_plural': 'واریز شتابی',
            },
        ),
    ]
