# Generated by Django 2.2.18 on 2021-05-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0064_merge_20210519_0302'),
        ('shetab', '0009_auto_20210522_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibitdeposit',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.BankDeposit', verbose_name='واریز بانکی'),
        ),
        migrations.AlterField(
            model_name='jibitdeposit',
            name='raw_bank_timestamp',
            field=models.CharField(max_length=25, verbose_name='زمان واریز'),
        ),
        migrations.AlterUniqueTogether(
            name='jibitdeposit',
            unique_together={('payment_id', 'external_reference_number')},
        ),
    ]
