# Generated by Django 2.1.8 on 2019-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay'), (5, 'Vandar')], default=1, verbose_name='درگاه پرداخت'),
        ),
    ]
