# Generated by Django 2.1.11 on 2019-08-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0002_auto_20190707_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shetabdeposit',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shetabdeposit',
            name='is_iranian',
            field=models.BooleanField(default=True),
        ),
    ]
