# Generated by Django 2.2.14 on 2020-07-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20200704_1241'),
        ('shetab', '0003_auto_20190827_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='shetabdeposit',
            name='selected_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shetab_deposits', to='accounts.BankCard', verbose_name='کارت انتخابی'),
        ),
        migrations.AlterField(
            model_name='shetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay'), (5, 'Vandar'), (6, 'Jibit'), (7, 'Vandar2Step')], default=1, verbose_name='درگاه پرداخت'),
        ),
    ]
