# Generated by Django 2.2.17 on 2020-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0004_auto_20200707_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shetabdeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان'),
        ),
    ]
