# Generated by Django 2.2.17 on 2020-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0005_auto_20201229_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shetabdeposit',
            name='nextpay_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
