# Generated by Django 2.2.20 on 2021-05-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0006_auto_20201229_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shetabdeposit',
            options={'permissions': [('view_gateway_performance_report', 'نمایش گزارش عملکرد درگاهها')]},
        )
    ]
