# Generated by Django 2.2.18 on 2021-05-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0006_auto_20201229_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='JibitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(choices=[(0, 'BMJIIR'), (1, 'BOIMIR'), (2, 'BKMTIR'), (3, 'REFAIR'), (4, 'BKMNIR'), (5, 'SEPBIR'), (6, 'KESHIR'), (7, 'MELIIR'), (8, 'BTEJIR'), (9, 'BSIRIR'), (10, 'EDBIIR'), (11, 'PBIRIR'), (12, 'TTBIIR'), (13, 'BTOSIR'), (14, 'GHAVIR'), (15, 'GHAVIR'), (16, 'BKPAIR'), (17, 'BEGNIR'), (18, 'SABCIR'), (19, 'BKBPIR'), (20, 'SRMBIR'), (21, 'SINAIR'), (22, 'MEHRIR'), (23, 'CIYBIR'), (24, 'AYBKIR'), (25, 'TOSMIR'), (26, 'HEKMIR'), (27, 'ANSBIR'), (28, 'DAYBIR'), (29, 'IRZAIR'), (30, 'MELLIR'), (31, 'KHMIIR'), (32, 'IVBBIR'), (33, 'NOORIR'), (34, 'MEGHIR')], default=7, verbose_name='بانک')),
                ('iban', models.CharField(max_length=26, verbose_name='شماره شبای مقصد')),
                ('account_number', models.CharField(max_length=25, verbose_name='شماره حساب مقصد')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
            ],
            options={
                'verbose_name': 'حساب\u200cهای جیبیت',
                'verbose_name_plural': 'حساب\u200cهای جیبیت',
            },
        ),
        migrations.CreateModel(
            name='JibitPayment_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=25, verbose_name='شناسه پرداخت')),
                ('reference_number', models.CharField(max_length=25, verbose_name='شماره مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount', verbose_name='حساب بانکی')),
                ('jibit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shetab.JibitAccount', verbose_name='حساب جیبیت')),
            ],
            options={
                'verbose_name': 'شناسه واریز',
                'verbose_name_plural': 'شناسه واریز',
            },
        ),
        migrations.CreateModel(
            name='JibitDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('status', models.IntegerField(choices=[(0, 'در حال پردازش'), (1, 'در حال انتظار تایید'), (2, 'ناموفق'), (3, 'موفق')], default=0)),
                ('external_reference_number', models.CharField(max_length=15, verbose_name='شناسه واریز در جیبیت')),
                ('bank_reference_number', models.CharField(max_length=15, verbose_name='شناسه واریز بانک')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('raw_bank_timestamp', models.CharField(max_length=25, verbose_name='شناسه واریز')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shetab.JibitPayment_id', verbose_name='حساب بانکی')),
            ],
            options={
                'verbose_name': 'واریزی\u200cهای جیبیت',
                'verbose_name_plural': 'واریزی\u200cهای جیبیت',
            },
        ),
    ]
