# Generated by Django 2.2.17 on 2021-05-21 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('shetab', '0007_auto_20210518_1648'), ('shetab', '0008_auto_20210518_1823'), ('shetab', '0009_auto_20210522_0239')]

    dependencies = [
        ('shetab', '0006_auto_20201229_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='JibitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(choices=[(0, 'markazi'), (1, 'SANAT_VA_MADAN'), (2, 'ملت'), (3, 'REFAH'), (4, 'MASKAN'), (5, 'SEPAH'), (6, 'KESHAARZI'), (7, 'ملی'), (8, 'TEJARAT'), (9, 'SADERAT'), (10, 'TOSEAH_SADERAT'), (11, 'POST'), (12, 'TOSEAH_TAAVON'), (13, 'TOSEAH'), (14, 'GHAVAMIN'), (15, 'KARAFARIN'), (16, 'PARSIAN'), (17, 'EGHTESADE_NOVIN'), (18, 'SAMAN'), (19, 'PASARGAD'), (20, 'SARMAIEH'), (21, 'SINA'), (22, 'MEHR_IRANIAN'), (23, 'SHAHR'), (24, 'AYANDEH'), (25, 'GARDESHGARI'), (26, 'HEKMAT_IRANIAN'), (27, 'RESALAT'), (28, 'DEY'), (29, 'IRANZAMIN'), (30, 'MELAL'), (31, 'KAVARMIANEH'), (32, 'IRAN_VENEZOELA'), (33, 'NOOR'), (34, 'MEHR_EGHTESAD')], default=7, verbose_name='بانک')),
                ('iban', models.CharField(max_length=26, unique=True, verbose_name='شماره شبای مقصد')),
                ('account_number', models.CharField(max_length=25, verbose_name='شماره حساب مقصد')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
            ],
            options={
                'verbose_name': 'حساب\u200cهای جیبیت',
                'verbose_name_plural': 'حساب\u200cهای جیبیت',
            },
        ),
        migrations.CreateModel(
            name='JibitPaymentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=25, verbose_name='شناسه پرداخت')),
                ('reference_number', models.CharField(max_length=25, verbose_name='شماره مرجع')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount', verbose_name='حساب بانکی')),
                ('jibit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shetab.JibitAccount', verbose_name='حساب جیبیت')),
            ],
            options={
                'verbose_name': 'شناسه واریز',
                'verbose_name_plural': 'شناسه واریز',
            },
        ),
        migrations.CreateModel(
            name='JibitDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('status', models.IntegerField(choices=[(0, 'در حال پردازش'), (1, 'در حال انتظار تایید'), (2, 'ناموفق'), (3, 'موفق')], default=0)),
                ('external_reference_number', models.CharField(max_length=15, verbose_name='شناسه واریز در جیبیت')),
                ('bank_reference_number', models.CharField(max_length=15, verbose_name='شناسه واریز بانک')),
                ('amount', models.BigIntegerField(help_text='ریال', verbose_name='مبلغ واریزی')),
                ('raw_bank_timestamp', models.CharField(max_length=25, verbose_name='شناسه واریز')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shetab.JibitPaymentId', verbose_name='حساب بانکی')),
            ],
            options={
                'verbose_name': 'واریزی\u200cهای جیبیت',
                'verbose_name_plural': 'واریزی\u200cهای جیبیت',
            },
        ),
        migrations.AlterField(
            model_name='shetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay'), (5, 'Vandar'), (6, 'Jibit'), (7, 'Vandar2Step'), (8, 'Sayment')], default=1, verbose_name='درگاه پرداخت'),
        ),
    ]
