# Generated by Django 2.2.18 on 2021-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0007_auto_20210518_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JibitPayment_id',
            new_name='JibitPaymentId',
        ),
    ]
