# Generated by Django 2.2.17 on 2021-05-21 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0008_auto_20210518_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibitaccount',
            name='bank',
            field=models.IntegerField(choices=[(0, 'markazi'), (1, 'SANAT_VA_MADAN'), (2, 'ملت'), (3, 'REFAH'), (4, 'MASKAN'), (5, 'SEPAH'), (6, 'KESHAARZI'), (7, 'ملی'), (8, 'TEJARAT'), (9, 'SADERAT'), (10, 'TOSEAH_SADERAT'), (11, 'POST'), (12, 'TOSEAH_TAAVON'), (13, 'TOSEAH'), (14, 'GHAVAMIN'), (15, 'KARAFARIN'), (16, 'PARSIAN'), (17, 'EGHTESADE_NOVIN'), (18, 'SAMAN'), (19, 'PASARGAD'), (20, 'SARMAIEH'), (21, 'SINA'), (22, 'MEHR_IRANIAN'), (23, 'SHAHR'), (24, 'AYANDEH'), (25, 'GARDESHGARI'), (26, 'HEKMAT_IRANIAN'), (27, 'RESALAT'), (28, 'DEY'), (29, 'IRANZAMIN'), (30, 'MELAL'), (31, 'KAVARMIANEH'), (32, 'IRAN_VENEZOELA'), (33, 'NOOR'), (34, 'MEHR_EGHTESAD')], default=7, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='jibitaccount',
            name='iban',
            field=models.CharField(max_length=26, unique=True, verbose_name='شماره شبای مقصد'),
        ),
        migrations.AlterField(
            model_name='jibitpaymentid',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='shetabdeposit',
            name='broker',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'NextPay'), (2, 'Pay.ir'), (3, 'PayPing'), (4, 'IDPay'), (5, 'Vandar'), (6, 'Jibit'), (7, 'Vandar2Step'), (8, 'Sayment')], default=1, verbose_name='درگاه پرداخت'),
        ),
    ]
