# Generated by Django 2.2.23 on 2021-06-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0007_auto_20210524_1105'),
        ('shetab', '00010_auto_20210523_1618'),
    ]

    operations = [
    ]
