# Generated by Django 2.2.17 on 2021-07-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0011_merge_20210603_1540'),
    ]

    operations = [
    ]
