# Generated by Django 2.2.18 on 2021-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0012_auto_20210711_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShetabDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('gateway_pk', models.CharField(max_length=70, verbose_name='شناسه درگاه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(max_length=5, verbose_name='نوع ارز')),
                ('reference_number', models.CharField(max_length=50, verbose_name='شناسه مرجع')),
                ('user_identifier', models.CharField(max_length=50, verbose_name='هویت کاربر')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('additional_data', models.CharField(max_length=300, verbose_name='اطلاعات اضافه شده')),
                ('status', models.CharField(max_length=13, verbose_name='وضیعت پرداخت')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(verbose_name='تاریخ تغییر')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انفضا')),
                ('payer_card', models.CharField(max_length=16, verbose_name='شماره کارت پرداخت کننده')),
                ('national_code', models.CharField(max_length=12, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'واریزی\u200cهای روزانه',
                'verbose_name_plural': 'واریزی\u200cهای روزانه',
            },
        ),
    ]
