# Generated by Django 2.2.18 on 2021-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0013_auto_20210911_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.IntegerField(choices=[(1, 'jibit')], verbose_name='درگاه')),
                ('transfer_pk', models.CharField(max_length=70, verbose_name='شناسه درگاه')),
                ('transfer_mode', models.CharField(max_length=10, verbose_name='روش انتقال')),
                ('destination', models.CharField(max_length=30, verbose_name='شبا مقصد')),
                ('destination_first_name', models.CharField(max_length=50, verbose_name='نام برداشت کننده')),
                ('destination_last_name', models.CharField(max_length=50, verbose_name='نام\u200cخانوادگی برداشت کننده')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('currency', models.CharField(max_length=8, verbose_name='واحد پول')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('bank_transfer', models.CharField(max_length=15, verbose_name='شناسه انتقال')),
                ('state', models.CharField(max_length=15, verbose_name='وضعیت')),
                ('transferred_amount', models.BigIntegerField(verbose_name='مبلغ انتقال داده شدع')),
                ('createdAt', models.DateTimeField(verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برداشت\u200cهای روزانه',
                'verbose_name_plural': 'برداشت\u200cهای روزانه',
            },
        ),
    ]
