# Generated by Django 2.2.18 on 2021-09-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0014_auto_20210911_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywithdraw',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
