# Generated by Django 2.2.24 on 2021-09-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0015_auto_20210911_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshetabdeposit',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shetab.ShetabDeposit'),
        ),
        migrations.AddField(
            model_name='dailywithdraw',
            name='withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.WithdrawRequest'),
        ),
    ]
