# Generated by Django 2.2.24 on 2021-09-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0016_auto_20210920_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyShetabDeposit',
        ),
        migrations.DeleteModel(
            name='DailyWithdraw',
        ),
    ]
