# Generated by Django 2.2.24 on 2021-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0017_auto_20210928_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibitdeposit',
            name='bank_reference_number',
            field=models.CharField(max_length=50, verbose_name='شناسه واریز بانک'),
        ),
        migrations.AlterField(
            model_name='jibitdeposit',
            name='external_reference_number',
            field=models.CharField(max_length=50, verbose_name='شناسه واریز در جیبیت'),
        ),
        migrations.AlterField(
            model_name='jibitdeposit',
            name='raw_bank_timestamp',
            field=models.CharField(max_length=50, verbose_name='زمان واریز'),
        ),
    ]
