# Generated by Django 2.2.26 on 2022-04-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0018_auto_20211221_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibitpaymentid',
            name='broker',
            field=models.IntegerField(choices=[(1, 'Jibit'), (2, 'Vandar')], default=1, verbose_name='سرویس پرداخت'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jibitpaymentid',
            name='reference_number',
        ),
        migrations.AlterUniqueTogether(
            name='jibitpaymentid',
            unique_together={('broker', 'payment_id')},
        ),
    ]
