# Generated by Django 2.2.26 on 2022-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0019_auto_20220426_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jibitpaymentid',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jibitpaymentid',
            name='broker',
        ),
    ]
