# Generated by Django 2.2.24 on 2022-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0020_auto_20220622_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibitaccount',
            name='account_number',
            field=models.CharField(max_length=25, unique=True, verbose_name='شماره حساب مقصد'),
        ),
    ]
