# Generated by Django 2.2.24 on 2022-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0021_auto_20220911_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='shetabdeposit',
            name='anomaly_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
