# Generated by Django 2.2.28 on 2023-05-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shetab', '0022_auto_20221001_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='VandarAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True, verbose_name='شناسه وندار کاربر')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب\u200cهای وندار',
                'verbose_name_plural': 'حساب\u200cهای وندار',
            },
        ),
        migrations.CreateModel(
            name='VandarPaymentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount', verbose_name='حساب بانکی')),
                ('vandar_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shetab.VandarAccount', verbose_name='حساب وندار')),
            ],
            options={
                'verbose_name': 'شناسه واریز وندار',
                'verbose_name_plural': 'شناسه واریز وندار',
            },
        ),
    ]
