# Generated by Django 3.2.23 on 2024-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0023_auto_20230508_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibitdeposit',
            name='bank_reference_number',
            field=models.CharField(max_length=255, verbose_name='شناسه واریز بانک'),
        ),
    ]
