# Generated by Django 4.2.15 on 2024-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shetab', '0024_auto_20240310_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jibitaccount',
            options={'verbose_name': 'حساب\u200cهای نزد جیبیت', 'verbose_name_plural': 'حساب\u200cهای نزد جیبیت'},
        ),
        migrations.AddField(
            model_name='jibitaccount',
            name='account_type',
            field=models.SmallIntegerField(default=0, verbose_name='نوع حساب'),
        ),
    ]
