# Generated by Django 4.2.18 on 2025-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shetab', '0025_alter_jibitaccount_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jibitpaymentid',
            constraint=models.UniqueConstraint(
                fields=['jibit_account', 'payment_id'],
                name='shetab_jibitpaymentid_jibit_account_payment_id_unique',
            ),
        ),
    ]
