# Generated by Django 2.2.24 on 2021-08-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0081_auto_20210825_1719')
    ]

    state_operations = [
        migrations.CreateModel(
            name='UserTotalMonthlyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date', models.DateField()),
                ('total_balance', models.DecimalField(decimal_places=10, max_digits=25)),
                ('first_day_total_balance', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('total_profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('total_profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سود و زیان ماهانه',
                'verbose_name_plural': 'سود و زیان ماهانه',
                'unique_together': {('report_date', 'user')},
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserTotalDailyProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_date', models.DateField()),
                ('total_balance', models.DecimalField(decimal_places=10, max_digits=25)),
                ('profit', models.DecimalField(decimal_places=10, max_digits=25)),
                ('profit_percentage', models.DecimalField(decimal_places=10, max_digits=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سود و زیان روزانه',
                'verbose_name_plural': 'سود و زیان روزانه',
                'unique_together': {('report_date', 'user')},
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
