# Generated by Django 2.2.24 on 2021-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotaldailyprofit',
            name='total_deposit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='usertotaldailyprofit',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='usertotalmonthlyprofit',
            name='total_deposit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='usertotalmonthlyprofit',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
