# Generated by Django 4.2.13 on 2024-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210921_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='profit',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='total_balance',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='first_day_total_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_balance',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_profit',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
