# Generated by Django 4.2.14 on 2024-09-08 13:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20240824_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='profit',
            field=models.DecimalField(decimal_places=10, max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='total_balance',
            field=models.DecimalField(decimal_places=10, max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='total_deposit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotaldailyprofit',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='first_day_total_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_balance',
            field=models.DecimalField(decimal_places=10, max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_deposit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_profit',
            field=models.DecimalField(decimal_places=10, max_digits=27),
        ),
        migrations.AlterField(
            model_name='usertotalmonthlyprofit',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=27),
        ),
    ]
