# Generated by Django 2.2.24 on 2021-07-24 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0027_merge_20210712_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('tp', models.IntegerField(choices=[(0, 'Price'), (1, 'Percent'), (2, 'Periodic')], db_index=True, verbose_name='نوع اعلان')),
                ('param_direction', models.BooleanField(null=True, verbose_name='پارامتر جهت تغییر')),
                ('param_value', models.DecimalField(decimal_places=10, max_digits=25, verbose_name='پارامتر قیمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر')),
                ('cooldown', models.IntegerField(blank=True, null=True, verbose_name='زمان تنفس')),
                ('channel', models.IntegerField(choices=[(1, 'Notif'), (2, 'Email'), (4, 'SMS')], default=0, verbose_name='کانال اطلاع\u200cرسانی')),
                ('last_alert', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین اطلاع\u200cرسانی')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market', verbose_name='بازار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان قیمت',
                'verbose_name_plural': 'اعلان قیمت',
            },
        ),
    ]
