# Generated by Django 2.2.28 on 2022-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricealert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='channel',
            field=models.IntegerField(choices=[(1, 'Notif'), (2, 'Email'), (3, 'Email/Notif'), (4, 'SMS'), (5, 'SMS/Notif'), (6, 'SMS/Email'), (7, 'SMS/Email/Notif')], default=0, verbose_name='کانال اطلاع\u200cرسانی'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='param_value',
            field=models.DecimalField(db_index=True, decimal_places=10, max_digits=25, verbose_name='پارامتر قیمت'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='tp',
            field=models.IntegerField(choices=[(1, 'Price'), (2, 'Percent'), (3, 'Periodic')], db_index=True, verbose_name='نوع اعلان'),
        ),
    ]
