# Generated by Django 2.2.28 on 2022-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن / موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('call_type', models.PositiveSmallIntegerField(choices=[(1, 'اینستاگرام'), (1, 'توییتر'), (2, 'آشنایان'), (3, 'کمپ تبلیغاتی')], verbose_name='طریقه آشنایی')),
            ],
        ),
    ]
