# Generated by Django 2.2.28 on 2022-11-15 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان تغییر'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='call_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'تماس تلفنی'), (2, 'چت آنلاین'), (3, 'نمایشگاه'), (4, 'ارتباط فردی')], verbose_name='طریقه آشنایی'),
        ),
    ]
