# Generated by Django 2.2.28 on 2022-11-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20221115_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'مشتری هدف', 'verbose_name_plural': 'مشتری\u200cهای هدف'},
        ),
    ]
