# Generated by Django 2.2.26 on 2023-01-07 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0003_auto_20221121_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1, verbose_name='اولویت')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'موضوع انتقادات و پیشنهادات',
                'verbose_name_plural': 'موضوع انتقادات و پیشنهادات',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='متن پیشنهاد')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=models.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_category', to='marketing.SuggestionCategory')),
            ],
            options={
                'verbose_name': 'انتقادات و پیشنهادات',
                'verbose_name_plural': 'انتقادات و پیشنهادات',
            },
        ),
        migrations.AddConstraint(
            model_name='suggestion',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', False), ('mobile__isnull', False), ('email__isnull', False), _connector='OR'), name='not_all_null'),
        ),
    ]
