# Generated by Django 2.2.24 on 2023-01-09 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20230107_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='پشتیبان'),
        ),
    ]
