# Generated by Django 2.2.28 on 2023-01-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20230109_1159'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='suggestion',
            name='not_all_null',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='متن پیشنهاد'),
        ),
    ]
