# Generated by Django 2.2.28 on 2023-10-10 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0006_auto_20230123_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='utm_parameters',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
