# Generated by Django 2.2.28 on 2023-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20231010_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utmparameter',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
