# Generated by Django 3.2.22 on 2024-05-14 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0008_auto_20231017_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaDiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('used_date', models.DateTimeField(null=True, blank=True)),
                (
                    'user',
                    models.OneToOneField(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pizza_discount_code',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'کد تخفیف پیتزا',
                'verbose_name_plural': 'کدهای تخفیف پیتزا',
            },
        ),
        migrations.AddConstraint(
            model_name='pizzadiscountcode',
            constraint=models.UniqueConstraint(
                condition=models.Q(('used_date__isnull', False)), fields=('user',), name='unique_used_code_on_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='pizzadiscountcode',
            constraint=models.UniqueConstraint(
                condition=models.Q(('code', 'finishedDiscountCode'), _negated=True),
                fields=('code',),
                name='unique_discount_codes',
            ),
        ),
    ]
