# Generated by Django 3.2.22 on 2024-06-08 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('marketing', '0009_auto_20240508_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaDiscountCode',
        ),
    ]
