# Generated by Django 4.2.17 on 2025-02-01 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0011_alter_suggestion_allocated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(null=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='external_discounts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='externaldiscount',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('user', 'campaign_id'),
                name='unique_user_id_campaign_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='externaldiscount',
            constraint=models.UniqueConstraint(fields=('code', 'campaign_id'), name='unique_code_campaign_id'),
        ),
    ]
