# Generated by Django 4.2.20 on 2025-05-19 07:45

from django.db import migrations, models

import exchange.base.calendar


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_external_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldiscount',
            name='enabled_at',
            field=models.DateTimeField(default=exchange.base.calendar.ir_now),
        ),
        migrations.AddIndex(
            model_name='externaldiscount',
            index=models.Index(
                condition=models.Q(('user__isnull', True)),
                fields=['enabled_at', 'campaign_id'],
                name='enabled_at_campaign_id',
            ),
        ),
    ]
