# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=25)),
                ('shaba_number', models.CharField(max_length=26)),
                ('owner_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'اکانت بانکی سیستم',
                'verbose_name_plural': 'اکانت بانکی سیستم',
            },
        ),
    ]
