# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembankaccount',
            name='account_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='systembankaccount',
            name='shaba_number',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
