# Generated by Django 2.2.24 on 2022-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_manualbinancetrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbinancetrade',
            name='created_at',
            field=models.DateField(db_index=True),
        ),
    ]
