# Generated by Django 2.2.24 on 2022-01-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20220101_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualbinancetrade',
            old_name='created_at',
            new_name='date',
        ),
    ]
