# Generated by Django 2.2.24 on 2022-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20220101_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSystemBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=25, unique=True)),
                ('iban_number', models.CharField(max_length=26, unique=True)),
                ('bank_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اکانت واریز بانکی سیستم',
                'verbose_name_plural': 'اکانت واریز بانکی سیستم',
            },
        ),
    ]
