# Generated by Django 2.2.24 on 2022-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20220904_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsystembankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='depositsystembankaccount',
            name='bank_id',
            field=models.IntegerField(choices=[(10, 'بانک\u200cمرکزی'), (11, 'صنعت\u200cو\u200cمعدن'), (12, 'ملت'), (13, 'رفاه'), (14, 'مسکن'), (15, 'سپه'), (16, 'کشاورزی'), (17, 'ملی'), (18, 'تجارت'), (19, 'صادرات'), (20, 'توسعه\u200cصادرات'), (21, 'پست\u200cبانک'), (22, 'توسعه\u200cتعاون'), (51, 'موسسه\u200cاعتباری\u200cتوسعه'), (52, 'قوامین'), (53, 'کار\u200cآفرین'), (54, 'پارسیان'), (55, 'اقتصاد\u200cنوین'), (56, 'سامان'), (57, 'پاسارگاد'), (58, 'سرمایه'), (59, 'سینا'), (60, 'مهر\u200cایران'), (61, 'شهر'), (62, 'آینده'), (63, 'انصار'), (64, 'گردشگری'), (65, 'حکمت\u200cایرانیان'), (66, 'دی'), (69, 'ایران\u200cزمین'), (70, 'رسالت'), (73, 'کوثر'), (75, 'موسسه\u200cملل'), (78, 'خاورمیانه'), (80, 'موسسه\u200cنور'), (999, 'وندار')], default=0, help_text='شناسه بانک'),
            preserve_default=False,
        ),
    ]
