# Generated by Django 2.2.24 on 2022-09-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20220906_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsystembankaccount',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
