# Generated by Django 2.2.24 on 2022-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20220907_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsystembankaccount',
            name='type_of_account',
            field=models.IntegerField(blank=True, choices=[(1, 'جیبیت')], null=True),
        ),
    ]
