# Generated by Django 2.2.28 on 2023-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20221030_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualBinanceTrade',
        ),
    ]
