# Generated by Django 2.1.8 on 2019-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_exchange', models.IntegerField(choices=[(0, 'None'), (1, 'Kraken'), (2, 'Binance')], default=0, verbose_name='بازار مقصد')),
                ('exchange_id', models.BigIntegerField(verbose_name='شناسه مقصد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('src_currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')], verbose_name='ارز مبدا')),
                ('dst_currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (21, 'Cardano')], verbose_name='ارز مقصد')),
                ('order_type', models.IntegerField(choices=[(1, 'Sell'), (2, 'Buy')], verbose_name='نوع')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='قیمت واحد')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='مقدار ارز')),
            ],
            options={
                'verbose_name': 'رکورد معامله بایننس',
                'verbose_name_plural': 'رکورد معامله بایننس',
            },
        ),
        migrations.AlterUniqueTogether(
            name='externaltraderecord',
            unique_together={('target_exchange', 'exchange_id')},
        ),
    ]
