# Generated by Django 2.1.8 on 2019-05-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltraderecord',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='تاریخ معامله'),
        ),
    ]
