# Generated by Django 2.1.8 on 2019-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20190520_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltraderecord',
            name='commission',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='کارمزد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externaltraderecord',
            name='exchange_order_id',
            field=models.BigIntegerField(default=0, verbose_name='شناسه سفارش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_id',
            field=models.BigIntegerField(verbose_name='شناسه معامله'),
        ),
    ]
