# Generated by Django 2.2.14 on 2020-10-13 17:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0053_auto_20201013_2102'),
        ('audit', '0003_auto_20190520_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')], verbose_name='رمزارز')),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'External Wallet',
                'verbose_name_plural': 'External Wallet',
            },
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='target_exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures']], default=0, verbose_name='بازار مقصد'),
        ),
        migrations.CreateModel(
            name='ExternalWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tp', models.IntegerField(choices=[(0, 'New'), (1, 'UserWithdraw'), (2, 'Unknown')], default=0, verbose_name='نوع برداشت')),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink')], default=0, verbose_name='رمزارز')),
                ('amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, verbose_name='مقدار برداشت')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='audit.ExternalWallet')),
                ('user_withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.WithdrawRequest')),
            ],
            options={
                'verbose_name': 'رکورد برداشت',
                'verbose_name_plural': 'رکورد برداشت',
                'unique_together': {('tx_hash', 'destination')},
            },
        ),
    ]
