# Generated by Django 2.2.14 on 2020-10-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20201013_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalwallet',
            name='tp',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Binance'), (2, 'Hot Wallet'), (3, 'Cold Wallet')], default=0, verbose_name='نوع'),
        ),
    ]
