# Generated by Django 2.2.14 on 2020-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_externalwallet_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalwithdraw',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ'),
        ),
    ]
