# Generated by Django 2.2.24 on 2022-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_externalwithdraw_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltraderecord',
            name='trader_type',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (1, 'Bot'), (2, 'Xchange'), (3, 'Manual')], default=-1, verbose_name='معامله\u200cگر'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='dst_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'My Neighbor Alice'), (52, 'Alpha Finance Lab'), (53, 'Ankr'), (54, 'ARPA Chain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie Infinity'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'Basic Attention Token'), (63, 'Bella Protocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'Celer Network'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'Elrond eGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'Mask Network'), (83, 'Maker'), (84, 'NEAR Protocol'), (85, 'Ocean Protocol'), (86, 'Ontology'), (87, 'Reef Finance'), (88, 'SafePal'), (89, 'Synthetix Network Token'), (90, 'Sushi'), (91, 'Swipe'), (92, 'Alien Worlds'), (93, 'Unifi Protocol DAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa')], verbose_name='ارز مقصد'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='src_currency',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'USD'), (2, '﷼'), (10, 'Bitcoin'), (11, 'Ethereum'), (12, 'Litecoin'), (13, 'Tether'), (14, 'Ripple'), (15, 'BitcoinCash'), (16, 'BinanceCoin'), (17, 'EOS'), (18, 'Dogecoin'), (19, 'Stellar'), (20, 'TRON'), (21, 'Cardano'), (22, 'Monero'), (23, 'NEM'), (24, 'IOTA'), (25, 'EthereumClassic'), (26, 'Dash'), (27, 'Zcash'), (28, 'Neo'), (29, 'Qtum'), (30, 'Tezos'), (31, 'Paymon'), (32, 'Chainlink'), (33, 'Dai'), (34, 'Polkadot'), (35, 'Uniswap'), (36, 'Aave'), (37, 'Solana'), (38, 'Polygon'), (39, 'Filecoin'), (40, 'Graph'), (41, 'Theta'), (42, '1000SHIB'), (50, '1inch'), (51, 'My Neighbor Alice'), (52, 'Alpha Finance Lab'), (53, 'Ankr'), (54, 'ARPA Chain'), (55, 'Automata'), (56, 'Cosmos'), (57, 'Avalanche'), (58, 'Axie Infinity'), (59, 'BakeryToken'), (60, 'Balancer'), (61, 'BAND'), (62, 'Basic Attention Token'), (63, 'Bella Protocol'), (64, 'Bluzelle'), (65, 'BitTorrent'), (66, 'Coin98'), (67, 'Celer Network'), (68, 'Chromia'), (69, 'Compound'), (70, 'COTI'), (71, 'CertiK'), (72, 'Cartesi'), (73, 'DODO'), (74, 'Elrond eGold'), (75, 'Fantom'), (76, 'Gala'), (77, 'IoTeX'), (78, 'KyberNetwork'), (79, 'Kusama'), (80, 'Linear'), (81, 'Litentry'), (82, 'Mask Network'), (83, 'Maker'), (84, 'NEAR Protocol'), (85, 'Ocean Protocol'), (86, 'Ontology'), (87, 'Reef Finance'), (88, 'SafePal'), (89, 'Synthetix Network Token'), (90, 'Sushi'), (91, 'Swipe'), (92, 'Alien Worlds'), (93, 'Unifi Protocol DAO'), (94, 'yearn.finance'), (95, 'DFI.Money'), (96, 'Zilliqa')], verbose_name='ارز مبدا'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='target_exchange',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Kraken'], [2, 'BINANCE'], [3, 'USD'], [4, 'Nobitex'], [5, 'BinanceFutures'], [6, 'BinanceMargin']], default=0, verbose_name='بازار مقصد'),
        ),
    ]
