# Generated by Django 2.2.26 on 2022-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20220110_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltraderecord',
            name='trader_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Bot'), (2, 'Xchange'), (3, 'Manual')], default=0, verbose_name='معامله\u200cگر'),
        ),
    ]
