# Generated by Django 2.2.28 on 2022-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20220112_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externaltraderecord',
            unique_together={('target_exchange', 'exchange_id', 'exchange_order_id')},
        ),
    ]
