# Generated by Django 2.2.28 on 2022-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_auto_20220515_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_id',
            field=models.DecimalField(decimal_places=0, max_digits=32, verbose_name='شناسه معامله'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_order_id',
            field=models.DecimalField(decimal_places=0, max_digits=32, verbose_name='شناسه سفارش'),
        ),
    ]
