# Generated by Django 2.2.28 on 2022-07-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('audit', '0012_auto_20220702_1737'), ('audit', '0013_auto_20220703_1603')]

    dependencies = [
        ('audit', '0011_auto_20220517_1140'),
    ]

    operations = [
    ]
