# Generated by Django 2.2.28 on 2022-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20220517_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_id',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='شناسه معامله'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_order_id',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='شناسه سفارش'),
        ),
    ]
