# Generated by Django 2.2.28 on 2023-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20220702_1737_squashed_0013_auto_20220703_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalTradeRecord',
        ),
    ]
