# Generated by Django 2.2.28 on 2022-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20220702_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_id',
            field=models.BigIntegerField(verbose_name='شناسه معامله'),
        ),
        migrations.AlterField(
            model_name='externaltraderecord',
            name='exchange_order_id',
            field=models.BigIntegerField(verbose_name='شناسه سفارش'),
        ),
    ]
