# Generated by Django 4.2.3 on 2024-02-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networkproviders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('success', models.BooleanField()),
                ('from_address', models.CharField(default='', max_length=100)),
                ('to_address', models.CharField(default='', max_length=100)),
                ('value', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
                ('block_height', models.IntegerField()),
                ('block_hash', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('memo', models.CharField(max_length=100, null=True)),
                ('tx_fee', models.FloatField(null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkproviders.network')),
            ],
            options={
            },
        ),
    ]
