# Generated by Django 4.2.3 on 2024-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='tx_fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
