# Generated by Django 4.2.3 on 2024-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transfer_tx_fee_alter_transfer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='block_height',
            field=models.IntegerField(db_index=True),
        ),
    ]
