# Generated by Django 4.2.3 on 2024-03-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transfer_block_height'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'block_height')},
        ),
    ]
