# Generated by Django 4.2.3 on 2024-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transfer_index_together'),
    ]

    operations = [

        migrations.AddField(
            model_name='transfer',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
