# Generated by Django 4.2.3 on 2024-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transfer_index_together'),
    ]

    operations = [

    ]
