# Generated by Django 4.2.3 on 2024-05-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transfer_unique_together'),
    ]

    operations = [

    ]
