# Generated by Django 4.2.3 on 2024-05-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transfer_unique_together_transfer_index_and_more'),
        ('transactions', '0007_alter_transfer_unique_together'),
    ]

    operations = [
    ]
