# Generated by Django 4.2.3 on 2024-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_merge_20240502_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
