# Generated by Django 4.2.3 on 2024-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transfer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
