# Generated by Django 4.2.13 on 2024-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transfer_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.CharField(max_length=75),
        ),
    ]
