# Generated by Django 4.2.13 on 2024-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transfer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='source_operation',
            field=models.CharField(default='block_txs'),
        ),
    ]
