# Generated by Django 4.2.13 on 2024-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transfer_unique_together_transfer_unique_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
