# Generated by Django 4.2.13 on 2024-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transfer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tx_hash',
            field=models.CharField(max_length=200),
        ),
    ]
