# Generated by Django 4.2.13 on 2024-09-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transfer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source_operation',
            field=models.CharField(),
        ),
    ]
