# Generated by Django 4.2.13 on 2024-10-05 11:25

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations, models


def migrate_addresses(apps, schema_editor):
    Transfer = apps.get_model('transactions', 'Transfer')
    Address = apps.get_model('wallets', 'Address')

    for transaction in Transfer.objects.all():
        # Create or get from_address
        if transaction.from_address:
            from_address_obj, created = Address.objects.get_or_create(blockchain_address=transaction.from_address)
            transaction.from_address2 = from_address_obj

        # Create or get to_address
        if transaction.to_address:
            to_address_obj, created = Address.objects.get_or_create(blockchain_address=transaction.to_address)
            transaction.to_address2 = to_address_obj

        # Set the new ForeignKey fields
        transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('wallets', '0001_initial'),
        ('transactions', '0017_alter_transfer_source_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_address2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='withdraw_transactions', to='wallets.address'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_address2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='deposit_transactions', to='wallets.address'),
        ),
        migrations.RunPython(migrate_addresses)
    ]
