# Generated by Django 4.2.13 on 2024-10-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transfer_from_address2_transfer_to_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_address',
        ),
    ]
