# Generated by Django 4.2.13 on 2024-10-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_remove_transfer_from_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='from_address2',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='to_address2',
            new_name='to_address',
        ),
    ]
