# Generated by Django 4.2.13 on 2024-10-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('wallets', '0003_alter_address_blockchain_address_alter_address_owner_and_more'),
        ('transactions', '0020_rename_from_address2_transfer_from_address_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'block_height')},
        ),
    ]
