# Generated by Django 4.2.13 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_transfer_index_together'),
    ]

    operations = [
    ]
