# Generated by Django 4.2.13 on 2024-10-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0022_uniqu_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'block_height')},
        ),
    ]
