# Generated by Django 4.2.13 on 2024-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_transfer_index_together'),
    ]

    operations = [
    ]
