# Generated by Django 4.2.13 on 2024-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_transfer_unique_tx2'),
    ]

    operations = [
    ]
