# Generated by Django 4.2.13 on 2024-11-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0026_remove_transfer_unique_tx_remove_transfer_unique_tx_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'block_height'), ('network', 'source_operation')},
        ),
    ]
