# Generated by Django 4.2.13 on 2024-11-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0027_alter_transfer_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'block_height'), ('from_address', 'to_address', 'network', 'source_operation')},
        ),
    ]
