# Generated by Django 4.2.13 on 2024-11-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0028_alter_transfer_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('network', 'source_operation', 'created_at'), ('from_address', 'to_address', 'network', 'source_operation'), ('network', 'block_height')},
        ),
    ]
