# Generated by Django 4.2.13 on 2024-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_transfer_index_together'),
    ]

    operations = [
    ]
