# Generated by Django 4.2.13 on 2024-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_address_unique_address'),
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0030_remove_transfer_unique_tx2_transfer_unique_tx2'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('from_address', 'to_address', 'network', 'source_operation'), ('network', 'block_height')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['network_id', 'source_operation', 'created_at'], include=('block_height',), name='idx_network_op_create'),
        ),
    ]
