# Generated by Django 4.2.13 on 2024-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_alter_transfer_index_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='idx_network_op_create',
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['network_id', 'source_operation', 'created_at', 'block_height'], name='idx_network_op_create'),
        ),
    ]
