# Generated by Django 4.2.13 on 2024-11-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_remove_transfer_idx_network_op_create_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='idx_network_op_create',
        ),
    ]
