# Generated by Django 4.2.13 on 2024-11-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_address_unique_address'),
        ('networkproviders', '0009_alter_networkdefaultprovider_operation_and_more'),
        ('transactions', '0033_remove_transfer_idx_network_op_create'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('from_address', 'to_address', 'network', 'source_operation'), ('network', 'source_operation', 'created_at'), ('network', 'block_height')},
        ),
    ]
