# Generated by Django 4.2.13 on 2024-11-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_address_unique_address'),
        ('transactions', '0034_alter_transfer_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_transactions', to='wallets.address'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='wallets.address'),
        ),
    ]
