# Generated by Django 4.2.13 on 2024-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_alter_transfer_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_address_str',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_address_str',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
