# Generated by Django 4.2.3 on 2024-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_pointer_alter_transfer_index_together'),
    ]

    operations = [
    ]
