# Generated by Django 4.2.3 on 2024-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_remove_transfer_unique_tx2_transfer_unique_tx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_address',
        ),
    ]
