# Generated by Django 4.2.3 on 2024-12-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_remove_transfer_from_address_and_more'),
    ]

    operations = [
    ]
