# Generated by Django 4.2.3 on 2024-12-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_remove_transfer_unique_tx2_transfer_unique_tx'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('source_operation', 'created_at'), ('from_address_str', 'to_address_str', 'source_operation')},
        ),
    ]
