# Generated by Django 4.2.3 on 2024-12-08 11:40

from django.db import migrations, models
import exchange.explorer.transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_alter_transfer_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transfer',
            index_together={('source_operation', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(exchange.explorer.transactions.models.Upper('from_address_str'), exchange.explorer.transactions.models.Upper('to_address_str'), name='idx_upper_from_to'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['network_id', 'source_operation'], name='idx_network_source'),
        ),
    ]
