# Generated by Django 4.2.3 on 2025-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_alter_transfer_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='block_height_bigint',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
