# Generated by Django 4.2.3 on 2025-01-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_transfer_block_height_bigint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='block_height',
        ),
    ]
