# Generated by Django 4.2.3 on 2025-01-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_remove_transfer_block_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='block_height_bigint',
            new_name='block_height',
        ),
    ]
