# Generated by Django 4.2.3 on 2025-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_rename_block_height_bigint_transfer_block_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointerProcessingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.CharField(max_length=64)),
                ('end_at', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('last_processed_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='pointer',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
