# Generated by Django 4.2.3 on 2025-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_pointerprocessingrange_alter_pointer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('network', 'tx_hash', 'from_address_str', 'to_address_str', 'value', 'block_height', 'index', 'memo'), name='unique_tx'),
        ),
    ]
