# Generated by Django 2.1.4 on 2018-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0001_initial'), ('base', '0002_log'), ('base', '0003_auto_20180713_1024'), ('base', '0004_auto_20180818_1143'), ('base', '0005_auto_20180922_1408')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=10)),
                ('category', models.IntegerField(choices=[(0, 'general'), (1, 'update'), (2, 'notice')], default=0)),
                ('module', models.IntegerField(choices=[(0, 'general'), (1, 'wallet'), (2, 'market')], default=0)),
                ('runner', models.IntegerField(choices=[(0, 'generic'), (1, 'celery'), (2, 'cron'), (3, 'matcher'), (4, 'autotrader'), (5, 'stats'), (6, 'telegram'), (7, 'kraken'), (8, 'deposit'), (9, 'api')], default=0)),
                ('message', models.CharField(blank=True, default='', max_length=1000)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'لاگ سیستم',
                'verbose_name_plural': 'لاگ سیستم',
            },
        ),
    ]
