# Generated by Django 2.1.4 on 2019-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_nobitex2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='module',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'wallet'), (2, 'market'), (3, 'shetab')], default=0),
        ),
    ]
