# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.IntegerField(choices=[(0, 'NOTSET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=10)),
                ('category', models.IntegerField(choices=[(0, 'general'), (1, 'update')], default=0)),
                ('module', models.IntegerField(choices=[(0, 'general'), (1, 'wallet')], default=0)),
                ('runner', models.IntegerField(choices=[(0, 'generic'), (1, 'celery'), (2, 'cron'), (3, 'matcher'), (4, 'autotrader'), (5, 'stats'), (6, 'telegram'), (7, 'kraken'), (8, 'deposit')], default=0)),
                ('message', models.CharField(blank=True, default='', max_length=1000)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
