# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ سیستم', 'verbose_name_plural': 'لاگ سیستم'},
        ),
    ]
