# Generated by Django 2.2.17 on 2020-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190115_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='module',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'wallet'), (2, 'market'), (3, 'shetab'), (4, 'settlement'), (5, 'apicall'), (6, 'cache')], default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='runner',
            field=models.IntegerField(choices=[(0, 'generic'), (1, 'workers'), (2, 'cron'), (3, 'matcher'), (4, 'autotrader'), (5, 'stats'), (6, 'telegram'), (7, 'kraken'), (8, 'deposit'), (9, 'api'), (10, 'admin'), (11, 'apicall')], default=0),
        ),
    ]
