# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180713_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'update'), (2, 'notice')], default=0),
        ),
    ]
