# Generated by Django 2.2.28 on 2023-05-24 09:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0003_auto_20201125_1320'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='APICallLog',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ایجاد')),
        #         ('object_id', models.PositiveIntegerField(null=True)),
        #         ('retry', models.SmallIntegerField(default=0, verbose_name='تکرار فراخوانی')),
        #         ('api_url', models.CharField(max_length=100, verbose_name='آدرس فراخوانی سرویس خارجی')),
        #         ('request_details', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='جزئیات درخواست')),
        #         ('response_details', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='جزئیات پاسخ')),
        #         ('status', models.SmallIntegerField(choices=[(0, 'success'), (1, 'failure')], verbose_name='وضعیت')),
        #         ('status_code', models.SmallIntegerField(verbose_name='کد وضعیت')),
        #         ('provider', models.SmallIntegerField(choices=[(0, 'alpha')], verbose_name='ارائه دهنده')),
        #         ('service', models.SmallIntegerField(choices=[(0, 'liveness')], verbose_name='سرویس')),
        #         ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
        #     ],
        #     options={
        #         'verbose_name': 'لاگ نتایج صدا زدن سرویس\u200cهای خارجی',
        #     },
        # ),
        # migrations.AddIndex(
        #     model_name='apicalllog',
        #     index=models.Index(fields=['content_type', 'object_id'], name='base_apical_content_fb8c61_idx'),
        # ),
    ]
