# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-22 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180818_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='module',
            field=models.IntegerField(choices=[(0, 'general'), (1, 'wallet'), (2, 'market')], default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='runner',
            field=models.IntegerField(choices=[(0, 'generic'), (1, 'celery'), (2, 'cron'), (3, 'matcher'), (4, 'autotrader'), (5, 'stats'), (6, 'telegram'), (7, 'kraken'), (8, 'deposit'), (9, 'api')], default=0),
        ),
    ]
