# Generated by Django 4.2.13 on 2024-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230524_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('src_ip', models.CharField(max_length=45)),
                ('process_time', models.PositiveIntegerField()),
                ('server', models.CharField(max_length=32)),
                ('is_internal', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('src_service', models.CharField(blank=True, default='', max_length=32)),
                ('extras', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
